Repository kubernetes-sigs/kustomize, pull requests merged in 2018-12, with the labels that each got.

#591 improve error message when failing to find an object to patch
  k8sdeps/transformer/patch/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#592 resolve namereference in an array
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#584 Add support for variable subsitution in Ingress hosts
  pkg/commands/build/testdata/testcase-variable-ref-ingress/expected.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/deployment.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/ingress.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/service.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/test.yaml
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#600 add APIService to cluster level kinds
  pkg/gvk/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#608 Require relocatable kustomizations and fix some nits.
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/helper.go
  pkg/loader/fileloader.go
  pkg/resid/resid.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#599 Add namespace for config map and secret generators
  docs/kustomization.yaml
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/secretfactory.go
  pkg/commands/build/testdata/testcase-generators-namespace/expected.yaml
  pkg/commands/build/testdata/testcase-generators-namespace/in/kustomization.yaml
  pkg/commands/build/testdata/testcase-generators-namespace/in/password.txt
  pkg/commands/build/testdata/testcase-generators-namespace/test.yaml
  pkg/types/kustomization.go
Labels: cncf-cla: yes, lgtm, size/M

#609 Extract common generator args to common type.
  k8sdeps/configmapandsecret/configmapfactory_test.go
  pkg/commands/edit/add/configmap.go
  pkg/resmap/factory_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#614 Add projected secret path to transformer config
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#612 add handling function for remote url hostname
  pkg/loader/gitcloner.go
  pkg/loader/gitcloner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#618 Add enforcement message for apiVersion and kind
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#620 Reduce size of missing field markers.
  pkg/commands/build/testdata/testcase-generators-namespace/expected.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/test.yaml
  pkg/gvk/gvk.go
  pkg/gvk/gvk_test.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#619 Tiny but noticeable typo fix
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#621 Add subcommand: edit fix
  pkg/commands/edit/all.go
  pkg/commands/edit/fix/fix.go
  pkg/commands/edit/fix/fix_test.go
  pkg/fs/fakefs.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#622 Add some resId tests to support refactor.
  pkg/gvk/gvk.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget_test.go
  pkg/transformers/prefixsuffixname.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#624 Allow directory substrings in cycle check.
  pkg/loader/fileloader.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#626 Fix incorrect use of filepath.Separator
  pkg/loader/gitcloner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#630 fix the missing fields in all edit commands
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#640 Convert file system based test to in-memory.
  pkg/commands/build/build_test.go
  pkg/commands/build/testdata/testcase-simple/expected.diff
  pkg/commands/build/testdata/testcase-simple/expected.yaml
  pkg/commands/build/testdata/testcase-simple/test.yaml
  pkg/examplelayout/simple/instances/exampleinstance/configmap/app-init.ini
  pkg/examplelayout/simple/instances/exampleinstance/configmap/app.env
  pkg/examplelayout/simple/instances/exampleinstance/deployment/deployment.yaml
  pkg/examplelayout/simple/instances/exampleinstance/kustomization.yaml
  pkg/examplelayout/simple/instances/exampleinstance/secret/tls.cert
  pkg/examplelayout/simple/instances/exampleinstance/secret/tls.key
  pkg/examplelayout/simple/package/Kube-descriptor.yaml
  pkg/examplelayout/simple/package/deployment/deployment.yaml
  pkg/examplelayout/simple/package/kustomization.yaml
  pkg/examplelayout/simple/package/service/service.yaml
  pkg/target/bigger_test.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#631 Forbid Var name collisions in a kustomization stack
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, size/L

#643 More fully in-memory integration tests.
  pkg/commands/build/testdata/testcase-multibases-conflict/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/base/rolebinding.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/base/serviceaccount.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/combined/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/overlays/a/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/overlays/a/serviceaccount.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/overlays/b/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/test.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/base/rolebinding.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/base/serviceaccount.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/combined/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/expected.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/overlays/a/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/overlays/b/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/test.yaml
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/kusttarget_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/utils_for_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#645 fix typos
  examples/transformerconfigs/README.md
  examples/transformerconfigs/crd/README.md
Labels: approved, cncf-cla: yes, size/XS

#647 Yet another kusttarget test.
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
Labels: approved, cncf-cla: yes, size/L

#644 add apiVersion and kind to docs and examples
  docs/kustomization.yaml
  examples/breakfast.md
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/generatorOptions.md
  examples/helloWorld/README.md
  examples/helloWorld/kustomization.yaml
  examples/imageTags.md
  examples/jsonpatch.md
  examples/ldap/base/kustomization.yaml
  examples/ldap/overlays/production/kustomization.yaml
  examples/ldap/overlays/staging/kustomization.yaml
  examples/multibases/README.md
  examples/multibases/base/kustomization.yaml
  examples/multibases/dev/kustomization.yaml
  examples/multibases/kustomization.yaml
  examples/multibases/production/kustomization.yaml
  examples/multibases/staging/kustomization.yaml
  examples/remoteBuild.md
  examples/springboot/overlays/production/kustomization.yaml
  examples/springboot/overlays/staging/kustomization.yaml
  examples/transformerconfigs/crd/kustomization.yaml
  examples/wordpress/README.md
  examples/wordpress/kustomization.yaml
  examples/wordpress/mysql/kustomization.yaml
  examples/wordpress/wordpress/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#637 List of strategic merge patches
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
  pkg/resource/factory.go
  pkg/resource/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#653 Revert "add apiVersion and kind to docs and examples"
  docs/kustomization.yaml
  examples/breakfast.md
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/generatorOptions.md
  examples/helloWorld/README.md
  examples/helloWorld/kustomization.yaml
  examples/imageTags.md
  examples/jsonpatch.md
  examples/ldap/base/kustomization.yaml
  examples/ldap/overlays/production/kustomization.yaml
  examples/ldap/overlays/staging/kustomization.yaml
  examples/multibases/README.md
  examples/multibases/base/kustomization.yaml
  examples/multibases/dev/kustomization.yaml
  examples/multibases/kustomization.yaml
  examples/multibases/production/kustomization.yaml
  examples/multibases/staging/kustomization.yaml
  examples/remoteBuild.md
  examples/springboot/overlays/production/kustomization.yaml
  examples/springboot/overlays/staging/kustomization.yaml
  examples/transformerconfigs/crd/kustomization.yaml
  examples/wordpress/README.md
  examples/wordpress/kustomization.yaml
  examples/wordpress/mysql/kustomization.yaml
  examples/wordpress/wordpress/kustomization.yaml
Labels: approved, cncf-cla: yes, size/M

#654 change current version from v1 to v1beta1
  pkg/commands/build/testdata/testcase-base-only/in/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/base/myapp/mycomponent/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/base/myapp/mycomponent2/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent2/kustomization.yaml
  pkg/commands/build/testdata/testcase-crds/crd/kustomization.yaml
  pkg/commands/build/testdata/testcase-generators-namespace/in/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/package/kustomization.yaml
  pkg/commands/edit/fix/fix.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/fs/fakefs.go
  pkg/target/kusttarget_test.go
  pkg/target/utils_for_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#655 Make KustTarget test harness to reduce boilerplate.
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/kusttarget_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/utils_for_test.go
Labels: approved, cncf-cla: yes, size/L

#659 More custom transform coverage.
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/customconfig_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/utils_for_test.go
Labels: approved, cncf-cla: yes, size/L

#660 Convert multi-patch test to in-memory.
  pkg/commands/build/build_test.go
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch1.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch2.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/package/deployment.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/in/package/service.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-conflict/test.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/expected.diff
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/expected.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/overlay/patches/deployment-patch1.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/overlay/patches/deployment-patch2.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/package/deployment.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/in/package/service.yaml
  pkg/commands/build/testdata/testcase-multiple-patches-noconflict/test.yaml
  pkg/target/multiplepatch_test.go
  pkg/target/utils_for_test.go
Labels: approved, cncf-cla: yes, size/XL

#661 Convert variable tests to in-memory.
  pkg/commands/build/testdata/testcase-variable-ref-ingress/expected.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/deployment.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/ingress.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/base/service.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref-ingress/test.yaml
  pkg/commands/build/testdata/testcase-variable-ref/expected.diff
  pkg/commands/build/testdata/testcase-variable-ref/expected.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/package/cockroachdb-statefulset-secure.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/package/cronjob.yaml
  pkg/commands/build/testdata/testcase-variable-ref/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-variable-ref/test.yaml
  pkg/target/utils_for_test.go
  pkg/target/variableref_test.go
Labels: approved, cncf-cla: yes, size/XXL

#663 Convert generator merge and replace tests to in-memory.
  pkg/commands/build/testdata/testcase-base-only/expected.diff
  pkg/commands/build/testdata/testcase-base-only/expected.yaml
  pkg/commands/build/testdata/testcase-base-only/in/kustomization.yaml
  pkg/commands/build/testdata/testcase-base-only/in/resources/deployment.yaml
  pkg/commands/build/testdata/testcase-base-only/in/resources/networkpolicy.yaml
  pkg/commands/build/testdata/testcase-base-only/in/resources/service.yaml
  pkg/commands/build/testdata/testcase-base-only/test.yaml
  pkg/commands/build/testdata/testcase-single-overlay/expected.diff
  pkg/commands/build/testdata/testcase-single-overlay/expected.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/overlay/deployment.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/overlay/kustomization.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/package/deployment.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/package/kustomization.yaml
  pkg/commands/build/testdata/testcase-single-overlay/in/package/service.yaml
  pkg/commands/build/testdata/testcase-single-overlay/test.yaml
  pkg/target/generatormergeandreplace_test.go
Labels: approved, cncf-cla: yes, size/XXL

#664 Check for config merge conflicts and duplication.
  pkg/gvk/gvk.go
  pkg/resource/factory.go
  pkg/target/customconfig_test.go
  pkg/target/kusttarget.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factorycrd.go
  pkg/transformers/config/fieldspec.go
  pkg/transformers/config/fieldspec_test.go
  pkg/transformers/config/namebackreferences.go
  pkg/transformers/config/namebackreferences_test.go
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/config/transformerconfig_test.go
Labels: approved, cncf-cla: yes, size/L

#665 Convert CRD tests to in-memory.
  pkg/commands/build/testdata/testcase-crds/crd/bee.yaml
  pkg/commands/build/testdata/testcase-crds/crd/kustomization.yaml
  pkg/commands/build/testdata/testcase-crds/crd/mykind.yaml
  pkg/commands/build/testdata/testcase-crds/crd/secret.yaml
  pkg/commands/build/testdata/testcase-crds/expected.diff
  pkg/commands/build/testdata/testcase-crds/expected.yaml
  pkg/commands/build/testdata/testcase-crds/test.yaml
  pkg/target/crd_test.go
Labels: approved, cncf-cla: yes, size/L

#666 Convert configmap tests to in-memory.
  pkg/commands/build/testdata/testcase-configmaps/base/myapp/mycomponent/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/base/myapp/mycomponent2/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/expected.diff
  pkg/commands/build/testdata/testcase-configmaps/expected.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent2/kustomization.yaml
  pkg/commands/build/testdata/testcase-configmaps/test.yaml
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, size/L

#667 Convert namespaced generators to in-memory.
  pkg/commands/build/testdata/testcase-generators-namespace/expected.yaml
  pkg/commands/build/testdata/testcase-generators-namespace/in/kustomization.yaml
  pkg/commands/build/testdata/testcase-generators-namespace/in/password.txt
  pkg/commands/build/testdata/testcase-generators-namespace/test.yaml
  pkg/target/namespacedgenerators_test.go
Labels: approved, cncf-cla: yes, size/L

#671 Fix some comments and format nits.
  pkg/target/customconfig_test.go
  pkg/target/kusttarget.go
  pkg/transformers/config/transformerconfig.go
Labels: approved, cncf-cla: yes, size/S
