Repository kubernetes-sigs/kustomize, pull requests merged in 2018-06, with the labels that each got.

#49 Remove util and privatize selectByGvk
  pkg/commands/kustomizationfile.go
  pkg/commands/kustomizationfile_test.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/namehash.go
  pkg/transformers/namereference.go
  pkg/transformers/prefixname.go
  pkg/transformers/selectbygvk.go
  pkg/transformers/selectbygvk_test.go
Labels: cncf-cla: yes, size/S

#54 kustomize namespace
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, size/L

#56 Add expansion package
  pkg/expansion/expand.go
  pkg/expansion/expand_test.go
Labels: cncf-cla: yes, size/L

#58 add PodDisruptionBudget labels
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, size/XS

#59 add namerefs for hpa
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/M

#60 add namerefs for initContainers
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/L

#62 add namerefs for ingress
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/S

#63 Improve package structure and documentation.
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/commands/commands.go
  pkg/configmapandsecret/configmap_secret.go
  pkg/configmapandsecret/util/util.go
  pkg/diff/doc.go
  pkg/diff/rundiff.go
  pkg/fs/fs.go
  pkg/hash/hash.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/loader.go
  pkg/resmap/configmap_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/transformers/transformer.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, size/M

#64 Doc the error package.
  pkg/internal/error/configmaperror.go
Labels: cncf-cla: yes, size/XS

#52 variable reference support
  pkg/app/application.go
  pkg/commands/testdata/testcase-variable-ref/expected.diff
  pkg/commands/testdata/testcase-variable-ref/expected.yaml
  pkg/commands/testdata/testcase-variable-ref/in/overlay/kustomization.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/cockroachdb-statefulset-secure.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/kustomization.yaml
  pkg/commands/testdata/testcase-variable-ref/test.yaml
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/transformers/refvars.go
  pkg/types/kustomization.go
  pkg/types/var.go
Labels: cncf-cla: yes, size/XL

#66 Reduce indirection in code w/r to the unstruct types.
  pkg/app/application.go
  pkg/diff/rundiff.go
  pkg/resmap/configmap.go
  pkg/resmap/resmap.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
  pkg/resource/generationbehavior.go
  pkg/resource/resource.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/namehash.go
  pkg/transformers/namereference.go
  pkg/transformers/namespace.go
  pkg/transformers/overlay.go
  pkg/transformers/overlayconflictdetector.go
  pkg/transformers/prefixname.go
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, size/L

#72 Add wordpress example for demonstrating variable reference
  examples/wordpress/kustomization.yaml
  examples/wordpress/mysql/deployment.yaml
  examples/wordpress/mysql/kustomization.yaml
  examples/wordpress/mysql/secret.yaml
  examples/wordpress/mysql/service.yaml
  examples/wordpress/patch.yaml
  examples/wordpress/wordpress/deployment.yaml
  examples/wordpress/wordpress/kustomization.yaml
  examples/wordpress/wordpress/service.yaml
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, size/L

#71 add namespace to the doc
  docs/kustomization.yaml
Labels: cncf-cla: yes, size/XS

#76 Reduce unstruct notation noise in Resource construction.
  pkg/app/application_test.go
  pkg/resmap/configmap_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resmap/secret_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namehash_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/overlay_test.go
  pkg/transformers/prefixname_test.go
Labels: cncf-cla: yes, size/XXL

#77 Fix go lint error and add golint checks to a pre-commit hook
  bin/pre-commit.sh
  pkg/app/application.go
  pkg/configmapandsecret/util/configmap.go
  pkg/configmapandsecret/util/util.go
  pkg/internal/error/configmaperror.go
  pkg/internal/error/kustomizationerror.go
  pkg/internal/error/patcherror.go
  pkg/internal/error/resourceerror.go
  pkg/internal/error/secreterror.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/loader.go
  pkg/resmap/resmap.go
  pkg/resource/generationbehavior.go
  pkg/resource/resid.go
  pkg/resource/resource.go
  pkg/types/kustomization.go
  pkg/types/var.go
  version/version.go
Labels: cncf-cla: yes, size/M

#78 Fixed gocyclo warnings and added pre-commit hook
  .travis.yml
  bin/pre-commit.sh
  pkg/commands/build_test.go
  pkg/commands/diff_test.go
Labels: cncf-cla: yes, size/L

#80 Rename OverlayTranformer to PatchTransformer.
  pkg/app/application.go
  pkg/transformers/patch.go
  pkg/transformers/patch_test.go
  pkg/transformers/patchconflictdetector.go
Labels: cncf-cla: yes, size/M

#84 Add more test coverage for RawResources.
  Gopkg.lock
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/resmap/resmap.go
  pkg/resmap/secret.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/bench_test.go
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/errors_test.go
  vendor/github.com/pkg/errors/example_test.go
  vendor/github.com/pkg/errors/format_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/pkg/errors/stack_test.go
Labels: cncf-cla: yes, size/XXL

#83 Return error along with a resource
  pkg/resource/resource.go
Labels: cncf-cla: yes, size/XS

#82 Add Ingress spec.tls.secretName to Secret namerefs
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/XS

#89 Some cleanup refactoring in app package.
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/commands/build.go
  pkg/commands/diff.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/transformers/patch.go
  pkg/transformers/patchconflictdetector.go
Labels: cncf-cla: yes, size/L

#70 Skip adding nameprefix for CRD
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/prefixname.go
  pkg/transformers/prefixname_test.go
Labels: cncf-cla: yes, size/M

#81 refactor namespaces to use PathConfig
  pkg/app/application_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: cncf-cla: yes, size/M

#90 Add README.md for wordpress to show variable reference usage
  examples/README.md
  examples/wordpress/README.md
Labels: cncf-cla: yes, size/L

#93 make generated configmaps composable
  pkg/commands/testdata/testcase-configmaps/base/myapp/mycomponent/kustomization.yaml
  pkg/commands/testdata/testcase-configmaps/base/myapp/mycomponent2/kustomization.yaml
  pkg/commands/testdata/testcase-configmaps/expected.diff
  pkg/commands/testdata/testcase-configmaps/expected.yaml
  pkg/commands/testdata/testcase-configmaps/overlay/dev/kustomization.yaml
  pkg/commands/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent/kustomization.yaml
  pkg/commands/testdata/testcase-configmaps/overlay/dev/myapp/mycomponent2/kustomization.yaml
  pkg/commands/testdata/testcase-configmaps/test.yaml
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
Labels: cncf-cla: yes, size/L

#96 Fixes #33; add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#95 Add skeleton for CRD support
  docs/kustomization.yaml
  pkg/app/application.go
  pkg/crds/crds.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/labelsandannotationsconfig.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namereferenceconfig.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, size/L

#99 Absorb exec package from k8s.io/utils.
  Gopkg.lock
  pkg/diff/program.go
  pkg/exec/doc.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/exec/new_test.go
  vendor/k8s.io/utils/.travis.yml
  vendor/k8s.io/utils/HOWTOMOVE.md
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/README.md
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock_test.go
  vendor/k8s.io/utils/code-of-conduct.md
  vendor/k8s.io/utils/exec/doc.go
  vendor/k8s.io/utils/exec/new_test.go
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/k8s.io/utils/temp/dir.go
  vendor/k8s.io/utils/temp/dir_test.go
  vendor/k8s.io/utils/temp/doc.go
  vendor/k8s.io/utils/temp/temptest/dir.go
  vendor/k8s.io/utils/temp/temptest/dir_test.go
  vendor/k8s.io/utils/temp/temptest/file.go
  vendor/k8s.io/utils/temp/temptest/file_test.go
Labels: cncf-cla: yes, size/XXL

#101 Move version.go to commands dir.
  pkg/commands/commands.go
  pkg/commands/version.go
Labels: cncf-cla: yes, size/S

#102 Replace deprecated crypto/md5 with crypto/sha256
  pkg/configmapandsecret/util/util.go
Labels: cncf-cla: yes, size/XS

#104 Rename examples dir to examplelayout.
  pkg/commands/testdata/testcase-simple/test.yaml
  pkg/configmapandsecret/configmap_secret_test.go
  pkg/examplelayout/simple/instances/exampleinstance/configmap/app-init.ini
  pkg/examplelayout/simple/instances/exampleinstance/configmap/app.env
  pkg/examplelayout/simple/instances/exampleinstance/deployment/deployment.yaml
  pkg/examplelayout/simple/instances/exampleinstance/kustomization.yaml
  pkg/examplelayout/simple/instances/exampleinstance/secret/tls.cert
  pkg/examplelayout/simple/instances/exampleinstance/secret/tls.key
  pkg/examplelayout/simple/package/Kube-descriptor.yaml
  pkg/examplelayout/simple/package/deployment/deployment.yaml
  pkg/examplelayout/simple/package/kustomization.yaml
  pkg/examplelayout/simple/package/service/service.yaml
Labels: cncf-cla: yes, size/XS

#108 Add variable reference support for args
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, size/S

#110 Add gometalinter to pre-commit hook
  .travis.yml
  bin/pre-commit.sh
  pkg/commands/configmap.go
  pkg/commands/init.go
  pkg/configmapandsecret/util/env_file.go
  pkg/configmapandsecret/util/util.go
  pkg/diff/program.go
  pkg/exec/exec_test.go
  pkg/fs/fakefile.go
  pkg/hash/hash_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
Labels: cncf-cla: yes, size/L

#111 Add variable reference to container env
  examples/wordpress/README.md
  examples/wordpress/patch.yaml
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, lgtm, size/S

#115 Update example to show correct environment
  examples/springboot/overlays/production/patch.yaml
Labels: cncf-cla: yes, size/XS

#113 Enable unparam linter and fix found issues
  bin/pre-commit.sh
  pkg/commands/addpatch.go
  pkg/commands/addpatch_test.go
  pkg/commands/addresource.go
  pkg/commands/addresource_test.go
  pkg/commands/build.go
  pkg/commands/build_test.go
  pkg/commands/commands.go
  pkg/commands/configmap.go
  pkg/commands/configmap_test.go
  pkg/commands/diff.go
  pkg/commands/kustomizationfile.go
  pkg/commands/set_name_prefix.go
  pkg/commands/set_name_prefix_test.go
  pkg/configmapandsecret/configmap_secret_test.go
  pkg/configmapandsecret/util/util.go
  pkg/diff/rundiff.go
  pkg/transformers/namehash.go
Labels: cncf-cla: yes, size/L

#123 Add variable reference to pod command,args,env
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, lgtm, size/S

#121 Jobs do not create a selector if not already present
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, size/L

#125 put namespace objects first in the output
  pkg/resmap/idslice.go
  pkg/resmap/idslice_test.go
Labels: cncf-cla: yes, size/M

#120 New command: kustomize edit add base
  pkg/commands/addbase.go
  pkg/commands/addbase_test.go
  pkg/commands/commands.go
Labels: cncf-cla: yes, size/L

#130 add imagePullSecrets namerefs
  pkg/transformers/namereference_test.go
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/M

#132 correct ordering of the k8s objects
  pkg/commands/testdata/testcase-variable-ref/expected.yaml
  pkg/resmap/idslice.go
  pkg/resmap/idslice_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#129 Enhancement for format error message
  pkg/commands/build.go
  pkg/internal/error/yamlformaterror.go
  pkg/internal/error/yamlformaterror_test.go
  pkg/resmap/resmap.go
Labels: cncf-cla: yes, size/L

#138 Adds example for secret download using curl
  docs/kustomization.yaml
Labels: cncf-cla: yes, size/XS

#137 Add CronJob to refvars transformer
  pkg/commands/testdata/testcase-variable-ref/expected.diff
  pkg/commands/testdata/testcase-variable-ref/expected.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/cronjob.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/kustomization.yaml
  pkg/transformers/refvars.go
Labels: cncf-cla: yes, size/M

#133 Add glob support
  pkg/commands/testdata/testcase-base-only/in/kustomization.yaml
  pkg/commands/testdata/testcase-base-only/in/resources/deployment.yaml
  pkg/commands/testdata/testcase-base-only/in/resources/service.yaml
  pkg/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomization.yaml
  pkg/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/patches/deployment-patch1.yaml
  pkg/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/patches/deployment-patch2.yaml
  pkg/crds/crds_test.go
  pkg/fs/fakefs.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/fs/realfs_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/loader.go
  pkg/resmap/resmap.go
  pkg/transformers/pathconfig.go
Labels: cncf-cla: yes, lgtm, size/L
