Repository kubernetes-sigs/kustomize, pull requests merged in 2018-07, with the labels that each got.

#150 add PersistentVolumeClaim to name reference transformer
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/M

#151 docs(vars): Add some documentation explaining the usage and limits of vars
  docs/kustomization.yaml
Labels: cncf-cla: yes, size/M

#158 Interpret projected configMap volume names
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/L

#140 Add NetworkPolicy to label transformer
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, lgtm, size/S

#145 Add common labels to pod affinity/anti-affinity label selector
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, size/M

#146 Run namehash transformer before resolving names for refvars
  pkg/app/application.go
  pkg/commands/testdata/testcase-variable-ref/expected.diff
  pkg/commands/testdata/testcase-variable-ref/expected.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/cronjob.yaml
  pkg/commands/testdata/testcase-variable-ref/in/package/kustomization.yaml
Labels: cncf-cla: yes, size/M

#166 Add namespace transformation for subjects.namespace in ClusterRoleBinding
  pkg/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomization.yaml
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, size/L

#175 skip adding namespace to CustomResourceDefinitions
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#177 Replace os.Stat with IsDir and Exists, simplifying FS abstraction.
  Gopkg.lock
  pkg/app/application_test.go
  pkg/commands/addbase.go
  pkg/commands/addbase_test.go
  pkg/commands/addpatch.go
  pkg/commands/addresource.go
  pkg/commands/kustomizationfile.go
  pkg/commands/kustomizationfile_test.go
  pkg/fs/fakefs.go
  pkg/fs/fakefs_test.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/fs/realfs_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/resmap/secret.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#180 Fix configGeneration.md
  examples/configGeneration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 configMap factory refactor for #86
  pkg/commands/cmapflagsandargs.go
  pkg/commands/cmapflagsandargs_test.go
  pkg/commands/configmap.go
  pkg/commands/configmap_test.go
  pkg/configmapandsecret/configmap_secret.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/configmapandsecret/util/configmap.go
  pkg/configmapandsecret/util/env_file.go
  pkg/configmapandsecret/util/secret.go
  pkg/configmapandsecret/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#182 Add ContainerRef in kustomization type
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 Disable NetworkPolicy podSelector.matchLabels CreateIfNotPresent
  pkg/commands/testdata/testcase-base-only/expected.diff
  pkg/commands/testdata/testcase-base-only/expected.yaml
  pkg/commands/testdata/testcase-base-only/in/resources/networkpolicy.yaml
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, lgtm, size/M

#183 Remove a util package; more cleanup for #86
  pkg/configmapandsecret/addfromenvfile.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/util/util.go
  pkg/resmap/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#185 Start remerging two forked sets of configmap factory code
  pkg/commands/configmap.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/configmapandsecret/kv.go
  pkg/configmapandsecret/kv_test.go
  pkg/resmap/configmap.go
Labels: approved, cncf-cla: yes, size/L

#186 Inject a file system object into "Application".
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/commands/build.go
  pkg/commands/configmap.go
  pkg/commands/diff.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/resmap/configmap.go
  pkg/resmap/configmap_test.go
Labels: approved, cncf-cla: yes, size/M

#184 Add imageTagTransformer
  pkg/transformers/imagetag.go
  pkg/transformers/imagetag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 Introduce secret factory.
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/secretfactory.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 Enable imageTagTransformer in application
  pkg/app/application.go
  pkg/commands/testdata/testcase-simple/expected.diff
  pkg/commands/testdata/testcase-simple/expected.yaml
  pkg/examplelayout/simple/instances/exampleinstance/kustomization.yaml
  pkg/transformers/imagetag.go
  pkg/transformers/imagetag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#192 Add set imagetag command
  pkg/commands/commands.go
  pkg/commands/setimagetag.go
  pkg/commands/setimagetag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#195 Pull factories up call stack (make them less often).
  pkg/app/application.go
  pkg/commands/configmap.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/configmapandsecret/secretfactory.go
  pkg/resmap/configmap.go
  pkg/resmap/configmap_test.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
Labels: approved, cncf-cla: yes, size/L

#194 fixed version info injection in build script
  build/build.sh
  build/goreleaser.yaml
  build/goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#191 Fix wrong path in diff tests on macOS
  pkg/commands/diff_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#198 Delete some code.
  pkg/configmapandsecret/configmapfactory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#196 Add docs and demo for imageTags
  docs/kustomization.yaml
  examples/README.md
  examples/imageTags.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#197 Change configmapGenerator to configmap.yaml in helloWorld example
  examples/README.md
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/helloWorld/README.md
  examples/helloWorld/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#199 Drop the notion of the SchemeLoader
  pkg/commands/build.go
  pkg/commands/diff.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
Labels: approved, cncf-cla: yes, size/L

#200 Delete duplicative code.
  pkg/commands/configmap.go
  pkg/configmapandsecret/addfromenvfile.go
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/configmapandsecret/kv.go
  pkg/resmap/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#201 Combine loaderImpl and fileLoader.
  pkg/commands/build.go
  pkg/commands/configmap.go
  pkg/commands/diff.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#203 More information in error message when secret gen fails
  pkg/configmapandsecret/secretfactory.go
Labels: cncf-cla: yes, lgtm, size/XS

#204 Add support for using common base
  examples/README.md
  examples/multibases/README.md
  examples/multibases/base/kustomization.yaml
  examples/multibases/base/pod.yaml
  examples/multibases/dev/kustomization.yaml
  examples/multibases/kustomization.yaml
  examples/multibases/production/kustomization.yaml
  examples/multibases/staging/kustomization.yaml
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/diff/rundiff.go
  pkg/resmap/resmap.go
  pkg/resource/resid.go
  pkg/transformers/patch.go
  pkg/transformers/prefixname.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#213 use regexp to determine if the image matched in imagetag transformer
  pkg/transformers/imagetag.go
  pkg/transformers/imagetag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#209 ignore the empty YAML object
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
Labels: approved, cncf-cla: yes, size/S

#214 add namespace in ResId
  pkg/app/application_test.go
  pkg/resource/resid.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#215 Enumerate eschewed features in a document.
  docs/eschewedFeatures.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#216 Add multibases example with different namespace
  examples/multibases/README.md
  examples/multibases/multi-namespace.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#219 remove glob support from kustomization.yaml
  examples/multibases/multi-namespace.md
  pkg/commands/testdata/testcase-base-only/in/kustomization.yaml
  pkg/resmap/resmap.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#220 Eschew globbing doc
  docs/eschewedFeatures.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#223 More description of eschewed features
  docs/eschewedFeatures.md
Labels: approved, cncf-cla: yes
