Repository kubernetes-sigs/kustomize, pull requests merged in 2018-08, with the labels that each got.

#224 Use regexp in set imagetag
  pkg/commands/setimagetag.go
  pkg/commands/setimagetag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#222 Add glob support in edit add resource
  pkg/commands/addresource.go
  pkg/commands/addresource_test.go
  pkg/fs/fakefs.go
  pkg/fs/fakefs_test.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/fs/realfs_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#228 Change the order of validate and expandFileSource in add configmap
  pkg/commands/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 Container Builder has been renamed Cloud Build
  build/README.md
Labels: cncf-cla: yes, lgtm, size/S

#237 add namepreference for secret in ingress annotation
  pkg/transformers/namereference_test.go
  pkg/transformers/namereferenceconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#239 Skip adding nameprefix to namespace
  pkg/app/application_test.go
  pkg/transformers/prefixname.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#240 Revert "Skip adding nameprefix to namespace"
  pkg/app/application_test.go
  pkg/transformers/prefixname.go
Labels: approved, cncf-cla: yes, size/XS

#233 preserve order and comments in edit
  pkg/app/application.go
  pkg/commands/kustomizationfile.go
  pkg/commands/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#243 Automated update of Gopkg.lock via dep ensure
  Gopkg.lock
Labels: approved, cncf-cla: yes, lgtm, size/L

#244 Add deprecation message for namePrefix behavior change
  pkg/transformers/prefixname.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#241 add env sources to secrets
  pkg/configmapandsecret/secretfactory.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, lgtm, size/L

#245 Add -o flag to kustomize build
  pkg/commands/build.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#247 add support for `kustomize edit set namespace`
  pkg/commands/commands.go
  pkg/commands/setnamespace.go
  pkg/commands/setnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#250 Don't crash on resource load errors
  pkg/app/application_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
Labels: cncf-cla: yes, lgtm, size/M

#256 Add timeoutSeconds to secretArgs
  docs/kustomization.yaml
  pkg/app/application_test.go
  pkg/configmapandsecret/secretfactory.go
  pkg/resmap/secret_test.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, lgtm, size/M

#255 add docs for envCommand
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 Add kustomize build {repoUrl}
  pkg/commands/build.go
  pkg/commands/diff.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/githubloader.go
  pkg/loader/loader.go
  vendor/github.com/hashicorp/go-getter/get.go
  vendor/github.com/hashicorp/go-getter/get_s3.go
  vendor/github.com/hashicorp/go-getter/get_s3_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#266 add homebrew package to INSTALL.md
  INSTALL.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#264 Add example for kustomize build {url} and remote bases
  docs/glossary.md
  docs/kustomization.yaml
  examples/README.md
  examples/remoteBuild.md
  pkg/commands/build.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#265 add typemeta to kustomization
  pkg/commands/kustomizationfile.go
  pkg/commands/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 Add namereference of PersistentVolume in PersistentVolumeClain
  pkg/transformers/namereferenceconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#270 fix bug in the example download links
  examples/wordpress/README.md
Labels: approved, cncf-cla: yes, size/XS

#147 Edit add label/annotation
  pkg/commands/addmetadata.go
  pkg/commands/addmetadata_test.go
  pkg/commands/commands.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: cncf-cla: yes, lgtm, size/XL

#271 cleanup after handling remote bases
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/githubloader.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#275 Delete diff command and code it uses.
  pkg/app/application.go
  pkg/app/application_test.go
  pkg/commands/commands.go
  pkg/commands/diff.go
  pkg/commands/diff_test.go
  pkg/diff/directory.go
  pkg/diff/program.go
  pkg/diff/rundiff.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#276 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved

#281 Add varcheck to presubmit.
  .travis.yml
  bin/pre-commit.sh
Labels: approved, cncf-cla: yes, size/XS

#279 fix the double quotation problem in ConfigMapGenerator
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/resmap/configmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#280 Fix some Go nits.
  pkg/commands/kustomizationfile.go
  pkg/commands/setimagetag.go
  pkg/commands/setimagetag_test.go
  pkg/resmap/resmap.go
  pkg/transformers/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#284 Add missing files when running dep ensure
  vendor/github.com/hashicorp/go-getter/get.go
  vendor/github.com/hashicorp/go-getter/get_s3.go
  vendor/github.com/hashicorp/go-getter/get_s3_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#285 Move some docs to docs dir (declutter the top).
  README.md
  code-of-conduct.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/INSTALL.md
  docs/README.md
  docs/SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#287 Fix loader loader when run from gopath
  pkg/loader/githubloader.go
  pkg/loader/githubloader_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#290 trivial: Change dep constraint to an override
  Gopkg.toml
Labels: cncf-cla: yes, lgtm, size/XS

#292 Disable creation of PDB matchLabels
  pkg/transformers/labelsandannotationsconfig.go
Labels: cncf-cla: yes, lgtm, size/XS

#286 Add patchesJson6902 and patchesStategicMerge to kustomization
  pkg/app/application.go
  pkg/patch/jsonpatch.go
  pkg/patch/strategicmergepatch.go
  pkg/resmap/resmap.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#302 Storage class secret
  pkg/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/S

#303 if the prefix of the base is 'git::' will make the use of go-getter to download repo
  pkg/loader/githubloader.go
  pkg/loader/githubloader_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#307 use apimachinery for annotation/label validation
  Gopkg.lock
  pkg/commands/addmetadata.go
  pkg/commands/addmetadata_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: cncf-cla: yes, size/L

#300 Add transformer to apply json patch6902
  Gopkg.lock
  Gopkg.toml
  pkg/patch/jsonpatch.go
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/patch/transformer/patchjson6902yaml.go
  pkg/patch/transformer/patchjson6902yaml_test.go
  pkg/patch/transformer/util.go
  vendor/github.com/krishicks/yaml-patch/LICENSE
  vendor/github.com/krishicks/yaml-patch/Makefile
  vendor/github.com/krishicks/yaml-patch/README.md
  vendor/github.com/krishicks/yaml-patch/cmd/yaml-patch/file_flag.go
  vendor/github.com/krishicks/yaml-patch/cmd/yaml-patch/main.go
  vendor/github.com/krishicks/yaml-patch/cmd/yaml-patch/main_suite_test.go
  vendor/github.com/krishicks/yaml-patch/cmd/yaml-patch/main_test.go
  vendor/github.com/krishicks/yaml-patch/container.go
  vendor/github.com/krishicks/yaml-patch/node.go
  vendor/github.com/krishicks/yaml-patch/operation.go
  vendor/github.com/krishicks/yaml-patch/patch.go
  vendor/github.com/krishicks/yaml-patch/patch_test.go
  vendor/github.com/krishicks/yaml-patch/pathfinder.go
  vendor/github.com/krishicks/yaml-patch/pathfinder_test.go
  vendor/github.com/krishicks/yaml-patch/placeholder_wrapper.go
  vendor/github.com/krishicks/yaml-patch/placeholder_wrapper_test.go
  vendor/github.com/krishicks/yaml-patch/yaml_patch_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#309 Simplify addmetadata.
  pkg/commands/addmetadata.go
  pkg/commands/addmetadata_test.go
  pkg/commands/commands.go
  pkg/validators/validators.go
Labels: approved, cncf-cla: yes, lgtm, size/L
