Repository kubernetes-sigs/kustomize, pull requests merged in 2018-11, with the labels that each got.

#528 add fallback for GVK comparison
  pkg/gvk/gvk.go
  pkg/gvk/gvk_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#529 Fix typo in namereference path for cronjobs
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#530 Update default var reference link
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#501 Add example for generatorOptions
  docs/kustomization.yaml
  examples/README.md
  examples/generatorOptions.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#522 make sure the objects loaded have name and kind
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#534 Add/fix some documentation and vars names.
  k8sdeps/kunstruct/factory.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget.go
  pkg/transformers/namereference.go
  pkg/transformers/prefixname.go
  pkg/transformers/util.go
Labels: approved, cncf-cla: yes, size/L

#533 fix incorrect path in default namereference configs
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#536 Update TransformerConfig.Merge function to handle nil
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/config/transformerconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 Fix typos: expectd->expected, cluser->cluster
  examples/combineConfigs.md
  pkg/transformers/labelsandannotations.go
  pkg/transformers/namereference.go
  pkg/transformers/prefixname.go
  pkg/transformers/refvars.go
  pkg/transformers/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#542 remove glog dependency from kustomize code
  Gopkg.lock
  Gopkg.toml
  kustomize.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, size/S

#543 Add StorageClass to the list of ordered objects
  pkg/gvk/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#550 Enable namePrefixTransformer to append name suffix
  pkg/commands/build/testdata/testcase-variable-ref/expected.yaml
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/target/kusttarget.go
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/config/transformerconfig_test.go
  pkg/transformers/prefixsuffixname.go
  pkg/transformers/prefixsuffixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#546 update docs for vars
  examples/README.md
  examples/wordpress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#544 Remove -t flag in build and add configurations field in kustomization file
  examples/transformerconfigs/README.md
  examples/transformerconfigs/crd/README.md
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#556 Add nameSuffix field to kustomization.yaml
  pkg/commands/edit/all.go
  pkg/commands/edit/set/all.go
  pkg/commands/edit/set/set_name_suffix.go
  pkg/commands/edit/set/set_name_suffix_test.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/fs/fakefs.go
  pkg/resid/resid.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#569 Add removeAll to fakeFs
  pkg/fs/fakefs.go
  pkg/fs/fakefs_test.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
Labels: approved, cncf-cla: yes, size/M

#570 Add test coverage to gitloader.
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/githubloader.go
  pkg/loader/githubloader_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, size/L

#571 Rename gitloader to gitcloner.
  pkg/loader/gitcloner.go
  pkg/loader/gitcloner_test.go
Labels: approved, cncf-cla: yes, size/S

#573 Enforce relocatable kustomizations.
  k8sdeps/configmapandsecret/configmapfactory_test.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/patch/transformer/factory_test.go
  pkg/resmap/factory_test.go
  pkg/resource/factory_test.go
  pkg/transformers/config/factory_test.go
  pkg/transformers/config/factorycrd_test.go
Labels: approved, cncf-cla: yes, size/M

#574 Introduce simple git cloner.
  pkg/loader/fileloader.go
  pkg/loader/gitcloner.go
  pkg/loader/gitcloner_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, size/L

#576 Remove stray comment.
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes

#547 POC: allow accessing labels and annotations in vars
  k8sdeps/kunstruct/helper.go
  k8sdeps/kunstruct/kunstruct.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#577 Deal with branch spec in simpleGitCloner.
  pkg/loader/gitcloner.go
  pkg/loader/gitcloner_test.go
Labels: approved, cncf-cla: yes, size/L

#578 Turn off hashicorp cloner, turn on simple cloner.
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, size/XS

#563 update crd example by using configurations file list
  examples/transformerconfigs/README.md
  examples/transformerconfigs/crd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#582 Add test for mutatefield
  pkg/transformers/mutatefield.go
  pkg/transformers/mutatefield_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#583 Ignore empty fields targeted by transformations.
  pkg/transformers/mutatefield.go
  pkg/transformers/mutatefield_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#565 Update docs, examples, comments, and test data for nameSuffix
  docs/glossary.md
  docs/kustomization.yaml
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/transformerconfigs/README.md
  pkg/commands/build/testdata/testcase-multibases-conflict/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/overlays/a/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-conflict/overlays/b/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/base/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/expected.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/overlays/a/kustomization.yaml
  pkg/commands/build/testdata/testcase-multibases-nonconflict/overlays/b/kustomization.yaml
  pkg/patch/json6902.go
  pkg/types/var.go
Labels: approved, cncf-cla: yes, lgtm, size/M
