Repository kubernetes-sigs/kustomize, pull requests merged in 2018-10, with the labels that each got.

#385 Fix some Go nits.
  docs/glossary.md
  pkg/commands/build.go
  pkg/loader/githubloader.go
  pkg/patch/json6902.go
  pkg/patch/strategicmerge.go
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/factory_test.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#391 change sets.NewString() to []string
  pkg/commands/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 Add tests for patch/resource reading.
  pkg/resmap/resmap.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#397 fix kustomize edit add label bug
  pkg/validators/validators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#394 use local types in var reference
  pkg/expansion/expand_test.go
  pkg/target/kusttarget.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#398 Introduce k8sdeps package to isolate k8s deps.
  pkg/commands/build.go
  pkg/commands/build_test.go
  pkg/commands/commands.go
  pkg/ifc/ifc.go
  pkg/internal/k8sdeps/decoder.go
  pkg/internal/k8sdeps/doc.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#400 Add validator interface
  pkg/commands/addmetadata.go
  pkg/commands/commands.go
  pkg/commands/setnamespace.go
  pkg/commands/setnamespace_test.go
  pkg/ifc/ifc.go
  pkg/internal/k8sdeps/validators.go
  pkg/validators/validators.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#403 Isolate k8sdeps to top level internal.
  internal/k8sdeps/decoder.go
  internal/k8sdeps/doc.go
  internal/k8sdeps/validators.go
  kustomize.go
  pkg/commands/build_test.go
  pkg/commands/commands.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#405 Isolate generator calls.
  pkg/resmap/resmap.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#406 error out if patchesJson6902 target can't be found, fixes #335
  pkg/patch/transformer/util.go
Labels: cncf-cla: yes, lgtm, size/XS

#415 Fix some go nits.
  pkg/commands/build/build_test.go
  pkg/commands/misc/config.go
  pkg/commands/misc/config_test.go
Labels: approved, cncf-cla: yes, size/XS

#411 decouple configmapandsecret and hash packages
  pkg/commands/edit/add/configmap.go
  pkg/configmapandsecret/configmapfactory.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#419 Delete unused unstruct code.
  pkg/configmapandsecret/configmapfactory.go
  pkg/configmapandsecret/configmapfactory_test.go
Labels: approved, cncf-cla: yes, size/M

#418 combine HashComfigMap and HashSecret to Hash
  pkg/hash/hash.go
  pkg/transformers/namehash.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#416 Move ResId to its own package.
  pkg/configmapandsecret/configmapfactory.go
  pkg/crds/crds.go
  pkg/crds/crds_test.go
  pkg/ifc/generationbehavior.go
  pkg/ifc/ifc.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader.go
  pkg/loader/githubloader.go
  pkg/loader/loader.go
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/patch/transformer/patchjson6902yaml.go
  pkg/patch/transformer/patchjson6902yaml_test.go
  pkg/patch/transformer/util.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/resmap/configmap.go
  pkg/resmap/configmap_test.go
  pkg/resmap/idslice.go
  pkg/resmap/idslice_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
  pkg/resource/resource.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformerconfig/transformerconfig.go
  pkg/transformerconfig/transformerconfig_test.go
  pkg/transformers/imagetag_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namehash_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/patch_test.go
  pkg/transformers/prefixname_test.go
  vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/dirstate
Labels: approved, cncf-cla: yes, lgtm, size/L

#421 Add hash interface
  internal/k8sdeps/hash.go
  internal/k8sdeps/hash_test.go
  kustomize.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/commands.go
  pkg/ifc/ifc.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformers/namehash.go
  pkg/transformers/namehash_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#422 unify processing of JSON6902 patches for both json and yaml format
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/patch/transformer/patchjson6902yaml.go
  pkg/patch/transformer/patchjson6902yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#425 use 'sed -i.bak' instead of 'sed -i' to make it compatible with macos…
  .gitignore
  examples/configGeneration.md
  examples/helloWorld/README.md
  examples/mySql/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#427 add tests for resmap
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#423 Hide unstructured.Unstructured behind interface.
  internal/k8sdeps/hash.go
  internal/k8sdeps/unstructadapter.go
  internal/k8sdeps/unstructadapter_test.go
  pkg/commands/build/build_test.go
  pkg/configmapandsecret/configmapfactory_test.go
  pkg/ifc/ifc.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/resmap/configmap.go
  pkg/resmap/configmap_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformers/imagetag.go
  pkg/transformers/imagetag_test.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namehash.go
  pkg/transformers/namehash_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
  pkg/transformers/patch.go
  pkg/transformers/patch_test.go
  pkg/transformers/patchconflictdetector.go
  pkg/transformers/prefixname.go
  pkg/transformers/prefixname_test.go
  pkg/transformers/refvars.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#431 remove apimachinery dependency from internal/error package
  pkg/internal/error/yamlformaterror.go
  pkg/internal/error/yamlformaterror_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#432 Gather resmap factory code into one file.
  pkg/resmap/configmap.go
  pkg/resmap/configmap_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resmap/secret.go
  pkg/resmap/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#434 Fix some minor naming mistakes.
  internal/k8sdeps/kunstructuredfactory.go
  internal/k8sdeps/kunstructuredfactory_test.go
  internal/k8sdeps/patch/patch_test.go
  internal/k8sdeps/unstructadapter_test.go
  kustomize.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/commands.go
  pkg/crds/crds_test.go
  pkg/ifc/patch/patch.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformers/imagetag_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namehash_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, size/M

#435 fix the flaky test in crd package
  pkg/crds/crds_test.go
Labels: approved, cncf-cla: yes, size/XS

#437 port to golangci and make travisci improvements
  .golangci.yml
  .travis.yml
  bin/pre-commit.sh
Labels: cncf-cla: yes, size/M

#441 Replant tree (needed for example tests).
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#440 Maintain fields of TransformerConfig in sorted order.
  pkg/crds/crds.go
  pkg/crds/crds_test.go
  pkg/transformerconfig/transformerconfig.go
Labels: approved, cncf-cla: yes, size/M

#443 Use Go 1.11 for CI Builds
  .travis.yml
Labels: cncf-cla: yes, lgtm, size/XS

#444 hide core/v1 behind interface
  internal/k8sdeps/configmapandsecret/configmapfactory.go
  internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  internal/k8sdeps/configmapandsecret/kv.go
  internal/k8sdeps/configmapandsecret/kv_test.go
  internal/k8sdeps/configmapandsecret/secretfactory.go
  internal/k8sdeps/kunstructuredfactory.go
  pkg/commands/commands.go
  pkg/commands/edit/add/all.go
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/add/configmap_test.go
  pkg/commands/edit/all.go
  pkg/ifc/ifc.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#445 copy TypeMeta from apimachinery
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#449 Consolidate TransformerConfig creation to factory.
  pkg/commands/build/build.go
  pkg/crds/crds.go
  pkg/crds/crds_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformerconfig/factory.go
  pkg/transformerconfig/factory_test.go
  pkg/transformerconfig/transformerconfig.go
  pkg/transformerconfig/transformerconfig_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#450 Move crd package to transformerconfig.factory.
  pkg/target/kusttarget.go
  pkg/transformerconfig/constants.go
  pkg/transformerconfig/factory.go
  pkg/transformerconfig/factorycrd.go
  pkg/transformerconfig/factorycrd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#451 add MakeHashTransformer in TransformerFactory; remove hash interface
  internal/k8sdeps/transformer/factory.go
  internal/k8sdeps/transformer/hash/hash.go
  internal/k8sdeps/transformer/hash/hash_test.go
  internal/k8sdeps/transformer/hash/namehash.go
  internal/k8sdeps/transformer/hash/namehash_test.go
  internal/k8sdeps/transformer/patch/patch.go
  internal/k8sdeps/transformer/patch/patch_test.go
  internal/k8sdeps/transformer/patch/patchconflictdetector.go
  kustomize.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/commands.go
  pkg/ifc/ifc.go
  pkg/ifc/transformer/transformer.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#452 move transformerconfig package to transformers/config
  pkg/commands/build/build.go
  pkg/commands/misc/config.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/transformers/config/constants.go
  pkg/transformers/config/defaultconfig/commonannotations.go
  pkg/transformers/config/defaultconfig/commonlabels.go
  pkg/transformers/config/defaultconfig/defaultconfig.go
  pkg/transformers/config/defaultconfig/nameprefix.go
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/config/defaultconfig/namespace.go
  pkg/transformers/config/defaultconfig/varreference.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factory_test.go
  pkg/transformers/config/factorycrd.go
  pkg/transformers/config/factorycrd_test.go
  pkg/transformers/config/pathconfig.go
  pkg/transformers/config/pathconfig_test.go
  pkg/transformers/config/referencepathconfig.go
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/config/transformerconfig_test.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namespace.go
  pkg/transformers/prefixname.go
  pkg/transformers/refvars.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#454 Literals documentation configMap Generation
  docs/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#457 split k8sdeps package into sub packages
  internal/k8sdeps/kunstruct/factory.go
  internal/k8sdeps/kunstruct/factory_test.go
  internal/k8sdeps/kunstruct/kunstruct.go
  internal/k8sdeps/kunstruct/kunstruct_test.go
  internal/k8sdeps/transformer/hash/namehash_test.go
  internal/k8sdeps/transformer/patch/patch_test.go
  internal/k8sdeps/validator/validators.go
  kustomize.go
  pkg/commands/build/build_test.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget_test.go
  pkg/transformers/imagetag_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#455 Add KustFactory as a wrapper of all factories
  internal/k8sdeps/factory.go
  kustomize.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/commands.go
  pkg/factory/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#458 Notes on mySql example
  examples/mySql/README.md
  examples/mySql/secret.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#462 Fix names/doc in transformation config code.
  internal/k8sdeps/transformer/hash/namehash.go
  pkg/commands/misc/config.go
  pkg/target/kusttarget.go
  pkg/transformers/config/defaultconfig/commonannotations.go
  pkg/transformers/config/defaultconfig/commonlabels.go
  pkg/transformers/config/defaultconfig/defaultconfig.go
  pkg/transformers/config/defaultconfig/nameprefix.go
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/config/defaultconfig/namespace.go
  pkg/transformers/config/defaultconfig/varreference.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factory_test.go
  pkg/transformers/config/factorycrd.go
  pkg/transformers/config/factorycrd_test.go
  pkg/transformers/config/fieldspec.go
  pkg/transformers/config/fieldspec_test.go
  pkg/transformers/config/namebackreferences.go
  pkg/transformers/config/namebackreferences_test.go
  pkg/transformers/config/pathconfig.go
  pkg/transformers/config/referencepathconfig.go
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/config/transformerconfig_test.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/namereference.go
  pkg/transformers/namespace.go
  pkg/transformers/prefixname.go
  pkg/transformers/refvars.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#465 Move yaml check to file in which it is called.
  internal/k8sdeps/kunstruct/factory.go
  internal/k8sdeps/kunstruct/kunstruct.go
Labels: approved, cncf-cla: yes, size/XS

#466 Improve unstruct test coverage and error messages.
  internal/k8sdeps/kunstruct/kunstruct.go
  internal/k8sdeps/kunstruct/kunstruct_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#467 Delete some kunstruct code in favor of apimachinery code.
  internal/k8sdeps/kunstruct/kunstruct.go
  internal/k8sdeps/kunstruct/kunstruct_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#468 add missing lines after copyright
  internal/k8sdeps/configmapandsecret/kv_test.go
  internal/k8sdeps/factory.go
Labels: approved, cncf-cla: yes, size/XS

#469 fix lint errors in internal
  internal/k8sdeps/factory.go
  internal/k8sdeps/transformer/factory.go
  internal/k8sdeps/transformer/patch/patchconflictdetector.go
Labels: approved, cncf-cla: yes, size/S

#472 fix copyright misalignment
  internal/k8sdeps/factory.go
Labels: approved, cncf-cla: yes, size/XS

#475 add namespace to id when create resmap from files
  pkg/resmap/factory_test.go
  pkg/resource/factory_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#481 Delete unused exec package.
  pkg/exec/doc.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/exec/new_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#482 fix kustomize edit add label bug
  internal/k8sdeps/validator/validators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#483 add commonLabel fieldpath for volumeClaimTemplates
  pkg/transformers/config/defaultconfig/commonlabels.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#477 skip filtering resmap when the resource is a cluster level resource
  pkg/gvk/gvk.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#485 Delete some unnecessary parameter passing.
  pkg/commands/edit/add/addbase.go
  pkg/commands/edit/add/addbase_test.go
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/edit/add/addmetadata_test.go
  pkg/commands/edit/add/addpatch.go
  pkg/commands/edit/add/addpatch_test.go
  pkg/commands/edit/add/addresource.go
  pkg/commands/edit/add/addresource_test.go
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/set/set_name_prefix.go
  pkg/commands/edit/set/set_name_prefix_test.go
  pkg/commands/edit/set/setimagetag.go
  pkg/commands/edit/set/setimagetag_test.go
  pkg/commands/edit/set/setnamespace.go
  pkg/commands/edit/set/setnamespace_test.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/fs/fakefs.go
  pkg/internal/error/configmaperror_test.go
  pkg/internal/error/kustomizationerror_test.go
  pkg/internal/error/patcherror_test.go
  pkg/internal/error/resourceerror_test.go
  pkg/internal/error/secreterror_test.go
  pkg/internal/error/yamlformaterror_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#488 Skip adding nameprefix to namespace
  pkg/target/kusttarget_test.go
  pkg/transformers/prefixname.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#490 Add generatorOptions in Kustomization type
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#487 Delete penultimate use of Patches field.
  pkg/commands/edit/add/addpatch.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#494 allow add labels/annotations to generated resources
  internal/k8sdeps/configmapandsecret/configmapfactory.go
  internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  internal/k8sdeps/configmapandsecret/secretfactory.go
  internal/k8sdeps/kunstruct/factory.go
  pkg/commands/edit/add/configmap.go
  pkg/ifc/ifc.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#495 Test field output ordering.
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#496 enable preserving order with generatorOptions
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#497 Allow setting shell and timeout in generatorOptions
  internal/k8sdeps/configmapandsecret/secretfactory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#500 create namespace resource if not found
  pkg/target/kusttarget.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#498 Add example for transformer configurations: crd
  examples/README.md
  examples/transformerconfigs/README.md
  examples/transformerconfigs/crd/README.md
  examples/transformerconfigs/crd/kustomization.yaml
  examples/transformerconfigs/crd/resources.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#510 fix goreleaser version injection
  build/goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 make k8sdeps.NewFactory() importable
  build/vendor_kustomize.sh
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/kv.go
  k8sdeps/configmapandsecret/kv_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/doc.go
  k8sdeps/factory.go
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
  k8sdeps/kunstruct/kunstruct.go
  k8sdeps/kunstruct/kunstruct_test.go
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/hash/hash.go
  k8sdeps/transformer/hash/hash_test.go
  k8sdeps/transformer/hash/namehash.go
  k8sdeps/transformer/hash/namehash_test.go
  k8sdeps/transformer/patch/patch.go
  k8sdeps/transformer/patch/patch_test.go
  k8sdeps/transformer/patch/patchconflictdetector.go
  k8sdeps/validator/validators.go
  kustomize.go
  pkg/commands/build/build_test.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget_test.go
  pkg/transformers/imagetag_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#513 fix spelling
  examples/transformerconfigs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#508 kustomize build loads transformer configs when path argument omitted
  pkg/commands/build/build.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#516 Revert "Skip adding nameprefix to namespace"
  pkg/target/kusttarget_test.go
  pkg/transformers/prefixname.go
  pkg/transformers/prefixname_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#517 Improve test coverage.
  k8sdeps/configmapandsecret/configmapfactory_test.go
  pkg/fs/fakefs.go
  pkg/fs/fakefs_test.go
  pkg/loader/fileloader_test.go
  pkg/loader/githubloader_test.go
  pkg/transformers/config/factory_test.go
Labels: approved, cncf-cla: yes, size/L

#502 add support .yml extension for kusotmization file
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/constants/constants.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#525 Rename disableHash to disableNameSuffixHash
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, size/S
