Repository kubernetes-sigs/kustomize, pull requests merged in 2018-05, with the labels that each got.

#1 update readme w/ travis
  README.md
Labels: cncf-cla: yes, size/XS

#3 fixStuffDueToKubectlDeletion
  bin/pre-commit.sh
  demos/helloWorld.md
  demos/ldap.md
  demos/mySql.md
  demos/springboot.md
Labels: cncf-cla: yes, size/M

#4 demoReorgToEaseTesting
  demos/README.md
  demos/helloWorld/README.md
  demos/helloWorld/configMap.yaml
  demos/helloWorld/deployment.yaml
  demos/helloWorld/kustomization.yaml
  demos/helloWorld/service.yaml
  demos/integration_tests.sh
  demos/ldap/README.md
  demos/ldap/base/deployment.yaml
  demos/ldap/base/env.startup.txt
  demos/ldap/base/kustomization.yaml
  demos/ldap/base/service.yaml
  demos/ldap/integration_test.sh
  demos/ldap/overlays/production/deployment.yaml
  demos/ldap/overlays/production/kustomization.yaml
  demos/ldap/overlays/staging/config.env
  demos/ldap/overlays/staging/deployment.yaml
  demos/ldap/overlays/staging/kustomization.yaml
  demos/mySql/README.md
  demos/mySql/deployment.yaml
  demos/mySql/secret.yaml
  demos/mySql/service.yaml
  demos/springboot/README.md
  demos/springboot/base/deployment.yaml
  demos/springboot/base/service.yaml
  demos/springboot/overlays/production/application.properties
  demos/springboot/overlays/production/healthcheck_patch.yaml
  demos/springboot/overlays/production/kustomization.yaml
  demos/springboot/overlays/production/memorylimit_patch.yaml
  demos/springboot/overlays/production/patch.yaml
  demos/springboot/overlays/staging/application.properties
  demos/springboot/overlays/staging/kustomization.yaml
  demos/springboot/overlays/staging/staging.env
Labels: cncf-cla: yes, size/M

#7 Tweak test script2
  demos/integration_tests.sh
Labels: cncf-cla: yes

#8 tweaking integration test
  demos/integration_tests.sh
  demos/ldap/integration_test.sh
Labels: cncf-cla: yes, size/M

#9 more logging
  demos/integration_tests.sh
Labels: cncf-cla: yes

#10 improve script readability
  demos/integration_tests.sh
  demos/ldap/integration_test.sh
Labels: cncf-cla: yes

#11 drop unnecessary -f from diff
  demos/ldap/integration_test.sh
  pkg/commands/build.go
  pkg/commands/diff.go
Labels: cncf-cla: yes, size/M

#20 reduce integration test noise
  demos/ldap/integration_test.sh
Labels: cncf-cla: yes, size/M

#21 updated release scripts for kustomize
  build/.goreleaser.yml
  build/README.md
  build/build.sh
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/goreleaser.yaml
Labels: cncf-cla: yes, size/L

#24 add goreleaser config file
  build/README.md
  build/goreleaser.yml
Labels: cncf-cla: yes, size/M

#25 use variant in figure
  docs/overlay.jpg
Labels: cncf-cla: yes, size/XS

#26 betterFigs
  docs/base.jpg
  docs/overlay.jpg
Labels: cncf-cla: yes

#2 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#29 Update README with file layout
  README.md
  docs/overlay.jpg
Labels: cncf-cla: yes, size/M

#31 add instructions for publishing a release
  build/README.md
Labels: cncf-cla: yes, size/S

#34 update readmes
  INSTALL.md
  README.md
  build/README.md
  demos/README.md
  docs/glossary.md
Labels: cncf-cla: yes, size/L

#35 Base overlay notes
  README.md
  docs/glossary.md
Labels: cncf-cla: yes, size/L

#37 demos --> examples
  CONTRIBUTING.md
  README.md
  bin/pre-commit.sh
  examples/README.md
  examples/breakfast.md
  examples/configGeneration.md
  examples/helloWorld/README.md
  examples/helloWorld/configMap.yaml
  examples/helloWorld/deployment.yaml
  examples/helloWorld/kustomization.yaml
  examples/helloWorld/service.yaml
  examples/integration_tests.sh
  examples/ldap/README.md
  examples/ldap/base/deployment.yaml
  examples/ldap/base/env.startup.txt
  examples/ldap/base/kustomization.yaml
  examples/ldap/base/service.yaml
  examples/ldap/integration_test.sh
  examples/ldap/overlays/production/deployment.yaml
  examples/ldap/overlays/production/kustomization.yaml
  examples/ldap/overlays/staging/config.env
  examples/ldap/overlays/staging/deployment.yaml
  examples/ldap/overlays/staging/kustomization.yaml
  examples/mySql/README.md
  examples/mySql/deployment.yaml
  examples/mySql/secret.yaml
  examples/mySql/service.yaml
  examples/springboot/README.md
  examples/springboot/base/deployment.yaml
  examples/springboot/base/service.yaml
  examples/springboot/overlays/production/application.properties
  examples/springboot/overlays/production/healthcheck_patch.yaml
  examples/springboot/overlays/production/kustomization.yaml
  examples/springboot/overlays/production/memorylimit_patch.yaml
  examples/springboot/overlays/production/patch.yaml
  examples/springboot/overlays/staging/application.properties
  examples/springboot/overlays/staging/kustomization.yaml
  examples/springboot/overlays/staging/staging.env
Labels: cncf-cla: yes, size/M

#39 Removes help text for `kustomize edit add secret`
  pkg/commands/commands.go
Labels: cncf-cla: yes, size/XS

#44 Document constants package.
  bin/pre-commit.sh
  pkg/commands/util.go
  pkg/constants/constants.go
  pkg/resource/util.go
Labels: cncf-cla: yes, size/M

#43 Fix URL in help message
  pkg/commands/commands.go
Labels: cncf-cla: yes, size/XS

#45 Create and document diff package.
  pkg/commands/build.go
  pkg/commands/diff.go
  pkg/diff/directory.go
  pkg/diff/doc.go
  pkg/diff/program.go
  pkg/diff/rundiff.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/util/diff.go
  pkg/util/util.go
Labels: cncf-cla: yes, size/L
