Repository kubernetes-sigs/kustomize, pull requests merged in 2019-01, with the labels that each got.

#668 Delete deprecated file-based build test code.
  pkg/commands/build/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#678 Drain more code from kusttarget.
  pkg/target/kusttarget.go
  pkg/target/resaccumulator_test.go
  pkg/transformers/config/constants.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factory_test.go
  pkg/transformers/config/factorycrd.go
  pkg/transformers/config/factorycrd_test.go
  pkg/transformers/config/transformerconfig.go
  pkg/transformers/labelsandannotations_test.go
Labels: approved, cncf-cla: yes, size/L

#691 Don't force all config to be explicit.
  pkg/transformers/config/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#697 remove myself from maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#698 Small cleanups, no change in exec.
  pkg/fs/fakefs.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, size/M

#700 Restrict loading to root or below.
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#690 Remove git:: prefix for all git URLs not only GitLab
  pkg/loader/gitcloner.go
  pkg/loader/gitcloner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#703 replace commands/envcommand by DataSource in SecretGenerator
  docs/kustomization.yaml
  examples/combineConfigs.md
  examples/generatorOptions.md
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kunstruct/factory.go
  pkg/commands/edit/add/configmap.go
  pkg/ifc/ifc.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/namespacedgenerators_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#679 make BuildOptions exported
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#674 configmap binarydata support
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#699 Allow namespaced object to refer cluster level object
  pkg/resmap/resmap.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#704 Add image transformer
  pkg/commands/edit/set/setimagetag.go
  pkg/image/append.go
  pkg/image/image.go
  pkg/image/imagetag.go
  pkg/target/kusttarget.go
  pkg/transformers/image.go
  pkg/transformers/image_test.go
  pkg/transformers/imagetag.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#711 add apiversion and kind to docs/kustomization.yaml
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#713 Add more loader tests.
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#714 DataSources is now common to Secrets and ConfigMaps.
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  pkg/resmap/factory_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, size/M

#716 Fix typo in generatorOptions example doc
  examples/generatorOptions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#707 add set image command
  pkg/commands/edit/set/all.go
  pkg/commands/edit/set/setimage.go
  pkg/commands/edit/set/setimage_test.go
  pkg/commands/edit/set/setimagetag.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, lgtm, size/L

#715 add 'images' documentation
  docs/kustomization.yaml
  examples/README.md
  examples/image.md
Labels: cncf-cla: yes, lgtm, size/M

#724 Cover CleanedAbs with tests.
  pkg/fs/fakefs.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/fs/realfs_test.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/resmap/factory_test.go
Labels: approved, cncf-cla: yes, size/L

#721 support different filenames for kustomization file
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/constants/constants.go
  pkg/fs/fakefs.go
  pkg/loader/gitcloner_test.go
  pkg/target/kusttarget.go
  pkg/target/utils_for_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#722 remove patches and imageTags from kustomization.yaml
  docs/kustomization.yaml
  pkg/commands/edit/set/all.go
  pkg/commands/edit/set/setimage.go
  pkg/commands/edit/set/setimagetag.go
  pkg/commands/edit/set/setimagetag_test.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#726 Add more coverage for loader and strengthen type safety
  pkg/fs/confirmeddir.go
  pkg/fs/confirmeddir_test.go
  pkg/fs/fakefs.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
  pkg/fs/realfs_test.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/gitcloner_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#730 Move git code to its own pkg.
  pkg/git/cloner.go
  pkg/git/cloner_test.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, size/L

#733 typo in doc
  pkg/commands/misc/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#734 added DaemonSet for Var
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#737 Add better error reporting to NewRepoSpecFromUrl
  pkg/git/cloner.go
  pkg/git/repospec.go
  pkg/git/repospec_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#740 Replace all repo uri strings with git.RepoSpec.
  pkg/git/cloner.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#728 Disallow cloned kustomization from using a local base outside the clone dir.
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#743 Delete some dead code and fix nits.
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/git/repospec.go
  pkg/git/repospec_test.go
  pkg/image/append.go
  pkg/image/deprecatedimage.go
  pkg/loader/fileloader_test.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factory_test.go
  pkg/transformers/image.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#744 Skip empty object validation
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#745 examples: typo
  examples/image.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#749 Document SMP behavior for custom resources
  docs/glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#754 Add Service nameReference to APIService
  pkg/transformers/config/defaultconfig/namereference.go
Labels: cncf-cla: yes, lgtm, size/XS
