Repository kubernetes-sigs/kustomize, pull requests merged in 2019-12, with the labels that each got.

#1875 fix quotation issues by using a bash array
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer
Labels: cncf-cla: yes, lgtm, size/XS

#1877 Fix three typos
  cmd/config/docs/commands/run-fns.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1881 Simplify test framework
  api/internal/loadertest/fakeloader.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/maker_test.go
  api/krusty/chartinflatorplugin_test.go
  api/krusty/customconfigofbuiltinplugin_test.go
  api/krusty/customconfigreusable_test.go
  api/krusty/diamondcomposition_test.go
  api/krusty/pluginenv_test.go
  api/krusty/resourceconflict_test.go
  api/krusty/transformerplugin_test.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
  api/testutils/kusttest/plugintestenv.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator_test.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer_test.go
  plugin/someteam.example.com/v1/gogetter/GoGetter_test.go
  plugin/someteam.example.com/v1/printpluginenv/PrintPluginEnv_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator_test.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer_test.go
  plugin/someteam.example.com/v1/validator/validator_test.go
Labels: approved, cncf-cla: yes, size/XXL

#1882 Fix some nits in the crawler and elsewhere.
  api/builtins/AnnotationsTransformer.go
  api/builtins/HashTransformer.go
  api/builtins/ImageTagTransformer.go
  api/builtins/LabelTransformer.go
  api/builtins/LegacyOrderTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PrefixSuffixTransformer.go
  api/builtins/ReplicaCountTransformer.go
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/crawler/crawler_test.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/queries.go
  api/internal/crawl/crawler/github/queries_test.go
  api/testutils/kusttest/harness.go
  api/testutils/resmaptest/rmbuilder.go
  api/testutils/valtest/fakevalidator.go
  api/transform/mutatefield_test.go
  kustomize/internal/commands/edit/add/addbase.go
  kustomize/internal/commands/edit/add/addpatch.go
  kustomize/internal/commands/edit/add/addresource.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/edit/set/set_name_prefix.go
  kustomize/internal/commands/edit/set/set_name_suffix.go
  kustomize/internal/commands/version/version.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
Labels: approved, cncf-cla: yes, size/L

#1822 Add Local Volume support to ContainerFilter
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1883 Set the ElasticSearch index creation configuration
  api/internal/crawl/index/elasticsearch.go
  api/internal/crawl/index/kustomize.go
Labels: cncf-cla: yes, lgtm, size/M

#1888 Remove duplicates in the `kinds` field of the kustomize ElasticSearch index
  api/internal/crawl/doc/doc.go
  api/internal/crawl/doc/doc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1887 add replacement type and an example transformer
  api/types/replacement.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer_test.go
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1892 Get rid of the 'fake' loader.
  api/internal/accumulator/loadconfigfromcrds_test.go
  api/internal/loadertest/fakeloader.go
  api/internal/plugins/builtinconfig/loaddefaultconfig_test.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/maker_test.go
  api/resmap/factory_test.go
  api/resource/factory_test.go
  api/testutils/kusttest/harnessenhanced.go
Labels: approved, cncf-cla: yes, size/L

#1894 Kustomize installation script.
  hack/install_kustomize.sh
Labels: cncf-cla: yes

#1896 Improve install script error message
  docs/INSTALL.md
  hack/install_kustomize.sh
Labels: cncf-cla: yes

#1897 support writing run output to files
  cmd/config/cmd/cat.go
  cmd/config/cmd/cat_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1891 Fix dependencies for kstatus
  kstatus/go.mod
  kstatus/go.sum
  kstatus/status/core.go
  kstatus/status/generic.go
  kstatus/status/status.go
  kstatus/status/status_augment_test.go
  kstatus/status/status_compute_test.go
  kstatus/status/util.go
Labels: cncf-cla: yes, lgtm, size/L

#1893 kyaml: Enable Go linters (lll, stylecheck, unparam, whitespace)
  cmd/config/cmd/cat.go
  cmd/config/cmd/cmdwrap.go
  cmd/config/cmd/cmdxargs.go
  kyaml/.golangci.yml
  kyaml/copyutil/copyutil_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_writer.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/filters/container.go
  kyaml/kio/filters/fmtr_test.go
  kyaml/kio/filters/merge.go
  kyaml/kio/filters/merge3.go
  kyaml/kio/filters/testyaml/testyaml.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_reader_test.go
  kyaml/kio/pkgio_writer.go
  kyaml/kio/tree.go
  kyaml/yaml/example_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/match.go
  kyaml/yaml/merge3/visitor.go
  kyaml/yaml/order.go
  kyaml/yaml/types.go
  kyaml/yaml/walk/associative_sequence.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1910 kyaml: Enable goconst Go Linter
  kyaml/.golangci.yml
  kyaml/runfn/runfn_test.go
  kyaml/yaml/fns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1917 Fix 'config run' by removing default mount.
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1905 shell completion for kustomize commands
  cmd/config/cmd/complete/complete.go
  cmd/config/cmddocs/commands/docs.go
  cmd/config/docs/commands/completion.md
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1921 kyaml: fix error handling
  cmd/config/cmd/cmdwrap.go
  cmd/config/cmd/cmdxargs.go
  cmd/config/cmd/run-fns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1927 Expand and format Configuration IO API Semantics.
  cmd/config/docs/api-conventions/config-io.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1916 Update plugins/doc.go link.
  plugin/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1909 Detect path to plugins from krusty tests.
  api/internal/plugins/compiler/compiler.go
Labels: cncf-cla: yes, lgtm, size/S

#1922 cmd/config: Documentation nits + updates.
  cmd/config/cmddocs/api/docs.go
  cmd/config/cmddocs/commands/docs.go
  cmd/config/cmddocs/tutorials/docs.go
  cmd/config/cmds/cmds.go
  cmd/config/docs/api-conventions/config-fn.md
  cmd/config/docs/api-conventions/config-io.md
  cmd/config/docs/api-conventions/merge2.md
  cmd/config/docs/commands/cat.md
  cmd/config/docs/commands/grep.md
  cmd/config/docs/commands/run-fns.md
  cmd/config/docs/commands/tree.md
  cmd/config/docs/tutorials/configuration-basics.md
  cmd/config/docs/tutorials/function-basics.md
  functions/examples/injection-tshirt-sizes/README.md
  functions/examples/template-go-nginx/README.md
  functions/examples/template-heredoc-cockroachdb/README.md
  functions/examples/validator-resource-requests/README.md
Labels: approved, cncf-cla: yes, size/L

#1928 Mulitple improvements of the crawler
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/config/crawler/cronjob/cronjob.yaml
  api/internal/crawl/config/crawler/job/job.yaml
  api/internal/crawl/config/webapp/backend/deployment.yaml
  api/internal/crawl/config/webapp/frontend/deployment.yaml
  api/internal/crawl/crawler/crawler.go
  api/internal/crawl/crawler/crawler_test.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/queries.go
  api/internal/crawl/crawler/github/queries_test.go
  api/internal/crawl/doc/doc.go
  api/internal/crawl/doc/docname.go
  api/internal/crawl/doc/docname_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1930 cli for status
  cmd/resource/.golangci.yml
  cmd/resource/LICENSE_TEMPLATE
  cmd/resource/Makefile
  cmd/resource/go.mod
  cmd/resource/go.sum
  cmd/resource/main.go
  cmd/resource/status/cmd/events.go
  cmd/resource/status/cmd/fetch.go
  cmd/resource/status/cmd/print.go
  cmd/resource/status/cmd/util.go
  cmd/resource/status/cmd/wait.go
  cmd/resource/status/status.go
  kstatus/status/generic.go
  kstatus/wait/wait.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1932 Avoid processing the nil pointer returned by kustomizationResultAdapter
  api/internal/crawl/crawler/github/crawler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1936 Introduce latest_kustomize tag in release process
  releasing/README.md
Labels: approved, cncf-cla: yes, size/XS

#1933 Expose ElasticSearch as a LoadBalancer-type service
  api/internal/crawl/config/elastic/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1939 Fix panic in merge2 comment merging
  kyaml/yaml/merge2/merge2.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1931 Disable Alpha commands by default
  cmd/config/cmds/cmds.go
  cmd/config/cmds/example_test.go
  cmd/config/main.go
  kustomize/go.mod
  kustomize/internal/commands/config/config.go
  kyaml/commandutil/commandutil.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1937 Fix issues with rules for Deployment and ReplicaSet
  kstatus/status/core.go
  kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1904 kyaml: Enable gocritic Go linter
  kyaml/.golangci.yml
  kyaml/yaml/filters.go
  kyaml/yaml/fns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1611 add zh doc transformerconfigs.md validationTransformer.md
  examples/zh/README.md
  examples/zh/chart.md
  examples/zh/transformerconfigs.md
  examples/zh/validationTransformer.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1941 Upgrade to mdrip 1.0.1
  api/go.mod
  api/go.sum
  cmd/config/go.sum
  cmd/resource/go.sum
  kstatus/go.mod
  kstatus/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#1920 Add script to detect/build Go plugins.
  Makefile
  hack/buildExternalGoPlugins.sh
Labels: cncf-cla: yes, size/M

#1943 Tweak Go plugin build script and targets.
  Makefile
  hack/buildExternalGoPlugins.sh
Labels: approved, cncf-cla: yes, size/M

#1942 refactor cmd/config to internal
  cmd/config/complete/complete.go
  cmd/config/configcobra/cmds.go
  cmd/config/configcobra/example_test.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cat_test.go
  cmd/config/internal/commands/cmdwrap.go
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/cmdxargs.go
  cmd/config/internal/commands/cmdxargs_test.go
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/count_test.go
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/fmt_test.go
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/grep_test.go
  cmd/config/internal/commands/merge.go
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/test/override.yaml
  cmd/config/internal/commands/test/test.sh
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/tree_test.go
  cmd/config/internal/commands/util.go
  cmd/config/internal/generateddocs/api/docs.go
  cmd/config/internal/generateddocs/commands/docs.go
  cmd/config/internal/generateddocs/tutorials/docs.go
  cmd/config/internal/inpututil/inpututil.go
  cmd/config/main.go
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/config/config.go
  kustomize/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1944 Update npm deps.
  api/internal/crawl/ui/package-lock.json
  api/internal/crawl/ui/package.json
Labels: approved, cncf-cla: yes, size/XXL

#1876 Fix process args fields
  api/go.sum
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1945 Go mod tidy b4 release.
  api/go.mod
  api/go.sum
  cmd/resource/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#1946 Drop last direct refs to pseudo/k8s.
  pseudo/update-fork-references.sh
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/cloudbuild_pseudok8s.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/L

#1947 expose apply Options so we can tune them
  cmd/kubectl/kubectlcobra/comands.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1950 Drop api module's explicit dependence on pluginator.
  api/go.mod
  api/go.sum
  api/internal/tools/tools.go
Labels: approved, cncf-cla: yes, size/S

#1949 Rename misspelled commands.go
  cmd/kubectl/kubectlcobra/commands.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1951 Pin pluginator to api v0.3.0
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/M

#1954 Pin to kustomize API v0.3.0
  api/internal/crawl/go.mod
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#1956 kyaml: Remove funlen from Go linters list
  kyaml/.golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1955 Minor grammar fix
  docs/glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1948 Add supports for crawling a specific git user or repo
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/crawler/crawler.go
  api/internal/crawl/crawler/crawler_test.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/queries.go
  api/internal/crawl/crawler/github/queries_test.go
  api/internal/crawl/crawler/github/split_search_ranges.go
Labels: cncf-cla: yes, size/L

#1961 Remove dependency on curse library
  cmd/resource/go.mod
  cmd/resource/go.sum
  cmd/resource/status/cmd/print.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1964 Update serialize-javascript
  api/internal/crawl/ui/package-lock.json
  api/internal/crawl/ui/package.json
Labels: approved, cncf-cla: yes, size/XXL

#1970 Fixed a wrong path and run `make generate`
  cmd/config/docs/tutorials/function-basics.md
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/generateddocs/api/docs.go
  cmd/config/internal/generateddocs/commands/docs.go
  cmd/config/internal/generateddocs/tutorials/docs.go
  functions/examples/template-go-nginx/README.md
  functions/examples/template-heredoc-cockroachdb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1965 Clarify removing annotations in config-io
  cmd/config/docs/api-conventions/config-io.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1971 Revert "Fixed a wrong path and run `make generate`"
  cmd/config/docs/tutorials/function-basics.md
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/generateddocs/api/docs.go
  cmd/config/internal/generateddocs/commands/docs.go
  cmd/config/internal/generateddocs/tutorials/docs.go
  functions/examples/template-go-nginx/README.md
  functions/examples/template-heredoc-cockroachdb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1972 Update go.sums
  api/internal/crawl/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1962 Support for set / substitution
  cmd/config/configcobra/cmds.go
  cmd/config/docs/commands/sub.md
  cmd/config/docs/commands/subset.md
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/cmdsub.go
  cmd/config/internal/commands/cmdsubcreate.go
  cmd/config/internal/generateddocs/commands/docs.go
  cmd/config/internal/sub/addkio.go
  cmd/config/internal/sub/addyaml.go
  cmd/config/internal/sub/dokio.go
  cmd/config/internal/sub/doyaml.go
  cmd/config/internal/sub/lookupkio.go
  cmd/config/internal/sub/lookupyaml.go
  cmd/config/internal/sub/types.go
  kustomize/go.sum
  kyaml/fieldmeta/fieldmeta.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1953 Update zh/INSTALL.md
  docs/zh/INSTALL.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1952 Add kubeval function example.
  functions/examples/validator-kubeval/LICENSE_TEMPLATE
  functions/examples/validator-kubeval/Makefile
  functions/examples/validator-kubeval/README.md
  functions/examples/validator-kubeval/image/Dockerfile
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-kubeval/image/main.go
  functions/examples/validator-kubeval/local-resource/example-use.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1973 Improve release process
  releasing/VERSIONS
  releasing/releaseallmodules.sh
  releasing/releasemodule.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1977 Pin kustomize to specific versions of local deps.
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#1976 Using single quote style when setting annotations
  cmd/config/internal/commands/cat_test.go
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/grep_test.go
  cmd/config/internal/generateddocs/api/docs.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/example_test.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/filters_test.go
  kyaml/kio/pkgio_reader_test.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/kfns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1984 pin version of mdrip and blackfriday to fix build errors
  api/go.mod
  api/go.sum
  api/internal/tools/tools.go
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/L

#1981 Rename ownedBy and refactor kyaml travis
  cmd/config/docs/commands/sub.md
  cmd/config/docs/commands/subset.md
  cmd/config/internal/generateddocs/commands/docs.go
  functions/examples/template-heredoc-cockroachdb/Makefile
  functions/examples/validator-kubeval/image/Dockerfile
  kyaml/fieldmeta/fieldmeta.go
  travis/consider-early-travis-exit.sh
  travis/kyaml-pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1986 Update api to 0.3.1
  kustomize/go.mod
  kustomize/go.sum
  releasing/VERSIONS
  releasing/releasemodule.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1880 Add documentation for the kstatus library
  kstatus/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1995 Handle variables in annotations
  api/konfig/builtinpluginconsts/varreference.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1998 Update go.mod to point to most recent version of k8s.io/kubectl
  cmd/kubectl/go.mod
  cmd/kubectl/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#1985 Crawler Improvements
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/config/crawler/job/README.md
  api/internal/crawl/config/crawler/job/job.yaml
  api/internal/crawl/crawler/crawler.go
  api/internal/crawl/crawler/crawler_test.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/doc/doc.go
  api/internal/crawl/doc/docname.go
  api/internal/crawl/doc/docname_test.go
  api/internal/crawl/go.mod
  api/internal/crawl/go.sum
  api/internal/crawl/index/elasticsearch.go
  api/internal/crawl/index/kustomize.go
Labels: cncf-cla: yes, lgtm, size/XL

#1999 fix issues caused by dropping or overriding style
  cmd/config/internal/commands/cat_test.go
  cmd/config/internal/commands/cmdwrap_test.go
  kyaml/kio/filters/fmtr.go
  kyaml/kio/filters/fmtr_test.go
  kyaml/kio/filters/testyaml/testyaml.go
  kyaml/kio/pkgio_writer_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/merge2/element_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/merge2_old_test.go
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2000 release `kyaml` and `cmd/config` 0.0.3
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2005 completion should suggest directories if use contains DIR
  cmd/config/complete/complete.go
  cmd/config/internal/commands/fmt.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2006 Move setters to be available as libraries
  cmd/config/internal/commands/cmdsub.go
  cmd/config/internal/commands/cmdsubcreate.go
  kyaml/set/addkio.go
  kyaml/set/addyaml.go
  kyaml/set/dokio.go
  kyaml/set/doyaml.go
  kyaml/set/lookupkio.go
  kyaml/set/lookupyaml.go
  kyaml/set/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2009 config tree defaults to graph structure when ownerRefs available
  cmd/config/docs/commands/tree.md
  cmd/config/internal/commands/tree.go
  cmd/config/internal/generateddocs/commands/docs.go
  kyaml/kio/tree.go
  kyaml/kio/tree_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
