Repository kubernetes-sigs/kustomize, pull requests merged in 2019-11, with the labels that each got.

#1717 strategic-merge-patch documentation has moved
  api/types/patchstrategicmerge.go
Labels: cncf-cla: yes, size/XS

#1719 Move plugin config to main config package.
  api/krusty/options.go
  api/pgmconfig/doc.go
  api/pgmconfig/pgmconfig.go
  api/pgmconfig/pluginconfig.go
  api/pgmconfig/pluginconfig_test.go
  api/plugins/compiler/compiler.go
  api/plugins/execplugin/execplugin_test.go
  api/plugins/loader/loader.go
  api/plugins/loader/loader_test.go
  api/target/baseandoverlaysmall_test.go
  api/target/plugindir_test.go
  api/testutils/kusttest/kusttestharness.go
  api/testutils/kusttest/plugintestenv.go
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/L

#1722 push flag code from api module to kustomize internal
  api/go.sum
  api/krusty/kustomizer.go
  api/krusty/loadrestrictions.go
  api/krusty/loadrestrictions_string.go
  api/krusty/options.go
  api/pgmconfig/pluginconfig.go
  api/plugins/loader/loader.go
  api/target/transformerplugin_test.go
  api/types/erronlybuiltinpluginsallowed.go
  api/types/loadrestrictions.go
  api/types/loadrestrictions_string.go
  api/types/pluginconfig.go
  api/types/pluginrestrictions.go
  api/types/pluginrestrictions_string.go
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/flagenableplugins.go
  kustomize/internal/commands/build/flagloadrestrictor.go
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1723 Improved plugin loading docs.
  api/pgmconfig/pluginconfig.go
  api/plugins/compiler/compiler.go
  api/plugins/loader/loader.go
  api/testutils/kusttest/plugintestenv.go
  api/types/pluginconfig.go
Labels: approved, cncf-cla: yes, size/M

#1724 Improve error messaging around plugin loading problems.
  api/krusty/kustomizer.go
  api/krusty/options.go
  api/pgmconfig/pluginconfig.go
  api/plugins/compiler/compiler.go
  api/plugins/execplugin/execplugin.go
  api/plugins/execplugin/execplugin_test.go
  api/plugins/loader/loader.go
  api/plugins/loader/loader_test.go
  api/target/baseandoverlaysmall_test.go
  api/target/plugindir_test.go
  api/testutils/kusttest/kusttestharness.go
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/L

#1725 Improve plugin home defaulting.
  api/pgmconfig/pluginconfig.go
  api/pgmconfig/pluginconfig_test.go
  api/plugins/compiler/compiler.go
  api/plugins/compiler/compiler_test.go
  api/plugins/loader/loader_test.go
  api/target/diamondcomposition_test.go
  api/target/plugindir_test.go
  api/testutils/kusttest/kusttestharness.go
  api/testutils/kusttest/plugintestenv.go
  api/types/errunabletofind.go
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/L

#1726 Improve config package names and reduce API exposure.
  api/konfig/builtinpluginconsts/commonannotations.go
  api/konfig/builtinpluginconsts/commonlabels.go
  api/konfig/builtinpluginconsts/defaultconfig.go
  api/konfig/builtinpluginconsts/doc.go
  api/konfig/builtinpluginconsts/images.go
  api/konfig/builtinpluginconsts/nameprefix.go
  api/konfig/builtinpluginconsts/namereference.go
  api/konfig/builtinpluginconsts/namespace.go
  api/konfig/builtinpluginconsts/replicas.go
  api/konfig/builtinpluginconsts/varreference.go
  api/konfig/doc.go
  api/konfig/general.go
  api/konfig/plugins.go
  api/konfig/plugins_test.go
  api/krusty/options.go
  api/loader/fileloader_test.go
  api/plugins/builtinconfig/consts/doc.go
  api/plugins/builtinconfig/transformerconfig.go
  api/plugins/compiler/compiler.go
  api/plugins/execplugin/execplugin_test.go
  api/plugins/loader/loader.go
  api/plugins/loader/loader_test.go
  api/target/baseandoverlaysmall_test.go
  api/target/kusttarget.go
  api/target/plugindir_test.go
  api/testutils/kusttest/kusttestharness.go
  api/testutils/kusttest/plugintestenv.go
  hack/whatApi.sh
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/build_test.go
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/config/config.go
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/patch/strategicmerge.go
  kustomize/internal/commands/edit/remove/removemetadata.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
  kustomize/internal/commands/testutils/testutils.go
Labels: approved, cncf-cla: yes, size/L

#1729 Correct typo
  hack/crawl/crawler/crawler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1730 No kubeval dependent test on travis.
  examples/validationTransformer/README.md
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1731 No kubeval dependent test on travis.
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/S

#1716 Support node configmap namereference.
  api/konfig/builtinpluginconsts/namereference.go
Labels: cncf-cla: yes, size/XS

#1732 Migrate some presubmit functionality to Makefile.
  Makefile
  api/go.mod
  api/go.sum
  api/internal/tools/tools.go
  api/plugins/builtins/tools.go
  kustomize/go.mod
  kustomize/go.sum
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1739 Remove git package from exposed API.
  api/internal/git/cloner.go
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  api/loader/loader.go
  examples/goGetterGeneratorPlugin.md
Labels: approved, cncf-cla: yes, size/XS

#1740 Remove target package from exposed API.
  api/internal/target/accumulation_test.go
  api/internal/target/baseandoverlaymedium_test.go
  api/internal/target/baseandoverlaysmall_test.go
  api/internal/target/basereusenameprefix_test.go
  api/internal/target/chartinflatorplugin_test.go
  api/internal/target/complexcomposition_test.go
  api/internal/target/configmaps_test.go
  api/internal/target/crd_test.go
  api/internal/target/customconfig_test.go
  api/internal/target/customconfigofbuiltinplugin_test.go
  api/internal/target/diamondcomposition_test.go
  api/internal/target/diamonds_test.go
  api/internal/target/extendedpatch_test.go
  api/internal/target/generatormergeandreplace_test.go
  api/internal/target/generatoroptions_test.go
  api/internal/target/inlinepatch_test.go
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_configplugin.go
  api/internal/target/kusttarget_test.go
  api/internal/target/multiplepatch_test.go
  api/internal/target/namespacedgenerators_test.go
  api/internal/target/namespaces_test.go
  api/internal/target/nullvalues_test.go
  api/internal/target/plugindir_test.go
  api/internal/target/pruneconfigmap_test.go
  api/internal/target/resourceconflict_test.go
  api/internal/target/transformerplugin_test.go
  api/internal/target/transformersarrays_test.go
  api/internal/target/transformersimage_test.go
  api/internal/target/variableref_test.go
  api/krusty/kustomizer.go
  api/testutils/kusttest/kusttestharness.go
  docs/v2.1.0.md
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1741 Remove CMSecret package from API.
  api/internal/k8sdeps/configmapandsecret/configmapfactory.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  api/internal/k8sdeps/configmapandsecret/factory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory_test.go
  api/k8sdeps/kunstruct/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1742 Move the builtins to the top level as part of API
  api/builtins/AnnotationsTransformer.go
  api/builtins/ConfigMapGenerator.go
  api/builtins/HashTransformer.go
  api/builtins/ImageTagTransformer.go
  api/builtins/InventoryTransformer.go
  api/builtins/LabelTransformer.go
  api/builtins/LegacyOrderTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/builtins/PrefixSuffixTransformer.go
  api/builtins/ReplicaCountTransformer.go
  api/builtins/SecretGenerator.go
  api/builtins/doc.go
  api/internal/target/kusttarget.go
  api/krusty/kustomizer.go
  api/plugins/builtinhelpers/builtins.go
  api/plugins/builtinhelpers/generateBuiltins.sh
  api/plugins/compiler/compiler.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  pluginator/main.go
Labels: approved, cncf-cla: yes, size/L

#1743 Lowercase the generated filenames per Go style.
  api/builtins/annotationstransformer.go
  api/builtins/configmapgenerator.go
  api/builtins/hashtransformer.go
  api/builtins/imagetagtransformer.go
  api/builtins/inventorytransformer.go
  api/builtins/labeltransformer.go
  api/builtins/legacyordertransformer.go
  api/builtins/namespacetransformer.go
  api/builtins/patchjson6902transformer.go
  api/builtins/patchstrategicmergetransformer.go
  api/builtins/patchtransformer.go
  api/builtins/prefixsuffixtransformer.go
  api/builtins/replicacounttransformer.go
  api/builtins/secretgenerator.go
  pluginator/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1744 Remove remaining plugins packages from external API.
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/accumulator/loadconfigfromcrds_test.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/resaccumulator.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/plugins/builtinconfig/doc.go
  api/internal/plugins/builtinconfig/loaddefaultconfig.go
  api/internal/plugins/builtinconfig/loaddefaultconfig_test.go
  api/internal/plugins/builtinconfig/namebackreferences.go
  api/internal/plugins/builtinconfig/namebackreferences_test.go
  api/internal/plugins/builtinconfig/transformerconfig.go
  api/internal/plugins/builtinconfig/transformerconfig_test.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/plugins/builtinhelpers/generateBuiltins.sh
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/internal/plugins/doc.go
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_configplugin.go
  api/internal/target/plugindir_test.go
  api/krusty/kustomizer.go
  api/testutils/kusttest/kusttestharness.go
  api/testutils/kusttest/plugintestenv.go
  api/transform/maptransformer_test.go
  examples/configureBuiltinPlugin.md
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1745 Remove more k8sdeps from external API.
  api/internal/k8sdeps/transformer/factory.go
  api/internal/k8sdeps/transformer/patch/conflictdetector.go
  api/internal/target/plugindir_test.go
  api/k8sdeps/doc.go
  api/krusty/kustomizer.go
  api/testutils/kusttest/kusttestharness.go
Labels: approved, cncf-cla: yes, size/M

#1746 Kyaml documentation improvements
  .gitignore
  kyaml/.golangci.yml
  kyaml/LICENSE_TEMPLATE
  kyaml/Makefile
  kyaml/doc.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/doc.go
  kyaml/kio/kio.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/tree.go
  kyaml/yaml/doc.go
  kyaml/yaml/example_test.go
  kyaml/yaml/filters.go
  kyaml/yaml/fns.go
  kyaml/yaml/order.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/L

#1755 Repin the plugins on head for release testing.
  hack/unpinRepinPluginApiDep.sh
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printworkdir/go.mod
  plugin/someteam.example.com/v1/printworkdir/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1758 Script to fork and fix k8s deps.
  hack/fork_k8s_and_fix_deps.sh
Labels: approved, cncf-cla: yes, size/M

#1750 Invoke plugin unit tests in presubmit.
  Makefile
  hack/runPluginUnitTests.sh
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1748 kyaml: rename annotations and fix linting
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/doc.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/filters.go
  kyaml/kio/filters/filters_test.go
  kyaml/kio/filters/stripcomments.go
  kyaml/kio/kio.go
  kyaml/kio/kioutil/kioutil.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_reader_test.go
  kyaml/kio/pkgio_writer.go
  kyaml/kio/pkgio_writer_test.go
  kyaml/kio/tree_test.go
  kyaml/yaml/alias.go
  kyaml/yaml/filters.go
  kyaml/yaml/match.go
  kyaml/yaml/types.go
  kyaml/yaml/walk/associative_sequence.go
  kyaml/yaml/walk/visitor.go
  kyaml/yaml/walk/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1760 pseudo: script for creating psuedo modules
  .travis.yml
  pseudo/README.md
  pseudo/init-pseudo-module.sh
  travis/verify-deps.sh
Labels: approved, area/pseudo, cncf-cla: yes, lgtm, size/L

#1761 Remove hack/fork_k8s_and_fix_deps.sh to avoid confusion.
  hack/fork_k8s_and_fix_deps.sh
Labels: approved, cncf-cla: yes, size/M

#1753 brew install gnu-sed
  docs/macDevGuide.md
Labels: cncf-cla: yes, lgtm, size/XS

#1764 Switch cmd/kyaml to pseudo/k8s
  cmd/kyaml/go.mod
  cmd/kyaml/go.sum
  travis/verify-deps.sh
Labels: approved, cncf-cla: yes, size/M

#1765 Move code generation to makefile.
  Makefile
  api/internal/plugins/builtinhelpers/generateBuiltins.sh
  pluginator/main.go
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1767 Update plugin go.sums
  api/builtins/annotationstransformer.go
  api/builtins/configmapgenerator.go
  api/builtins/hashtransformer.go
  api/builtins/imagetagtransformer.go
  api/builtins/inventorytransformer.go
  api/builtins/labeltransformer.go
  api/builtins/legacyordertransformer.go
  api/builtins/namespacetransformer.go
  api/builtins/patchjson6902transformer.go
  api/builtins/patchstrategicmergetransformer.go
  api/builtins/patchtransformer.go
  api/builtins/prefixsuffixtransformer.go
  api/builtins/replicacounttransformer.go
  api/builtins/secretgenerator.go
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printworkdir/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: cncf-cla: yes

#1766 Simplify pre-submit.sh
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/M

#1768 Add a relative path option for finding plugin source.
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/testutils/kusttest/plugintestenv.go
Labels: approved, cncf-cla: yes, size/S

#1769 Remove opsys comment from generated code
  Makefile
  api/builtins/annotationstransformer.go
  api/builtins/configmapgenerator.go
  api/builtins/hashtransformer.go
  api/builtins/imagetagtransformer.go
  api/builtins/inventorytransformer.go
  api/builtins/labeltransformer.go
  api/builtins/legacyordertransformer.go
  api/builtins/namespacetransformer.go
  api/builtins/patchjson6902transformer.go
  api/builtins/patchstrategicmergetransformer.go
  api/builtins/patchtransformer.go
  api/builtins/prefixsuffixtransformer.go
  api/builtins/replicacounttransformer.go
  api/builtins/secretgenerator.go
  api/main.go
  api/provenance/provenance.go
  docs/macDevGuide.md
  kustomize/internal/commands/version/version.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
  pluginator/go.mod
  pluginator/go.sum
  pluginator/main.go
Labels: approved, cncf-cla: yes, size/L

#1773 A pseudo main to make goreleaser happier.
  pseudo/k8s/main.go
Labels: cncf-cla: yes

#1774 Set up for pseudok8s release.
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/cloudbuild_pseudok8s.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1775 Set up for pseudok8s release.
  releasing/README.md
  releasing/cloudbuild_pseudok8s.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes

#1776 Tweaks to accomodate pseudo/k8s.
  releasing/cloudbuild.sh
  releasing/localbuild.sh
Labels: cncf-cla: yes

#1777 Pin kustomize API to pseudok8s v0.1.0
  api/go.mod
  api/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printworkdir/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
  releasing/README.md
Labels: approved, cncf-cla: yes, size/L

#1779 Pin kustomize and the plugins to kust Api v0.2.0
  hack/crawl/go.mod
  hack/pinUnpinPluginApiDep.sh
  hack/unpinRepinPluginApiDep.sh
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printworkdir/go.mod
  plugin/someteam.example.com/v1/printworkdir/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#1780 Pluginator v2
  pluginator/go.mod
Labels: cncf-cla: yes

#1781 Pin api HEAD to pluginator v2.
  Makefile
  api/go.mod
  api/go.sum
  api/internal/tools/tools.go
Labels: approved, cncf-cla: yes, size/S

#1783 Improve error handling in kyaml libraries
  cmd/kyaml/cmd/cat.go
  cmd/kyaml/cmd/count.go
  cmd/kyaml/cmd/fmt.go
  cmd/kyaml/cmd/grep.go
  cmd/kyaml/cmd/merge.go
  cmd/kyaml/cmd/tree.go
  cmd/kyaml/cmd/util.go
  cmd/kyaml/go.mod
  cmd/kyaml/go.sum
  cmd/kyaml/main.go
  hack/crawl/go.mod
  hack/crawl/go.sum
  kyaml/Makefile
  kyaml/errors/errors.go
  kyaml/inpututil/inpututil.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_writer.go
  kyaml/kio/kio.go
  kyaml/kio/kioutil/kioutil.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_writer.go
  kyaml/yaml/fns.go
  kyaml/yaml/types.go
Labels: approved, area/kyaml, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#1789 Add kyaml command for invoking container filters
  cmd/kyaml/cmd/cat.go
  cmd/kyaml/cmd/cat_test.go
  cmd/kyaml/cmd/cmdwrap.go
  cmd/kyaml/cmd/cmdwrap_test.go
  cmd/kyaml/cmd/cmdxargs.go
  cmd/kyaml/cmd/cmdxargs_test.go
  cmd/kyaml/cmd/run-fns.go
  cmd/kyaml/cmd/test/override.yaml
  cmd/kyaml/cmd/test/test.sh
  cmd/kyaml/cmd/tree.go
  cmd/kyaml/cmd/tree_test.go
  cmd/kyaml/main.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/local.go
  kyaml/kio/filters/merge3.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
  kyaml/runfn/test/testdata/java/java-configmap.resource.yaml
  kyaml/runfn/test/testdata/java/java-deployment.resource.yaml
  kyaml/runfn/test/testdata/java/java-service.resource.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1799 Drive kustomize repo verification entirely from Makefile
  .travis.yml
  Makefile
  hack/testExamplesAgainstKustomize.sh
  hack/testUnitKustomizePlugins.sh
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1787 kyaml: fix scopelint issues
  kyaml/.golangci.yml
  kyaml/yaml/fns.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1785 kyaml: add Network to ContainerFilter
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1797 quote PATH to run `make` successfully even if PATH includes whitespace
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1798 fix typo in pseudo/README.md
  pseudo/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#1786 Add tree to necessary tools
  docs/macDevGuide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1793 Fix two broken deps to allow tests under hack/crawl to pass
  hack/crawl/crawler/crawler_test.go
  hack/crawl/crawler/git/cloner.go
  hack/crawl/crawler/git/repospec.go
  hack/crawl/crawler/git/repospec_test.go
  hack/crawl/crawler/github/crawler.go
  hack/crawl/doc/doc.go
  hack/crawl/doc/docname.go
  hack/crawl/go.mod
  hack/crawl/go.sum
Labels: cncf-cla: yes, lgtm, size/XL

#1784 Fix broken redirect for contributor cheatsheet
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1801 Raise the golinter bar.
  .golangci.yml
  Makefile
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  api/internal/k8sdeps/configmapandsecret/secretfactory_test.go
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/baseandoverlaymedium_test.go
  api/internal/target/basereusenameprefix_test.go
  api/internal/target/complexcomposition_test.go
  api/internal/target/configmaps_test.go
  api/internal/target/crd_test.go
  api/internal/target/customconfig_test.go
  api/internal/target/customconfigofbuiltinplugin_test.go
  api/internal/target/diamondcomposition_test.go
  api/internal/target/diamonds_test.go
  api/internal/target/extendedpatch_test.go
  api/internal/target/generatormergeandreplace_test.go
  api/internal/target/generatoroptions_test.go
  api/internal/target/inlinepatch_test.go
  api/internal/target/multiplepatch_test.go
  api/internal/target/namespacedgenerators_test.go
  api/internal/target/namespaces_test.go
  api/internal/target/nullvalues_test.go
  api/internal/target/pruneconfigmap_test.go
  api/internal/target/resourceconflict_test.go
  api/internal/target/transformersarrays_test.go
  api/internal/target/transformersimage_test.go
  api/internal/target/variableref_test.go
  api/k8sdeps/kunstruct/hasher.go
  api/k8sdeps/kunstruct/hasher_test.go
  api/krusty/kustomizer_test.go
  api/kv/kv_test.go
  api/main.go
  api/resmap/factory_test.go
  api/resmap/resmap_test.go
  api/resource/resource_test.go
  api/transform/maptransformer_test.go
  api/types/erronlybuiltinpluginsallowed.go
Labels: approved, cncf-cla: yes, size/L

#1804 kyaml: enable errcheck & golint; fix gofmt
  kyaml/.golangci.yml
  kyaml/kio/filters/container_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1795 Library for computing status for Kubernetes resources
  kstatus/.golangci.yml
  kstatus/LICENSE_TEMPLATE
  kstatus/Makefile
  kstatus/doc.go
  kstatus/go.mod
  kstatus/go.sum
  kstatus/status/core.go
  kstatus/status/doc.go
  kstatus/status/example_test.go
  kstatus/status/generic.go
  kstatus/status/status.go
  kstatus/status/status_augment_test.go
  kstatus/status/status_compute_test.go
  kstatus/status/util.go
  kstatus/status/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1805 Activate lint gosimple.
  .golangci-kustomize.yml
  Makefile
  api/filesys/fsinmemory_test.go
  api/go.mod
  api/go.sum
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/plugins/compiler/compiler.go
  api/internal/target/multiplepatch_test.go
  api/types/genargs.go
  api/types/kustomization.go
Labels: approved, cncf-cla: yes, size/L

#1807 Activate lint staticcheck.
  .golangci-kustomize.yml
  api/internal/accumulator/refvartransformer.go
  api/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, size/XS

#1808 Fix makefile tabs (sigh).
  Makefile
Labels: approved, cncf-cla: yes, size/M

#1792 Add support to choose 'chartRelease' and 'chartVersion' while kustomizing remote helm charts
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
Labels: approved, cncf-cla: yes, lgtm, size/S

#1811 Activate lint for unused code.
  .golangci-kustomize.yml
  api/builtins/hashtransformer.go
  api/go.sum
  api/internal/accumulator/refvartransformer.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/target/kusttarget.go
  api/resource/resource.go
  api/types/genargs.go
Labels: cncf-cla: yes

#1810 Fix typo: suing -> using
  examples/goGetterGeneratorPlugin.md
Labels: approved, cncf-cla: yes, size/XS

#1812 Activate lint typecheck
  .golangci-kustomize.yml
  api/builtins/hashtransformer.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/resource/resource.go
  api/types/genargs.go
Labels: approved, cncf-cla: yes, size/S

#1813 Add test elaborating on custom config.
  api/internal/target/customconfigofbuiltinplugin_test.go
  api/internal/target/customconfigreusable_test.go
Labels: approved, cncf-cla: yes, size/L

#1819 fix typo
  docs/glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1815 Rename cmd/kyaml to cmd/config
  cmd/config/.golangci.yml
  cmd/config/LICENSE_TEMPLATE
  cmd/config/Makefile
  cmd/config/README.md
  cmd/config/cmd/cat.go
  cmd/config/cmd/cat_test.go
  cmd/config/cmd/cmdwrap.go
  cmd/config/cmd/cmdwrap_test.go
  cmd/config/cmd/cmdxargs.go
  cmd/config/cmd/cmdxargs_test.go
  cmd/config/cmd/count.go
  cmd/config/cmd/count_test.go
  cmd/config/cmd/fmt.go
  cmd/config/cmd/fmt_test.go
  cmd/config/cmd/grep.go
  cmd/config/cmd/grep_test.go
  cmd/config/cmd/merge.go
  cmd/config/cmd/run-fns.go
  cmd/config/cmd/test/override.yaml
  cmd/config/cmd/test/test.sh
  cmd/config/cmd/tree.go
  cmd/config/cmd/tree_test.go
  cmd/config/cmd/util.go
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/inpututil/inpututil.go
  cmd/config/main.go
  travis/kyaml-pre-commit.sh
  travis/verify-deps.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1814 Fix dir paths in crawler backend Dockerfile
  api/internal/crawl/cmd/backend/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS

#1821 Improve code generation rules.
  Makefile
  api/builtins/AnnotationsTransformer.go
  api/builtins/ConfigMapGenerator.go
  api/builtins/HashTransformer.go
  api/builtins/ImageTagTransformer.go
  api/builtins/InventoryTransformer.go
  api/builtins/LabelTransformer.go
  api/builtins/LegacyOrderTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/builtins/PrefixSuffixTransformer.go
  api/builtins/ReplicaCountTransformer.go
  api/builtins/SecretGenerator.go
  pluginator/go.mod
  pluginator/go.sum
  pluginator/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1631 Replacement poc
  api/types/replacement.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer_test.go
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XXL

#1823 Revert "Replacement poc"
  api/types/replacement.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer.go
  plugin/someteam.example.com/v1/replacementtransformer/ReplacementTransformer_test.go
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#1824 Fix docs broken files links as Github relative links
  README.md
  docs/FAQ.md
  docs/INSTALL.md
  docs/README.md
  docs/bugs.md
  docs/fields.md
  docs/glossary.md
  docs/plugins/goPluginGuidedExample.md
  docs/v2.1.0.md
  docs/v3.0.0.md
  docs/v3.3.0.md
  docs/versioningPolicy.md
  docs/zh/INSTALL.md
  docs/zh/README.md
  docs/zh/fields.md
  docs/zh/glossary.md
  examples/configGeneration.md
  examples/goGetterGeneratorPlugin.md
  examples/remoteBuild.md
  examples/secretGeneratorPlugin.md
  examples/zh/configGeneration.md
  examples/zh/remoteBuild.md
  examples/zh/secretGeneratorPlugin.md
  releasing/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1827 Add utility for generating cobra documentation from .md files
  cmd/mdtogo/go.mod
  cmd/mdtogo/main.go
Labels: approved, cncf-cla: yes, size/L

#1828 kyaml: fixup Makefile
  cmd/config/Makefile
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, size/M

#1829 kyaml: refactor command documentation into .md files from go files
  cmd/config/Makefile
  cmd/config/README.md
  cmd/config/cmd/cat.go
  cmd/config/cmd/cat_test.go
  cmd/config/cmd/count.go
  cmd/config/cmd/count_test.go
  cmd/config/cmd/fmt.go
  cmd/config/cmd/fmt_test.go
  cmd/config/cmd/grep.go
  cmd/config/cmd/grep_test.go
  cmd/config/cmd/merge.go
  cmd/config/cmd/run-fns.go
  cmd/config/cmd/tree.go
  cmd/config/cmd/tree_test.go
  cmd/config/cmd/util.go
  cmd/config/cmddocs/api/docs.go
  cmd/config/cmddocs/commands/docs.go
  cmd/config/docs/api-conventions/merge2.md
  cmd/config/docs/api-conventions/merge3.md
  cmd/config/docs/commands/cat.md
  cmd/config/docs/commands/count.md
  cmd/config/docs/commands/fmt.md
  cmd/config/docs/commands/grep.md
  cmd/config/docs/commands/merge.md
  cmd/config/docs/commands/run-fns.md
  cmd/config/docs/commands/tree.md
  cmd/config/main.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge3/merge3.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1831 Unpin the builtin plugins.
  hack/pinUnpinPluginApiDep.sh
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
Labels: approved, cncf-cla: yes, size/XL

#1830 Add api documentation for annotations and fns
  cmd/config/cmddocs/api/docs.go
  cmd/config/docs/api-conventions/config-fn.md
  cmd/config/docs/api-conventions/config-io.md
  cmd/config/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1820 Skip updating empty containers in image tranformer
  api/builtins/ImageTagTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1720 migrate Deployment from apps/v1beta2 to apps/v1
  examples/ldap/README.md
  examples/ldap/base/deployment.yaml
  examples/ldap/overlays/production/deployment.yaml
  examples/ldap/overlays/staging/deployment.yaml
  examples/mySql/README.md
  examples/mySql/deployment.yaml
  examples/springboot/README.md
  examples/springboot/base/deployment.yaml
  examples/springboot/overlays/production/healthcheck_patch.yaml
  examples/springboot/overlays/production/memorylimit_patch.yaml
  examples/wordpress/README.md
  examples/wordpress/mysql/deployment.yaml
  examples/wordpress/patch.yaml
  examples/wordpress/wordpress/deployment.yaml
  examples/zh/vars.md
Labels: cncf-cla: yes, size/M

#1832 Fix nit leftover from 1820
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchTransformer.go
Labels: approved, cncf-cla: yes, size/XS

#1834 docs: Fix images and name{Prefix,Suffix} field links.
  docs/fields.md
  docs/plugins/builtins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1836 Unpin all the plugins (non-builtins too).
  hack/pinUnpinPluginApiDep.sh
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printworkdir/go.mod
  plugin/someteam.example.com/v1/printworkdir/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/XL

#1837 Publish `cmd/config` as Kustomize subcommand group
  cmd/config/cmddocs/commands/docs.go
  cmd/config/cmds/cmds.go
  cmd/config/cmds/example_test.go
  cmd/config/docs/commands/cat.md
  cmd/config/docs/commands/count.md
  cmd/config/docs/commands/fmt.md
  cmd/config/docs/commands/grep.md
  cmd/config/docs/commands/merge.md
  cmd/config/docs/commands/run-fns.md
  cmd/config/docs/commands/tree.md
  cmd/config/main.go
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1840 mdtogo: support for alternate license headers
  cmd/config/.golangci.yml
  cmd/config/main.go
  cmd/mdtogo/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1842 cmd/config: add built-in tutorials
  cmd/config/cmd/tree.go
  cmd/config/cmddocs/tutorials/docs.go
  cmd/config/cmds/cmds.go
  cmd/config/docs/tutorials/configuration-basics.md
  cmd/config/main.go
  kyaml/kio/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1847 Refactor filesys to prep for new filesys.Walk
  api/filesys/file.go
  api/filesys/fileinfo.go
  api/filesys/filesystem.go
  api/filesys/fsinmemory.go
  api/filesys/fsinmemory_test.go
  api/filesys/util.go
  api/filesys/util_test.go
Labels: approved, cncf-cla: yes, size/L

#1818 Add APIs for computing status based on fetching resource info from a cluster
  kstatus/go.mod
  kstatus/go.sum
  kstatus/status/core.go
  kstatus/status/doc.go
  kstatus/status/example_test.go
  kstatus/status/generic.go
  kstatus/status/status.go
  kstatus/status/status_augment_test.go
  kstatus/status/status_compute_test.go
  kstatus/status/util.go
  kstatus/wait/doc.go
  kstatus/wait/util.go
  kstatus/wait/wait.go
  kstatus/wait/wait_test.go
  kstatus/wait/waitstate.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1849 More tests, better errors.
  api/filesys/fileinfo.go
  api/filesys/filesystem.go
  api/filesys/fsinmemory.go
  api/filesys/util.go
  api/filesys/util_test.go
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/target/kusttarget_test.go
  api/internal/target/plugindir_test.go
  api/konfig/plugins.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  api/loader/loadrestrictions.go
  api/loader/loadrestrictions_test.go
  api/resmap/factory_test.go
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/build_test.go
  kustomize/internal/commands/create/create.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, size/L

#1850 cmd/config: Add examples and tutorials for config functions
  cmd/config/cmd/run-fns.go
  cmd/config/cmddocs/tutorials/docs.go
  cmd/config/cmds/cmds.go
  cmd/config/docs/tutorials/function-basics.md
  functions/examples/injection-tshirt-sizes/LICENSE_TEMPLATE
  functions/examples/injection-tshirt-sizes/Makefile
  functions/examples/injection-tshirt-sizes/README.md
  functions/examples/injection-tshirt-sizes/image/Dockerfile
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/injection-tshirt-sizes/image/main.go
  functions/examples/injection-tshirt-sizes/local-resource/example-use.yaml
  functions/examples/template-go-nginx/LICENSE_TEMPLATE
  functions/examples/template-go-nginx/Makefile
  functions/examples/template-go-nginx/README.md
  functions/examples/template-go-nginx/image/Dockerfile
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/template-go-nginx/image/main.go
  functions/examples/template-go-nginx/local-resource/example-use.yaml
  functions/examples/template-heredoc-cockroachdb/LICENSE_TEMPLATE
  functions/examples/template-heredoc-cockroachdb/Makefile
  functions/examples/template-heredoc-cockroachdb/README.md
  functions/examples/template-heredoc-cockroachdb/image/Dockerfile
  functions/examples/template-heredoc-cockroachdb/image/cockroachdb-template.sh
  functions/examples/template-heredoc-cockroachdb/local-resource/example-use.yaml
  functions/examples/validator-resource-requests/LICENSE_TEMPLATE
  functions/examples/validator-resource-requests/Makefile
  functions/examples/validator-resource-requests/README.md
  functions/examples/validator-resource-requests/image/Dockerfile
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  functions/examples/validator-resource-requests/image/main.go
  functions/examples/validator-resource-requests/local-resource/example-use.yaml
Labels: approved, area/kyaml, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#1855 Make filesys.Walk work.
  api/filesys/fileinfo.go
  api/filesys/fileinmemory.go
  api/filesys/filesystem.go
  api/filesys/fsinmemory.go
  api/filesys/fsinmemory_test.go
  api/filesys/fsnode.go
  api/filesys/fsnode_test.go
  api/krusty/kustomizer_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  kustomize/internal/commands/create/create_test.go
  kustomize/internal/commands/edit/add/addpatch_test.go
  kustomize/internal/commands/edit/add/addresource_test.go
  kustomize/internal/commands/edit/add/flagsandargs_test.go
  kustomize/internal/commands/edit/remove/removepatch_test.go
Labels: approved, cncf-cla: yes, size/XXL

#1845 Make the crawler work
  api/internal/crawl/cmd/crawler/Dockerfile
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/config/crawler/base/github_api_secret.txt
  api/internal/crawl/config/crawler/base/kustomization.yaml
  api/internal/crawl/config/elastic/escluster.yaml
  api/internal/crawl/config/webapp/backend/deployment.yaml
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/queries.go
  api/internal/crawl/crawler/github/queries_test.go
  api/internal/crawl/doc/doc.go
Labels: cncf-cla: yes, lgtm, size/L

#1856 cmd/config: update naming of commands
  cmd/config/README.md
  cmd/config/cmd/cmdxargs.go
  cmd/config/cmd/run-fns.go
  cmd/config/cmd/util.go
  cmd/config/cmddocs/api/docs.go
  cmd/config/cmddocs/commands/docs.go
  cmd/config/cmddocs/tutorials/docs.go
  cmd/config/docs/api-conventions/config-fn.md
  cmd/config/docs/commands/cat.md
  cmd/config/docs/commands/count.md
  cmd/config/docs/commands/fmt.md
  cmd/config/docs/commands/grep.md
  cmd/config/docs/commands/merge.md
  cmd/config/docs/commands/run-fns.md
  cmd/config/docs/commands/tree.md
  cmd/config/docs/tutorials/function-basics.md
  functions/examples/injection-tshirt-sizes/README.md
  functions/examples/injection-tshirt-sizes/image/main.go
  functions/examples/template-go-nginx/README.md
  functions/examples/template-go-nginx/local-resource/example-use.yaml
  functions/examples/template-heredoc-cockroachdb/README.md
  functions/examples/template-heredoc-cockroachdb/image/cockroachdb-template.sh
  functions/examples/template-heredoc-cockroachdb/local-resource/example-use.yaml
  functions/examples/validator-resource-requests/README.md
  functions/examples/validator-resource-requests/image/main.go
Labels: approved, area/kyaml, cncf-cla: yes, kind/cleanup, lgtm, size/L

#1860 Start making examples more visible.
  api/krusty/baseandoverlaysmall_test.go
  api/krusty/doc.go
  api/krusty/kustomizer.go
  api/krusty/testingharness_test.go
Labels: approved, cncf-cla: yes, size/L

#1861 Provide another high level example.
  api/krusty/baseandoverlaymedium_test.go
Labels: approved, cncf-cla: yes, size/S

#1859 Fallback to full clone if git fetch fails
  api/internal/git/cloner.go
  kustomize/go.sum
Labels: cncf-cla: yes, size/S

#1863 Add example for replicas in kustomization.yaml
  examples/replicas.md
Labels: cncf-cla: yes, size/M

#1864 mv basereusenameprefix_test to api/krusty/
  api/krusty/basereusenameprefix_test.go
Labels: cncf-cla: yes, size/S

#1865 Simplify and document plugin test harness.
  Makefile
  api/internal/target/chartinflatorplugin_test.go
  api/internal/target/plugindir_test.go
  api/internal/target/transformerplugin_test.go
  api/krusty/testingharness_test.go
  api/testutils/kusttest/plugintestenv.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
  plugin/someteam.example.com/v1/gogetter/GoGetter_test.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/validator/validator_test.go
Labels: approved, cncf-cla: yes, size/L

#1866 Move another test up.
  api/krusty/testingharness_test.go
  api/krusty/transformerplugin_test.go
Labels: cncf-cla: yes

#1867 More tests.
  api/krusty/customconfig_test.go
  api/krusty/kustomizer_test.go
  api/krusty/testingharness_test.go
  api/krusty/transformersarrays_test.go
  api/krusty/transformersimage_test.go
Labels: approved, cncf-cla: yes, size/L

#1869 mv /api/internal/target example to /api/krusty
  api/krusty/configmaps_test.go
  api/krusty/crd_test.go
  api/krusty/diamonds_test.go
  api/krusty/extendedpatch_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/generatoroptions_test.go
  api/krusty/inlinepatch_test.go
  api/krusty/multiplepatch_test.go
  api/krusty/namespacedgenerators_test.go
  api/krusty/namespaces_test.go
  api/krusty/nullvalues_test.go
  api/krusty/pruneconfigmap_test.go
  api/krusty/resourceconflict_test.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1870 Move more examples up.
  api/krusty/accumulation_test.go
  api/krusty/chartinflatorplugin_test.go
Labels: cncf-cla: yes

#1871 Move remaining examples.
  api/krusty/complexcomposition_test.go
  api/krusty/customconfigofbuiltinplugin_test.go
  api/krusty/customconfigreusable_test.go
  api/krusty/diamondcomposition_test.go
  api/krusty/testingharness_test.go
Labels: approved, cncf-cla: yes, size/L

#1872 Add PrintPluginEnv plugin.
  api/internal/target/errmissingkustomization.go
  api/internal/target/kusttarget.go
  api/internal/target/plugindir_test.go
  api/krusty/pluginenv_test.go
  api/krusty/testingharness_test.go
  api/testutils/kusttest/plugintestenv.go
  plugin/someteam.example.com/v1/printpluginenv/PrintPluginEnv
  plugin/someteam.example.com/v1/printpluginenv/PrintPluginEnv_test.go
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir
Labels: approved, cncf-cla: yes, size/L

#1874 More tests/examples.
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_test.go
  api/internal/target/vars_test.go
  api/krusty/accumulation_test.go
  api/krusty/directoryarrangement_test.go
  api/krusty/disablenamesuffix_test.go
  api/krusty/kustomizer.go
  api/testutils/kusttest/kusttestharness.go
Labels: cncf-cla: yes
