Repository kubernetes-sigs/kustomize, pull requests merged in 2019-07, with the labels that each got.

#1288 Push json transform code down to plugin.
  go.sum
  pkg/kusttest/kusttestharness.go
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
Labels: approved, cncf-cla: yes, size/XXL

#1290 Update the diamond composition test case
  pkg/target/diamondcomposition_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#1289 Add more json transformer examples.
  pkg/kusttest/kusttestharness.go
  pkg/target/diamondcomposition_test.go
Labels: approved, cncf-cla: yes, size/L

#1291 Add another resmap test.
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1294 Add a test combining imagetag and jsonpatch
  pkg/target/transformersimage_test.go
Labels: approved, cncf-cla: yes, size/M

#1293 Fix 1281
  pkg/target/kusttarget_configplugin.go
  pkg/target/transformersimage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1297 Add complex overlay composition test
  pkg/target/complexcomposition_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1270 Chinese localization & fix fields.md
  docs/fields.md
  docs/zh/README.md
  docs/zh/fields.md
  docs/zh/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1302 Add support for nginx.ingress.kubernetes.io/auth-tls-secret
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference_test.go
Labels: cncf-cla: yes, lgtm, size/S

#1305 Update goPluginGuidedExample.md
  docs/plugins/goPluginGuidedExample.md
  go.sum
Labels: cncf-cla: yes

#1306 Update v3 notes
  docs/v3.0.0.md
Labels: cncf-cla: yes

#1309 Fix typo in the go plugin guide
  docs/plugins/goPluginGuidedExample.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1321 Enable ns transformer for webhook
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1328 fix the regression on merging configmap with different namespace
  pkg/ifc/ifc.go
  pkg/resource/resource.go
  pkg/target/namespacedgenerators_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1330 Generate updated ns transformer
  plugin/builtin/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1338 Fix missing nameReference in default config
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1340 refactor the strategic merge patch transformer toward moving it to a plugin
  k8sdeps/kunstruct/kunstruct.go
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/patch/conflictdetector.go
  k8sdeps/transformer/patch/transformer.go
  pkg/commands/commands.go
  pkg/ifc/ifc.go
  pkg/kusttest/kusttestharness.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader_test.go
  pkg/resmap/factory.go
  pkg/resmap/patchfactory.go
  pkg/resmap/resmap_test.go
  pkg/target/plugindir_test.go
Labels: approved, cncf-cla: yes, size/L

#1341 move strategic merge patch transformer to a builtin transformer
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/patch/transformer.go
  k8sdeps/transformer/patch/transformer_test.go
  pkg/commands/build/build.go
  pkg/ifc/transformer/factory.go
  pkg/kusttest/kusttestharness.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1344 include nameprefix and namesuffix to find matched reference for cluster level kinds
  pkg/resmap/resmap.go
  pkg/target/resourceconflict_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1333 Fix typo: kubectl v1.15 -> kubectl v1.14
  README.md
Labels: cncf-cla: no, size/XS

#1331 docs/versioningPolicy.md: fix expired urls
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1346 add extended patch transformer
  k8sdeps/kunstruct/kunstruct.go
  pkg/ifc/ifc.go
  plugin/builtin/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1336 Remove go testing flags from kustomize help
  pkg/plugins/loader_test.go
  pkg/plugins/test/envfortest.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/diamondcomposition_test.go
  pkg/target/plugindir_test.go
  pkg/target/transformerplugin_test.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator_test.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer_test.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator_test.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer_test.go
  plugin/someteam.example.com/v1/validator/validator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1348 Add storage class name ref
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1356 Test tracking issue patchesStrategicMerge elements can be dropped
  pkg/target/chartinflatorplugin_test.go
  pkg/target/multiplepatch_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1359 Address replacement of digest by ImageTransformer
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1350 Convert go plugin example to GPG based
  docs/plugins/goPluginGuidedExample.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1349 Add FAQ about how to customize configuration
  docs/FAQ.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1362 update the latest version in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1325 NameReference Transformer needs to account for namespace and cluster wide objects.
  pkg/commands/build/build.go
  pkg/resmap/resmap.go
  pkg/resmaptest/rmbuilder.go
  pkg/resource/factory.go
  pkg/resource/resource.go
  pkg/target/namespaces_test.go
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1365 Fix kustomize install in integration test
  examples/integration_tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1326 Residequals patchtransformer
  k8sdeps/transformer/patch/conflictdetector.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1369 add ResourceQuota to the order list
  pkg/gvk/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1327 ResId.Equals usable for VariableRef.
  pkg/accumulator/resaccumulator.go
  pkg/target/namespaces_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1371 Add namespace to variable definition
  pkg/accumulator/resaccumulator.go
  pkg/target/namespaces_test.go
  pkg/types/var.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1363 update edit fix to convert the old patches to patchesStrategicMerge
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/target/extendedpatch_test.go
  pkg/target/kusttarget_configplugin.go
  pkg/types/fix.go
  pkg/types/kustomization.go
  plugin/builtin/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1379 Update Namespace and Name simultaneously
  pkg/target/namespaces_test.go
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1388 add example for extended patches
  examples/README.md
  examples/patchMultipleObjects.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1378 Name Prefix and Suffix Transformation for multi level level kustomize context
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/target/resourceconflict_test.go
  plugin/builtin/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1398 Update v3.1.0 release notes.
  docs/README.md
  docs/v3.1.0.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1397 release note for v3.1.0
  docs/README.md
  docs/v3.1.0.md
Labels: approved, cncf-cla: yes, size/XS

#1308 Demonstrate need for Var.DeepEqual method equivalent
  pkg/target/kusttarget_test.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1396 support strategic merge patch with $patch: delete
  k8sdeps/kunstruct/kunstruct.go
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1400 Force the namespace value for the "default" service object.
  pkg/target/namespaces_test.go
  pkg/transformers/config/defaultconfig/namespace.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1403 add testing for patch transformers
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1402 Allow replicas to find modified names.
  go.sum
  pkg/kusttest/kusttestharness.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1405 add inline patch support for Strategic Merge Patch and JSON patch
  pkg/target/inlinepatch_test.go
  pkg/target/kusttarget_configplugin.go
  pkg/types/kustomization.go
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1411 add document for inline patch
  docs/fields.md
Labels: approved, cncf-cla: yes, size/M

#1413 Fix typo in patches definition
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1389 make repospec memebers public
  pkg/git/cloner.go
  pkg/git/repospec.go
  pkg/git/repospec_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1412 Automatically anchor resource selector patterns
  docs/fields.md
  pkg/resmap/resmap.go
  pkg/resmap/selector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1394 Simplify name reference candidate resmap building
  pkg/resmap/resmap.go
Labels: approved, cncf-cla: yes, lgtm, size/S
