Repository kubernetes-sigs/kustomize, pull requests merged in 2019-08, with the labels that each got.

#1423 Update zh-README.md & zh-example-README.md
  docs/zh/README.md
  examples/zh/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1416 add Makefile for local development
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1432 Retain replicas field in edit marshal path
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1436 docs: Additional details for kubectl integration
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1450 Add internal tooling for kustomize
  internal/tools/crawler/crawler.go
  internal/tools/crawler/crawler_test.go
  internal/tools/crawler/github/crawler.go
  internal/tools/crawler/github/queries.go
  internal/tools/crawler/github/queries_test.go
  internal/tools/crawler/github/split_search_ranges.go
  internal/tools/crawler/github/split_search_ranges_test.go
  internal/tools/doc/doc.go
  internal/tools/doc/doc_test.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/httpclient/httpclient.go
Labels: cncf-cla: yes, lgtm, size/XXL

#1374 fix: windows builds
  pkg/plugins/execplugin.go
Labels: cncf-cla: yes, lgtm, size/XS

#1461 Fix non-travis tests.
  pkg/target/chartinflatorplugin_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
  plugin/someteam.example.com/v1/validator/validator_test.go
Labels: cncf-cla: yes

#1462 in plugin executor remove unnecessary code and improve error messages
  pkg/plugins/execplugin.go
  plugin/someteam.example.com/v1/validator/validator_test.go
Labels: approved, cncf-cla: yes, size/M

#1465 Test examples against HEAD as well as against latest release.
  docs/INSTALL.md
  docs/zh/INSTALL.md
  examples/README.md
  examples/breakfast.md
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/generatorOptions.md
  examples/helloWorld/README.md
  examples/image.md
  examples/jsonpatch.md
  examples/ldap/README.md
  examples/multibases/README.md
  examples/multibases/multi-namespace.md
  examples/mySql/README.md
  examples/patchMultipleObjects.md
  examples/remoteBuild.md
  examples/secretGeneratorPlugin.md
  examples/springboot/README.md
  examples/transformerconfigs/crd/README.md
  examples/transformerconfigs/images/README.md
  examples/validationTransformer/README.md
  examples/wordpress/README.md
  examples/zh/configGeneration.md
  examples/zh/helloWorld.md
  examples/zh/jsonpatch.md
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1419 Handle git:: prefix in urls containing _git
  pkg/git/repospec.go
  pkg/git/repospec_test.go
Labels: cncf-cla: yes, lgtm, size/S

#1426 translate-zh: glossary.md
  docs/zh/README.md
  docs/zh/glossary.md
Labels: cncf-cla: yes, lgtm, size/L

#1435 Download submodules when using base from git
  pkg/git/cloner.go
Labels: cncf-cla: yes, lgtm, size/S

#1437 add PriorityClass to the order list
  pkg/gvk/gvk.go
Labels: cncf-cla: yes, lgtm, size/XS

#1445 Fix patch path example
  docs/fields.md
Labels: cncf-cla: yes, lgtm, size/XS

#1464 Add internal tooling library for index managment.
  internal/tools/index/elasticsearch.go
  internal/tools/index/kustomize.go
  internal/tools/index/kustomize_test.go
Labels: cncf-cla: yes, lgtm, size/XL

#1449 Fix indirect cycle detection for git resources
  pkg/git/cloner.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/target/kusttarget.go
Labels: cncf-cla: yes, lgtm, size/M

#1414 Create subcommand
  pkg/commands/commands.go
  pkg/commands/create/create.go
  pkg/commands/create/create_test.go
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/edit/add/addmetadata_test.go
  pkg/commands/edit/add/addpatch.go
  pkg/commands/edit/add/addresource.go
  pkg/commands/edit/add/flagsandargs.go
  pkg/commands/edit/remove/removepatch.go
  pkg/commands/edit/util/functions.go
  pkg/commands/util/util.go
  pkg/commands/util/util_test.go
  pkg/fs/fakefs.go
  pkg/fs/fs.go
  pkg/fs/realfs.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1456 fix latest version
  README.md
Labels: cncf-cla: yes, lgtm, size/XS

#1455 Add short version flag
  pkg/commands/misc/version.go
Labels: cncf-cla: yes, lgtm, size/S

#1467 Fixes to create sub-command
  pkg/commands/create/create.go
  pkg/commands/create/create_test.go
  pkg/commands/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1469 Add simple service/configs to internal tooling.
  internal/tools/backend/search_backend.go
  internal/tools/cmd/backend/Dockerfile
  internal/tools/cmd/backend/main.go
  internal/tools/config/base/kustomization.yaml
  internal/tools/config/webapp/backend/deployment.yaml
  internal/tools/config/webapp/backend/kustomization.yaml
  internal/tools/config/webapp/backend/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1470 First draft of documentation for internal/tools
  internal/tools/README.md
  internal/tools/ROADMAP.md
  internal/tools/pictures/github_token.png
  internal/tools/pictures/sys_arch.png
  internal/tools/pictures/token_config.png
Labels: cncf-cla: yes, lgtm, size/XL

#1476 Adds frontend + configs to interal/tools
  internal/tools/config/webapp/frontend/deployment.yaml
  internal/tools/config/webapp/frontend/kustomization.yaml
  internal/tools/config/webapp/frontend/service.yaml
  internal/tools/ui/.dockerignore
  internal/tools/ui/.gcloudignore
  internal/tools/ui/.gitignore
  internal/tools/ui/Dockerfile
  internal/tools/ui/README.md
  internal/tools/ui/angular.json
  internal/tools/ui/browserslist
  internal/tools/ui/cloudbuild.yaml
  internal/tools/ui/e2e/protractor.conf.js
  internal/tools/ui/e2e/src/app.e2e-spec.ts
  internal/tools/ui/e2e/src/app.po.ts
  internal/tools/ui/e2e/tsconfig.json
  internal/tools/ui/karma.conf.js
  internal/tools/ui/nginx.conf
  internal/tools/ui/package-lock.json
  internal/tools/ui/package.json
  internal/tools/ui/src/app/app.component.css
  internal/tools/ui/src/app/app.component.html
  internal/tools/ui/src/app/app.component.spec.ts
  internal/tools/ui/src/app/app.component.ts
  internal/tools/ui/src/app/app.module.ts
  internal/tools/ui/src/app/documents.ts
  internal/tools/ui/src/app/histogram/histogram.component.css
  internal/tools/ui/src/app/histogram/histogram.component.html
  internal/tools/ui/src/app/histogram/histogram.component.spec.ts
  internal/tools/ui/src/app/histogram/histogram.component.ts
  internal/tools/ui/src/app/search/search.component.css
  internal/tools/ui/src/app/search/search.component.html
  internal/tools/ui/src/app/search/search.component.spec.ts
  internal/tools/ui/src/app/search/search.component.ts
  internal/tools/ui/src/app/search/search.service.ts
  internal/tools/ui/src/app/timeseries/timeseries.component.css
  internal/tools/ui/src/app/timeseries/timeseries.component.html
  internal/tools/ui/src/app/timeseries/timeseries.component.spec.ts
  internal/tools/ui/src/app/timeseries/timeseries.component.ts
  internal/tools/ui/src/assets/.gitkeep
  internal/tools/ui/src/environments/environment.prod.ts
  internal/tools/ui/src/environments/environment.ts
  internal/tools/ui/src/favicon.ico
  internal/tools/ui/src/index.html
  internal/tools/ui/src/main.ts
  internal/tools/ui/src/polyfills.ts
  internal/tools/ui/src/styles.css
  internal/tools/ui/src/test.ts
  internal/tools/ui/tsconfig.app.json
  internal/tools/ui/tsconfig.json
  internal/tools/ui/tsconfig.spec.json
  internal/tools/ui/tslint.json
Labels: cncf-cla: yes, lgtm, size/XXL

#1460 Detect ID conflicts in namespace transformer
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1474 Add cover target to Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1383 Handle ordering patch with SMP delete directives
  docs/fields.md
  docs/glossary.md
  k8sdeps/transformer/patch/conflictdetector.go
  pkg/target/multiplepatch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1481 Add configs
  internal/tools/config/crawler/base/kustomization.yaml
  internal/tools/config/crawler/cronjob/cronjob.yaml
  internal/tools/config/crawler/cronjob/kustomization.yaml
  internal/tools/config/crawler/job/job.yaml
  internal/tools/config/crawler/job/kustomization.yaml
  internal/tools/config/redis/document_keystore/kustomization.yaml
  internal/tools/config/redis/document_keystore/redis.yaml
  internal/tools/config/redis/document_keystore/service.yaml
  internal/tools/config/redis/http_cache/kustomization.yaml
  internal/tools/config/redis/http_cache/redis.yaml
  internal/tools/config/redis/http_cache/service.yaml
Labels: cncf-cla: yes, size/L

#1446 IsInKustomizeCtx should use end of nameprefix array instead of beginning
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/target/resourceconflict_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1487 properly omitempty for 'inventory' in 'kustomize'
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1490 feat: Add instructions for setting key in configmap
  docs/fields.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1492 Test custom configuration of a builtin plugin.
  pkg/target/customconfigofbuiltinplugin_test.go
Labels: approved, cncf-cla: yes, size/L
