Repository kubernetes-sigs/kustomize, pull requests merged in 2019-04, with the labels that each got.

#938 Expound on plugin caveats
  examples/kvSourceGoPlugin.md
Labels: approved, cncf-cla: yes, size/L

#939 add tutorial for custom images transformer
  examples/transformerconfigs/README.md
  examples/transformerconfigs/images/README.md
  examples/transformerconfigs/images/kustomization.yaml
  examples/transformerconfigs/images/mykind.yaml
  examples/transformerconfigs/images/resources.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#941 add generators/transformers fields in kusotmization.yaml
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#946 add support for transformer goplugins
  pkg/commands/build/build.go
  pkg/commands/commands.go
  pkg/pgmconfig/constants.go
  pkg/plugins/transformers.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/kusttestharness_test.go
  pkg/target/transformerplugin_test.go
  pkg/transformers/transformer.go
  plugins/DatePrefixer.go
  plugins/StringPrefixer.go
  plugins/kvMaker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#948 Fix path
  docs/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#950 Add --force flag to modify annotations and labels
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/edit/add/addmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#953 Cleanup plugin builds.
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/kunstruct/factory.go
  k8sdeps/kv/plugin/registry.go
  pkg/commands/build/build.go
  pkg/commands/commands.go
  pkg/pgmconfig/constants.go
  pkg/plugins/transformers.go
  pkg/target/generatoroptions_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/kusttestharness_test.go
  pkg/target/testenvcontroller_test.go
  pkg/target/transformerplugin_test.go
  pkg/types/kustomization.go
  plugins/someteam.example.com/v1/DatePrefixer.go
  plugins/someteam.example.com/v1/StringPrefixer.go
  plugins/someteam.example.com/v1/kvMaker.go
Labels: approved, cncf-cla: yes, size/L

#951 add support for generator go-plugins
  pkg/plugins/generators.go
  pkg/target/generatorplugin_test.go
  pkg/target/kusttarget.go
  plugins/ServiceGenerator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#954 Consolidate some generator and transformer code.
  k8sdeps/kv/plugin/registry.go
  pkg/plugins/generators.go
  pkg/plugins/transformers.go
  pkg/target/generatorplugin_test.go
  pkg/target/kusttarget.go
  pkg/target/testenvcontroller_test.go
  pkg/transformers/transformer.go
  plugins/someteam.example.com/v1/DatePrefixer.go
  plugins/someteam.example.com/v1/ServiceGenerator.go
  plugins/someteam.example.com/v1/StringPrefixer.go
  plugins/someteam.example.com/v1/kvMaker.go
Labels: approved, cncf-cla: yes, size/L

#955 Add secret generator.
  k8sdeps/kunstruct/kunstruct.go
  pkg/ifc/ifc.go
  pkg/plugins/generators.go
  pkg/plugins/transformers.go
  pkg/target/generatorplugin_test.go
  pkg/target/kusttarget.go
  plugins/kustomize.config.k8s.io/v1/SecretGenerator.go
  plugins/someteam.example.com/v1/DatePrefixer.go
  plugins/someteam.example.com/v1/ServiceGenerator.go
  plugins/someteam.example.com/v1/StringPrefixer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#926 generate configmap for pruning
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/hash/hash.go
  k8sdeps/transformer/hash/hash_test.go
  k8sdeps/transformer/prune/prune.go
  k8sdeps/transformer/prune/prune_test.go
  pkg/commands/build/build.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/ifc/transformer/factory.go
  pkg/resid/resid.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
  pkg/target/pruneconfigmap_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#957 Define a plugin compiler.
  pkg/commands/commands.go
  pkg/pgmconfig/config.go
  pkg/pgmconfig/config_test.go
  pkg/pgmconfig/constants.go
  pkg/plugins/compiler.go
  pkg/plugins/compiler_test.go
  pkg/plugins/transformers.go
  pkg/target/kusttarget.go
  pkg/target/testenvcontroller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#959 add goplugin for exec generators and transformers
  bin/pre-commit.sh
  pkg/plugins/builtin/executable.go
  pkg/plugins/generators.go
  pkg/plugins/transformers.go
  pkg/target/generatorplugin_test.go
  pkg/target/testenvcontroller_test.go
  plugins/someteam.example.com/v1/ConfigMapGenerator
Labels: approved, cncf-cla: yes, lgtm, size/L

#974 add support for exec plugins
  bin/pre-commit.sh
  k8sdeps/kunstruct/kunstruct.go
  pkg/plugins/builtin/executable.go
  pkg/plugins/compiler.go
  pkg/plugins/executable.go
  pkg/plugins/transformers.go
  pkg/target/generatorplugin_test.go
  pkg/target/transformerplugin_test.go
  pkg/types/errors.go
  plugins/someteam.example.com/v1/ConfigMapGenerator
  plugins/someteam.example.com/v1/SedTransformer
Labels: approved, cncf-cla: yes, lgtm, size/L

#983 add the unstructured to ENV of exec plugins
  pkg/plugins/executable.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#980 Helm chart generator exec plugin
  .travis.yml
  bin/pre-commit.sh
  pkg/plugins/execplugin.go
  pkg/plugins/execplugin_test.go
  pkg/target/chartinflatorexecplugin_test.go
  pkg/target/generatorplugin_test.go
  pkg/target/transformerplugin_test.go
  plugins/kustomize.config.k8s.io/v1/ChartInflatorExec
  plugins/someteam.example.com/v1/ConfigMapGenerator
  plugins/someteam.example.com/v1/SedTransformer
Labels: approved, cncf-cla: yes, lgtm, size/L

#984 Vars should expand in ingress/spec/tls/secretName
  pkg/target/variableref_test.go
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#989 update PruneString for resources
  k8sdeps/transformer/prune/prune.go
  k8sdeps/transformer/prune/prune_test.go
  pkg/resid/resid.go
  pkg/resource/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#988 fix namespace transformer for cluster-scoped resources
  pkg/gvk/gvk.go
  pkg/transformers/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#960 Write individual files to output path if it is a directory
  pkg/commands/build/build.go
Labels: cncf-cla: yes, lgtm, size/M

#971 tests: demonstrate issue with JSON patch when base adds name prefix
  pkg/target/baseandoverlaysmall_test.go
Labels: cncf-cla: yes, lgtm, size/M

#990 Remove some duped code.
  pkg/commands/build/build.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#992 docs add kubectl command
  docs/workflows.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#993 Fix some comment nits.
  k8sdeps/transformer/prune/prune.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/loader/fileloader.go
  pkg/plugins/execplugin.go
Labels: approved, cncf-cla: yes, size/M

#996 Add test showing shared patches disallowed
  pkg/target/baseandoverlaysmall_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#995 Remove local load restrictions.
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
  pkg/loader/loadrestrictions.go
  pkg/loader/loadrestrictions_test.go
  pkg/target/baseandoverlaysmall_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#998 Add load_restrictor flag.
  go.mod
  pkg/commands/build/build.go
  pkg/internal/loadertest/fakeloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
  pkg/loader/loadrestrictions.go
  pkg/loader/loadrestrictions_string.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/kusttestharness_test.go
Labels: approved, cncf-cla: yes, size/L

#1000 Add faq
  docs/FAQ.md
  docs/README.md
Labels: approved, cncf-cla: yes, size/M

#1002 Delete kustomizationerror.
  go.mod
  go.sum
  pkg/internal/error/kustomizationerror.go
  pkg/internal/error/kustomizationerror_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1003 Simplify plugin loader code.
  pkg/commands/build/build.go
  pkg/commands/commands.go
  pkg/plugins/compiler.go
  pkg/plugins/execplugin.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/generators.go
  pkg/plugins/transformers.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/kusttestharness_test.go
  pkg/target/transformerplugin_test.go
  plugins/someteam.example.com/v1/DatePrefixer.go
  plugins/someteam.example.com/v1/StringPrefixer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1004 change field name: prune -> inventory
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/inventory/inventory.go
  k8sdeps/transformer/inventory/inventory_test.go
  pkg/commands/build/build.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/ifc/transformer/factory.go
  pkg/target/kusttarget.go
  pkg/target/pruneconfigmap_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1005 Add a plugin loader test.
  internal/plugintest/plugintestenv.go
  pkg/plugins/generators.go
  pkg/plugins/loader.go
  pkg/plugins/loader_test.go
  pkg/target/chartinflatorexecplugin_test.go
  pkg/target/generatorplugin_test.go
  pkg/target/transformerplugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1007 Collect existing internal pkgs under one roof.
  internal/kusterr/configmaperror.go
  internal/kusterr/configmaperror_test.go
  internal/kusterr/patcherror.go
  internal/kusterr/patcherror_test.go
  internal/kusterr/resourceerror.go
  internal/kusterr/resourceerror_test.go
  internal/kusterr/secreterror.go
  internal/kusterr/secreterror_test.go
  internal/kusterr/yamlformaterror.go
  internal/kusterr/yamlformaterror_test.go
  internal/loadertest/fakeloader.go
  pkg/patch/transformer/factory_test.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/resource/factory_test.go
  pkg/target/kusttarget_test.go
  pkg/target/kusttestharness_test.go
  pkg/transformers/config/factorycrd_test.go
Labels: approved, cncf-cla: yes, size/M

#1008 add ItemId type
  pkg/gvk/gvk.go
  pkg/resid/itemid.go
  pkg/resid/itemid_test.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1011 pass loader root to exec plugins
  pkg/plugins/execplugin.go
  pkg/target/plugindir_test.go
  plugins/someteam.example.com/v1/PrintWorkDir
Labels: approved, cncf-cla: yes, lgtm, size/L

#1016 Make plugin dir match Go conventions.
  examples/kvSourceGoPlugin.md
  k8sdeps/kv/plugin/registry.go
  pkg/plugins/compiler_test.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader_test.go
  pkg/target/chartinflatorexecplugin_test.go
  pkg/target/generatorplugin_test.go
  plugin/builtin/ChartInflatorExec
  plugin/builtin/SecretGenerator.go
  plugin/someteam.example.com/v1/ConfigMapGenerator
  plugin/someteam.example.com/v1/DatePrefixer.go
  plugin/someteam.example.com/v1/PrintWorkDir
  plugin/someteam.example.com/v1/SedTransformer
  plugin/someteam.example.com/v1/ServiceGenerator.go
  plugin/someteam.example.com/v1/StringPrefixer.go
  plugin/someteam.example.com/v1/kvMaker.go
Labels: approved, cncf-cla: yes, size/M

#1014 Remove dependency on ghodss/yaml
  go.mod
  go.sum
  pkg/commands/build/build.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/plugins/execplugin.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget.go
  pkg/transformers/config/factory.go
  pkg/transformers/config/factorycrd.go
Labels: cncf-cla: yes, lgtm, size/S

#1019 Mods to chart inflator plugin
  pkg/target/chartinflatorexecplugin_test.go
  plugin/someteam.example.com/v1/ChartInflatorExec
Labels: approved, cncf-cla: yes, lgtm, size/M

#1021 Update strategic-merge link
  docs/glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#828 Adds documentation for choco package for windows
  docs/INSTALL.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1024 Update remoteBuild.md
  examples/remoteBuild.md
Labels: approved, cncf-cla: yes, size/M

#1030 start v2.1 release notes
  docs/README.md
  docs/glossary.md
  docs/plugins.md
  docs/version2.1.0.md
Labels: approved, cncf-cla: yes

#1031 Add bug report page.
  README.md
  docs/README.md
  docs/bugs.md
  docs/v_2.0.0.md
  docs/v_2.1.0.md
Labels: cncf-cla: yes

#1020 Helm chart generator plugin example.
  bin/pre-commit.sh
  examples/README.md
  examples/chart.md
Labels: approved, cncf-cla: yes, size/L
