Repository kubernetes-sigs/kustomize, pull requests merged in 2019-02, with the labels that each got.

#755 Combine generatorArgs and generatorOptions into options of Resource
  k8sdeps/transformer/hash/namehash.go
  k8sdeps/transformer/hash/namehash_test.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/factory.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/utils_for_test.go
  pkg/types/genargs.go
  pkg/types/generationbehavior.go
Labels: approved, cncf-cla: yes, size/L

#748 add group name as kustomize.config.k8s.io
  docs/kustomization.yaml
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/fs/fakefs.go
  pkg/target/configmaps_test.go
  pkg/target/crd_test.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/kusttarget_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/namespacedgenerators_test.go
  pkg/target/utils_for_test.go
  pkg/target/variableref_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#751 Accept a wider variety of kubernetes yaml values
  pkg/target/nullvalues_test.go
  pkg/transformers/refvars.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#757 minor fix: incorrect apiVersion and add NoOpTransformer for vars
  pkg/target/generatoroptions_test.go
  pkg/target/nullvalues_test.go
  pkg/transformers/refvars.go
Labels: approved, cncf-cla: yes, size/XS

#753 Versioning policy.
  docs/README.md
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#763 allow apiVersion and Kind to be empty or specific values
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#764 refactor kv pairs
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/kv.go
  k8sdeps/configmapandsecret/kv_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/kv/kv.go
  k8sdeps/kv/kv_test.go
Labels: cncf-cla: yes, lgtm, size/L

#752 add documentation for kustomize 2.0.0
  docs/README.md
  docs/version2.0.0.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#773 Rename kv.KVPair to kv.Pair
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/kv.go
  k8sdeps/configmapandsecret/kv_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/kv/kv.go
  k8sdeps/kv/kv_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#779 Add nil ptr check
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#771 Improve error msg returned when no kustomization file is found
  pkg/constants/constants.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 Add more git url regression coverage
  pkg/git/repospec.go
  pkg/git/repospec_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#761 add volumeMounts/mountPath to varreference
  pkg/target/variableref_test.go
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#781 transformers/image: loop refactoring
  pkg/transformers/image.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#783 Test missing kust file message
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/secretfactory.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, size/M

#785 Switch to black box testing of KustTarget and Resource
  pkg/commands/build/build.go
  pkg/resource/factory_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/configmaps_test.go
  pkg/target/crd_test.go
  pkg/target/customconfig_test.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/kusttestharness_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/namespacedgenerators_test.go
  pkg/target/nullvalues_test.go
  pkg/target/resaccumulator.go
  pkg/target/resaccumulator_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/variableref_test.go
  pkg/types/genargs.go
  pkg/types/genargs_test.go
  pkg/types/var.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#788 fix invalid relative path in kustomization.yaml
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#790 Allow all kind list types
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
  pkg/resource/factory.go
  pkg/resource/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#782 add support for varref in maps values
  pkg/target/variableref_test.go
  pkg/transformers/config/defaultconfig/varreference.go
  pkg/transformers/refvars.go
  pkg/transformers/refvars_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#795 Delete extraneous copyright.
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/util.go
Labels: approved, cncf-cla: yes, size/M

#789 Pulling goos and goarch from runtime
  pkg/commands/misc/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#796 Add more resid test coverage.
  k8sdeps/transformer/patch/patch.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/target/resaccumulator.go
  pkg/transformers/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#762 typo: makes verb number agree with subject
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 Add doc indicating existing of 'behavior' in configMapGenerator
  docs/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#809 prevent panic on image transformer
  pkg/transformers/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#786 Change ExpandFileSource to work with key=val patterns
  pkg/commands/edit/add/flagsandargs.go
  pkg/commands/edit/add/flagsandargs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#811 fix absolute path for temp folder in MacOs
  pkg/fs/confirmeddir.go
  pkg/fs/confirmeddir_test.go
  pkg/fs/realfs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#812 More generator tests.
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, size/L

#813 Add Pod initContainer to var reference
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#820 Change imagetag to image in docs/eschewedFeatures.md
  docs/eschewedFeatures.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#827 Improve error handling during var resolution.
  pkg/commands/build/build_test.go
  pkg/commands/edit/add/flagsandargs.go
  pkg/expansion/expand.go
  pkg/expansion/expand_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/target/resaccumulator.go
  pkg/target/resaccumulator_test.go
Labels: approved, cncf-cla: yes, size/L

#825 Update golang/x/net dependency to release-branch.go1.11
  Gopkg.lock
  vendor/golang.org/x/net/http/httpguts/guts.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/ciphers.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/configure_transport.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go111.go
  vendor/golang.org/x/net/http2/go16.go
  vendor/golang.org/x/net/http2/go17.go
  vendor/golang.org/x/net/http2/go17_not18.go
  vendor/golang.org/x/net/http2/go18.go
  vendor/golang.org/x/net/http2/go19.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/not_go111.go
  vendor/golang.org/x/net/http2/not_go16.go
  vendor/golang.org/x/net/http2/not_go17.go
  vendor/golang.org/x/net/http2/not_go18.go
  vendor/golang.org/x/net/http2/not_go19.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/idna/idna.go
  vendor/golang.org/x/net/idna/tables.go
  vendor/golang.org/x/net/idna/trieval.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#822 Add webhooks to order list of gvk
  pkg/gvk/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#829 Log warning about well-defined but unused variables.
  pkg/expansion/expand.go
  pkg/expansion/expand_test.go
  pkg/target/resaccumulator.go
  pkg/target/resaccumulator_test.go
  pkg/transformers/refvars.go
  pkg/transformers/refvars_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#830 update transformerconfigs/crd example
  docs/kustomization.yaml
  examples/transformerconfigs/README.md
  examples/transformerconfigs/crd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
