Repository kubernetes-sigs/kustomize, pull requests merged in 2019-05, with the labels that each got.

#1022 add the Chhinese translation of docs list & install
  docs/README.md
  docs/zh/INSTALL.md
  docs/zh/README.md
  docs/zh/workflows.md
Labels: approved, cncf-cla: yes, size/L

#1041 Introduce envs field.
  docs/kustomization.yaml
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kv/plugin/registry.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/plugins/config.go
  pkg/plugins/loader.go
  pkg/resmap/factory_test.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/generatorplugin_test.go
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
  plugin/builtin/SecretGenerator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1046 Make kusttestharness shareable.
  pkg/kusttest/kusttestharness.go
  pkg/plugins/loader.go
  pkg/resource/factory.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/builtinplugins_test.go
  pkg/target/chartinflatorexecplugin_test.go
  pkg/target/configmaps_test.go
  pkg/target/crd_test.go
  pkg/target/customconfig_test.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/generatorplugin_test.go
  pkg/target/kusttarget_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/namespacedgenerators_test.go
  pkg/target/nullvalues_test.go
  pkg/target/plugindir_test.go
  pkg/target/pruneconfigmap_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/transformerplugin_test.go
  pkg/target/transformersimage_test.go
  pkg/target/variableref_test.go
Labels: approved, cncf-cla: yes, size/XL

#1045 pass resources to transformer plugin all together
  pkg/plugins/execplugin.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/target/transformerplugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1047 Add test for builtin secretgenerator plugin.
  pkg/kusttest/kusttestharness.go
  pkg/plugins/loader.go
  pkg/resmap/legacygeneratorargs.go
  pkg/target/generatorplugin_test.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/SecretGenerator_test.go
Labels: approved, cncf-cla: yes, size/L

#1048 fix the bug for setting annotations when triggering transformers
  pkg/plugins/execplugin.go
  pkg/target/transformerplugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1050 Add ConfigMapGenerator and test.
  pkg/resmap/legacygeneratorargs.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ConfigMapGenerator_test.go
Labels: approved, cncf-cla: yes, size/L

#1051 Fix a plugin nit.
  pkg/resmap/legacygeneratorargs.go
  plugin/builtin/SecretGenerator.go
Labels: approved, cncf-cla: yes

#1056 Translate kustomization.yaml
  docs/zh/README.md
  docs/zh/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1064 fix the boilerplate copyright header
  internal/plugintest/plugintestenv.go
  pkg/commands/edit/set/setnamespace.go
  pkg/commands/edit/set/setnamespace_test.go
  pkg/inventory/constants.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/loader/loadrestrictions_string.go
  pkg/plugins/compiler.go
  pkg/plugins/compiler_test.go
  pkg/plugins/execplugin_test.go
  pkg/resid/itemid.go
  pkg/resid/resid_test.go
  pkg/resmap/legacygeneratorargs.go
  pkg/target/chartinflatorexecplugin_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/generatorplugin_test.go
  pkg/target/plugindir_test.go
  pkg/target/transformerplugin_test.go
  pkg/transformers/refvars.go
  pkg/transformers/refvars_test.go
  pkg/types/errors.go
  pkg/types/genargs.go
  pkg/types/genargs_test.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ConfigMapGenerator_test.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/SecretGenerator_test.go
  plugin/someteam.example.com/v1/DatePrefixer.go
  plugin/someteam.example.com/v1/ServiceGenerator.go
  plugin/someteam.example.com/v1/StringPrefixer.go
  plugin/someteam.example.com/v1/kvMaker.go
Labels: approved, cncf-cla: yes, size/L

#1066 Add SedTransformerTest
  bin/pre-commit.sh
  internal/plugintest/plugintestenv.go
  k8sdeps/kv/plugin/registry.go
  pkg/kusttest/kusttestharness.go
  pkg/pgmconfig/config.go
  pkg/plugins/compiler.go
  pkg/plugins/config.go
  pkg/plugins/loader.go
  pkg/target/baseandoverlaysmall_test.go
  plugin/builtin/ConfigMapGenerator_test.go
  plugin/builtin/SecretGenerator_test.go
  plugin/someteam.example.com/v1/ChartInflatorExec
  plugin/someteam.example.com/v1/SedTransformer_test.go
Labels: approved

#1067 Convert example plugins to accept bytes instead of unstruct.
  pkg/plugins/execplugin.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader.go
  pkg/resmap/factory_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/generatorplugin_test.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ConfigMapGenerator_test.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/SecretGenerator_test.go
  plugin/someteam.example.com/v1/DatePrefixer.go
  plugin/someteam.example.com/v1/ServiceGenerator.go
  plugin/someteam.example.com/v1/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/L

#1063 allow set image without tag
  pkg/commands/edit/set/setimage.go
  pkg/commands/edit/set/setimage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1068 Fix typo
  pkg/resmap/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1057 add remove resource subcommand
  pkg/commands/edit/all.go
  pkg/commands/edit/remove/all.go
  pkg/commands/edit/remove/removeresource.go
  pkg/commands/edit/remove/removeresource_test.go
Labels: cncf-cla: yes, size/L

#997 add document to explain inventory field
  docs/inventory_object.md
  docs/v_2.1.0.md
Labels: approved, cncf-cla: yes, size/L

#1071 Standalone ChartInflator plugin test.
  bin/pre-commit.sh
  docs/plugins.md
  examples/chart.md
  pkg/target/chartinflatorplugin_test.go
  plugin/someteam.example.com/v1/ChartInflator
  plugin/someteam.example.com/v1/ChartInflator_test.go
Labels: approved, cncf-cla: yes, size/L

#1072 Standalone service generator test
  pkg/plugins/loader_test.go
  pkg/target/generatorplugin_test.go
  plugin/someteam.example.com/v1/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/SomeServiceGenerator_test.go
Labels: cncf-cla: yes

#1070 Delete some code.
  pkg/inventory/inventory_test.go
  pkg/resmap/legacygeneratorargs.go
  pkg/transformers/image.go
Labels: approved, cncf-cla: yes, size/M

#1073 add test for empty patch file
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1074 Update order of resources to include psps
  pkg/gvk/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1077 Upgrade version of minecraft used in tests.
  pkg/target/chartinflatorplugin_test.go
  plugin/someteam.example.com/v1/ChartInflator_test.go
Labels: cncf-cla: yes

#1079 Add builtin NameTransformer plugin.
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/NameTransformer.go
  plugin/builtin/NameTransformer_test.go
  plugin/builtingen/NameTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1084 Simplifications to the plugin test code.
  pkg/kusttest/kusttestharness.go
  pkg/plugins/compiler.go
  pkg/plugins/loader_test.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/plugindir_test.go
  pkg/target/transformerplugin_test.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ConfigMapGenerator_test.go
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/ImageTagTransformer_test.go
  plugin/builtin/NameTransformer_test.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/SecretGenerator_test.go
  plugin/builtingen/ConfigMapGenerator.go
  plugin/builtingen/ImageTagTransformer.go
  plugin/builtingen/NameTransformer.go
  plugin/builtingen/SecretGenerator.go
  plugin/plugintestenv.go
  plugin/someteam.example.com/v1/ChartInflator_test.go
  plugin/someteam.example.com/v1/SedTransformer_test.go
  plugin/someteam.example.com/v1/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/SomeServiceGenerator_test.go
  plugin/someteam.example.com/v1/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/L

#1086 Add builtin label transformer plugin.
  bin/pre-commit.sh
  examples/chart.md
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/LabelTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
Labels: approved, cncf-cla: yes, size/L

#1087 Add builtin annotation transformer.
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1088 Add builtin JSON patch transformer
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1037 Apply LimitRange resources before workloads
  pkg/gvk/gvk.go
Labels: cncf-cla: yes, lgtm, size/XS

#1089 Fix some nits.
  .travis.yml
  docs/inventory_object.md
  k8sdeps/transformer/inventory/inventory.go
  pkg/inventory/constants.go
  pkg/inventory/inventory.go
Labels: approved, cncf-cla: yes, size/M

#1091 Allow nil label and annotaion
  pkg/transformers/labelsandannotations.go
  pkg/transformers/labelsandannotations_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1095 Format generated code.
  plugin/builtin/AnnotationsTransformer.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/LabelTransformer.go
  plugin/builtin/NameTransformer.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/SecretGenerator.go
  plugin/generateBuiltins.sh
Labels: approved, cncf-cla: yes

#1090 replace ambiguous parameters regarding prune
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/inventory/inventory.go
  k8sdeps/transformer/inventory/inventory_test.go
  pkg/ifc/transformer/factory.go
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1096 Cleanup kusttarget.
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
Labels: approved, cncf-cla: yes

#1097 Add builtin namespace transformer plugin
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  pkg/transformers/namespace.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1099 Add name reference of storageClass
  pkg/transformers/config/defaultconfig/namereference.go
Labels: cncf-cla: yes, lgtm, size/XS

#1101 Break a bad dep.
  pkg/patch/json6902.go
  pkg/patch/strategicmerge.go
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/factory_test.go
  pkg/resource/factory.go
  pkg/resource/factory_test.go
  pkg/target/kusttarget_configplugin.go
  pkg/types/kustomization.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
Labels: approved, cncf-cla: yes, size/L

#1102 bye bye baseFactory
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/factory.go
  k8sdeps/configmapandsecret/factory_test.go
Labels: approved, cncf-cla: yes, size/M

#1103 Test all the plugins.
  pkg/resmap/factory.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/someteam.example.com/v1/configmapgenerator/ConfigMapGenerator_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer_test.go
  plugin/someteam.example.com/v1/kvmaker/kvMaker.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase_test.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1105 Rewrite plugin docs.
  docs/plugins.md
  examples/README.md
  examples/kvSourceGoPlugin.md
  examples/secretGeneratorPlugin.md
  plugin/doc.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
Labels: approved, cncf-cla: yes, size/XXL

#1093 translate example list
  examples/README.md
  examples/zh/README-CN.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1104 Order ValidatingWebhookConfig last.
  pkg/gvk/gvk.go
  pkg/gvk/gvk_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1115 reorganize the examples layout
  examples/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1109 Add support for escaping characters in Doc
  examples/transformerconfigs/README.md
Labels: cncf-cla: yes, lgtm, size/S

#1118 Delete the KV plugin code.
  docs/plugins.md
  examples/chart.md
  examples/secretGeneratorPlugin.md
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/factory.go
  k8sdeps/configmapandsecret/factory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kunstruct/factory.go
  k8sdeps/kv/plugin/builtin/envfiles.go
  k8sdeps/kv/plugin/builtin/files.go
  k8sdeps/kv/plugin/builtin/literals.go
  k8sdeps/kv/plugin/builtinplugin.go
  k8sdeps/kv/plugin/goplugin.go
  k8sdeps/kv/plugin/plugin.go
  k8sdeps/kv/plugin/registry.go
  pkg/commands/build/build.go
  pkg/commands/commands.go
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/add/configmap_test.go
  pkg/commands/edit/add/secret.go
  pkg/commands/edit/add/secret_test.go
  pkg/kusttest/kusttestharness.go
  pkg/plugins/compiler.go
  pkg/plugins/config.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader.go
  pkg/plugins/loader_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/builtinplugins_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/plugindir_test.go
  pkg/target/transformerplugin_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, size/XXL

#1121 Move 400loc from k8sdeps to loader
  examples/zh/README-CN.md
  internal/loadertest/fakeloader.go
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/factory.go
  k8sdeps/configmapandsecret/factory_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kv/kv.go
  k8sdeps/kv/kv_test.go
  k8sdeps/kv/util.go
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/inventory/inventory.go
  k8sdeps/transformer/inventory/inventory_test.go
  k8sdeps/validator/validators.go
  pkg/commands/build/build.go
  pkg/commands/commands.go
  pkg/commands/edit/add/all.go
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/add/configmap_test.go
  pkg/commands/edit/add/secret.go
  pkg/commands/edit/add/secret_test.go
  pkg/commands/edit/all.go
  pkg/ifc/ifc.go
  pkg/ifc/transformer/factory.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/kv.go
  pkg/loader/kv_test.go
  pkg/loader/loader.go
  pkg/plugins/config.go
  pkg/plugins/loader.go
  pkg/resmap/factory_test.go
  pkg/target/kusttarget.go
  pkg/target/plugindir_test.go
  pkg/transformers/config/factory_test.go
  pkg/types/kustomization.go
  pkg/validators/validators.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
Labels: approved, cncf-cla: yes, size/XXL

#1123 Add Webhookconfiguration in default name references
  pkg/transformers/config/defaultconfig/namereference.go
Labels: cncf-cla: yes, lgtm, size/XS

#1128 Add script to run cloud build 'locally'.
  build/cloudbuild.sh
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/localbuild.sh
Labels: approved, cncf-cla: yes, size/L

#1129 Idiom fixes.
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/hash/kusthash.go
  k8sdeps/transformer/hash/kusthash_test.go
  k8sdeps/transformer/hash/namehash.go
  k8sdeps/transformer/hash/transformer.go
  k8sdeps/transformer/hash/transformer_test.go
  k8sdeps/transformer/inventory/transformer.go
  k8sdeps/transformer/inventory/transformer_test.go
  k8sdeps/transformer/patch/conflictdetector.go
  k8sdeps/transformer/patch/transformer.go
  k8sdeps/transformer/patch/transformer_test.go
Labels: approved, cncf-cla: yes, size/L

#1120 Fix commonLabels spec for volumeClaimTemplates
  pkg/transformers/config/defaultconfig/commonlabels.go
Labels: cncf-cla: yes, lgtm, size/XS

#1130 Fix yaml in generator examples.
  pkg/target/configmaps_test.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/namespacedgenerators_test.go
  pkg/target/variableref_test.go
Labels: approved, cncf-cla: yes, size/M

#1131 Update minecraft version in example.
  pkg/target/chartinflatorplugin_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, size/S

#1133 Move basic hashing code out of k8sdeps.
  k8sdeps/transformer/hash/kusthash.go
  k8sdeps/transformer/hash/kusthash_test.go
  k8sdeps/transformer/inventory/transformer.go
  pkg/hasher/hasher.go
  pkg/hasher/hasher_test.go
Labels: approved, cncf-cla: yes, size/L

#1134 Rename ./bin dir to ./travis.
  .travis.yml
  travis/consider-early-travis-exit.sh
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/XS

#1117 chinese helloworld doc
  examples/README.md
  examples/zh/README-CN.md
  examples/zh/README.md
  examples/zh/helloWorld.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1136 Use go modules in cloud builder.
  build/README.md
  build/cloudbuild.sh
  build/cloudbuild.yaml
  build/goreleaser.yaml
  build/localbuild.sh
Labels: approved, cncf-cla: yes, size/M

#1137 Move hashing transformer out of k8sdeps.
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/hasher.go
  k8sdeps/kunstruct/hasher_test.go
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/hash/transformer.go
  k8sdeps/transformer/hash/transformer_test.go
  pkg/ifc/ifc.go
  pkg/ifc/transformer/factory.go
  pkg/resource/factory.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/HashTransformer.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1112 add validation transformer
  pkg/kusttest/kusttestharness.go
  pkg/plugins/execplugin.go
  plugin/someteam.example.com/v1/validator/Validator
  plugin/someteam.example.com/v1/validator/validator_test.go
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1141 Update 2.1 release notes.
  README.md
  docs/glossary.md
  docs/images/abandonedTrainingWheels.png
  docs/images/base.jpg
  docs/images/goModules.png
  docs/images/overlay.jpg
  docs/images/plugins.png
  docs/images/pruning.png
  docs/images/workflowBespoke.jpg
  docs/images/workflowOts.jpg
  docs/inventory_object.md
  docs/v_2.1.0.md
  docs/workflows.md
  docs/zh/workflows.md
  examples/README.md
  examples/zh/README.md
  pkg/hasher/hasher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1116 add example for transformer plugin
  examples/validationTransformer/README.md
  examples/validationTransformer/invalid.yaml
  examples/validationTransformer/valid.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1143 update validation transformer example text
  examples/validationTransformer/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#797 Translated kustomization.yaml into markdown in fields.md.
  docs/README.md
  docs/fields.md
  docs/glossary.md
  docs/kustomization.yaml
  examples/validationTransformer/README.md
Labels: cncf-cla: yes, lgtm, size/XL

#1139 Implement replica transformer as patch alternative
  docs/fields.md
  pkg/target/kusttarget_configplugin.go
  pkg/types/kustomization.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1144 Add entry for inventory in fields.md
  docs/fields.md
Labels: approved
