Repository kubernetes-sigs/kustomize, pull requests merged in 2019-09, with the labels that each got.

#1489 tooling performance improvements, better structure
  internal/tools/crawler/crawler.go
  internal/tools/crawler/crawler_test.go
  internal/tools/crawler/github/crawler.go
  internal/tools/crawler/github/queries.go
  internal/tools/crawler/github/split_search_ranges.go
  internal/tools/doc/doc.go
  internal/tools/doc/doc_test.go
  internal/tools/doc/docname.go
  internal/tools/doc/docname_test.go
  internal/tools/doc/kustomize_util.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/httpclient/httpclient.go
Labels: cncf-cla: yes, size/XXL

#1488 Add example plugin for go-getter
  docs/plugins/README.md
  examples/README.md
  examples/goGetterGeneratorPlugin.md
  plugin/someteam.example.com/v1/gogetter/GoGetter
  plugin/someteam.example.com/v1/gogetter/GoGetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1495 use `kubectl apply -k` #
  examples/helloWorld/README.md
Labels: cncf-cla: no, size/XS

#1507 Add an example of reusable builtin plugins with custom config.
  pkg/target/customconfigofbuiltinplugin_test.go
Labels: approved, cncf-cla: yes, size/L

#1484 update zh doc
  examples/zh/README.md
  examples/zh/image.md
  examples/zh/jsonpatch.md
  examples/zh/patchMultipleObjects.md
  examples/zh/remoteBuild.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1515 plugin/go-getter: support urls including `:`
  plugin/someteam.example.com/v1/gogetter/GoGetter
  plugin/someteam.example.com/v1/gogetter/GoGetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1505 add inline patch document
  examples/inlinePatch.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1520 Consider also currentId when replacing/merging resources
  pkg/resmap/resmap.go
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1522 Add test for name conflict with base reuse
  pkg/target/basereusenameprefix_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1526 Do not prefix/suffix APIService resources
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1532 Ease configuring and running the builtin plugins.
  cmd/pluginator/main.go
  cmd/pluginator/plugintype_string.go
  pkg/accumulator/resaccumulator.go
  pkg/plugins/builtinplugintype_string.go
  pkg/plugins/builtins.go
  pkg/plugins/config.go
  pkg/plugins/loader.go
  pkg/resmap/resmap.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  pkg/target/transformerplugin_test.go
  pkg/transformers/doc.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/multitransformer.go
  pkg/transformers/namereference.go
  pkg/transformers/nooptransformer.go
  pkg/transformers/transformer.go
  plugin/builtin/AnnotationsTransformer.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/HashTransformer.go
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/LabelTransformer.go
  plugin/builtin/LegacyOrderTransformer.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/PatchTransformer.go
  plugin/builtin/PrefixSuffixTransformer.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/SecretGenerator.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1534 Example of configuring builtin plugin.
  docs/fields.md
  docs/plugins/builtins.md
  examples/configureBuiltinPlugin.md
  pkg/image/image.go
  pkg/types/configmapargs.go
  pkg/types/generatorargs.go
  pkg/types/generatoroptions.go
  pkg/types/kustomization.go
  pkg/types/objectmeta.go
  pkg/types/patchstrategicmerge.go
  pkg/types/patchtarget.go
  pkg/types/replica.go
  pkg/types/secretargs.go
  pkg/types/selector.go
  plugin/builtin/PrefixSuffixTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1542 Tweak file path handling and logging in test.
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  pkg/fs/fakefs.go
Labels: cncf-cla: yes

#1541 Fix typo in transformerconfigs README
  examples/transformerconfigs/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#1537 add note about GO111MODULE for source install
  docs/INSTALL.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1547 Update Ingress apiVersion to networking.k8s.io/v1beta1
  examples/jsonpatch.md
  examples/zh/jsonpatch.md
  pkg/target/variableref_test.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1550 Fix typo yaml declaration of APIVersion field of Kustomization type
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1506 add release note for v3.2.0
  docs/v3.2.0.md
Labels: approved, cncf-cla: yes, size/S

#1557 Copy pluginator to its own module.
  pluginator/go.mod
  pluginator/go.sum
  pluginator/main.go
  pluginator/plugintype_string.go
Labels: cncf-cla: yes

#1559 Compress copyright in the commands package.
  pkg/commands/build/build_test.go
  pkg/commands/edit/add/addbase.go
  pkg/commands/edit/add/addbase_test.go
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/edit/add/addmetadata_test.go
  pkg/commands/edit/add/addpatch.go
  pkg/commands/edit/add/addpatch_test.go
  pkg/commands/edit/add/addresource.go
  pkg/commands/edit/add/addresource_test.go
  pkg/commands/edit/add/flagsandargs.go
  pkg/commands/edit/add/flagsandargs_test.go
  pkg/commands/edit/fix/fix.go
  pkg/commands/edit/fix/fix_test.go
  pkg/commands/edit/remove/all.go
  pkg/commands/edit/remove/removemetadata.go
  pkg/commands/edit/remove/removemetadata_test.go
  pkg/commands/edit/remove/removeresource.go
  pkg/commands/edit/remove/removeresource_test.go
  pkg/commands/edit/set/all.go
  pkg/commands/edit/set/set_name_prefix.go
  pkg/commands/edit/set/set_name_prefix_test.go
  pkg/commands/edit/set/set_name_suffix.go
  pkg/commands/edit/set/set_name_suffix_test.go
  pkg/commands/edit/set/setimage.go
  pkg/commands/edit/set/setimage_test.go
  pkg/commands/edit/set/setnamespace.go
  pkg/commands/edit/set/setnamespace_test.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/commands/misc/config.go
  pkg/commands/misc/config_test.go
  pkg/commands/misc/version.go
Labels: approved, cncf-cla: yes, size/XL

#1558 Depend on new pluginator location.
  .travis.yml
  cmd/pluginator/main.go
  cmd/pluginator/plugintype_string.go
  go.mod
  go.sum
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/tools.go
Labels: approved, cncf-cla: yes, size/L

#1560 Make pre-commit more portable and less tricky.
  .travis.yml
  go.mod
  go.sum
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1554 Update README.md to include Kubernetes 1.16
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1562 Pin tool versions using go modules
  go.mod
  go.sum
  tools/tools.go
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1565 Pin the kustomize binary's dependence on kustomize libs.
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/L

#1566 v3.2.1 release notes
  docs/README.md
  docs/v3.2.1.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1473 Support resource generator options in exec plugins
  docs/authoriing.md
  docs/plugins/README.md
  pkg/plugins/execplugin.go
  pkg/plugins/execplugin_test.go
  pkg/resource/resource.go
  pkg/target/kusttarget.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1571 Update cloud build process for kustomize.
  go.mod
  go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/config/config.go
  kustomize/internal/commands/config/config_test.go
  kustomize/internal/commands/misc/version.go
  kustomize/internal/commands/version/version.go
  kustomize/provenance/provenance.go
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
  releasing/goreleaser.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1570 Fix compile kustomize example.
  docs/plugins/goPluginCaveats.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
