Repository kubernetes-sigs/kustomize, pull requests merged in 2019-03, with the labels that each got.

#835 Run kustomize tests on OSx
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#844 Add configmaps test for json string
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#837 Fix for #831 - Ignore domain when finding the image tag
  pkg/transformers/image.go
  pkg/transformers/image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#832 improve error message in json patch transformer
  pkg/patch/transformer/factory.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#833 improve error message for loading files listed under crds
  pkg/transformers/config/factorycrd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#842 Fix for #818 - Added support for quoted values
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/edit/add/addmetadata_test.go
Labels: cncf-cla: yes, lgtm, size/L

#857 Reduce time required for cloning remote bases
  pkg/git/cloner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#864 Fix typo in namereference path for cronjobs initContainers.
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#866 Fix error message
  pkg/commands/edit/fix/fix.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#870 Add Job initContainer to varreference config
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#872 fix help msg for set image cmd
  pkg/commands/edit/set/setimage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#867 Fix field names
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#874 Fix function comments based on best practices from Effective Go
  pkg/resource/resource.go
  pkg/types/genargs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#877 fix typo in namereference where serviceaccount name would not resolve
  pkg/transformers/config/defaultconfig/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#879 Secret/configmap factory cleanup.
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kunstruct/factory.go
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/add/secret.go
  pkg/ifc/ifc.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, size/L

#760 add secret and configmap generator plugins
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kunstruct/factory.go
  k8sdeps/kv/plugin/goplugin.go
  k8sdeps/kv/plugin/plugin.go
  k8sdeps/kv/plugin/registry.go
  k8sdeps/kv/plugin/testonly.go
  pkg/target/configmaps_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#885 Convert image transformer test to a more readable format
  pkg/target/transformersimage_test.go
  pkg/transformers/image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#884 Fix incorrect and missing varReferences
  pkg/transformers/config/defaultconfig/varreference.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#882 honor XDG_CONFIG_HOME
  k8sdeps/kv/plugin/goplugin.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#861 correct spelling, minor word ordering
  examples/transformerconfigs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#887 Put goplugins behind flag.
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/factory.go
  k8sdeps/kunstruct/factory.go
  k8sdeps/kv/plugin/goplugin.go
  k8sdeps/kv/plugin/registry.go
  kustomize.go
  pkg/commands/build/build.go
  pkg/commands/build/build_test.go
  pkg/commands/commands.go
  pkg/commands/edit/add/addmetadata.go
  pkg/commands/kustfile/kustomizationfile.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/factory/factory.go
  pkg/fs/fakefs.go
  pkg/loader/fileloader_test.go
  pkg/pgmconfig/config.go
  pkg/pgmconfig/config_test.go
  pkg/pgmconfig/constants.go
  pkg/target/generatoroptions_test.go
  pkg/target/kusttarget.go
  pkg/target/kusttestharness_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, size/L

#883 add builtin plugin for literals
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/kv/plugin/builtin/literals.go
  k8sdeps/kv/plugin/builtinplugin.go
  k8sdeps/kv/plugin/registry.go
  k8sdeps/kv/util.go
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#888 add builtin files plugin
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/kv/plugin/builtin/files.go
  k8sdeps/kv/plugin/builtinplugin.go
  pkg/target/builtinplugins_test.go
  pkg/target/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#892 Make builtin the default pluginType
  k8sdeps/kv/plugin/registry.go
  pkg/target/builtinplugins_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, size/M

#891 add builtin envfiles plugin
  k8sdeps/configmapandsecret/basefactory_test.go
  k8sdeps/kv/plugin/builtin/envfiles.go
  k8sdeps/kv/plugin/builtinplugin.go
  pkg/target/builtinplugins_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#895 skip adding namespace when the object is empty
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#889 update edit add secrets/configmaps to use plugins
  pkg/commands/edit/add/configmap.go
  pkg/commands/edit/add/configmap_test.go
  pkg/commands/edit/add/secret.go
  pkg/commands/edit/add/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#919 Move accumulator code to its own package.
  pkg/accumulator/resaccumulator.go
  pkg/accumulator/resaccumulator_test.go
  pkg/commands/edit/add/configmap_test.go
  pkg/commands/edit/add/secret_test.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, size/M

#920 fix a bool check
  pkg/transformers/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#933 Update travis file.
  .travis.yml
Labels: approved, cncf-cla: yes, size/S

#925 Add goplugin KV generator example.
  examples/README.md
  examples/kvSourceGoPlugin.md
  k8sdeps/configmapandsecret/basefactory.go
  k8sdeps/kv/plugin/builtin/envfiles.go
  k8sdeps/kv/plugin/builtin/files.go
  k8sdeps/kv/plugin/builtin/literals.go
  k8sdeps/kv/plugin/builtinplugin.go
  k8sdeps/kv/plugin/goplugin.go
  k8sdeps/kv/plugin/plugin.go
  pkg/commands/commands.go
  pkg/pgmconfig/config.go
Labels: approved, cncf-cla: yes, size/L

#934 Improve plugin doc.
  examples/kvSourceGoPlugin.md
Labels: approved, cncf-cla: yes, size/M

#931 fix configmap/secret name references for cronjobs with projected volumes
  pkg/transformers/config/defaultconfig/namereference.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#935 fix the regression of building remote url
  examples/remoteBuild.md
  pkg/git/cloner.go
Labels: approved, cncf-cla: yes, size/XS

#911 Support non-array container(s) in image transformer
  pkg/target/crd_test.go
  pkg/target/transformersimage_test.go
  pkg/transformers/image.go
Labels: cncf-cla: yes, size/L

#936 add note for availability in kubectl
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
