Repository kubernetes-sigs/kustomize, pull requests merged in 2019-10, with the labels that each got.

#1575 Update versioning notes.
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes, size/L

#1561 improve test code coverage in transformers
  pkg/transformers/refvars_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1513 empty list or map item return error
  k8sdeps/kunstruct/factory.go
  k8sdeps/kunstruct/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1579 Improve fs package and doc in prep to officially go public
  internal/loadertest/fakeloader.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  pkg/fs/confirmeddir.go
  pkg/fs/confirmeddir_test.go
  pkg/fs/fakefile.go
  pkg/fs/fakefileinfo.go
  pkg/fs/fileinfo.go
  pkg/fs/fileinmemory.go
  pkg/fs/fileondisk.go
  pkg/fs/fs.go
  pkg/fs/fsinmemory.go
  pkg/fs/fsinmemory_test.go
  pkg/fs/fsondisk.go
  pkg/fs/fsondisk_test.go
  pkg/fs/realfile.go
  pkg/fs/rpath.go
  pkg/loader/fileloader_test.go
  pkg/loader/kv_test.go
  pkg/loader/loadrestrictions_test.go
  pkg/resmap/factory_test.go
  pkg/target/plugindir_test.go
Labels: approved, cncf-cla: yes, size/XL

#1578 Fix: documentation link for plugins
  pkg/plugins/config.go
Labels: cncf-cla: yes, lgtm, size/XS

#1581 Break the dep between fs and pgmconfig.
  internal/tools/crawler/github/split_search_ranges.go
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/build_test.go
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/config/config_test.go
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/create/create_test.go
  kustomize/internal/commands/edit/add/addbase_test.go
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/add/addmetadata_test.go
  kustomize/internal/commands/edit/add/addpatch_test.go
  kustomize/internal/commands/edit/add/addresource_test.go
  kustomize/internal/commands/edit/add/configmap_test.go
  kustomize/internal/commands/edit/add/flagsandargs_test.go
  kustomize/internal/commands/edit/add/secret_test.go
  kustomize/internal/commands/edit/fix/fix_test.go
  kustomize/internal/commands/edit/remove/removemetadata.go
  kustomize/internal/commands/edit/remove/removemetadata_test.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removepatch_test.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/edit/remove/removeresource_test.go
  kustomize/internal/commands/edit/set/set_name_prefix_test.go
  kustomize/internal/commands/edit/set/set_name_suffix_test.go
  kustomize/internal/commands/edit/set/setimage_test.go
  kustomize/internal/commands/edit/set/setnamespace_test.go
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
  kustomize/internal/commands/testutils/testutils.go
  pkg/fs/fsinmemory.go
  pkg/kusttest/kusttestharness.go
  pkg/loader/fileloader_test.go
  pkg/pgmconfig/config.go
  pkg/pgmconfig/constants.go
  pkg/resmap/factory_test.go
  pkg/target/kusttarget.go
  pkg/transformers/multitransformer.go
  pkg/transformers/namereference.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
Labels: approved, cncf-cla: yes, size/XXL

#1544 add transformer href
  docs/glossary.md
Labels: cncf-cla: yes, lgtm, size/XS

#1587 Reduce size of pgmconfig package
  internal/loadertest/fakeloader.go
  internal/tools/README.md
  internal/tools/httpclient/httpclient.go
  kustomize/go.mod
  pkg/pgmconfig/config.go
  pkg/pgmconfig/config_test.go
  pkg/pgmconfig/pgmconfig.go
  pkg/plugins/compiler.go
  pkg/plugins/config.go
  pkg/plugins/config_test.go
  pkg/plugins/loader.go
  pkg/plugins/loader_test.go
  pkg/plugins/testenv/envfortest.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/customconfigofbuiltinplugin_test.go
  pkg/target/diamondcomposition_test.go
  pkg/target/diamonds_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/plugindir_test.go
  pkg/target/transformerplugin_test.go
  plugin/builtin/LegacyOrderTransformer.go
  plugin/builtin/PatchJson6902Transformer.go
  plugin/builtin/PatchStrategicMergeTransformer.go
  plugin/builtin/PatchTransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator_test.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer_test.go
  plugin/someteam.example.com/v1/gogetter/GoGetter_test.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator_test.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer_test.go
  plugin/someteam.example.com/v1/validator/validator_test.go
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/XL

#1589 improve tests for alternative kustomization file names
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/build_test.go
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/remove/removemetadata.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
  kustomize/internal/commands/testutils/testutils.go
  pkg/kusttest/kusttestharness.go
  pkg/loader/fileloader_test.go
  pkg/pgmconfig/pgmconfig.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/kusttarget.go
Labels: approved, cncf-cla: yes, size/L

#1590 update release process doc
  releasing/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1595 Differentiate the cloud builders.
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
  releasing/goreleaser.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/L

#1596 Move pluginator to kustomize Go API v3.3.0
  pluginator/go.mod
  pluginator/go.sum
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/S

#1597 v3.3.0 release notes
  docs/README.md
  docs/v3.3.0.md
Labels: cncf-cla: yes

#1519 zh example:chart,secret generator plugin
  examples/zh/README.md
  examples/zh/chart.md
  examples/zh/secretGeneratorPlugin.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1616 cleanup on errors in git loader
  pkg/loader/fileloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1618 doc: add configmap generator key example
  examples/configGeneration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1615 More composition testing
  pkg/target/complexcomposition_test.go
Labels: approved, cncf-cla: yes, size/L

#1576 Upgrade golang to v1.13
  .travis.yml
  docs/plugins/execPluginGuidedExample.md
  docs/plugins/goPluginGuidedExample.md
  go.mod
  internal/crawl/go.mod
  kustomize/go.mod
  pluginator/go.mod
Labels: cncf-cla: yes, size/S

#1622 Fix some nits
  internal/crawl/ROADMAP.md
  internal/crawl/crawler/crawler.go
  internal/crawl/crawler/crawler_test.go
  internal/crawl/crawler/github/crawler.go
  internal/crawl/crawler/github/queries.go
  internal/crawl/crawler/github/split_search_ranges.go
  internal/crawl/index/elasticsearch.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/complexcomposition_test.go
  pkg/target/variableref_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, size/L

#1621 Update broken URL in Exec Plugin Tutorial
  docs/plugins/execPluginGuidedExample.md
Labels: cncf-cla: yes, lgtm, size/XS

#1623 Remove minecraft version check from chart plugin tests.
  pkg/kusttest/kusttestharness.go
  pkg/target/chartinflatorplugin_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, size/M

#1635 fix string trim in normalizeGitHostSpec func
  pkg/git/repospec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1637 Rename DataSources to KvPairSources and remove deprecated env field.
  go.sum
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  kustomize/go.sum
  pkg/resmap/factory_test.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/types/generatorargs.go
  pkg/types/kustomization.go
  pkg/types/kvpairsources.go
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#1634 make failing test showing spurious variable conflicts
  pkg/accumulator/resaccumulator_test.go
Labels: cncf-cla: yes, size/M

#1640 Extract kv loader from file loader, and place in public package.
  internal/loadertest/fakeloader.go
  k8sdeps/configmapandsecret/configmapfactory.go
  k8sdeps/configmapandsecret/configmapfactory_test.go
  k8sdeps/configmapandsecret/factory.go
  k8sdeps/configmapandsecret/secretfactory.go
  k8sdeps/configmapandsecret/secretfactory_test.go
  k8sdeps/kunstruct/factory.go
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/edit/add/all.go
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/configmap_test.go
  kustomize/internal/commands/edit/add/secret.go
  kustomize/internal/commands/edit/add/secret_test.go
  kustomize/internal/commands/edit/all.go
  kustomize/internal/commands/edit/remove/all.go
  kv/kv.go
  kv/kv_test.go
  pkg/ifc/ifc.go
  pkg/kusttest/kusttestharness.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
  pkg/plugins/execplugin_test.go
  pkg/plugins/loader.go
  pkg/plugins/loader_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap.go
  pkg/resource/factory.go
  pkg/target/kusttarget.go
  pkg/target/kusttarget_test.go
  pkg/target/plugindir_test.go
  pkg/types/kustomization.go
  pkg/types/kvpairsources.go
  pkg/types/pair.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
Labels: approved, cncf-cla: yes, size/L

#1639 Fix yaml formatting of replicas count when count is 0
  pkg/types/replica.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1638 Add support for kustomize edit set replicas
  kustomize/internal/commands/edit/set/all.go
  kustomize/internal/commands/edit/set/setimage_test.go
  kustomize/internal/commands/edit/set/setreplicas.go
  kustomize/internal/commands/edit/set/setreplicas_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1642 Maker hasher public for now.
  hacks/awker.sh
  hasher/hasher.go
  hasher/hasher_test.go
  k8sdeps/kunstruct/hasher.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
Labels: approved, cncf-cla: yes, size/S

#1643 Cleanup types package before going public.
  internal/crawl/README.md
  internal/crawl/ROADMAP.md
  k8sdeps/kunstruct/unstructadapter.go
  k8sdeps/kunstruct/unstructadapter_test.go
  pkg/types/errors.go
  pkg/types/fix.go
  pkg/types/garbagepolicy.go
  pkg/types/genargs.go
  pkg/types/genargs_test.go
  pkg/types/generationbehavior.go
  pkg/types/generatorargs.go
  pkg/types/inventory.go
  pkg/types/kustomization.go
  pkg/types/patch.go
  pkg/types/patchjson6902.go
  pkg/types/pluginconfig.go
  pkg/types/typemeta.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: approved, cncf-cla: yes, size/L

#1645 Document the types package.
  types/doc.go
  types/fix.go
  types/kustomization.go
Labels: approved, cncf-cla: yes, size/S

#1649 fixNits
  hacks/awker.sh
  types/doc.go
Labels: cncf-cla: yes

#1653 Update docs
  docs/INSTALL.md
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1654 Make SMP code private to CLI.
  kustomize/internal/commands/edit/add/addpatch.go
  kustomize/internal/commands/edit/patch/strategicmerge.go
  kustomize/internal/commands/edit/patch/strategicmerge_test.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removepatch_test.go
Labels: approved, cncf-cla: yes, size/XS

#1657 Make git package private
  api/internal/git/cloner.go
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  api/loader/loader.go
  pkg/accumulator/expansion/expand.go
  pkg/accumulator/expansion/expand_test.go
  pkg/accumulator/refvartransformer.go
  pkg/git/cloner_test.go
Labels: approved, cncf-cla: yes, size/M

#1658 Make inventory public.
  api/inventory/constants.go
  api/inventory/inventory.go
  api/inventory/inventory_test.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
Labels: approved, cncf-cla: yes, size/S

#1661 Move ks8deps to api for now.
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/k8sdeps/configmapandsecret/configmapfactory.go
  api/k8sdeps/configmapandsecret/configmapfactory_test.go
  api/k8sdeps/configmapandsecret/factory.go
  api/k8sdeps/configmapandsecret/secretfactory.go
  api/k8sdeps/configmapandsecret/secretfactory_test.go
  api/k8sdeps/doc.go
  api/k8sdeps/kunstruct/factory.go
  api/k8sdeps/kunstruct/factory_test.go
  api/k8sdeps/kunstruct/hasher.go
  api/k8sdeps/kunstruct/hasher_test.go
  api/k8sdeps/kunstruct/helper.go
  api/k8sdeps/kunstruct/helper_test.go
  api/k8sdeps/kunstruct/unstructadapter.go
  api/k8sdeps/kunstruct/unstructadapter_test.go
  api/k8sdeps/transformer/factory.go
  api/k8sdeps/transformer/patch/conflictdetector.go
  api/k8sdeps/validator/validators.go
  api/plugins/execplugin/execplugin_test.go
  api/plugins/loader/loader.go
  api/plugins/loader/loader_test.go
  api/resmap/resmap_test.go
  api/resource/resource_test.go
  api/target/plugindir_test.go
  api/testutils/kusttest/kusttestharness.go
  api/transform/maptransformer_test.go
  api/transform/mutatefield_test.go
  hacks/crawl/doc/doc.go
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/create/create_test.go
Labels: approved, cncf-cla: yes, size/M

#1662 Make new nesting place for generated builtin code.
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/accumulator/loadconfigfromcrds_test.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/resaccumulator.go
  api/internal/accumulator/resaccumulator_test.go
  api/plugins/builtinconfig/consts/commonannotations.go
  api/plugins/builtinconfig/consts/commonlabels.go
  api/plugins/builtinconfig/consts/defaultconfig.go
  api/plugins/builtinconfig/consts/doc.go
  api/plugins/builtinconfig/consts/images.go
  api/plugins/builtinconfig/consts/nameprefix.go
  api/plugins/builtinconfig/consts/namereference.go
  api/plugins/builtinconfig/consts/namespace.go
  api/plugins/builtinconfig/consts/replicas.go
  api/plugins/builtinconfig/consts/varreference.go
  api/plugins/builtinconfig/doc.go
  api/plugins/builtinconfig/loaddefaultconfig.go
  api/plugins/builtinconfig/loaddefaultconfig_test.go
  api/plugins/builtinconfig/namebackreferences.go
  api/plugins/builtinconfig/namebackreferences_test.go
  api/plugins/builtinconfig/transformerconfig.go
  api/plugins/builtinconfig/transformerconfig_test.go
  api/plugins/builtinhelpers/builtinplugintype_string.go
  api/plugins/builtinhelpers/builtins.go
  api/plugins/builtins/builtinplugintype_string.go
  api/plugins/builtins/doc.go
  api/plugins/config/config.go
  api/plugins/loader/loader.go
  api/target/kusttarget.go
  api/target/kusttarget_configplugin.go
  api/testutils/kusttest/kusttestharness.go
  api/transform/maptransformer_test.go
  docs/plugins/builtins.md
  examples/configureBuiltinPlugin.md
  kustomize/internal/commands/config/config.go
Labels: approved, cncf-cla: yes, size/L

#1664 Move generated code
  api/plugins/builtinconfig/doc.go
  api/plugins/builtinhelpers/builtins.go
  api/plugins/builtinhelpers/generateBuiltins.sh
  api/plugins/builtins/AnnotationsTransformer.go
  api/plugins/builtins/ConfigMapGenerator.go
  api/plugins/builtins/HashTransformer.go
  api/plugins/builtins/ImageTagTransformer.go
  api/plugins/builtins/InventoryTransformer.go
  api/plugins/builtins/LabelTransformer.go
  api/plugins/builtins/LegacyOrderTransformer.go
  api/plugins/builtins/NamespaceTransformer.go
  api/plugins/builtins/PatchJson6902Transformer.go
  api/plugins/builtins/PatchStrategicMergeTransformer.go
  api/plugins/builtins/PatchTransformer.go
  api/plugins/builtins/PrefixSuffixTransformer.go
  api/plugins/builtins/ReplicaCountTransformer.go
  api/plugins/builtins/SecretGenerator.go
  api/plugins/builtins/doc.go
  api/plugins/builtins/tools.go
  api/plugins/doc.go
  api/target/kusttarget.go
  go.mod
  go.sum
  hacks/crawl/go.mod
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/build/build.go
  pkg/pgmconfig/pgmconfig.go
  pkg/plugins/config.go
  plugin/README.md
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
  plugin/tools.go
  pluginator/go.mod
  pluginator/main.go
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes, size/L

#1667 Define the API release process.
  .travis.yml
  api/main.go
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/M

#1668 Experimenting with cloud build and goreleaser
  api/cloudbuild.sh
  api/cloudbuild.yaml
  kustomize/cloudbuild.sh
  kustomize/cloudbuild.yaml
  pluginator/cloudbuild.sh
  pluginator/cloudbuild.yaml
  releasing/README.md
  releasing/localbuild.sh
Labels: cncf-cla: yes

#1669 Cloud build adjustments.
  kustomize/cloudbuild.sh
  pluginator/cloudbuild.sh
  releasing/cloudbuild.sh
  releasing/cloudbuild_api.yaml
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
  releasing/localbuild.sh
Labels: cncf-cla: yes

#1670 Add kubeval install notes.
  travis/pre-commit.sh
Labels: approved, cncf-cla: yes

#1672 Pin the cloudbuild step container tags.
  releasing/cloudbuild.sh
  releasing/cloudbuild_api.yaml
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/M

#1673 Add tag check to release script
  releasing/README.md
  releasing/cloudbuild.sh
Labels: cncf-cla: yes

#1674 Deal with goreleaser field deprecations.
  releasing/cloudbuild.sh
  releasing/cloudbuild_api.yaml
Labels: cncf-cla: yes

#1675 Pin kustomize CLI to API v0.1.1
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#1676 Use latest cloudbuilder image.
  pluginator/go.mod
  pluginator/go.sum
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
Labels: cncf-cla: yes

#1678 Fix internal kustomize CLI deps
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/create/create_test.go
  kustomize/internal/commands/edit/add/addbase.go
  kustomize/internal/commands/edit/add/addbase_test.go
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/add/addmetadata_test.go
  kustomize/internal/commands/edit/add/addpatch.go
  kustomize/internal/commands/edit/add/addpatch_test.go
  kustomize/internal/commands/edit/add/addresource.go
  kustomize/internal/commands/edit/add/addresource_test.go
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/configmap_test.go
  kustomize/internal/commands/edit/add/flagsandargs.go
  kustomize/internal/commands/edit/add/secret.go
  kustomize/internal/commands/edit/add/secret_test.go
  kustomize/internal/commands/edit/all.go
  kustomize/internal/commands/edit/fix/fix.go
  kustomize/internal/commands/edit/fix/fix_test.go
  kustomize/internal/commands/edit/remove/removemetadata.go
  kustomize/internal/commands/edit/remove/removemetadata_test.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removepatch_test.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/edit/remove/removeresource_test.go
  kustomize/internal/commands/edit/set/set_name_prefix.go
  kustomize/internal/commands/edit/set/set_name_prefix_test.go
  kustomize/internal/commands/edit/set/set_name_suffix.go
  kustomize/internal/commands/edit/set/set_name_suffix_test.go
  kustomize/internal/commands/edit/set/setimage.go
  kustomize/internal/commands/edit/set/setimage_test.go
  kustomize/internal/commands/edit/set/setnamespace.go
  kustomize/internal/commands/edit/set/setnamespace_test.go
  kustomize/internal/commands/edit/set/setreplicas.go
  kustomize/internal/commands/edit/set/setreplicas_test.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
  kustomize/main.go
  releasing/cloudbuild.sh
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/L

#1679 Improve the release process instructions
  releasing/README.md
  releasing/cloudbuild.sh
Labels: cncf-cla: yes

#1688 Move kustomize back to v3
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/create/create_test.go
  kustomize/internal/commands/edit/add/addbase.go
  kustomize/internal/commands/edit/add/addbase_test.go
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/add/addmetadata_test.go
  kustomize/internal/commands/edit/add/addpatch.go
  kustomize/internal/commands/edit/add/addpatch_test.go
  kustomize/internal/commands/edit/add/addresource.go
  kustomize/internal/commands/edit/add/addresource_test.go
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/flagsandargs.go
  kustomize/internal/commands/edit/add/secret.go
  kustomize/internal/commands/edit/all.go
  kustomize/internal/commands/edit/fix/fix.go
  kustomize/internal/commands/edit/fix/fix_test.go
  kustomize/internal/commands/edit/remove/removemetadata.go
  kustomize/internal/commands/edit/remove/removemetadata_test.go
  kustomize/internal/commands/edit/remove/removepatch.go
  kustomize/internal/commands/edit/remove/removepatch_test.go
  kustomize/internal/commands/edit/remove/removeresource.go
  kustomize/internal/commands/edit/remove/removeresource_test.go
  kustomize/internal/commands/edit/set/set_name_prefix.go
  kustomize/internal/commands/edit/set/set_name_prefix_test.go
  kustomize/internal/commands/edit/set/set_name_suffix.go
  kustomize/internal/commands/edit/set/set_name_suffix_test.go
  kustomize/internal/commands/edit/set/setimage.go
  kustomize/internal/commands/edit/set/setimage_test.go
  kustomize/internal/commands/edit/set/setnamespace.go
  kustomize/internal/commands/edit/set/setnamespace_test.go
  kustomize/internal/commands/edit/set/setreplicas.go
  kustomize/internal/commands/edit/set/setreplicas_test.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
  kustomize/main.go
  releasing/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1663 Refactor exec plugin load to error if plugin isn't executable
  api/plugins/execplugin/execplugin.go
  api/plugins/execplugin/execplugin_test.go
  api/plugins/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1690 Tune up hack/crawl.
  hacks/crawl/backend/search_backend.go
  hacks/crawl/cmd/backend/main.go
  hacks/crawl/crawler/crawler.go
  hacks/crawl/crawler/crawler_test.go
  hacks/crawl/crawler/github/crawler.go
  hacks/crawl/go.mod
  hacks/crawl/go.sum
  hacks/crawl/index/kustomize.go
Labels: cncf-cla: yes

#1671 delete duplicated entry in slice
  api/resid/gvk.go
Labels: cncf-cla: yes, lgtm, size/XS

#1693 Fix some nits.
  docs/plugins/builtins.md
  hacks/crawl/crawler/crawler_test.go
  hacks/crawl/crawler/github/split_search_ranges_test.go
Labels: approved, cncf-cla: yes

#1681 Add support to render charts using '.Release.Name' and .Release.Namespace'
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
Labels: cncf-cla: yes, lgtm, size/S

#1699 Make krusty package - high-level CLI-like package.
  api/krusty/doc.go
  api/krusty/kustomizer.go
  api/krusty/kustomizer_test.go
  api/krusty/options.go
  hack/awker.sh
Labels: approved, cncf-cla: yes, size/L

#1701 Point kustomize to local API for development.
  hack/awker.sh
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#1703 Update travis.yaml for osx
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#1702 Reduce the size of the API used by the build command
  api/krusty/kustomizer.go
  api/krusty/loadrestrictions.go
  api/krusty/loadrestrictions_string.go
  api/krusty/options.go
  api/loader/loadrestrictions.go
  api/loader/loadrestrictions_test.go
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/commands.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1704 Script to report on api usage.
  hack/awker.sh
  hack/whatApi.sh
Labels: cncf-cla: yes

#1709 Support for ignoring specific Resources via annotation.
  api/k8sdeps/kunstruct/factory.go
  api/k8sdeps/kunstruct/factory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1712 Add Mac development guide
  CONTRIBUTING.md
  docs/macDevGuide.md
Labels: approved, cncf-cla: yes, size/M

#1714 Add some kustomization tests.
  Makefile
  api/target/accumulation_test.go
  api/target/kusttarget.go
  api/testutils/kusttest/kusttestharness.go
Labels: approved, cncf-cla: yes, lgtm, size/L
