Repository kubernetes-sigs/kustomize, pull requests merged in 2019-06, with the labels that each got.

#1145 Convert inventory transformer to plugin, reduce k8sdeps.
  go.mod
  go.sum
  k8sdeps/transformer/factory.go
  k8sdeps/transformer/inventory/transformer.go
  k8sdeps/transformer/inventory/transformer_test.go
  pkg/accumulator/resaccumulator.go
  pkg/ifc/transformer/factory.go
  pkg/target/kusttarget.go
  pkg/types/garbagepolicy_string.go
  pkg/types/kustomization.go
  plugin/builtin/HashTransformer.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
Labels: approved, cncf-cla: yes, size/XL

#1148 update examples/README.md
  examples/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1152 fix the bug for patching CRDs
  k8sdeps/transformer/patch/transformer.go
  pkg/target/crd_test.go
  pkg/target/customconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1153 enable go module in the integration test
  examples/integration_tests.sh
Labels: approved, cncf-cla: yes, size/XS

#1154 Maintain resources in a list.
  k8sdeps/transformer/patch/transformer.go
  k8sdeps/transformer/patch/transformer_test.go
  pkg/accumulator/resaccumulator.go
  pkg/accumulator/resaccumulator_test.go
  pkg/commands/build/build.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/plugins/execplugin.go
  pkg/plugins/loader.go
  pkg/resid/itemid.go
  pkg/resid/resid.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/kusttarget_test.go
  pkg/target/variableref_test.go
  pkg/transformers/image.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/multitransformer.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixsuffixname.go
  pkg/transformers/prefixsuffixname_test.go
  pkg/transformers/refvars.go
  pkg/transformers/refvars_test.go
  plugin/builtin/HashTransformer.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1158 Preserve order when merging.
  pkg/accumulator/resaccumulator.go
  pkg/accumulator/resaccumulator_test.go
  pkg/commands/build/build.go
  pkg/kusttest/kusttestharness.go
  pkg/plugins/execplugin.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/target/kusttarget.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
Labels: approved, cncf-cla: yes, size/XL

#1159 Rename ErrorIfNotEqual to ErrorIfNotEqualSets
  k8sdeps/transformer/patch/transformer_test.go
  pkg/patch/transformer/factory_test.go
  pkg/patch/transformer/patchjson6902json_test.go
  pkg/resmap/factory.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/target/kusttarget_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/multitransformer.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
  pkg/transformers/prefixsuffixname_test.go
  pkg/transformers/refvars_test.go
Labels: approved, cncf-cla: yes, size/M

#1160 Update inventory_object.md
  docs/inventory_object.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1161 Add copy method to VarSet
  pkg/accumulator/resaccumulator.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1162 Add Merge (one Var) method to VarSet
  pkg/target/kusttarget_test.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: approved, cncf-cla: yes, size/S

#1163 Add a sorting plugin, as an example.
  pkg/commands/build/build.go
  pkg/kusttest/kusttestharness.go
  pkg/plugins/execplugin.go
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  plugin/builtin/PreferredOrderTransformer.go
  plugin/builtin/preferredordertransformer/PreferredOrderTransformer.go
  plugin/builtin/preferredordertransformer/PreferredOrderTransformer_test.go
  plugin/someteam.example.com/v1/printworkdir/PrintWorkDir_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1166 Cover #1155 with a test.
  pkg/target/generatormergeandreplace_test.go
Labels: approved, cncf-cla: yes, size/S

#1165 Add test for ordered transformers.
  pkg/plugins/loader.go
  pkg/target/transformerplugin_test.go
  plugin/builtin/PreferredOrderTransformer.go
  plugin/builtin/preferredordertransformer/PreferredOrderTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1169 Improve performance in name transform code.
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/transformers/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1171 Add --reorder flag.
  go.mod
  go.sum
  pkg/commands/build/build.go
  pkg/commands/build/reorderoutput.go
  pkg/commands/build/reorderoutput_string.go
  pkg/kusttest/kusttestharness.go
  pkg/loader/loadrestrictions.go
  pkg/plugins/config.go
  pkg/target/baseandoverlaysmall_test.go
  plugin/builtin/LegacyOrderTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1172 Rename the prefix/suffix transformer.
  pkg/transformers/prefixsuffix.go
  pkg/transformers/prefixsuffix_test.go
  plugin/builtin/NameTransformer.go
  plugin/builtin/nametransformer/NameTransformer.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/M

#1173 Push suffix/prefix code to plugin.
  docs/plugins.md
  pkg/resid/resid.go
  pkg/target/kusttarget_configplugin.go
  pkg/transformers/image.go
  pkg/transformers/labelsandannotations.go
  pkg/transformers/mutatefield.go
  pkg/transformers/mutatefield_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namespace.go
  pkg/transformers/prefixsuffix.go
  pkg/transformers/prefixsuffix_test.go
  pkg/transformers/refvars.go
  plugin/builtin/NameTransformer.go
  plugin/builtin/PrefixSuffixTransformer.go
  plugin/builtin/nametransformer/NameTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/XL

#1149 Keep var refernce in resources
  pkg/accumulator/resaccumulator.go
  pkg/accumulator/resaccumulator_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/target/kusttarget.go
  pkg/target/variableref_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1174 Add originalName field to resource.
  pkg/accumulator/resaccumulator_test.go
  pkg/patch/transformer/factory.go
  pkg/resid/resid.go
  pkg/resmap/factory_test.go
  pkg/resource/factory.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/transformers/labelsandannotations_test.go
  pkg/transformers/namereference.go
  pkg/transformers/namereference_test.go
  pkg/transformers/namespace_test.go
Labels: approved, cncf-cla: yes, size/XL

#1178 Update golinter to 1.17.1
  .travis.yml
  k8sdeps/kunstruct/hasher_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator.go
Labels: approved, cncf-cla: yes, size/S

#1175 Add some utilities.
  pkg/resmap/resmap.go
  pkg/resmap/resmap_test.go
  pkg/resource/resource.go
  pkg/target/kusttarget_test.go
  pkg/transformers/namereference.go
Labels: approved, cncf-cla: yes, size/L

#1180 Move the rmBuilder test helper to a test package.
  pkg/accumulator/resaccumulator_test.go
  pkg/resmap/factory_test.go
  pkg/resmap/resmap_test.go
  pkg/resmaptest/rmbuilder.go
  pkg/resource/factory.go
  pkg/resource/resource.go
  pkg/target/kusttarget_test.go
  pkg/target/resourceconflict_test.go
  pkg/transformers/namereference_test.go
Labels: approved, cncf-cla: yes, size/XL

#1181 Make the replica transformer `kind` aware.
  docs/fields.md
  pkg/target/kusttarget_configplugin.go
  pkg/transformers/config/defaultconfig/defaultconfig.go
  pkg/transformers/config/defaultconfig/replicas.go
  pkg/transformers/config/transformerconfig.go
  pkg/types/kustomization.go
  plugin/builtin/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1185 Expected raw kustomize ordering in tests.
  docs/images/sorted.png
  docs/v_2.1.0.md
  pkg/kusttest/kusttestharness.go
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/baseandoverlaysmall_test.go
  pkg/target/chartinflatorplugin_test.go
  pkg/target/configmaps_test.go
  pkg/target/crd_test.go
  pkg/target/customconfig_test.go
  pkg/target/generatormergeandreplace_test.go
  pkg/target/generatoroptions_test.go
  pkg/target/kusttarget_test.go
  pkg/target/multiplepatch_test.go
  pkg/target/pruneconfigmap_test.go
  pkg/target/resourceconflict_test.go
  pkg/target/variableref_test.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, do-not-merge/invalid-commit-message, lgtm, size/XXL

#610 Proposal: Make transformer configs array-aware
  pkg/target/transformersarrays_test.go
  pkg/transformers/config/defaultconfig/commonlabels.go
  pkg/transformers/mutatefield.go
Labels: cncf-cla: yes, size/L

#852 Windows Tests - Precommit Script
  bin/Invoke-PreCommit.ps1
  docs/howtowindows.md
Labels: cncf-cla: yes, size/L

#1186 Put windows test script next to pre-commit.sh
  docs/howtowindows.md
  travis/Invoke-PreCommit.ps1
Labels: cncf-cla: yes

#1188 Fix test broken by the change in ordering.
  pkg/target/transformersarrays_test.go
Labels: approved, cncf-cla: yes, size/M

#1191 Tell homebrew to update.
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#1187 Added test to verify usage of multiline strip chomp in configMapGener…
  pkg/target/configmaps_test.go
Labels: cncf-cla: yes, size/XS

#1192 Move pluginator main.go from plugin to cmd directory.
  cmd/pluginator/main.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/doc.go
  plugin/generateBuiltins.sh
Labels: approved, cncf-cla: yes, size/M

#1189 Deprecate 'bases:' field.
  docs/fields.md
  docs/zh/kustomization.yaml
  examples/breakfast.md
  examples/combineConfigs.md
  examples/configGeneration.md
  examples/helloWorld/README.md
  examples/ldap/overlays/production/kustomization.yaml
  examples/ldap/overlays/staging/kustomization.yaml
  examples/multibases/README.md
  examples/multibases/dev/kustomization.yaml
  examples/multibases/kustomization.yaml
  examples/multibases/multi-namespace.md
  examples/multibases/production/kustomization.yaml
  examples/multibases/staging/kustomization.yaml
  examples/remoteBuild.md
  examples/springboot/overlays/production/kustomization.yaml
  examples/springboot/overlays/staging/kustomization.yaml
  examples/wordpress/README.md
  examples/wordpress/kustomization.yaml
  examples/zh/helloWorld.md
  pkg/commands/edit/add/addbase.go
  pkg/commands/kustfile/kustomizationfile_test.go
  pkg/target/kusttarget.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1193 More release note tweaks.
  docs/v_2.1.0.md
Labels: cncf-cla: yes

#1111 Improvment var and varRefs handling
  k8sdeps/kunstruct/helper.go
  k8sdeps/kunstruct/helper_test.go
  k8sdeps/kunstruct/kunstruct.go
  k8sdeps/kunstruct/kunstruct_test.go
  pkg/accumulator/resaccumulator.go
  pkg/accumulator/resaccumulator_test.go
  pkg/expansion/expand.go
  pkg/expansion/expand_test.go
  pkg/ifc/ifc.go
  pkg/resource/resource.go
  pkg/transformers/mutatefield_test.go
  pkg/transformers/refvars.go
  pkg/transformers/refvars_test.go
  pkg/types/kustomization.go
Labels: cncf-cla: yes, size/XXL

#1194 Move kustomize main to cmd directory.
  .gitignore
  build/goreleaser.yaml
  cmd/kustomize/main.go
  docs/INSTALL.md
  examples/README.md
  kustomize.go
Labels: approved, cncf-cla: yes, size/M

#1195 Update release note links.
  README.md
  docs/README.md
  docs/v1.0.1.md
  docs/v2.0.0.md
  docs/v2.1.0.md
  docs/v2.1.0_changelog.md
  docs/zh/README.md
Labels: approved, cncf-cla: yes

#1196 Improve robutness of helper code
  k8sdeps/kunstruct/helper.go
  k8sdeps/kunstruct/helper_test.go
  k8sdeps/kunstruct/kunstruct.go
Labels: cncf-cla: yes, size/M

#1198 update docs/zh/README.md
  docs/zh/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#1197 Demonstrate new capabilities in pkg/target testing
  pkg/target/variableref_test.go
  pkg/transformers/config/defaultconfig/varreference.go
Labels: cncf-cla: yes, lgtm, size/S

#1205 Fix typo in comment
  pkg/commands/edit/set/setimage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1201 Fix typo in docs
  docs/inventory_object.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1199 Corrected spelling mistake
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1202 Typo correction in 2.1.0 release notes
  docs/v2.1.0.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1206 Addresses issue discovered in attempting to patch K8s objects across different namespaces.
  k8sdeps/transformer/patch/transformer.go
  k8sdeps/transformer/patch/transformer_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1211 Push namespace transformer code to plugin.
  pkg/resmap/resmap.go
  pkg/transformers/namespace.go
  pkg/transformers/namespace_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, size/L

#1210 Push image tag transform code to plugin.
  pkg/transformers/image.go
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
Labels: approved, cncf-cla: yes, size/XL

#1213 Commit generated code for image and namespace transformers.
  plugin/builtin/ImageTagTransformer.go
  plugin/builtin/NamespaceTransformer.go
Labels: approved, cncf-cla: yes

#1214 A secret generator using sops.
  go.mod
  go.sum
  plugin/someteam.example.com/v1/sopsencodedsecrets/SopsEncodedSecrets.go
  plugin/someteam.example.com/v1/sopsencodedsecrets/SopsEncodedSecrets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1222 Another plugin demo.
  docs/execPluginIn30sec.md
  docs/plugins.md
Labels: approved, cncf-cla: yes, size/L

#1220 FieldPath syntax backward compatibility
  k8sdeps/kunstruct/helper.go
  k8sdeps/kunstruct/helper_test.go
  k8sdeps/kunstruct/kunstruct_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1225 Fixed unit test failures when GOROOT was unset
  pkg/plugins/compiler.go
Labels: cncf-cla: yes, lgtm, size/XS

#1232 More var test coverage.
  pkg/target/variableref_test.go
Labels: approved, cncf-cla: yes, size/L

#1227 Fix typo
  docs/v1.0.1.md
Labels: cncf-cla: yes, lgtm, size/XS

#1237 Add metadata remover
  k8sdeps/validator/validators.go
  pkg/commands/edit/all.go
  pkg/commands/edit/remove/all.go
  pkg/commands/edit/remove/removemetadata.go
  pkg/commands/edit/remove/removemetadata_test.go
  pkg/ifc/ifc.go
  pkg/validators/validators.go
Labels: cncf-cla: yes, lgtm, size/XL

#1231 Iterate over fieldspecs for name tranformations (fixes #1228)
  plugin/builtin/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1224 Change the backing data structure of VarSet from slice to map
  pkg/accumulator/resaccumulator.go
  pkg/types/var.go
  pkg/types/var_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1238 Remove SopsEncodedSecretsPlugin
  go.mod
  go.sum
  pkg/target/transformerplugin_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/sopsencodedsecrets/SopsEncodedSecrets.go
  plugin/someteam.example.com/v1/sopsencodedsecrets/SopsEncodedSecrets_test.go
Labels: approved, cncf-cla: yes, size/XL

#1241 Hack for local testing of isolated plugins.
  pkg/kusttest/kusttestharness.go
  pkg/plugins/compiler.go
Labels: approved, cncf-cla: yes

#1246 Add another detailed plugin example.
  docs/README.md
  docs/execPluginIn30sec.md
  docs/fields.md
  docs/glossary.md
  docs/plugins/README.md
  docs/plugins/execPluginGuidedExample.md
  docs/plugins/goPluginGuidedExample.md
  docs/v2.1.0.md
  docs/v3.0.0.md
  docs/zh/README.md
  examples/chart.md
  examples/secretGeneratorPlugin.md
  examples/validationTransformer/README.md
Labels: approved, cncf-cla: yes, size/XL

#1247 Update versioning policy.
  docs/v3.0.0.md
  docs/versioningPolicy.md
Labels: approved, cncf-cla: yes

#1204 Chinese translation:jsonpatch.md
  examples/zh/README.md
  examples/zh/jsonpatch.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1239 allow reuse of plugins
  pkg/plugins/loader.go
  pkg/target/transformerplugin_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1242 Add patch remover
  pkg/commands/edit/add/addpatch.go
  pkg/commands/edit/add/addresource.go
  pkg/commands/edit/add/flagsandargs.go
  pkg/commands/edit/add/util.go
  pkg/commands/edit/remove/all.go
  pkg/commands/edit/remove/removepatch.go
  pkg/commands/edit/remove/removepatch_test.go
  pkg/commands/edit/remove/removeresource.go
  pkg/commands/edit/util/functions.go
  pkg/patch/strategicmerge.go
  pkg/patch/strategicmerge_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1221 ConfigMap Generators with identical name in different namespaces
  pkg/commands/build/build.go
  pkg/gvk/gvk.go
  pkg/resid/resid.go
  pkg/resmap/resmap.go
  pkg/target/generatormergeandreplace_test.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: cncf-cla: yes, lgtm, size/L

#1255 Fix some random Go nits.
  k8sdeps/kunstruct/helper.go
  k8sdeps/kunstruct/helper_test.go
  pkg/plugins/loader.go
  pkg/target/transformerplugin_test.go
  pkg/target/transformersarrays_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/M

#1200 Chinese configGeneration.md dosc
  examples/zh/README.md
  examples/zh/configGeneration.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1254 Fix some minor nits around namespace code.
  pkg/commands/build/build.go
  pkg/gvk/gvk.go
  pkg/resid/resid.go
  pkg/resid/resid_test.go
  pkg/resmap/resmap.go
Labels: approved, cncf-cla: yes, size/L

#1244 add type for extended patches
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#1259 Update notes for releasing.
  build/README.md
  docs/INSTALL.md
  docs/plugins/execPluginGuidedExample.md
  docs/plugins/goPluginGuidedExample.md
  docs/versioningPolicy.md
  releasing/README.md
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
  releasing/goreleaser.yaml
  releasing/localbuild.sh
  releasing/vendor_kustomize.diff
  releasing/vendor_kustomize.sh
Labels: approved, cncf-cla: yes, size/L

#1263 More plugin docs.
  docs/plugins/README.md
  docs/plugins/goPluginCaveats.md
  plugin/doc.go
Labels: cncf-cla: yes

#1274 Plainer plugin security discussion.
  docs/plugins/README.md
  docs/plugins/goPluginCaveats.md
Labels: cncf-cla: yes

#1271 Add suport for _git in git url
  pkg/git/repospec.go
  pkg/git/repospec_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1277 Delete deprecated GetById
  pkg/resmap/resmap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1278 Add diamond base test, improve patching error messages.
  k8sdeps/transformer/patch/transformer.go
  k8sdeps/transformer/patch/transformer_test.go
  pkg/target/diamonds_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1279 Fix JSON patch targetting issue.
  k8sdeps/transformer/patch/transformer.go
  pkg/patch/transformer/patchjson6902json.go
  pkg/resmap/resmap.go
  pkg/target/baseandoverlaysmall_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1282 Repo bug 1044
  pkg/target/namespaces_test.go
Labels: approved, cncf-cla: yes, size/M

#1284 Add ObjectMeta type.
  pkg/types/kustomization.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: approved, cncf-cla: yes, size/M

#1275 add function to find all matched patch targets
  k8sdeps/kunstruct/kunstruct.go
  pkg/ifc/ifc.go
  pkg/resmap/resmap.go
  pkg/resmap/selector_test.go
  pkg/types/kustomization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1280 use ObjectMeta
  pkg/target/kusttarget.go
  pkg/target/kusttarget_configplugin.go
  plugin/builtin/ConfigMapGenerator.go
  plugin/builtin/InventoryTransformer.go
  plugin/builtin/NamespaceTransformer.go
  plugin/builtin/SecretGenerator.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator_test.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase_test.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1283 Add diamond composition test with multiple patches
  pkg/target/diamondcomposition_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1285 Switch Deployment apiVersion to apps/v1 in a couple of tests.
  pkg/target/baseandoverlaymedium_test.go
  pkg/target/diamondcomposition_test.go
Labels: approved, cncf-cla: yes, size/M

#1287 Define some constants in a test for later reuse.
  pkg/target/diamondcomposition_test.go
Labels: approved, cncf-cla: yes

#1286 Stacked patching example
  pkg/target/diamondcomposition_test.go
Labels: approved, cncf-cla: yes, size/M
