Repository kubernetes-sigs/kustomize, pull requests merged in 2020-02, with the labels that each got.

#2165 kyaml: Handle functions in top-level directory.
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2172 Several improvements on crawler
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/cmd/kustomize_stats/main.go
  api/internal/crawl/config/crawler/cronjob/cronjob.yaml
  api/internal/crawl/config/elastic/esbackup.yaml
  api/internal/crawl/config/elastic/escluster.yaml
  api/internal/crawl/config/elastic/esrestore.yaml
  api/internal/crawl/config/elastic/essnaptshot.yaml
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/split_search_ranges.go
  api/internal/crawl/crawler/github/split_search_ranges_test.go
  api/internal/crawl/doc/doc.go
  api/internal/crawl/search_cmds/generator.md
  api/internal/crawl/search_cmds/snapshot.md
  api/internal/crawl/search_cmds/transformer.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2173 kyaml patch increment to 0.0.10
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2174 Fix tshirt-size image resources
  functions/examples/injection-tshirt-sizes/image/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2175 Optionally use filepath as part of merge key for merge3
  cmd/config/internal/commands/merge3.go
  kyaml/kio/filters/merge3.go
  kyaml/kio/filters/merge3_test.go
  kyaml/kio/filters/testdata2/dataset1-expected/java/java-deployment-1.resource.yaml
  kyaml/kio/filters/testdata2/dataset1-expected/java/java-deployment-2.resource.yaml
  kyaml/kio/filters/testdata2/dataset1-localupdates/java/java-deployment-1.resource.yaml
  kyaml/kio/filters/testdata2/dataset1-localupdates/java/java-deployment-2.resource.yaml
  kyaml/kio/filters/testdata2/dataset1-remoteupdates/java/java-deployment-1.resource.yaml
  kyaml/kio/filters/testdata2/dataset1-remoteupdates/java/java-deployment-2.resource.yaml
  kyaml/kio/filters/testdata2/dataset1/java/java-deployment-1.resource.yaml
  kyaml/kio/filters/testdata2/dataset1/java/java-deployment-2.resource.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2176 Opt in to use schema
  cmd/config/internal/commands/fmt.go
  kyaml/kio/filters/fmtr.go
  kyaml/kio/filters/fmtr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2177 kio: don't apply folded style to wrapped items
  kyaml/kio/byteio_writer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2178 Support loading openapi from []bytes
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2181 Make field optional flag for create setter
  cmd/config/internal/commands/cmdcreatesetter.go
  kyaml/setters/addyaml.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2185 cmd/config: support for stdin/stdout in source/sink
  cmd/config/docs/commands/sink.md
  cmd/config/docs/commands/source.md
  cmd/config/internal/commands/sink.go
  cmd/config/internal/commands/sink_test.go
  cmd/config/internal/commands/source.go
  cmd/config/internal/commands/source_test.go
  cmd/config/internal/generateddocs/commands/docs.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2186 Fix typo in kustomization file resources field explanation
  docs/fields.md
Labels: cncf-cla: yes, lgtm, size/XS

#2189 release cmd/config and kyaml
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2183 Add curl commands for kustomize stats
  api/internal/crawl/cmd/kustomize_stats/main.go
  api/internal/crawl/cmd/log-parser/kustomize-stats-cmd
  api/internal/crawl/config/crawler/base/.gitignore
  api/internal/crawl/config/crawler/kustomize_stats/job.yaml
  api/internal/crawl/config/elastic/esbackup.yaml
  api/internal/crawl/config/elastic/esrestore.yaml
  api/internal/crawl/config/elastic/essnaptshot.yaml
  api/internal/crawl/search_cmds/creationTime.md
  api/internal/crawl/search_cmds/defaultBranch.md
  api/internal/crawl/search_cmds/fieldExistence.md
  api/internal/crawl/search_cmds/fileType.md
  api/internal/crawl/search_cmds/generator.md
  api/internal/crawl/search_cmds/id.md
  api/internal/crawl/search_cmds/keyword_search.md
  api/internal/crawl/search_cmds/misc.md
  api/internal/crawl/search_cmds/repositoryUrl.md
  api/internal/crawl/search_cmds/snapshot.md
  api/internal/crawl/search_cmds/stats.md
  api/internal/crawl/search_cmds/text_search.md
  api/internal/crawl/search_cmds/transformer.md
  api/internal/crawl/search_cmds/user.md
Labels: cncf-cla: yes, lgtm, size/XXL

#2192 Support exposing network as a function option
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2195 Add notes on backup and restore
  api/internal/crawl/config/elastic/esbackup.yaml
  api/internal/crawl/config/elastic/escluster.yaml
  api/internal/crawl/config/elastic/esrestore.yaml
  api/internal/crawl/config/elastic/essnapshot.yaml
Labels: cncf-cla: yes, lgtm, size/S

#2197 setters 2.0
  kyaml/fieldmeta/fieldmeta.go
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/setters2/doc.go
  kyaml/setters2/example_test.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/types.go
  kyaml/setters2/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2200 setters 2.0: add references
  kyaml/fieldmeta/fieldmeta.go
  kyaml/setters2/add.go
  kyaml/setters2/add_test.go
  kyaml/setters2/doc.go
  kyaml/setters2/example_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2199 Setter Definitions read and write
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/setters2/setterdefinition.go
  kyaml/setters2/setterdefinition_test.go
  kyaml/setters2/substitutiondefinition.go
  kyaml/setters2/substitutiondefinition_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2203 Setter 2.0 commands
  cmd/config/configcobra/cmds.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/fmt_test.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/setters2/add.go
  kyaml/setters2/add_test.go
  kyaml/setters2/list.go
  kyaml/setters2/list_test.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/setterdefinition.go
  kyaml/setters2/setterdefinition_test.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/substitutiondefinition.go
  kyaml/setters2/substitutiondefinition_test.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/XXL

#2216 release cmd/config and kyaml 0.0.12
  releasing/VERSIONS
Labels: approved, size/XS

#2211 Make GetOpenAPIFile publicly settable
  cmd/config/ext/ext.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2218 Update kyaml to v0.0.13
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2220 Add lint-kustomize to prow-presubmit-check
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2213 Correct explanation of ApendAll method in ResMap interface
  api/resmap/resmap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2224 Disable travis testing now that prow works.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2219 Create setters for substitutions
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/settersutil/substitutioncreator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2228 Setters: clear set-by if unspecified when setting a value
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2232 Setters: support for enums
  cmd/config/internal/commands/cmdset_test.go
  kyaml/setters2/add.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2236 Setters type support
  cmd/config/go.sum
  cmd/config/internal/commands/cmdcreatesetter.go
  kyaml/setters2/add.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2237 add SetLabel function in kyaml library
  kyaml/yaml/filters.go
  kyaml/yaml/kfns.go
  kyaml/yaml/kfns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2238 Release kyaml and cmd/config v0.1.0
  Makefile
  kyaml/yaml/kfns_test.go
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/S
