Repository kubernetes-sigs/kustomize, pull requests merged in 2020-04, with the labels that each got.

#2314 Set all setter definitions from source package
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/fieldsetter_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2318 Refactor and optimize function to set all setters
  kyaml/setters2/set.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/fieldsetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2315 Improve tests for AnnotationsTransformer
  api/builtins/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2316 Add replicacount filter based on kyaml libraries
  api/filters/replicacount/doc.go
  api/filters/replicacount/example_test.go
  api/filters/replicacount/replicacount.go
  api/filters/replicacount/replicacount_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2317 added markdown format flag for create-setters
  cmd/config/internal/commands/cmdlistsetters.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2323 release kyaml 0.1.4
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2312 Support mounting volumes to containers
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  functions/examples/validator-kubeval/local-resource/example-use.yaml
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/functiontypes.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2320 Import environment and openAPI into starlark fn runtime
  kyaml/starlark/context.go
  kyaml/starlark/example_test.go
  kyaml/starlark/starlark.go
  kyaml/starlark/starlark_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2319 Implement json marshal / unmarshal for RNode
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2324 Better support for testing tranformers with kyaml support
  api/testutils/kusttest/harnessenhanced.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#2334 Fix issue with kyaml json unmarshalling
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2326 Export noFieldError
  api/k8sdeps/kunstruct/unstructadapter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2306 Add imagetag filter based on kayml libraries
  api/filters/imagetag/doc.go
  api/filters/imagetag/example_test.go
  api/filters/imagetag/imagetag.go
  api/filters/imagetag/imagetag_test.go
  api/filters/imagetag/legacy.go
  api/filters/imagetag/legacy_test.go
  api/filters/imagetag/updater.go
  api/image/image.go
  api/image/image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2327 Add strategic merge patch filter based on kyaml libraries
  api/builtins/PatchStrategicMergeTransformer.go
  api/filters/patchstrategicmerge/doc.go
  api/filters/patchstrategicmerge/example_test.go
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kyaml/filtersutil/filtersutil.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2330 Remove format filter for merge
  kyaml/kio/filters/merge3.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2331 Improve json6902 patch example.
  examples/jsonpatch.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2229 Add namereference for PriorityClass
  api/konfig/builtinpluginconsts/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2336 Add mortent to the maintainers list
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS

#2337 release kyaml 0.1.5
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2338 Better multi-patch demo.
  examples/jsonpatch.md
  examples/patchMultipleObjects.md
Labels: approved, cncf-cla: yes, size/L

#2342 Remove use of patchjson6902 field.
  examples/jsonpatch.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2341 Fix program path in runfn
  kyaml/kio/filters/functiontypes.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2343 Copy file from source to destination
  kyaml/copyutil/copyutil.go
  kyaml/copyutil/copyutil_test.go
  kyaml/kio/pkgio_reader.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2350 fix copy comments to include document comments
  kyaml/comments/comments.go
  kyaml/comments/comments_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2344 Add json6902 patch filter based on kyaml libraries
  api/builtins/PatchJson6902Transformer.go
  api/filters/patchjson6902/doc.go
  api/filters/patchjson6902/example_test.go
  api/filters/patchjson6902/patchjson6902.go
  api/filters/patchjson6902/patchjson6902_test.go
  api/go.mod
  api/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer_test.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2352 Unpin the plugins (i.e. point them to head).
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#2353 Show prow build instead of deprecated travis
  README.md
Labels: approved, cncf-cla: yes, size/XS

#2357 Define hash suffix behavior in the presence of multiple GeneratorOptions.
  api/builtins/ConfigMapGenerator.go
  api/builtins/InventoryTransformer.go
  api/builtins/SecretGenerator.go
  api/ifc/ifc.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  api/internal/k8sdeps/configmapandsecret/factory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory_test.go
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/target/kusttarget_configplugin.go
  api/k8sdeps/kunstruct/factory.go
  api/krusty/complexcomposition_test.go
  api/resmap/factory.go
  api/resmap/factory_test.go
  api/resmap/resmap_test.go
  api/resource/factory.go
  api/types/genargs.go
  api/types/genargs_test.go
  api/types/generatorargs.go
  api/types/generatoroptions.go
  api/types/generatoroptions_test.go
  kustomize/go.sum
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/secret.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2360 More documentation for field.
  api/types/generatorargs.go
  docs/plugins/builtins.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2361 Update tests for PatchTransformer
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, size/L

#2363 Add more patch transformer coverage.
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2354 Kustomization openapi ConfigMapGenerator and SecretGenerator
  kyaml/Makefile
  kyaml/openapi/kubernetesapi/swagger.go
  kyaml/openapi/kubernetesapi/swagger.json
  kyaml/openapi/kustomizationapi/swagger.go
  kyaml/openapi/kustomizationapi/swagger.json
  kyaml/openapi/openapi.go
  kyaml/openapi/swagger.go
  kyaml/yaml/merge3/kustomization_test.go
  kyaml/yaml/merge3/merge3_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2373 Add coverage to the disable name hash option in generators.
  api/krusty/disablenamesuffix_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2359 Update PatchTransformer to use kyaml filters
  api/builtins/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/patchtransformer/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#2376 Update deps (autogenerated)
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/inventorytransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/S

#2377 PatchTransformer readability mods and another test.
  api/builtins/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2362 Support for serializing ResourceList.results field from functions
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_readwriter_test.go
  kyaml/kio/byteio_writer.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/runfn/runfn.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2382 release cmd/config and kyaml
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2384 Enable functions to defer failures
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/functiontypes.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2385 Plugin flow doc improvements and a new option for the plugin loader
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/internal/plugins/loader/loader.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/kusttarget_test.go
  api/konfig/plugins.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
  api/testutils/kusttest/plugintestenv.go
  api/types/pluginconfig.go
  api/types/pluginrestrictions.go
  hack/buildExternalGoPlugins.sh
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/L

#2387 Add compiler utils test.
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/utils.go
  api/internal/plugins/compiler/utils_test.go
Labels: approved, cncf-cla: yes, size/L

#2383 Issue #2381 - bug fix for unmodified `found` variable
  functions/examples/application-cr/image/main.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#2388 Remove static cling in plugin development flow.
  Makefile
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
  api/testutils/kusttest/plugintestenv.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2372 Print file difference like git diff
  kyaml/copyutil/copyutil.go
  kyaml/copyutil/copyutil_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2394 Start adding helm3 to ChartInflator and its coverage.
  Makefile
  hack/testUnitKustomizePlugins.sh
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2395 Check for prow, not travis, in CI test.
  hack/testUnitKustomizePlugins.sh
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: approved, cncf-cla: yes, size/S

#2391 Allow declaratively running starlark functions
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2403 Remove time guessing.
  api/internal/plugins/compiler/compiler_test.go
  api/internal/plugins/compiler/utils.go
Labels: approved, cncf-cla: yes, size/S

#2401 Fix broken Makefiles.
  cmd/kubectl/Makefile
  functions/examples/application-cr/Makefile
  functions/examples/injection-tshirt-sizes/Makefile
  functions/examples/template-go-nginx/Makefile
  functions/examples/template-heredoc-cockroachdb/Makefile
  functions/examples/validator-kubeval/Makefile
  functions/examples/validator-resource-requests/Makefile
  travis/kyaml-pre-commit.sh
Labels: approved, cncf-cla: yes, size/M

#2402 release kyaml and cmd/config
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2404 Adjust scripts to allow either Go v.13 or Go v1.14
  Makefile
  hack/shellHelpers.sh
  hack/testExamplesAgainstKustomize.sh
  hack/testUnitKustomizePlugins.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2406 Bug hunting; add more tests high and low.
  api/filters/fsslice/fsslice_test.go
  api/filters/labels/labels_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2409 Isolate apiVersion parsing.
  api/filters/fsslice/fieldspec_filter.go
  api/filters/fsslice/fsslice.go
  api/filters/fsslice/fsslice_test.go
  api/filters/fsslice/gvk.go
  api/filters/fsslice/gvk_test.go
Labels: approved, cncf-cla: yes, size/L

#2411 More GVK tests before GV treatment changes.
  api/filters/fsslice/gvk_test.go
Labels: approved, cncf-cla: yes, size/M

#2414 Migrate label transformer
  api/builtins/LabelTransformer.go
  api/filters/fsslice/fsslice_test.go
  api/filters/fsslice/gvk.go
  api/filters/fsslice/gvk_test.go
  api/filters/labels/labels_test.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/labeltransformer/go.mod
Labels: approved, cncf-cla: yes, size/M

#2416 Finalize helm v3 support
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
  plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2417 Disable flaky git diff checks.
  travis/check-go-mod.sh
  travis/kyaml-pre-commit.sh
Labels: approved, cncf-cla: yes, size/S

#2418 Remove MapTransformer.
  api/builtins/AnnotationsTransformer.go
  api/go.sum
  api/transform/maptransformer.go
  api/transform/maptransformer_test.go
  api/transform/nooptransformer.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/someteam.example.com/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2389 Fix formating of example
  cmd/config/docs/api-conventions/functions-spec.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#2420 Fix a panic when doing variable replacement.
  api/internal/accumulator/refvartransformer.go
  api/internal/accumulator/refvartransformer_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2422 add test to demonstrate kubernetes-sigs/kustomize#1835
  api/krusty/mergeenvfrom_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2421 Remove inventory transformer
  Makefile
  api/builtins/InventoryTransformer.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/target/kusttarget.go
  api/inventory/constants.go
  api/inventory/inventory.go
  api/inventory/inventory_test.go
  api/krusty/kustomizer.go
  api/krusty/pruneconfigmap_test.go
  api/types/garbagepolicy.go
  api/types/garbagepolicy_string.go
  docs/howItWorks.md
  docs/inventory_object.md
  kustomize/internal/commands/build/build.go
  plugin/builtin/inventorytransformer/InventoryTransformer.go
  plugin/builtin/inventorytransformer/InventoryTransformer_test.go
  plugin/builtin/inventorytransformer/go.mod
  plugin/builtin/inventorytransformer/go.sum
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2419 Simplify substitutions
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2423 Fix godocs on MergeFilter
  kyaml/kio/filters/merge.go
Labels: approved, cncf-cla: yes, size/XS

#2424 Improve config failure error message.
  api/internal/target/kusttarget.go
  cmd/config/internal/generateddocs/api/docs.go
Labels: approved, cncf-cla: yes, size/XS

#2428 Update link to travis pre-commit hook in docs
  api/internal/plugins/doc.go
  examples/README.md
  examples/zh/README.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2430 kyaml 0.1.8, cmd/config 0.1.7
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS
