Repository kubernetes-sigs/kustomize, pull requests merged in 2020-06, with the labels that each got.

#2555 Release v0.1.13 of kyaml
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2556 release cmd/config
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, size/XS

#2551 Nested substitutions
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdset_test.go
  kyaml/setters2/set.go
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2547 Update set.md examples to use correct field name
  cmd/config/docs/commands/set.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2558 Update StatefulSet ref name in HPA
  api/konfig/builtinpluginconsts/namereference.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2565 Fix windows builds.
  kustomize/go.mod
  kustomize/go.sum
  releasing/cloudbuild.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2552 Write setter definitions to `Krmfile` instead of `kustomization`
  cmd/config/configcobra/cmds.go
  cmd/config/docs/commands/init.md
  cmd/config/ext/ext.go
  cmd/config/internal/commands/cmdinit.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/e2e/create_setter_test.go
  cmd/config/internal/commands/e2e/e2e_test.go
  cmd/config/internal/commands/e2e/init_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  cmd/config/internal/commands/e2e/set_test.go
  cmd/config/internal/commands/e2e/test_util_test.go
  cmd/config/internal/commands/init_test.go
  cmd/config/internal/generateddocs/commands/docs.go
  kyaml/krmfile/doc.go
  kyaml/krmfile/krmfile.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2562 add zh doc exec/go plugin
  docs/zh/execPluginGuidedExample.md
  docs/zh/goPluginCaveats.md
  docs/zh/goPluginGuidedExample.md
  docs/zh/plugins.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2568 Add kustomize v3.6.1 e2e testing to prow tests
  Makefile
Labels: approved, cncf-cla: yes, size/S

#2560 Add test case when image tag is a number
  kustomize/internal/commands/edit/set/setimage_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2554 Fix length checking for ResMap resources
  api/resmap/resmap.go
  api/resmap/resmap_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2570 Treat empty strings as string type instead of null type
  kyaml/yaml/compatibility.go
  kyaml/yaml/compatibility_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2575 Add tests for reading json
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/pkgio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2573 Update go.mod to go 1.14
  api/go.mod
  api/go.sum
  api/internal/crawl/go.mod
  cmd/config/go.mod
  cmd/mdtogo/go.mod
  functions/examples/application-cr/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-resource-requests/image/go.mod
  kstatus/go.mod
  kustomize/go.mod
  kustomize/go.sum
  kyaml/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
  pluginator/go.mod
  releasing/releasing/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2571 Update kustomize to use latest version of cmd/config and cli-utils
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/config/config.go
  kustomize/internal/commands/config/config_test.go
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/L

#2481 support option for adding managed-by label
  Makefile
  api/krusty/kustomizer.go
  api/krusty/managedbylabel_test.go
  api/krusty/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2580 Avoid exposing ElasticSearch DB over public IPs
  api/internal/crawl/config/elastic/service.yaml
Labels: cncf-cla: yes, size/S

#2579 Re-introduce shallow git clones for git based remote resources
  api/internal/git/cloner.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2589 Fixes markdown.
  docs/authoring.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2593 kustomize docs tweaks
  docs/api-reference/kustomization/commonannotations/index.html
  docs/api-reference/kustomization/commonlabels/index.html
  docs/api-reference/kustomization/index.xml
  docs/api-reference/kustomization/patches/index.html
  docs/contributing/docs/index.html
  docs/sitemap.xml
  site/content/en/api-reference/kustomization/commonannotations/_index.md
  site/content/en/api-reference/kustomization/commonlabels/_index.md
  site/content/en/api-reference/kustomization/patches/_index.md
  site/content/en/contributing/docs/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2599 Fix validation logic to use yaml parsing instead of json
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2603 Update GO plugin doc
  site/content/en/guides/plugins/_index.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2605 Avoid manual step for creating array setters
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset_test.go
  kyaml/setters2/add.go
  kyaml/setters2/set.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/walk.go
  kyaml/yaml/compatibility_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2612 Update VERSIONS file with latest versions of kyaml and cmd/config
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2617 Fix validation for array setters
  cmd/config/internal/commands/cmdcreatesetter_test.go
  kyaml/go.mod
  kyaml/setters2/add.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2622 Revamp components example
  examples/components.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2613 Introduce `validators` field in kustomization file
  api/internal/target/kusttarget.go
  api/konfig/general.go
  api/types/kustomization.go
  examples/validatorPlugin.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2624 Sort ifc.go for easier change monitoring during refactor.
  api/ifc/ifc.go
Labels: approved, cncf-cla: yes, size/M

#2626 Delegate to Kunstructured.
  api/builtins/AnnotationsTransformer.go
  api/builtins/LabelTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/builtins/ValueAddTransformer.go
  api/internal/crawl/go.sum
  api/internal/plugins/execplugin/execplugin.go
  api/resource/factory.go
  api/resource/resource.go
  kustomize/go.sum
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/ValueAddTransformer.go
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2630 Drop ghodss/yaml dependency
  cmd/config/docs/api-conventions/functions-spec.md
  kstatus/go.mod
  kstatus/go.sum
  kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2633 fix typo
  site/content/en/installation/binaries/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2546 Include json files for fn source and sink
  cmd/config/internal/commands/e2e/e2e_test.go
  cmd/config/internal/commands/sink_test.go
  cmd/config/internal/commands/source.go
  cmd/config/internal/commands/source_test.go
  kyaml/kio/byteio_writer.go
  kyaml/kio/filters/testyaml/testyaml.go
  kyaml/kio/pkgio_reader.go
  kyaml/runfn/runfn.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2553 Delete setters
  cmd/config/configcobra/cmds.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesetter_test.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/setters2/delete.go
  kyaml/setters2/delete_test.go
  kyaml/setters2/settersutil/deletecreator_test.go
  kyaml/setters2/settersutil/deletercreator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2635 Required setters for apply
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  cmd/config/internal/commands/e2e/set_test.go
  kyaml/setters2/add.go
  kyaml/setters2/delete.go
  kyaml/setters2/list.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/settercreator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2642 Fix failing list setters test
  cmd/config/internal/commands/cmdlistsetters_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2639 Add back reference for secret in knative service
  api/konfig/builtinpluginconsts/namereference.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2638 Avoid reprocess queries whose range size is 0 and improve memory usage
  api/internal/crawl/cmd/crawler/Dockerfile
  api/internal/crawl/cmd/crawler/crawler.go
  api/internal/crawl/crawler/crawler.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/queries.go
  api/internal/crawl/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/L

#2636 add test case showing that kustomize/kpt fmt works on yaml file with top-level lists
  kyaml/kio/filters/fmtr_test.go
  kyaml/kio/filters/testyaml/testyaml.go
Labels: cncf-cla: yes, ok-to-test, size/M

#2648 Add more SMP tests.
  api/krusty/baseandoverlaysmall_test.go
  api/krusty/multiplepatch_test.go
Labels: approved, cncf-cla: yes, size/L

#2653 Convert all deployments to v1 to use openapi schema.
  api/krusty/extendedpatch_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/multiplepatch_test.go
  cmd/config/internal/generateddocs/api/docs.go
Labels: approved, cncf-cla: yes, size/L

#2654 More kyaml list merge tests
  kyaml/yaml/merge2/list_test.go
Labels: approved, cncf-cla: yes, size/M

#2655 Update SMP transformer for kyaml
  api/builtins/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
Labels: approved, cncf-cla: yes, size/M

#2657 Fix copy comments for Folded style scalar nodes
  kyaml/comments/comments.go
  kyaml/comments/comments_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2658 Deployment volume merge tests.
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kyaml/yaml/merge2/list_test.go
Labels: approved, cncf-cla: yes, size/L

#2659 Allow multiple patch strategies.
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/schema/schema.go
  kyaml/yaml/schema/schema_test.go
Labels: approved, cncf-cla: yes, size/M

#2660 Switch to kyaml v0.3.1
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2663 Start supporting strategic merge patch in kyaml/yaml/merge2.
  kyaml/Makefile
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/merge2/map_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/smpdirective.go
  kyaml/yaml/merge2/smpdirective_string.go
  kyaml/yaml/merge2/smpdirective_test.go
Labels: approved, cncf-cla: yes, size/L

#2664 Upgrade kustomize to kyaml v0.3.2
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2597 PoC to use kpt functions as kustomize plugins
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/execplugin/fnplugin.go
  api/internal/plugins/execplugin/utils.go
  api/internal/plugins/execplugin/utils_test.go
  api/internal/plugins/loader/loader.go
  api/krusty/fnplugin_test.go
  api/krusty/fnplugin_test/fnexectest.sh
  api/types/pluginconfig.go
  api/types/pluginrestrictions.go
  kustomize/internal/commands/build/build.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2672 fix k8s api doc
  examples/helloWorld/README.md
  examples/secretGeneratorPlugin.md
  examples/zh/helloWorld.md
  examples/zh/secretGeneratorPlugin.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2671 help doc
  examples/helloWorld/README.md
  examples/zh/helloWorld.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#2669 Fix an index.
  kyaml/filtersutil/filtersutil.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2667 Improvements for KRM function implementation
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/utils.go
  api/internal/plugins/execplugin/utils_test.go
  api/internal/plugins/fnplugin/fnplugin.go
  api/internal/plugins/loader/loader.go
  api/internal/plugins/utils/utils.go
  api/internal/plugins/utils/utils_test.go
  api/krusty/fnplugin_test.go
  api/krusty/fnplugin_test/fnexectest.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2670 Check if required setters are set
  kyaml/setters2/types.go
  kyaml/setters2/util.go
  kyaml/setters2/util_test.go
  kyaml/yaml/merge2/smpdirective_string.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2661 Error message for creating setter that matches no fields
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/e2e/create_setter_test.go
  kyaml/setters2/add.go
  kyaml/setters2/settersutil/settercreator.go
Labels: cncf-cla: yes, ok-to-test, size/M

#2652 Add link to another Go plugin
  site/content/en/guides/plugins/_index.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2674 Remove the kstatus module
  api/go.sum
  kstatus/.golangci.yml
  kstatus/LICENSE_TEMPLATE
  kstatus/Makefile
  kstatus/README.md
  kstatus/doc.go
  kstatus/go.mod
  kstatus/go.sum
  kstatus/status/core.go
  kstatus/status/doc.go
  kstatus/status/example_test.go
  kstatus/status/generic.go
  kstatus/status/status.go
  kstatus/status/status_augment_test.go
  kstatus/status/status_compute_test.go
  kstatus/status/util.go
  kstatus/status/util_test.go
  kstatus/wait/doc.go
  kstatus/wait/util.go
  kstatus/wait/wait.go
  kstatus/wait/wait_test.go
  kstatus/wait/waitstate.go
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/status/all.go
  kustomize/internal/commands/status/cmd/events.go
  kustomize/internal/commands/status/cmd/events_test.go
  kustomize/internal/commands/status/cmd/fetch.go
  kustomize/internal/commands/status/cmd/fetch_test.go
  kustomize/internal/commands/status/cmd/helpers_test.go
  kustomize/internal/commands/status/cmd/print.go
  kustomize/internal/commands/status/cmd/util.go
  kustomize/internal/commands/status/cmd/util_test.go
  kustomize/internal/commands/status/cmd/wait.go
  kustomize/internal/commands/status/cmd/wait_test.go
  kustomize/internal/commands/status/docs/commands/events.md
  kustomize/internal/commands/status/docs/commands/fetch.md
  kustomize/internal/commands/status/docs/commands/wait.md
  kustomize/internal/commands/status/generateddocs/commands/docs.go
  releasing/README.md
  releasing/releasing/main.go
  releasing/releasing/modulemeta_test.go
  releasing/releasing/moduleversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
