Repository kubernetes-sigs/kustomize, pull requests merged in 2020-07, with the labels that each got.

#2675 Switch kustomize to kyaml v0.3.3
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2678 Upgrade to gopkg.in/yaml.v2 v2.3.0
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/configmaps_test.go
  api/krusty/variableref_test.go
  kustomize/go.sum
  kyaml/setters2/add.go
  kyaml/setters2/settersutil/settercreator.go
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/M

#2680 Sync everything to gopkg.in/yaml.v2 v2.3.0 via kyaml v0.3.4
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2682 Prep to release kustomize 3.7.0 on api v0.4.2
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, size/L

#2676 Remove count field, convert error to warning
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/e2e/create_setter_test.go
  kyaml/setters2/settersutil/settercreator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2686 Update build strategy.
  releasing/cloudbuild_api.yaml
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
  releasing/localbuild.sh
Labels: cncf-cla: yes

#2688 Drop grep invert-match shorthand flag
  cmd/config/internal/commands/grep.go
Labels: cncf-cla: yes, lgtm, size/XS

#2691 Hide list-subst behind a flag
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
Labels: approved, cncf-cla: yes, size/M

#2692 New cloud build scripts.
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
  releasing/cloudbuild_api.yaml
  releasing/cloudbuild_kustomize.yaml
  releasing/cloudbuild_pluginator.yaml
  releasing/localbuild.sh
Labels: approved, cncf-cla: yes, size/L

#2668 Switch namespace and patch transformers to kyaml.
  Makefile
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/customconfig_test.go
  api/krusty/extendedpatch_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/inlinepatch_test.go
  api/krusty/multiplepatch_test.go
  kyaml/yaml/merge2/map_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer.go
Labels: approved, cncf-cla: yes, size/L

#2694 Switch to kustomize/api v0.5.0
  Makefile
  examples/patchMultipleObjects.md
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, size/L

#2693 Update function annotation on docs
  cmd/config/docs/api-conventions/functions-impl.md
  cmd/config/docs/api-conventions/functions-spec.md
  cmd/config/internal/generateddocs/api/docs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2698 Prep cmd/config for release
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, size/M

#2699 Return go.mod replace directives
  cmd/config/go.mod
Labels: approved, cncf-cla: yes, size/S

#2700 modify the byteioreader to handler windows line ending.
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2706 Fix go.mod file in cmd/config
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#2711 Don't allow creating setter with same name as substitution
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2707 Allow setters/substitutions with . in the name
  cmd/config/internal/commands/cmdcreatesetter_test.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/kio/byteio_reader_test.go
  kyaml/setters2/add_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2708 Removing YAMLSupport==false code path.
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/testutils/kusttest/harnessenhanced.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/patchtransformer/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2709 Fixed incorrect docker mount arguments generation
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2696 docs: Add guide for components
  site/content/en/guides/components/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2683 KRM Function benchmark
  hack/krmFunctionBenchmark/.gitignore
  hack/krmFunctionBenchmark/benchmark.sh
  hack/krmFunctionBenchmark/cleanup.sh
  hack/krmFunctionBenchmark/example_tshirt/containerfn/data.yaml
  hack/krmFunctionBenchmark/example_tshirt/containerfn/kustomization.yaml
  hack/krmFunctionBenchmark/example_tshirt/containerfn/transf.yaml
  hack/krmFunctionBenchmark/example_tshirt/execfn/Dockerfile
  hack/krmFunctionBenchmark/example_tshirt/execfn/build.sh
  hack/krmFunctionBenchmark/example_tshirt/execfn/data.yaml
  hack/krmFunctionBenchmark/example_tshirt/execfn/kustomization.yaml
  hack/krmFunctionBenchmark/example_tshirt/execfn/transf.yaml
  hack/krmFunctionBenchmark/label_namespace/containerfn/containerfn.yaml
  hack/krmFunctionBenchmark/label_namespace/containerfn/data1.yaml
  hack/krmFunctionBenchmark/label_namespace/containerfn/data2.yaml
  hack/krmFunctionBenchmark/label_namespace/containerfn/kustomization.yaml
  hack/krmFunctionBenchmark/label_namespace/execfn/Dockerfile
  hack/krmFunctionBenchmark/label_namespace/execfn/build.sh
  hack/krmFunctionBenchmark/label_namespace/execfn/data1.yaml
  hack/krmFunctionBenchmark/label_namespace/execfn/data2.yaml
  hack/krmFunctionBenchmark/label_namespace/execfn/execfn.yaml
  hack/krmFunctionBenchmark/label_namespace/execfn/fn.sh
  hack/krmFunctionBenchmark/label_namespace/execfn/kustomization.yaml
  hack/krmFunctionBenchmark/readme.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2713 Keep empty array in output
  api/krusty/keepemptyarray_test.go
  kustomize/go.mod
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2718 Uniform unmarshal function
  api/internal/target/kusttarget.go
  api/types/kustomization.go
  api/types/kustomization_test.go
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2725 Pin To Kyaml/v0.4.1
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2726 Pin to kustomize/api v0.5.1
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, size/L

#2727 Pre v3.8.1; Add e2e tests pinned at v3.8.0
  Makefile
Labels: approved, cncf-cla: yes, size/S

#2730 Add a test and temporarily disable some plugin tests.
  api/go.mod
  api/go.sum
  api/internal/target/kusttarget.go
  api/krusty/transformerplugin_test.go
  api/resource/factory_test.go
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/L

#2731 Fix go plugins caveats link
  site/content/en/guides/plugins/_index.md
Labels: cncf-cla: yes, size/XS

#2733 Update formatting of component_test.go
  api/krusty/component_test.go
Labels: approved, cncf-cla: yes, size/S

#2735 Switch replica count transformer to kyaml.
  api/builtins/ReplicaCountTransformer.go
  api/filters/replicacount/example_test.go
  api/filters/replicacount/replicacount.go
  api/filters/replicacount/replicacount_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/go.mod
Labels: approved, cncf-cla: yes, size/L

#2595 Error for null files while reading
  kyaml/kio/byteio_writer.go
  kyaml/kio/pkgio_reader_test.go
  kyaml/yaml/kfns.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2742 Avoiding Prefix Transformer for Namespace resource
  api/builtins/PrefixSuffixTransformer.go
  api/internal/target/kusttarget_test.go
  api/krusty/baseandoverlaysmall_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#2748 Tweak sequence treatment in fieldspecs
  api/filters/annotations/annotations.go
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
  api/filters/labels/labels.go
  api/filters/replicacount/replicacount.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/setters2/set.go
  kyaml/yaml/compatibility.go
  kyaml/yaml/compatibility_test.go
  kyaml/yaml/kfns.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/L

#2743 Fix V1 setters
  cmd/config/internal/commands/cmdset_test.go
  kyaml/fieldmeta/fieldmeta.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2750 Add test for role binding across namespace.
  api/krusty/rolebindingacrossnamespace_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#2751 Add more tests to imagetag filter
  api/filters/imagetag/imagetag_test.go
Labels: approved, cncf-cla: yes, size/XL

#2752 Convert image transformer to kyaml.
  api/builtins/ImageTagTransformer.go
  api/filters/imagetag/imagetag.go
  api/filters/imagetag/imagetag_test.go
  api/konfig/builtinpluginconsts/images.go
  api/krusty/transformersimage_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
  plugin/builtin/imagetagtransformer/go.mod
Labels: approved, cncf-cla: yes, size/L

#2739 Role binding for serviceaccount across namesapce.
  api/krusty/rolebindingacrossnamespace_test.go
  api/resmap/resmap.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2753 Add v1 create setter tests
  cmd/config/internal/commands/cmdcreatesetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2737 Allow hash suffixing of arbitrary types
  api/k8sdeps/kunstruct/hasher.go
  api/k8sdeps/kunstruct/hasher_test.go
  site/content/en/guides/plugins/_index.md
Labels: cncf-cla: yes, lgtm, size/M

#2738 List and set setters in folders recursively
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  kyaml/pathutil/pathutil.go
  kyaml/printutil/printutil.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2757 Revert "List and set setters in folders recursively"
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  kyaml/pathutil/pathutil.go
  kyaml/printutil/printutil.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2763 Update release instructions.
  releasing/README.md
Labels: approved, cncf-cla: yes, size/L

#2764 Add seq tag in kyaml
  kyaml/yaml/types.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2762 Retain components field in edit
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2765 Try goreleaser's skip to deal with no-binary releases
  releasing/cloudbuild.sh
Labels: approved, cncf-cla: yes, size/S

#2766 Switch to kyaml v0.4.2
  api/go.mod
  cmd/config/go.mod
  functions/examples/application-cr/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-resource-requests/image/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/valueaddtransformer/go.mod
Labels: approved, cncf-cla: yes, size/M

#2770 Bump cli-utils version in cmd/config for relase
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#2772 Add back replace directive for kyaml in cmd/config
  cmd/config/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2759 Refactor refvartransformer with kyaml
  api/filters/refvar/doc.go
  api/filters/refvar/refvar.go
  api/filters/refvar/refvar_test.go
  api/go.sum
  api/internal/accumulator/refvartransformer.go
  api/internal/accumulator/refvartransformer_test.go
  api/testutils/filtertest/runfilter.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2771 support slash in path in fieldspec
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#2768 Support remote resources for kustomize edit add
  kustomize/internal/commands/create/create.go
  kustomize/internal/commands/edit/add/addresource.go
  kustomize/internal/commands/util/util.go
  kustomize/internal/commands/util/util_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2769 add kustomize edit add component command
  kustomize/internal/commands/edit/add/addcomponent.go
  kustomize/internal/commands/edit/add/addcomponent_test.go
  kustomize/internal/commands/edit/add/all.go
Labels: cncf-cla: yes, ok-to-test, size/L

#2783 Validate provided schema when creating setter
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  kyaml/setters2/settersutil/settercreator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2784 Handle some incorrect type values like 'int' and 'bool' in setters
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2778 Fix command: Migrate v1 Setters to latest
  cmd/config/go.sum
  cmd/config/internal/commands/cmdcreatesubstitution.go
  kyaml/fix/fixsetters/fieldmetav1.go
  kyaml/fix/fixsetters/fixsetters.go
  kyaml/fix/fixsetters/fixsetters_test.go
  kyaml/fix/fixsetters/lookupupgrade.go
  kyaml/fix/fixsetters/lookupupgradekio.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
