Repository kubernetes-sigs/kustomize, pull requests merged in 2020-10, with the labels that each got.

#3038 support merge strategy directive in list
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kustomize/go.mod
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/smpdirective.go
  kyaml/yaml/merge2/smpdirective_test.go
Labels: approved, cncf-cla: yes, size/L

#3048 add option to choose prepend/append patch items to list in merge
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/multiplepatch_test.go
  examples/patchMultipleObjects.md
  kyaml/kio/filters/merge.go
  kyaml/yaml/merge2/element_test.go
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/merge2/map_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/merge2_old_test.go
  kyaml/yaml/merge2/merge2_test.go
  kyaml/yaml/merge2/scalar_test.go
  kyaml/yaml/types.go
  kyaml/yaml/walk/associative_sequence.go
  kyaml/yaml/walk/map.go
  kyaml/yaml/walk/walk.go
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3050 support var ref in deployment template annotations
  api/konfig/builtinpluginconsts/varreference.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, size/M

#3054 refactor Gkv.isNamespaceableKind
  api/resid/gvk.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3055 Cleanup Cfg/Grep Command Output
  cmd/config/internal/commands/annotate_test.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cat_test.go
  cmd/config/internal/commands/count_test.go
  cmd/config/internal/commands/fmt_test.go
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/grep_test.go
  cmd/config/internal/commands/util.go
Labels: approved, cncf-cla: yes, size/L

#2948 Update _index.md
  site/content/en/guides/_index.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3056 Update generated go.sum files.
  kustomize/go.sum
  kyaml/yaml/merge2/element_test.go
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3059 Add metadata field to kustomization file
  api/krusty/kustomizationmetadata_test.go
  api/types/kustomization.go
  api/types/kustomization_test.go
  api/types/objectmeta.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3060 Remove the lines about config save command
  examples/transformerconfigs/README.md
Labels: approved, cncf-cla: yes, size/XS

#3066 Improve setter output message
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3064 remove ',' separator in edit add label/annotation
  kustomize/internal/commands/edit/add/addmetadata.go
  kustomize/internal/commands/edit/add/addmetadata_test.go
  kustomize/internal/commands/util/util.go
  kustomize/internal/commands/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3067 make file name more readable when no group
  api/resid/gvk.go
  api/resid/gvk_test.go
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/M

#3027 Support exec plugin on Windows
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#3068 Pin to kyaml/v0.9.1 and cli-utils/v0.20.4
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3069 Pin to cmd/config/v0.8.2, api/v0.6.3
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3072 Replace bash release helper scripts with Go progam
  Makefile
  cmd/gorepomod/Makefile
  cmd/gorepomod/README.md
  cmd/gorepomod/go.mod
  cmd/gorepomod/go.sum
  cmd/gorepomod/internal/arguments/args.go
  cmd/gorepomod/internal/edit/editor.go
  cmd/gorepomod/internal/edit/editor_test.go
  cmd/gorepomod/internal/gen/main.go
  cmd/gorepomod/internal/git/runner.go
  cmd/gorepomod/internal/misc/interfaces.go
  cmd/gorepomod/internal/misc/moduleshortname.go
  cmd/gorepomod/internal/misc/moduleshortname_test.go
  cmd/gorepomod/internal/misc/taggedmodule.go
  cmd/gorepomod/internal/misc/trackedrepo.go
  cmd/gorepomod/internal/mod/module.go
  cmd/gorepomod/internal/mod/module_test.go
  cmd/gorepomod/internal/repo/dotgitdata.go
  cmd/gorepomod/internal/repo/dotgitdata_test.go
  cmd/gorepomod/internal/repo/manager.go
  cmd/gorepomod/internal/repo/managerfactory.go
  cmd/gorepomod/internal/repo/protomodule.go
  cmd/gorepomod/internal/repo/protomodule_test.go
  cmd/gorepomod/internal/semver/semver.go
  cmd/gorepomod/internal/semver/semver_test.go
  cmd/gorepomod/internal/semver/svbump.go
  cmd/gorepomod/internal/utils/utils.go
  cmd/gorepomod/main.go
  cmd/gorepomod/usage.go
  hack/pinUnpin.sh
  hack/pinUnpinPluginApiDep.sh
Labels: cncf-cla: yes, size/XXL

#3071 Unpin api,cmd/config,kyaml
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3081 files for building image when release kustomize
  .dockerignore
  kustomize.Dockerfile
  releasing/cloudbuild_kustomize_image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3088 add arm build
  releasing/cloudbuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3076 Fetch openAPI data
  hack/install_kpt.sh
  kyaml/Makefile
  kyaml/openapi/README.md
  releasing/README.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#3083 Group regex within anchoring
  api/resmap/reswrangler.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#3097 add --as-current-user flag to fn run
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3100 Move pluginator to cmd dir.
  Makefile
  api/internal/tools/tools.go
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  cmd/pluginator/main.go
  cmd/pluginator/plugintype_string.go
Labels: approved, cncf-cla: yes, size/S

#3096 Add Support for Paginated Pull Request Responses to Multi-Module Check
  travis/module-span/multi-module-span.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#3099 Updated description for commonannotations
  site/content/en/api-reference/kustomization/commonannotations/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3103 Move multi-module-span.go to cmd/prchecker
  Makefile
  cmd/prchecker/go.mod
  cmd/prchecker/go.sum
  cmd/prchecker/main.go
Labels: approved, cncf-cla: yes, size/M

#3104 Pin to kyaml v0.9.2
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3105 Unpin kyaml
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#3107 Created a "kustomize openapi info" command
  kustomize/go.mod
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/openapi/info/info.go
  kustomize/internal/commands/openapi/openapi.go
  kyaml/Makefile
  kyaml/hack/fetchOpenApiData.sh
  kyaml/openapi/kubernetesapi/openapiinfo.go
  releasing/README.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#3115 Refactor making of openapi generated files.
  kyaml/Makefile
  kyaml/hack/fetchOpenApiData.sh
  kyaml/openapi/Makefile
  kyaml/openapi/README.md
  kyaml/openapi/kubernetesapi/openapiinfo.go
  kyaml/openapi/makeOpenApiInfoDotGo.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#3113 Add IsSet to SetterDefinition for kyaml release.
  kyaml/setters2/add.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3112 [kyaml] Option to continue pipeline processing when filter returns empty result
  kyaml/kio/kio.go
  kyaml/kio/kio_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3121 regenerated swagger.go files and updated asset name
  kyaml/openapi/kubernetesapi/swagger.go
  kyaml/openapi/kustomizationapi/swagger.go
  kyaml/openapi/openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3114 Hide openapi top-level command
  kustomize/internal/commands/openapi/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3119 Make recurse logic public
  cmd/config/configcobra/cmds.go
  cmd/config/internal/commands/annotate.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmdinit.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdwrap.go
  cmd/config/internal/commands/cmdxargs.go
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/merge.go
  cmd/config/internal/commands/merge3.go
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/sink.go
  cmd/config/internal/commands/source.go
  cmd/config/internal/commands/tree.go
  cmd/config/runner/runner.go
  cmd/config/runner/runner_test.go
  kyaml/commandutil/commandutil.go
  kyaml/fn/runtime/starlark/example_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/filters/filters.go
  kyaml/kio/filters/grep.go
  kyaml/kio/tree_test.go
  kyaml/setters/doyaml.go
  kyaml/setters2/add_test.go
  kyaml/setters2/types.go
  kyaml/yaml/order.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3110 Use Cobra for shell completion
  cmd/config/complete/complete.go
  cmd/config/completion/completion.go
  cmd/config/docs/commands/completion.md
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.sum
  kustomize/internal/commands/commands.go
  kustomize/main.go
Labels: cncf-cla: yes, hacktoberfest-accepted, lgtm, ok-to-test, size/L

#3087 Add isSet to ListSetters cmd.
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#3106 support array index in PathGetter
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3122 check Gvk in roleRef when update name reference
  api/filters/nameref/nameref.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/krusty/nameupdateinroleref_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3126 Generated go.sum/mod and docs.go changes.
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/generateddocs/commands/docs.go
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/M

#3134 Make isSet a parameter
  cmd/config/internal/commands/cmdset.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/fieldsetter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3123 doc: add varReference example
  site/content/en/api-reference/kustomization/vars/_index.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#3132 Add Ingress v1 support to builtin name references
  api/konfig/builtinpluginconsts/namereference.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3133 Add Ingress tls secretName to Secret builtin nameref
  api/konfig/builtinpluginconsts/namereference.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3136 removed hardcoded list of namespaceable resources
  api/filters/namespace/namespace_test.go
  api/krusty/namespaces_test.go
  api/resid/gvk.go
  api/resid/gvk_test.go
  api/resid/resid_test.go
  api/resmap/reswrangler_test.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#3140 Fix broken link to release page
  site/content/en/installation/binaries/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3135 cleanup namespace transformer
  api/builtins/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3146 Add better configMap cleanup description.
  examples/combineConfigs.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3150 Pin to kyaml v0.9.3
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3151 Pin to cmd/config 0.8.4
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3152 Pin to api 0.6.4
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3153 unpin modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3155 fix binary install script
  hack/install_kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
