Repository kubernetes-sigs/kustomize, pull requests merged in 2020-05, with the labels that each got.

#2429 Better support for writing functions in go
  cmd/config/go.mod
  cmd/config/go.sum
  kyaml/fn/framework/doc.go
  kyaml/fn/framework/example/Dockerfile
  kyaml/fn/framework/example/doc.go
  kyaml/fn/framework/example/main.go
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/types.go
  kyaml/go.mod
  kyaml/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2440 Create go.yml
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, size/S

#2441 Do not modify CM and Secrets Generator
  api/krusty/baseandoverlaymedium_test.go
  api/kv/kv.go
  api/kv/kv_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2433 Fix typo
  plugin/someteam.example.com/v1/chartinflator/ChartInflator
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2397 Update zh docs
  docs/zh/README.md
  docs/zh/fields.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2439 List substitutions
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  kyaml/setters2/list.go
  kyaml/setters2/list_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2445 UX improvements to kyaml/fn/framework
  kyaml/fn/framework/doc.go
  kyaml/fn/framework/example/main.go
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2446 release kyaml and cmd/config v0.1.10
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2447 update cmd/config e2e tests with new go function framework
  cmd/config/go.sum
  cmd/config/internal/commands/e2e/e2econtainerconfig/doc.go
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.mod
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.sum
  cmd/config/internal/commands/e2e/e2econtainerconfig/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2451 Upgrade to latest kyaml, cmd/config
  api/go.mod
  api/go.sum
  api/internal/crawl/go.mod
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.sum
  cmd/kubectl/go.mod
  cmd/kubectl/go.sum
  kstatus/go.mod
  kstatus/go.sum
  kustomize/go.mod
  kustomize/go.sum
  kyaml/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/XL

#2452 Add filesys.InsertPathPart function
  api/filesys/util.go
  api/filesys/util_test.go
Labels: approved, cncf-cla: yes, size/L

#2453 Define global const for metadata/namespace field
  api/builtins/NamespaceTransformer.go
  api/filters/namespace/namespace.go
  api/types/kustomization.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, size/M

#2454 add value add filter
  api/filters/valueadd/valueadd.go
  api/filters/valueadd/valueadd_test.go
Labels: approved, cncf-cla: yes, size/L

#2455 Introduce ValueAddTransformer.
  Makefile
  api/builtins/ValueAddTransformer.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/target/kusttarget_configplugin.go
  examples/README.md
  examples/valueAdd.md
  plugin/builtin/valueaddtransformer/ValueAddTransformer.go
  plugin/builtin/valueaddtransformer/ValueAddTransformer_test.go
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#2457 Pin kustomize CLI to kustomize API v0.3.3
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#2458 Update build scripts
  releasing/cloudbuild.sh
  releasing/cloudbuild_api.yaml
  releasing/cloudbuild_kustomize.yaml
Labels: cncf-cla: yes

#2459 Relative Order of Mutating/Validating WebhookConfigs
  api/resid/gvk.go
  api/resid/gvk_test.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#2449 add missing required key in example
  examples/helloWorld/deployment.yaml
Labels: cncf-cla: yes, ok-to-test, size/XS

#2442 Add maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2465 Copy comments from function inputs to function outputs.
  kyaml/comments/comments.go
  kyaml/comments/comments_test.go
  kyaml/fn/runtime/runtimeutil/runtimeutil.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/fn/runtime/starlark/starlark.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2461 Add install command for MacPorts user
  docs/INSTALL.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2456 Add plugins zh docs
  docs/zh/README.md
  docs/zh/plugins.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2469 unpin kyaml for cmd/config
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#2432 Fix MarshalJSON of array
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2471 Validate setters against openAPI
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/cmdset_test.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/yaml/compatibility.go
  kyaml/yaml/compatibility_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2473 Set common labels and annotations as strings
  api/filters/annotations/annotations.go
  api/filters/annotations/annotations_test.go
  api/filters/fsslice/fsslice.go
  api/filters/labels/labels.go
  api/filters/labels/labels_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2478 Validate substitutions against openAPI
  cmd/config/internal/commands/cmdset_test.go
  kyaml/setters2/set.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2470 Support publishing starlark functions from urls
  cmd/config/internal/commands/e2e/e2e_test.go
  cmd/config/internal/commands/e2e/starlark/annotate.star
  cmd/config/internal/commands/run-fns.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/fn/runtime/starlark/starlark.go
  kyaml/runfn/runfn.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2483 release kyaml and cmd/config
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2482 Fix mkdir -p problem in example
  examples/valueAdd.md
Labels: approved, cncf-cla: yes, size/S

#2484 Add more labelling tests.
  api/krusty/baseandoverlaysmall_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
Labels: approved, cncf-cla: yes, size/M

#2486 Automated ./hack/doGoMod.sh tidy;verify
  cmd/config/go.mod
  cmd/config/go.sum
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/template-go-nginx/local-resource/example-use.yaml
  hack/go.sum
Labels: approved, cncf-cla: yes, size/L

#2488 Fix verify-kustomize target in Makefile
  Makefile
Labels: approved, cncf-cla: yes, size/M

#2487 Quote yaml 1.1 non-string values for commonlabels and commonAnnotations
  api/filters/annotations/annotations_test.go
  api/filters/fsslice/fsslice.go
  api/filters/labels/labels_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2489 Test kustomize examples against head in prow presubmit.
  Makefile
  examples/helloWorld/README.md
  examples/ldap/README.md
  examples/valueAdd.md
  examples/zh/helloWorld.md
  examples/zh/ldap.md
Labels: approved, cncf-cla: yes, size/S

#2493 kustomize transformers to create fields if they are null
  api/filters/annotations/annotations.go
  api/filters/annotations/annotations_test.go
  api/filters/fsslice/fieldspec_filter.go
  api/filters/fsslice/fsslice.go
  api/filters/labels/labels.go
  api/filters/labels/labels_test.go
  api/filters/namespace/namespace.go
  api/filters/namespace/namespace_test.go
  api/filters/prefixsuffix/prefixsuffix.go
  api/filters/replicacount/replicacount.go
  api/filters/replicacount/replicacount_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2480 Add annotation for opting out of formatting
  kyaml/kio/filters/fmtr.go
  kyaml/kio/filters/fmtr_test.go
  kyaml/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2495 Validate list values against openAPI
  cmd/config/internal/commands/cmdset_test.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2468 Test coverage for numeric-looking commonLabels strings
  api/krusty/numericcommonlabels_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#2438 Kustomize API Proposal: Add an example with components
  examples/README.md
  examples/components.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/XL

#2501 Address kyaml windows compatibility issues
  kyaml/copyutil/copyutil_test.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/fn/runtime/starlark/starlark_test.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_writer_test.go
  kyaml/kio/tree_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
  kyaml/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2502 Add coverage for kusttarget.Load
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_test.go
  api/internal/target/maker_test.go
  api/internal/target/vars_test.go
  api/types/fix.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2503 Beef up test.
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2505 Fix nondeterminstic failure
  api/internal/target/kusttarget_test.go
Labels: approved, cncf-cla: yes, size/M

#2504 Automated fix to hack/go.sum
  hack/go.sum
Labels: approved, cncf-cla: yes, size/L

#2507 complete TODOs in docs/readme
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#2508 Upgrade to kyaml v0.1.11
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/kubectl/go.mod
  cmd/kubectl/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/XXL

#2510 Make a test more relocatable.
  api/internal/plugins/compiler/utils_test.go
Labels: approved, cncf-cla: yes, size/XS

#2515 Release kyaml
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, size/XS

#2516 Add Cluster as not namespaceable kind
  api/resid/gvk.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2519 Release cmd/config
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, size/XS

#2511 Fix cmd/config windows issues
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/cmdxargs_test.go
  cmd/config/internal/commands/e2e/e2e_test.go
  cmd/config/internal/commands/fmt_test.go
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/exec/exec.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/kio/filters/merge3_test.go
  kyaml/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2522 Mark components example as WIP
  examples/components.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2527 Remove flakey test optimization.
  api/internal/plugins/compiler/compiler.go
Labels: approved, cncf-cla: yes, size/S

#2520 Run GitHub actions to test on MacOS and Windows
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, size/L

#2499 Release program
  releasing/README.md
  releasing/releasing/gitrunner.go
  releasing/releasing/go.mod
  releasing/releasing/go.sum
  releasing/releasing/main.go
  releasing/releasing/main_test.go
  releasing/releasing/modulemeta.go
  releasing/releasing/modulemeta_test.go
  releasing/releasing/moduleversion.go
  releasing/releasing/moduleversion_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#2517 Update examples versions
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2526 Add init as an alias to create
  kustomize/internal/commands/create/create.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2525 Add tools package, tidy go mods
  Makefile
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  hack/go.sum
  hack/tools.go
  travis/check-go-mod.sh
Labels: cncf-cla: yes, ok-to-test, size/M

#2528 Make plugin utils package.
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/internal/plugins/loader/loader.go
  api/internal/plugins/utils/utils.go
  api/internal/plugins/utils/utils_test.go
  api/testutils/kusttest/plugintestenv.go
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.sum
Labels: approved, cncf-cla: yes, size/M

#2529 Add logging.
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/loader/loader.go
Labels: cncf-cla: yes

#2530 Remove race in tests.
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/compiler/compiler_test.go
  api/internal/plugins/loader/loader.go
Labels: approved, cncf-cla: yes, size/S

#2532 Upgrade CLI to API v0.4.0
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/kustfile/kustomizationfile.go
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, size/L

#2536 Improve error message for merge error
  api/krusty/generatormergeandreplace_test.go
  api/resmap/resmap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2490 add zh docs plugins-builtions.md
  docs/zh/fields.md
  docs/zh/plugins-builtins.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2541 Pin to kstatus/v0.0.2
  cmd/kubectl/go.mod
  cmd/kubectl/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#2542 pin kustomize to cmd/kubectl_v0_1_0
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#2537 Fix git commit hash ignored
  api/internal/git/cloner.go
  api/loader/getter.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2543 pin CLI to API v0.4.1
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#2509 Short hand notation for setters/subst
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset_test.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/setters2/add.go
  kyaml/setters2/add_test.go
  kyaml/setters2/example_test.go
  kyaml/setters2/list.go
  kyaml/setters2/set.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2544 Consider stringData when calculate secret hash
  api/k8sdeps/kunstruct/hasher.go
  api/k8sdeps/kunstruct/hasher_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2548 Add a note for go-getter
  examples/remoteBuild.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2550 Check replace in go.mod before releasing
  releasing/releasing/go.mod
  releasing/releasing/go.sum
  releasing/releasing/main.go
  releasing/releasing/modulemeta.go
  releasing/releasing/modulemeta_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2545 Accept `set` value as flag or argument
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
