Repository kubernetes-sigs/kustomize, pull requests merged in 2020-09, with the labels that each got.

#2929 Test examples against v3.8.2
  Makefile
  api/internal/crawl/go.sum
Labels: approved, cncf-cla: yes, size/S

#2930 fix “chart s” to “charts ”
  examples/zh/chart.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2911 Setters/substitutions with subpackages
  cmd/config/go.mod
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/Krmfile
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/nosetters/Krmfile
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/nosetters/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/storage/Krmfile
  cmd/config/internal/commands/test/testdata/dataset-with-setters/mysql/storage/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset-without-setters/mysql/Krmfile
  cmd/config/internal/commands/test/testdata/dataset-without-setters/mysql/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset-without-setters/mysql/storage/Krmfile
  cmd/config/internal/commands/test/testdata/dataset-without-setters/mysql/storage/deployment.yaml
  kustomize/go.mod
  kustomize/go.sum
  kyaml/kio/ignorefilesmatcher.go
  kyaml/kio/ignorefilesmatcher_test.go
  kyaml/kio/pkgio_reader.go
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/pathutil/pathutil.go
  kyaml/pathutil/pathutil_test.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2931 add legacy filter to image tag transformer
  api/builtins/ImageTagTransformer.go
  api/krusty/transformersimage_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2940 Fix setters subpkgs friction
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2942 add Donny to maintainer
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS

#2941 Fix issue where ignoreFilesMatcher doesn't work correctly
  kyaml/kio/ignorefilesmatcher.go
  kyaml/kio/ignorefilesmatcher_test.go
  kyaml/kio/pkgio_reader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2946 Refactor subpackages logic
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/util.go
  cmd/config/internal/commands/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2938 annotate, delete-setter, delete-subst With Subpackages
  cmd/config/internal/commands/annotate.go
  cmd/config/internal/commands/annotate_test.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesetter_test.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmddeletesubstitution_test.go
  kyaml/setters2/delete.go
  kyaml/setters2/settersutil/deletecreator_test.go
  kyaml/setters2/settersutil/deletercreator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2955 Fmt with subpackages
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/fmt_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2957 Count with Subpackages
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/count_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2958 Grep with subpackages
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/grep_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2959 Cat with subpackages
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cat_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2943 remove all temp dir
  api/loader/getter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2956 Replace language with more inclusive & accurate "hard-coded"
  api/filters/namespace/namespace.go
Labels: approved, cncf-cla: yes, size/XS

#2953 Add namespace name to namespace transformer defaults
  api/konfig/builtinpluginconsts/namespace.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2939 Add --log-steps flag
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2971 Fix unintended patches change in all Kustomization writes.
  kustomize/internal/commands/edit/fix/fix.go
  kustomize/internal/commands/edit/fix/fix_test.go
  kustomize/internal/commands/edit/set/setimage_test.go
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#2969 Fix comment on SplitIndexNameValue
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2944 Remove some obsolete references to GrepFilter
  kyaml/yaml/filters.go
  kyaml/yaml/rnode.go
Labels: approved, cncf-cla: yes, size/S

#2920 Technical details structure picture
  api/internal/crawl/README.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2975 Add test representing 2960
  api/krusty/nullvalues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2973 Format the output of cfg commands
  cmd/config/internal/commands/annotate.go
  cmd/config/internal/commands/annotate_test.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cat_test.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesetter_test.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmddeletesubstitution_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/count_test.go
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/fmt_test.go
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/grep_test.go
  cmd/config/internal/commands/util.go
  cmd/config/internal/commands/util_test.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2967 Print Krmfile data for cfg tree
  cmd/config/go.sum
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/tree_test.go
  kyaml/kio/tree.go
  kyaml/kio/tree_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2976 Remove live; done testing. Bring to sig-cli for discussion.
  cmd/config/configcobra/cmds.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2982 Update cmd/config to use latest version of cli-utils
  cmd/config/configcobra/live.go
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2984 Do not print package info in grep
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/grep_test.go
  kyaml/pathutil/pathutil.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2988 Add --env/-e flag to fn run
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2974 remove not used args & use const string instead of literal
  cmd/config/internal/commands/run-fns.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2989 Generated changes.
  api/internal/crawl/go.sum
  cmd/config/go.sum
  cmd/config/internal/commands/util_test.go
  kustomize/go.sum
Labels: cncf-cla: yes

#2990 Pin to kyaml v0.8.0
  api/go.mod
  cmd/config/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/valueaddtransformer/go.mod
Labels: approved, cncf-cla: yes, size/M

#2991 Go sum updates
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2932 add DisableNameSuffixHash parameter to edit Secret & ConfigMap
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/flagsandargs.go
  kustomize/internal/commands/edit/add/secret.go
  kustomize/internal/commands/edit/add/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2997 Update go.mod
  cmd/config/go.mod
Labels: approved, cncf-cla: yes, size/XS

#3002 Pin to api/v0.6.1
  api/internal/plugins/loader/loader_test.go
  cmd/config/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2998 Change network to a boolean in kpt fn run
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3007 Unpin the dependencies post release.
  kustomize/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
  pluginator/go.mod
Labels: approved, cncf-cla: yes, size/M

#3008 Pin to kyaml v0.8.1
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3010 Pin to cli-utils/v0.20.2
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3009 put endpoints before service
  api/resid/gvk.go
  api/resid/gvk_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3012 remove --network-name flag from kpt fn run
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  kyaml/runfn/runfn.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3013 Generated pin to cli-utils v0.20.2 hash
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3015 Pin to cmd/config/v0.8.1
  kustomize/go.mod
Labels: approved, cncf-cla: yes, size/XS

#3016 Pin to api v0.6.2
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3017 Update release instructions.
  releasing/README.md
Labels: cncf-cla: yes

#3019 Install gh cli tool via make
  Makefile
Labels: approved, cncf-cla: yes

#3018 Unpin api, kyaml and cmd/config
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  api/internal/plugins/fnplugin/fnplugin.go
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3011 test for issue 2896
  api/krusty/issue2896_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#3001 handle the "$patch: delete" in patch transformer
  api/builtins/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/patchtransformer/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#3000 fix namespace will match all empty namespace
  api/resmap/reswrangler.go
  api/resmap/selector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2981 Simplify the cmd/config ext package
  cmd/config/ext/ext.go
  cmd/config/internal/commands/annotate.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/grep.go
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3025 Small change to live commands retrieval
  cmd/config/configcobra/live.go
Labels: cncf-cla: yes, size/XS

#3026 Drop the get prefix from GetIgnoreFileName function
  kyaml/ext/ext.go
  kyaml/kio/ignorefilesmatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3030 copyutil should not ignore files that just happen to start with .git
  kyaml/copyutil/copyutil.go
  kyaml/copyutil/copyutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3029 Sync openAPI setter values with schema
  kyaml/openapi/openapi.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/fieldsetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3034 add Kustomization to cfg tree
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/tree_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3023 Enable the installation of specific versions with the "install_kustomize.sh" script (#3022)
  hack/install_kustomize.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3024 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, cncf-cla: yes, size/L

#3037 Remove dependency from cmd/config on cli-utils
  cmd/config/configcobra/live.go
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, size/L

#2994 fix typo
  site/content/en/api-reference/kustomization/patches/_index.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2992 add as-current-user for fn run
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, size/L

#2949 Chore: docs : Add basic structure for command line options
  site/content/en/guides/cmd/_index.md
  site/content/en/guides/cmd/build/_index.md
  site/content/en/guides/cmd/cfg/_index.md
  site/content/en/guides/cmd/create/_index.md
  site/content/en/guides/cmd/edit/_index.md
  site/content/en/guides/cmd/fn/_index.md
  site/content/en/guides/cmd/help/_index.md
  site/content/en/guides/cmd/install-completion/_index.md
  site/content/en/guides/cmd/live/_index.md
  site/content/en/guides/cmd/version/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#2999 Added list of env variables for fn-plugins
  api/internal/plugins/fnplugin/fnplugin.go
  api/krusty/fnplugin_test.go
  api/types/pluginrestrictions.go
  kustomize/internal/commands/build/build.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#3032 remove default master branch in cloner
  api/internal/git/cloner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3033 fix multiple match issue in rolebinding
  api/filters/nameref/nameref.go
  api/krusty/rolebindingacrossnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3044 add GetElementByKey
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3040 fixed issue 2896
  api/builtins/PatchTransformer.go
  api/krusty/issue2896_test.go
  plugin/builtin/patchtransformer/PatchTransformer.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3052 added IsEmpty() method
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/resource/resource.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3003 Adds a directory spanning check script
  travis/module-span/multi-module-span.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L
