Repository kubernetes-sigs/kustomize, pull requests merged in 2020-08, with the labels that each got.

#2776 add test for issues raised in #2734
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2799 Throw insufficient arguments error for create-setter
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2795 Update setter comments during 3-way merge
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/merge3/kustomization_test.go
  kyaml/yaml/merge3/list_test.go
  kyaml/yaml/merge3/map_test.go
  kyaml/yaml/merge3/scalar_test.go
  kyaml/yaml/merge3/visitor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2797 Infix/Suffix subst creation for fix
  kyaml/fix/fixsetters/fixsetters_test.go
  kyaml/fix/fixsetters/lookupupgrade.go
  kyaml/fix/fixsetters/lookupupgradekio.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2777 adds test for issue#2767
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2792 Fix issue where the schema was not propagated correctly when walking yaml doc
  kyaml/setters2/add.go
  kyaml/setters2/delete.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2796 Order PersistentVolume before Deployment
  api/resid/gvk.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2801 Update module hashes
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.sum
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2780 Refactor namereferencetransformer with kyaml
  api/filters/nameref/doc.go
  api/filters/nameref/nameref.go
  api/filters/nameref/nameref_test.go
  api/filters/nameref/seqfilter.go
  api/filters/nameref/seqfilter_test.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/resmap/factory.go
  api/resource/factory.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2787 Refactor hasher with kyaml
  api/hasher/hasher.go
  api/hasher/hasher_test.go
  api/internal/target/kusttarget_test.go
  api/k8sdeps/kunstruct/hasher.go
  api/k8sdeps/kunstruct/hasher_test.go
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/component_test.go
  api/krusty/configmaps_test.go
  api/krusty/disablenamesuffix_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/generatoroptions_test.go
  api/krusty/multiplepatch_test.go
  api/krusty/namespacedgenerators_test.go
  api/krusty/transformerplugin_test.go
  api/krusty/variableref_test.go
  examples/configGeneration.md
  examples/zh/configGeneration.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2800 Ignore TMPDIR when run container
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2802 Auto module hash update.
  api/internal/crawl/go.sum
Labels: approved, cncf-cla: yes, size/S

#2804 Error on creation if setter/subst exists
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmdcreatesubstitution_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2807 Fix typo in build sub-command example
  kustomize/internal/commands/build/build.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#2805 Keep empty map in kustomize output
  api/krusty/extendedpatch_test.go
  api/krusty/inlinepatch_test.go
  api/krusty/multiplepatch_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/merge2/element_test.go
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/merge2/map_test.go
  kyaml/yaml/merge2/scalar_test.go
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
  kyaml/yaml/walk/associative_sequence.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchstrategicmergetransformer/go.mod
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2810 fix panic when fieldspec refers an empty value
  api/krusty/namereference_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2811 Move to new constants.
  api/filters/annotations/annotations.go
  api/filters/filtersutil/setters.go
  api/filters/labels/labels.go
  api/filters/namespace/namespace.go
  api/filters/prefixsuffix/prefixsuffix.go
  api/filters/refvar/refvar.go
  api/filters/replicacount/replicacount.go
  plugin/builtin/patchstrategicmergetransformer/go.sum
Labels: approved, cncf-cla: yes, size/M

#2812 Remove old constants from kyaml
  kyaml/kio/byteio_reader.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/S

#2813 Kyaml api cleanup
  kyaml/kio/byteio_reader.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/M

#2814 Fix more constants.
  api/filters/fieldspec/fieldspec.go
  api/filters/refvar/refvar_test.go
Labels: approved, cncf-cla: yes, size/XS

#2816 Move to kyaml v0.5.0
  api/go.mod
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2817 Switch to cmd/config v0.5.0
  kustomize/go.mod
Labels: approved, cncf-cla: yes, size/XS

#2818 Use yaml.IsYNodeString
  api/filters/refvar/refvar.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/S

#2820 Replace all calls to yaml.IsEmpty with IsMissingOrNull
  api/filters/namespace/namespace.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/openapi/openapi.go
  kyaml/setters2/list.go
  kyaml/setters2/walk.go
  kyaml/yaml/fns.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge3/visitor.go
  kyaml/yaml/schema/schema.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
  kyaml/yaml/walk/associative_sequence.go
  kyaml/yaml/walk/map.go
  kyaml/yaml/walk/walk.go
Labels: approved, cncf-cla: yes, size/M

#2815 Add full github link to varreference.go
  site/content/en/api-reference/kustomization/vars/_index.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#2821 Testing for nilness, nullness and emptyness.
  kyaml/yaml/fns.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge3/visitor.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/L

#2822 IsFieldEmpty renamed to MapNode.IsNilOrEmpty
  kyaml/kio/tree.go
  kyaml/openapi/openapi.go
  kyaml/yaml/fns.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/M

#2824 Remove unused IsFieldEmpty function, add more godoc.
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/S

#2830 Drop link to github release page from main readme
  README.md
Labels: approved, cncf-cla: yes, size/S

#2832 Fix IsFieldEmpty in cmdxargs
  cmd/config/go.mod
  cmd/config/internal/commands/cmdxargs.go
  kustomize/go.mod
Labels: cncf-cla: yes, ok-to-test, size/XS

#2836 Bump kyaml and cli-utils in cmd/config
  cmd/config/go.mod
  cmd/config/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#2838 Unpin kyaml v0.6.0 from cmd/comnfig
  cmd/config/go.mod
Labels: approved, cncf-cla: yes, size/XS

#2831 Add test for long quoted string with blanks
  api/krusty/stringquoteblank_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2840 Improve the description of the --field flag for create-setter
  cmd/config/internal/commands/cmdcreatesetter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2839 Add test for adding setter with path inside a sequence
  kyaml/setters2/add_test.go
Labels: approved, cncf-cla: yes, size/M

#2829 Bug: name prefix or suffix in base results in incorrect references
  api/krusty/nameprefixsuffixpatch_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2835 Transform namespace inside of APIService
  api/konfig/builtinpluginconsts/namespace.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#2850 Automated go.sum/format updates.
  cmd/config/go.sum
  cmd/config/internal/commands/cmdcreatesetter.go
  kustomize/go.sum
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, size/S

#2851 Split rnode.go from types.go, preserving line history
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/XXL

#2852 Make mapnode.go, preserving line history.
  kyaml/yaml/mapnode.go
  kyaml/yaml/mapnode_test.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/L

#2853 Print message if subst doesn't match any field value
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2848 Update setter comments correctly on updates
  kyaml/yaml/fns.go
  kyaml/yaml/merge3/list_test.go
  kyaml/yaml/merge3/merge3.go
  kyaml/yaml/merge3/scalar_test.go
  kyaml/yaml/merge3/visitor.go
  kyaml/yaml/types.go
  kyaml/yaml/walk/map.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2826 Add an option to log which function is running
  kyaml/kio/kio.go
  kyaml/kio/kio_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2854 Inline repeated types.
  kyaml/kio/kioutil/kioutil_test.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/rnode_test.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2859 Add TypeMeta.IsNamespaceable
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2855 Delete substitution and fix delete setters
  cmd/config/configcobra/cmds.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesetter_test.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmddeletesubstitution_test.go
  kyaml/setters2/delete.go
  kyaml/setters2/delete_test.go
  kyaml/setters2/set.go
  kyaml/setters2/settersutil/deletecreator_test.go
  kyaml/setters2/settersutil/deletercreator.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2794 Replace patchesJson6902 field with patches.
  api/types/fix.go
  api/types/kustomization.go
  api/types/patchjson6902.go
  api/types/patchtarget.go
  kustomize/go.mod
  kustomize/go.sum
  kustomize/internal/commands/kustfile/kustomizationfile.go
  kustomize/internal/commands/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#2866 Update dead URL to base in glossary.
  site/content/en/api-reference/kustomization/bases/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#2870 Delete newly orphaned code.
  api/ifc/ifc.go
  api/internal/target/kusttarget.go
  api/internal/target/multitransformer.go
  api/k8sdeps/kunstruct/unstructadapter_test.go
  api/resource/resource.go
  api/transform/mutatefield.go
  api/transform/mutatefield_test.go
  cmd/config/go.sum
  kustomize/go.sum
  kyaml/go.sum
  kyaml/runfn/runfn_test.go
  plugin/builtin/patchstrategicmergetransformer/go.sum
Labels: approved, cncf-cla: yes, size/XL

#2864 add option to continue pipeline when the input is empty
  kyaml/kio/kio.go
  kyaml/kio/kio_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2885 Clean up option construction.
  api/k8sdeps/validator/kustvalidator.go
  api/krusty/options.go
  api/testutils/kusttest/harness.go
  kustomize/internal/commands/build/build.go
Labels: approved, cncf-cla: yes, size/M

#2886 Add types and proposal for k8s to kyaml migration.
  api/go.mod
  api/internal/merge/merginator.go
  api/internal/merge/merginator_test.go
  api/internal/validate/fieldvalidator.go
  api/internal/validate/fieldvalidator_test.go
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
  api/k8sdeps/validator/kustvalidator.go
  api/krusty/internal/provider/depprovider.go
  api/krusty/kustomizer.go
  api/krusty/options.go
  kustomize/internal/commands/build/build.go
  kustomize/internal/commands/build/flagEnableKyaml.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2889 Add logging for module release notes.
  releasing/cloudbuild.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2887 refactor network name in kyaml container
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2890 add --fn-user flag to function run
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2847 fix name reference with prefixsuffix
  api/filters/nameref/nameref.go
  api/filters/nameref/nameref_test.go
  api/krusty/nameprefixsuffixpatch_test.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/resource.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XL

#2888 explicitly specify envs to be exported in function
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#2891 List setters in subpackages
  cmd/config/ext/ext.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdlistsetters_test.go
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/e2e/list_setters_test.go
  cmd/config/internal/commands/test/testdata/dataset1/mysql/Krmfile
  cmd/config/internal/commands/test/testdata/dataset1/mysql/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset1/mysql/nosetters/Krmfile
  cmd/config/internal/commands/test/testdata/dataset1/mysql/nosetters/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset1/mysql/storage/Krmfile
  cmd/config/internal/commands/test/testdata/dataset1/mysql/storage/deployment.yaml
  kyaml/go.mod
  kyaml/go.sum
  kyaml/pathutil/pathutil.go
  kyaml/pathutil/pathutil_test.go
  kyaml/setters2/list.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2900 add --fn-env flag to fn run
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#2902 Fix some generated comments.
  cmd/config/internal/commands/test/testdata/dataset1/mysql/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset1/mysql/nosetters/deployment.yaml
  cmd/config/internal/commands/test/testdata/dataset1/mysql/storage/deployment.yaml
Labels: cncf-cla: yes

#2909 remove --fn-user and --fn-env flags
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2910 Add recommended sequence to release instructions.
  releasing/README.md
Labels: approved, cncf-cla: yes, size/S

#2898 Add support for .krmignore file
  kyaml/ext/ext.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/kio/ignorefilesmatcher.go
  kyaml/kio/ignorefilesmatcher_test.go
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_reader_test.go
  kyaml/kio/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2912 Pin to cmd/config to kyaml/v0.7.1 and cli-utils/v0.19.2
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/valueaddtransformer/go.sum
Labels: approved, cncf-cla: yes, size/M

#2913 Pin api to kyaml/v0.7.1
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.mod
  functions/examples/validator-resource-requests/image/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2915 Pin to kustomize api v0.6.0
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
Labels: approved, cncf-cla: yes, size/L

#2926 Repair a go module spec.
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
Labels: approved, cncf-cla: yes, size/XS

#2927 Unpinning after release releases
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  pluginator/go.mod
  pluginator/go.sum
Labels: approved, cncf-cla: yes, size/L

#2928 Add more release instructions
  Makefile
  api/go.mod
  api/go.sum
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  pluginator/go.sum
  releasing/README.md
Labels: approved, cncf-cla: yes, size/M
