Repository kubernetes-sigs/kustomize, pull requests merged in 2020-11, with the labels that each got.

#3160 update cloudbuild for image pushing job
  releasing/cloudbuild_kustomize_image.yaml
Labels: approved, cncf-cla: yes, size/M

#3163 update version in image creation
  releasing/cloudbuild_kustomize_image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3164 fix version in releasing/cloudbuild_kustomize_image.yaml
  releasing/cloudbuild_kustomize_image.yaml
Labels: approved, cncf-cla: yes, size/XS

#3143 Convert helminflator to builtin plugin HelmChartGenerator
  Makefile
  api/builtins/HelmChartInflationGenerator.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/target/kusttarget_configplugin.go
  api/krusty/helmchartinflationgenerator_test.go
  api/types/helmchartargs.go
  api/types/kustomization.go
  examples/chart.md
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  site/content/en/guides/plugins/builtins.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3161 removing travis references
  .github/workflows/go.yml
  Makefile
  api/internal/plugins/doc.go
  docs/contributing/windows/index.html
  docs/zh/contributing/windows/index.html
  examples/README.md
  examples/zh/README.md
  scripts/Invoke-PreCommit.ps1
  scripts/check-go-mod.sh
  scripts/kyaml-pre-commit.sh
  site/content/en/contributing/windows/_index.md
  site/content/zh/contributing/windows/_index.md
  travis/consider-early-travis-exit.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#2951 Add ability to specify behavior adding configmap
  kustomize/internal/commands/edit/add/configmap.go
  kustomize/internal/commands/edit/add/configmap_test.go
  kustomize/internal/commands/edit/add/flagsandargs.go
  kustomize/internal/commands/edit/add/flagsandargs_test.go
  kustomize/internal/commands/edit/add/secret.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3173 added StringList set
  kyaml/sets/sets_test.go
  kyaml/sets/string.go
  kyaml/sets/stringlist.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#3174 add tests for ElementSetter
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3139 Update Multi Module Check to Scan Commits
  cmd/prchecker/main.go
  cmd/prchecker/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#3170 added tests for merge key tuple behavior
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kyaml/yaml/merge3/element_test.go
Labels: cncf-cla: yes, ok-to-test, size/XL

#3166 Defer openAPI cleanup
  cmd/config/runner/runner.go
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/setters2/add_test.go
  kyaml/setters2/delete_test.go
  kyaml/setters2/list.go
  kyaml/setters2/settersutil/deletecreator_test.go
  kyaml/setters2/settersutil/deletercreator.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/settersutil/substitutioncreator_test.go
  kyaml/setters2/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3167 re-enable test for edit patch add
  Makefile
  examples/springboot/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3187 Run multi-module check during presubmit
  Makefile
  cmd/prchecker/main.go
  cmd/prchecker/main_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#3176 add ElementSetterList and ElementMatcherList to fns.go
  kyaml/yaml/example_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/merge2/smpdirective.go
  kyaml/yaml/walk/associative_sequence.go
Labels: cncf-cla: yes, lgtm, size/L

#3169 support regex in GVK selection
  api/resmap/reswrangler.go
  api/types/selector.go
  api/types/selector_test.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3177 Improve json patch plugin
  api/builtins/HelmChartInflationGenerator.go
  api/builtins/PatchJson6902Transformer.go
  api/internal/target/kusttarget_configplugin.go
  api/types/kustomization.go
  api/types/patchjson6902.go
  api/types/patchtarget.go
  kyaml/sets/stringlist.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
Labels: approved, cncf-cla: yes, size/L

#3159 use merge key list instead of a single merge key
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kyaml/openapi/openapi.go
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/rnode.go
  kyaml/yaml/walk/associative_sequence.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3200 cleaned comments
  kyaml/yaml/merge3/element_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#3201 Temporarily remove cross-module PR check.
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#3197 add link for component reference
  site/content/en/api-reference/kustomization/components/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3203 fix helm chart inflation generator
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/krusty/helmchartinflationgenerator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3206 Disable helm inflator tests.
  api/krusty/helmchartinflationgenerator_test.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3118 Implement WNode methods
  api/go.mod
  api/internal/wrappy/factory_test.go
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3207 Skip multi-mod check if PULL_NUMBER unset
  Makefile
  scripts/check-multi-module.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#3213 Pin to cli-utils_v0.21.1 kyaml_v0.9.4
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3214 Pin to cmd/config/v0.8.5
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3216 Pin to api_v0.6.5
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3218 Unpin everything post v3.8.7 release
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/gogetter/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3217 remove a tag from image
  releasing/cloudbuild_kustomize_image.yaml
Labels: approved, cncf-cla: yes, size/XS

#3221 Function framework standalone feature
  kyaml/errors/errors.go
  kyaml/fn/framework/doc.go
  kyaml/fn/framework/example2/Dockerfile
  kyaml/fn/framework/example2/config.yaml
  kyaml/fn/framework/example2/main.go
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/testdata/command/config.yaml
  kyaml/fn/framework/testdata/command/expected.yaml
  kyaml/fn/framework/testdata/command/input.yaml
  kyaml/fn/framework/testdata/template/config.yaml
  kyaml/fn/framework/testdata/templatefiles/config.yaml
  kyaml/fn/framework/testdata/templatefiles/deployment.template
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_readwriter_test.go
  kyaml/kio/filters/merge.go
  kyaml/kio/filters/merge_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3226 Delete v1 setters code
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesetter_test.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
  kyaml/openapi/openapi.go
  kyaml/setters/addkio.go
  kyaml/setters/addyaml.go
  kyaml/setters/dokio.go
  kyaml/setters/doyaml.go
  kyaml/setters/lookupkio.go
  kyaml/setters/lookupyaml.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3225 support inline transformer and generator
  api/internal/target/kusttarget.go
  api/krusty/inlinetransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3223 Add namereference for PersistentVolume
  api/konfig/builtinpluginconsts/namereference.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3222 added kustomize edit set label
  kustomize/internal/commands/edit/all.go
  kustomize/internal/commands/edit/set/all.go
  kustomize/internal/commands/edit/set/setlabel.go
  kustomize/internal/commands/edit/set/setlabel_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3227 update kustomize download script
  hack/install_kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3185 Allowing RunFns not to stop on empty result
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3230 Fix go fmt.
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
Labels: cncf-cla: yes

#3231 Add RNode FromMap factory method.
  api/internal/wrappy/wnode.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/L

#3232 Expand rnode function comments to point to multi-object options.
  kyaml/yaml/rnode.go
Labels: approved, cncf-cla: yes, size/XS

#3229 Add methods to convert ResMap to and from RNodes
  api/resmap/factory.go
  api/resmap/factory_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3236 Remove merge commits from release notes
  releasing/cloudbuild.sh
Labels: cncf-cla: yes, lgtm, size/XS

#3233 Implement WNodeFactory.SliceFromBytes
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  api/k8sdeps/kunstruct/factory.go
  api/konfig/general.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, size/XL

#3235 fn framework TemplatePatch support
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/frameworktestutil/frameworktestutil.go
  kyaml/fn/framework/patch.go
  kyaml/fn/framework/patch_test.go
  kyaml/fn/framework/patchtestdata/annotationselector/config.yaml
  kyaml/fn/framework/patchtestdata/annotationselector/expected.yaml
  kyaml/fn/framework/patchtestdata/annotationselector/input.yaml
  kyaml/fn/framework/patchtestdata/apiversionselector/config.yaml
  kyaml/fn/framework/patchtestdata/apiversionselector/expected.yaml
  kyaml/fn/framework/patchtestdata/apiversionselector/input.yaml
  kyaml/fn/framework/patchtestdata/filterselector/config.yaml
  kyaml/fn/framework/patchtestdata/filterselector/expected.yaml
  kyaml/fn/framework/patchtestdata/filterselector/input.yaml
  kyaml/fn/framework/patchtestdata/kindselector/config.yaml
  kyaml/fn/framework/patchtestdata/kindselector/expected.yaml
  kyaml/fn/framework/patchtestdata/kindselector/input.yaml
  kyaml/fn/framework/patchtestdata/labelselector/config.yaml
  kyaml/fn/framework/patchtestdata/labelselector/expected.yaml
  kyaml/fn/framework/patchtestdata/labelselector/input.yaml
  kyaml/fn/framework/patchtestdata/longlistpreprocess/config.yaml
  kyaml/fn/framework/patchtestdata/longlistpreprocess/expected.yaml
  kyaml/fn/framework/patchtestdata/longlistpreprocess/input.yaml
  kyaml/fn/framework/patchtestdata/nameselector/config.yaml
  kyaml/fn/framework/patchtestdata/nameselector/expected.yaml
  kyaml/fn/framework/patchtestdata/nameselector/input.yaml
  kyaml/fn/framework/patchtestdata/namespaceselector/config.yaml
  kyaml/fn/framework/patchtestdata/namespaceselector/expected.yaml
  kyaml/fn/framework/patchtestdata/namespaceselector/input.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3242 Gather and use some of the kyaml constants.
  kyaml/yaml/const.go
  kyaml/yaml/kfns.go
  kyaml/yaml/kfns_test.go
  kyaml/yaml/rnode.go
Labels: approved, cncf-cla: yes, size/M

#3219 Refactor open api
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/runner/runner.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
  kyaml/setters2/add.go
  kyaml/setters2/delete.go
  kyaml/setters2/example_test.go
  kyaml/setters2/list.go
  kyaml/setters2/list_test.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/deletecreator_test.go
  kyaml/setters2/settersutil/deletercreator.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/fieldsetter_test.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/util.go
  kyaml/setters2/util_test.go
  kyaml/setters2/walk.go
  kyaml/yaml/walk/map.go
  kyaml/yaml/walk/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3239 Function framework features
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/frameworktestutil/frameworktestutil.go
  kyaml/fn/framework/patch.go
  kyaml/fn/framework/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3247 Secrets and ConfigMaps with string data in kyaml
  api/go.mod
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  kyaml/yaml/kfns.go
  kyaml/yaml/kfns_test.go
Labels: approved, cncf-cla: yes, size/XL

#3238 fix invalid managed-by label value
  api/krusty/kustomizer.go
  api/provenance/provenance.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3240 Add command to list builtin plugins
  api/konfig/plugins.go
  kustomize/internal/commands/edit/all.go
  kustomize/internal/commands/edit/listbuiltin/listbuiltin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3211 modify pluginator to support convert builtin plugin to krm function
  cmd/pluginator/Makefile
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  cmd/pluginator/internal/builtinplugin/builtinplugin.go
  cmd/pluginator/internal/builtinplugin/plugintype_string.go
  cmd/pluginator/internal/krmfunction/cmd.go
  cmd/pluginator/internal/krmfunction/converter.go
  cmd/pluginator/internal/krmfunction/converter_test.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/fakeplugin.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/go.mod.src
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
  cmd/pluginator/main.go
  hack/generateBuiltinKrmFunctions.sh
Labels: approved, cncf-cla: yes, size/XXL

#3253 Fix test against examples
  examples/remoteBuild.md
Labels: cncf-cla: yes, lgtm, size/XS

#3252 Update release notes generation
  releasing/cloudbuild.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3250 Function framework support for patching containers
  kyaml/fn/framework/containers.go
  kyaml/fn/framework/example_test.go
  kyaml/kio/byteio_reader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3255 fix rnode string format converted from resmap
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3258 Automated go.sum change.
  api/internal/crawl/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3256 update module api version in wrapper
  cmd/pluginator/internal/krmfunction/converter_test.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/go.mod.src
Labels: approved, cncf-cla: yes, size/S

#3251 [KRM function converter] Get plugin config from data field
  cmd/pluginator/internal/krmfunction/converter_test.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
Labels: approved, cncf-cla: yes, size/M

#3259 fn/framework support for reading from stdin in standalone
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/frameworktestutil/frameworktestutil.go
  kyaml/fn/framework/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3261 Use DepProvider in tests to access kyaml impls.
  api/filters/nameref/nameref_test.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/crawl/doc/doc.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader_test.go
  api/internal/plugins/utils/utils_test.go
  api/internal/target/kusttarget_test.go
  api/internal/target/maker_test.go
  api/konfig/general.go
  api/krusty/kustomizer.go
  api/provider/depprovider.go
  api/resmap/reswrangler_test.go
  api/resource/resource_test.go
  api/testutils/kusttest/harnessenhanced.go
  api/testutils/resmaptest/rmbuilder.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
  kustomize/internal/commands/build/flagEnableKyaml.go
  kustomize/internal/commands/commands.go
  kustomize/internal/commands/create/create_test.go
Labels: approved, cncf-cla: yes, size/L

#3257 Secrets and ConfigMaps with binary data in kyaml
  api/internal/generators/configmap.go
  api/internal/generators/configmap_test.go
  api/internal/generators/secret.go
  api/internal/generators/secret_test.go
  api/internal/generators/utils.go
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  kyaml/yaml/const.go
  kyaml/yaml/kfns.go
  kyaml/yaml/kfns_test.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, size/XXL

#3263 In some tests, replace reflection with yaml compare.
  api/internal/plugins/utils/utils_test.go
  api/internal/target/kusttarget_test.go
  api/resmap/factory_test.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/factory_test.go
  api/resource/resource.go
Labels: approved, cncf-cla: yes, size/L

#3266 Consistently prefix make targets with clean, generate, build.
  Makefile
Labels: approved, cncf-cla: yes, size/S

#3267 Add generated code.
  api/types/builtinpluginloadingoptions_string.go
Labels: cncf-cla: yes

#3270 Improved fn framework support for patching
  kyaml/fn/framework/containers.go
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3272 Add more tests around yaml parsing.
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  api/resource/factory.go
  api/resource/factory_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3275 Start a gitattributes file.
  .gitattributes
Labels: cncf-cla: yes

#3273 Re-enable multi-module check
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3277 More RNode setters and WNode delegation
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
  api/resmap/reswrangler_test.go
  api/resource/factory_test.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3281 update Go version to 1.15
  api/go.mod
  api/internal/crawl/go.mod
  cmd/config/go.mod
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.mod
  cmd/mdtogo/go.mod
  cmd/pluginator/go.mod
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/go.mod.src
  functions/examples/application-cr/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-resource-requests/image/go.mod
  hack/go.mod
  kustomize/go.mod
  kyaml/go.mod
  kyaml/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/chartinflator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/gogetter/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/replacementtransformer/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
  releasing/releasing/go.mod
  releasing/releasing/modulemeta_test.go
  site/go.mod
Labels: approved, cncf-cla: yes, size/L

#3285 Add labels to selector test.
  api/resmap/selector_test.go
Labels: approved, cncf-cla: yes, size/M

#3283 Add git and openssh in docker image
  kustomize.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3279 Add label and annotation selector code.
  api/internal/wrappy/wnode.go
  kyaml/Makefile
  kyaml/yaml/internal/k8sgen/doc.go
  kyaml/yaml/internal/k8sgen/generator/go.mod
  kyaml/yaml/internal/k8sgen/generator/main.go
  kyaml/yaml/internal/k8sgen/pkg/labels/labels.go
  kyaml/yaml/internal/k8sgen/pkg/labels/selector.go
  kyaml/yaml/internal/k8sgen/pkg/labels/zz_generated.deepcopy.go
  kyaml/yaml/internal/k8sgen/pkg/selection/operator.go
  kyaml/yaml/internal/k8sgen/pkg/util/errors/errors.go
  kyaml/yaml/internal/k8sgen/pkg/util/sets/empty.go
  kyaml/yaml/internal/k8sgen/pkg/util/sets/string.go
  kyaml/yaml/internal/k8sgen/pkg/util/validation/field/errors.go
  kyaml/yaml/internal/k8sgen/pkg/util/validation/field/path.go
  kyaml/yaml/internal/k8sgen/pkg/util/validation/validation.go
  kyaml/yaml/merge2/smpdirective_string.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3290 Add resource id set.
  api/resource/idset.go
  api/resource/idset_test.go
Labels: cncf-cla: yes

#3282 Fn framework utilities for parsing templates from directories
  kyaml/fn/framework/example2/Dockerfile
  kyaml/fn/framework/example2/data/container-patches/container.template.yaml
  kyaml/fn/framework/example2/data/patches/patch.template.yaml
  kyaml/fn/framework/example2/data/templates/deploy.template.yaml
  kyaml/fn/framework/example2/doc.go
  kyaml/fn/framework/example2/example_test.go
  kyaml/fn/framework/example2/main.go
  kyaml/fn/framework/example2/pkged.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/pkger.go
  kyaml/go.mod
  kyaml/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3291 Patchtransformers - drop copied code, improve deletion handling.
  api/builtins/PatchStrategicMergeTransformer.go
  api/builtins/PatchTransformer.go
  api/internal/target/kusttarget_configplugin.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resource/resource.go
  api/resource/resource_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XL
