Repository kubernetes-sigs/kustomize, pull requests merged in 2020-03, with the labels that each got.

#2245 Use OpenAPI when 3-way merging resources
  kyaml/fieldmeta/fieldmeta.go
  kyaml/openapi/openapi.go
  kyaml/yaml/merge2/element_test.go
  kyaml/yaml/merge2/list_test.go
  kyaml/yaml/merge2/map_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/merge2_old_test.go
  kyaml/yaml/merge2/merge2_test.go
  kyaml/yaml/merge2/scalar_test.go
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/merge3/list_test.go
  kyaml/yaml/merge3/map_test.go
  kyaml/yaml/merge3/merge3.go
  kyaml/yaml/merge3/merge3_test.go
  kyaml/yaml/merge3/scalar_test.go
  kyaml/yaml/merge3/visitor.go
  kyaml/yaml/schema/schema.go
  kyaml/yaml/types.go
  kyaml/yaml/walk/associative_sequence.go
  kyaml/yaml/walk/map.go
  kyaml/yaml/walk/nonassociative_sequence.go
  kyaml/yaml/walk/scalar.go
  kyaml/yaml/walk/visitor.go
  kyaml/yaml/walk/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2251 Use sigs.k8s.io/Application type instead of go template
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/application-cr/image/main.go
  functions/examples/application-cr/image/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2253 #2252: convert tests to exercise openapi and inference
  kyaml/yaml/merge2/element_test.go
  kyaml/yaml/merge2/merge2_test.go
  kyaml/yaml/merge3/element_test.go
  kyaml/yaml/merge3/merge3_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2249 Allow braces in image tag name (api)
  api/builtins/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2258 increment api patch release to 0.3.3
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2261 release kyaml cmd/config 1.1
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm

#2182 Enable specifying GeneratorOptions per resource
  api/internal/k8sdeps/configmapandsecret/configmapfactory.go
  api/internal/k8sdeps/configmapandsecret/configmapfactory_test.go
  api/internal/k8sdeps/configmapandsecret/factory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory.go
  api/internal/k8sdeps/configmapandsecret/secretfactory_test.go
  api/types/generatorargs.go
  docs/fields.md
  docs/plugins/builtins.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#2167 Allow loading file from http
  api/internal/target/kusttarget.go
  api/krusty/accumulation_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  examples/loadHttp.md
  examples/loadHttp/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#2169 Replace git cloner with go getter to support various target
  api/go.mod
  api/go.sum
  api/internal/git/repospec.go
  api/krusty/kustomizer_test.go
  api/loader/fileloader.go
  api/loader/loader.go
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2264 Revert "Merge pull request #2169 from yujunz/loader/go-getter"
  api/go.mod
  api/go.sum
  api/internal/git/repospec.go
  api/krusty/kustomizer_test.go
  api/loader/fileloader.go
  api/loader/loader.go
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2267 Starlark Filter support
  cmd/config/go.sum
  kyaml/comments/comments.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/starlark/doc.go
  kyaml/starlark/example_test.go
  kyaml/starlark/starlark.go
  kyaml/starlark/starlark_test.go
  kyaml/yaml/walk/associative_sequence.go
  kyaml/yaml/walk/map.go
  kyaml/yaml/walk/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2215 #2214 : Variable reference does not work on the nfs.server
  api/konfig/builtinpluginconsts/varreference.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2280 Exlude golangci-lint v1.24.0 which breaks CI
  Makefile
  hack/go.mod
  hack/go.sum
  travis/check-go-mod.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#2265 Setters: support for setting string list fields
  cmd/config/internal/commands/cmdlistsetters.go
  cmd/config/internal/commands/cmdset.go
  kyaml/fieldmeta/fieldmeta.go
  kyaml/openapi/openapi.go
  kyaml/setters2/add.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/types.go
  kyaml/setters2/walk.go
  kyaml/yaml/compatibility.go
  kyaml/yaml/kfns.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2283 Add FieldSetter filter
  kyaml/setters2/settersutil/fieldsetter.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#2257 fix misspellings
  README.md
  api/builtins/NamespaceTransformer.go
  api/internal/crawl/README.md
  api/internal/crawl/config/elastic/esbackup.yaml
  api/internal/crawl/search_cmds/transformer.md
  docs/FAQ.md
  docs/eschewedFeatures.md
  docs/fields.md
  docs/glossary.md
  docs/plugins/README.md
  docs/v2.1.0_changelog.md
  docs/versioningPolicy.md
  examples/inlinePatch.md
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2284 Generate network config
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2287 Skip writing to unedited files
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/fieldsetter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2291 kyaml release 0.1.2
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2278 Support various target and resource with go-getter
  api/go.mod
  api/go.sum
  api/krusty/kustomizer_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  api/loader/getter.go
  api/loader/loader.go
  examples/remoteBuild.md
  kustomize/go.sum
  plugin/builtin/imagetagtransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2295 refactor function filters
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2286 Update inventory_object.md
  docs/inventory_object.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2255 Updated README to use 'bases' instead of 'resources' in overlays examples
  examples/helloWorld/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2247 print to stderr when encoutnering errors
  functions/examples/injection-tshirt-sizes/image/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2296 Refactor function code and allow for using starlark based filters
  cmd/config/go.sum
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  kyaml/kio/filters/container.go
  kyaml/kio/filters/container_test.go
  kyaml/kio/filters/functiontypes.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
  kyaml/starlark/starlark.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2288 Kustomize API: implement a FieldSpec transformer using kyaml libraries
  api/builtins/NamespaceTransformer.go
  api/filters/filtersutil/filtersutil.go
  api/filters/filtersutil/filtersutil_test.go
  api/filters/fsslice/doc.go
  api/filters/fsslice/example_test.go
  api/filters/fsslice/fieldspec_filter.go
  api/filters/fsslice/fsslice.go
  api/filters/fsslice/fsslice_test.go
  api/filters/namespace/doc.go
  api/filters/namespace/example_test.go
  api/filters/namespace/namespace.go
  api/filters/namespace/namespace_test.go
  api/go.mod
  api/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2298 Add annotations filter based on kyaml libraries
  api/builtins/AnnotationsTransformer.go
  api/filters/annotations/annotations.go
  api/filters/annotations/annotations_test.go
  api/filters/annotations/doc.go
  api/filters/annotations/example_test.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
Labels: cncf-cla: yes, lgtm, size/L

#2297 Utilities for working with map[string]interface{} + yaml.Node
  kyaml/filtersutil/doc.go
  kyaml/filtersutil/example_test.go
  kyaml/filtersutil/filtersutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2302 Update kyaml version
  releasing/VERSIONS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2303 Move filltersutil serialization to kyaml
  api/builtins/AnnotationsTransformer.go
  api/builtins/NamespaceTransformer.go
  api/filters/filtersutil/filtersutil.go
  api/filters/filtersutil/filtersutil_test.go
  api/go.mod
  api/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2309 config: update docs to use list-setters.
  cmd/config/docs/commands/list-setters.md
  cmd/config/docs/commands/set.md
  cmd/config/internal/generateddocs/commands/docs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2307 Rearrange comments for yaml/V3 bug fix
  kyaml/kio/byteio_writer.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/filters/fmtr_test.go
  kyaml/yaml/serialization.go
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2304 Fix argument name to provide digest to an image
  kustomize/internal/commands/edit/set/setimage.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2305 NamespaceTransformer tests
  api/builtins/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2311 kyaml implementation of the PrefixSuffixTransformer
  api/filters/namespace/namespace.go
  api/filters/prefixsuffix/doc.go
  api/filters/prefixsuffix/example_test.go
  api/filters/prefixsuffix/prefixsuffix.go
  api/filters/prefixsuffix/prefixsuffix_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
