Repository kubernetes-sigs/kustomize, pull requests merged in 2021-05, with the labels that each got.

#3855 When releasing, allow certain replacements.
  cmd/gorepomod/internal/arguments/args.go
  cmd/gorepomod/internal/repo/manager.go
  cmd/gorepomod/internal/utils/utils.go
  cmd/gorepomod/main.go
Labels: cncf-cla: yes

#3857 Pin to kyaml/v0.10.18
  api/builtins/PatchTransformer.go
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/replacementtransformer/go.mod
Labels: approved, cncf-cla: yes, size/M

#3858 In module lists, handle allowed replacements.
  cmd/gorepomod/internal/arguments/args.go
  cmd/gorepomod/internal/misc/interfaces.go
  cmd/gorepomod/internal/mod/module.go
  cmd/gorepomod/internal/repo/manager.go
  cmd/gorepomod/internal/repo/managerfactory.go
  cmd/gorepomod/main.go
Labels: cncf-cla: yes

#3859 Pin to cmd/config v0.9.11
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3862 Update plugin go.mod, go.sum w/r to kyaml.
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
Labels: approved, cncf-cla: yes, size/M

#3864 Run e2e tests against 4.1.2
  Makefile
  hack/testExamplesAgainstKustomize.sh
Labels: approved, cncf-cla: yes, size/S

#3838 A last-mile helm example, with namespace and prefix
  api/krusty/helmchartinflationgenerator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3854 update openapi fetch command
  kustomize/commands/openapi/fetch/fetch.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3863 Simplify gvk, speed up cluster-scoped checks.
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
  api/filters/fieldspec/gvk.go
  api/filters/fieldspec/gvk_test.go
  api/filters/nameref/nameref.go
  api/filters/namespace/namespace.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/resaccumulator.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/resource.go
  api/resource/resource_test.go
  kustomize/commands/build/writer.go
  kyaml/openapi/openapi.go
  kyaml/resid/gvk.go
  kyaml/resid/gvk_test.go
  kyaml/resid/resid.go
  kyaml/resid/resid_test.go
  kyaml/yaml/rnode.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3870 add helm fields to ordered fields
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3874 Add a dependency debugging directory.
  cmd/depprobcheck/README.md
  cmd/depprobcheck/go.mod
  cmd/depprobcheck/go.sum
  cmd/depprobcheck/main.go
Labels: approved, cncf-cla: yes, size/XL

#3880 Make result in function filter public
  api/krusty/fnplugin_test.go
  cmd/config/internal/commands/tree_test.go
  kyaml/fn/runtime/runtimeutil/runtimeutil.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3832 Add ability to set target namespace for helm chart template
  api/types/helmchartargs.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3888 Remove delegation to RNode in Resource
  api/builtins/NamespaceTransformer.go
  api/filters/fieldspec/fieldspec.go
  api/filters/nameref/nameref.go
  api/filters/replacement/replacement.go
  api/internal/accumulator/resaccumulator.go
  api/internal/plugins/utils/utils.go
  api/internal/plugins/utils/utils_test.go
  api/internal/target/kusttarget.go
  api/resmap/reswrangler.go
  api/resource/factory.go
  api/resource/resource.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3893 use assert statements for kustomize edit tests
  kustomize/commands/edit/add/addbase_test.go
  kustomize/commands/edit/add/addcomponent_test.go
  kustomize/commands/edit/add/addmetadata_test.go
  kustomize/commands/edit/add/addpatch_test.go
  kustomize/commands/edit/add/addresource_test.go
  kustomize/commands/edit/add/addtransformer_test.go
  kustomize/commands/edit/add/configmap_test.go
  kustomize/commands/edit/add/flagsandargs_test.go
  kustomize/commands/edit/add/secret_test.go
  kustomize/commands/edit/fix/fix_test.go
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3889 Fix api tests on MacOS
  api/testutils/kusttest/harnessenhanced.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#3900 URL based configuration for git exec timeouts and git submodule cloning
  api/internal/git/cloner.go
  api/internal/git/gitrunner.go
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3903 Fix repospec test
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
Labels: approved, cncf-cla: yes, size/L

#3905 Fix makefile install-tools for Go 1.16
  Makefile
  hack/go.mod
  hack/go.sum
Labels: approved, cncf-cla: yes, size/L

#3906 Pin to kyaml v0.10.20
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
Labels: approved, cncf-cla: yes, size/M

#3907 Fix go.mod in plugins.
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
Labels: cncf-cla: yes

#3908 Pin to cmd/config v0.9.12
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3910 No more plugin pinning.
  cmd/gorepomod/internal/arguments/args.go
Labels: cncf-cla: yes

#3909 Pin to api v0.8.10
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3920 Back to development mode; unpin the modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3921 Consolidate scripts into k8s-traditional hack dir.
  .github/workflows/go.yml
  Makefile
  api/filesys/doc.go
  api/filesys/filesystem.go
  api/filters/doc.go
  api/internal/plugins/doc.go
  api/konfig/doc.go
  examples/README.md
  examples/zh/README.md
  hack/Invoke-PreCommit.ps1
  hack/check-go-mod.sh
  hack/check-multi-module.sh
  hack/kyaml-pre-commit.sh
Labels: approved, cncf-cla: yes, size/M

#3917 Cleanup tempfiles
  kyaml/kio/filters/fmtr_test.go
  kyaml/runfn/runfn_test.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#3911 Handle errors
  api/krusty/kustomizer.go
Labels: cncf-cla: yes, lgtm, size/S

#3930 Demonstrate issue 3929
  api/krusty/multiplepatch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3914 Gke service account generator
  Makefile
  api/builtins/IAMPolicyGenerator.go
  api/filters/iampolicygenerator/doc.go
  api/filters/iampolicygenerator/example_test.go
  api/filters/iampolicygenerator/iampolicygenerator.go
  api/filters/iampolicygenerator/iampolicygenerator_test.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/krusty/iampolicygenerator_test.go
  api/types/genargs.go
  api/types/iampolicygenerator.go
  plugin/builtin/iampolicygenerator/IAMPolicyGenerator.go
  plugin/builtin/iampolicygenerator/go.mod
  plugin/builtin/iampolicygenerator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3898 Add includeCRDs Field to HelmChart
  api/builtins/HelmChartInflationGenerator.go
  api/types/helmchartargs.go
  examples/chart.md
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
  plugin/builtin/helmchartinflationgenerator/include_crds_testdata.txt
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L
