Repository kubernetes-sigs/kustomize, pull requests merged in 2021-10, with the labels that each got.

#4202 Updated README to use 'resources' instead of 'bases' in overlays example.
  examples/helloWorld/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4210 fix issue with getting openapi schema from components
  Makefile
  api/krusty/openapicustomschema_test.go
  api/krusty/testdata/openshiftschema.json
  kyaml/openapi/openapi.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4249 bump ResourceList from v1alpha1 to v1
  cmd/config/internal/commands/cmdwrap_test.go
  cmd/config/internal/commands/cmdxargs_test.go
  cmd/config/internal/commands/sink_test.go
  cmd/config/internal/commands/source_test.go
  cmd/pluginator/internal/krmfunction/converter_test.go
  functions/examples/application-cr/image/main_test.go
  kyaml/fn/framework/command/example_test.go
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/processors_test.go
  kyaml/fn/framework/testdata/validation/error/input.yaml
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_readwriter_test.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/kio_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4253 provide utility helpers for preserving internal annotations
  api/resource/resource.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/sink.go
  kyaml/kio/kioutil/kioutil.go
  kyaml/kio/kioutil/kioutil_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4248 [breaking] update results field of ResourceList to implement function spec v1
  kyaml/fn/framework/command/example_test.go
  kyaml/fn/framework/framework.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/result.go
Labels: cncf-cla: yes, size/L, approved, lgtm
