Repository kubernetes-sigs/kustomize, pull requests merged in 2021-08, with the labels that each got.

#4088 replace genargs with two separate annotations
  api/internal/plugins/utils/utils.go
  api/internal/utils/makeResIds.go
  api/resource/factory.go
  api/resource/resource.go
  api/resource/resource_test.go
  api/types/genargs.go
  api/types/genargs_test.go
  plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4085 Add a filesys.FileSystem interface to kio.LocalPackageReader
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4102 Kyaml anchor failure test.
  kyaml/kio/byteio_reader_test.go
  kyaml/kio/byteio_readwriter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4087 Avoid aliasing in fsnode by forcing copies for file contents
  kyaml/filesys/fsnode.go
  kyaml/filesys/fsnode_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4110 Update openapi updater scripts
  kyaml/openapi/Makefile
  kyaml/openapi/README.md
  kyaml/openapi/scripts/fetchSchemaFromCluster.sh
Labels: cncf-cla: yes, size/M, approved

#4073 Feature: Add edit set annotation
  kustomize/commands/edit/set/all.go
  kustomize/commands/edit/set/setannotation.go
  kustomize/commands/edit/set/setannotation_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4113 Enable fn framework container patches to work with more kinds
  kyaml/fn/framework/patch.go
  kyaml/fn/framework/processors_test.go
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/cron_job.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/daemon_set.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/deployment.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/job.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/pod.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/pod_template.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/replica_set.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/replication_controller.template.yaml
  kyaml/fn/framework/testdata/template-processor/templates/container-sources/stateful_set.template.yaml
  kyaml/openapi/kubernetesapi/openapiinfo.go
  kyaml/openapi/kubernetesapi/v1212/swagger.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4122 support for darwin and linux
  Makefile
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash, ok-to-test

#4065 option for origin data as annotation
  api/internal/target/kusttarget.go
  api/internal/target/vars_test.go
  api/internal/utils/annotations.go
  api/internal/utils/makeResIds.go
  api/krusty/buildmetadata_test.go
  api/krusty/remoteload_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resource/origin.go
  api/resource/origin_test.go
  api/types/kustomization.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#4094 Add unit tests to cover existing behavior of three way merge and strategic merge patch
  api/resource/resource_test.go
  kyaml/yaml/merge3/element_test.go
Labels: cncf-cla: yes, size/L, lgtm

#4086 Add FileSystem interface to LocalPackageWriter
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_writer.go
  kyaml/kio/pkgio_writer_test.go
  kyaml/kio/testing.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4125 exec function working dir is the kustomization that referenced it
  api/internal/plugins/fnplugin/fnplugin.go
  api/internal/plugins/loader/loader.go
  api/internal/target/kusttarget.go
  api/krusty/fnplugin_test.go
  api/krusty/fnplugin_test/fnexectest.sh
  api/types/pluginrestrictions.go
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/commands/run_test.go
  kyaml/fn/runtime/exec/exec.go
  kyaml/runfn/runfn.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4132 move check for working dir for exec functions
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/exec/exec.go
  kyaml/fn/runtime/exec/exec_test.go
  kyaml/runfn/runfn.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4134 Preserve field order: Add test for null value
  kyaml/order/syncorder_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#4114 Add YAML anchor/alias expansion.
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  kyaml/kio/byteio_reader_test.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: cncf-cla: yes, size/L, approved

#4137 Pin to kyaml v0.11.1
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
Labels: cncf-cla: yes, size/S, approved, lgtm

#4138 Pin to cmd/config v0.10.0
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4139 Pin to api v0.9.0
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#4141 Back to development mode; unpin the modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#4143 Release updates
  Makefile
  cmd/gorepomod/internal/git/runner.go
  releasing/README.md
  releasing/helpers.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#4128 Introduce in-repo proposal process
  proposals/00-00-template.md
  proposals/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#4157 Return a meaningful message if we hit the rate-limiter of GitHub
  hack/install_kustomize.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4158 Revert "Return a meaningful message if we hit the rate-limiter of GitHub"
  hack/install_kustomize.sh
Labels: cncf-cla: yes, size/XS, approved
