Repository kubernetes-sigs/kustomize, pull requests merged in 2021-01, with the labels that each got.

#3416 Updated link to Kustomize plugins documentation
  docs/plugins/README.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3425 Add test for issue 3424
  api/krusty/issue3424_test.go
Labels: approved, cncf-cla: yes, size/M

#3427 Move plugin lister to avoid import cycle.
  api/konfig/plugins.go
  api/krusty/options.go
  kustomize/internal/commands/edit/listbuiltin/listbuiltin.go
Labels: approved, cncf-cla: yes, size/M

#3428 Confine calls to ApplyToJSON.
  api/builtins/AnnotationsTransformer.go
  api/builtins/ImageTagTransformer.go
  api/builtins/LabelTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchJson6902Transformer.go
  api/builtins/PatchTransformer.go
  api/builtins/PrefixSuffixTransformer.go
  api/builtins/ReplicaCountTransformer.go
  api/builtins/ValueAddTransformer.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/refvartransformer.go
  api/internal/wrappy/wnode.go
  api/resource/resource.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/valueaddtransformer/ValueAddTransformer.go
  plugin/builtin/valueaddtransformer/go.mod
Labels: approved, cncf-cla: yes, size/L

#3432 Short circuit anno/label transformer for performance.
  api/builtins/AnnotationsTransformer.go
  api/builtins/LabelTransformer.go
  api/internal/accumulator/resaccumulator.go
  api/krusty/variableref_test.go
  kyaml/yaml/fns.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
Labels: approved, cncf-cla: yes, size/M

#3433 Improve handling of empty resource maps.
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
  api/resmap/reswrangler_test.go
  api/resource/resource.go
  kyaml/go.mod
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, size/M

#3434 Reduce complexity in NameReferenceTransformer.
  api/filters/nameref/nameref.go
  api/filters/nameref/nameref_test.go
  api/internal/accumulator/namereferencetransformer.go
Labels: approved, cncf-cla: yes, size/L

#3436 Add var ref replacement tests and more doc.
  api/filters/nameref/nameref.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/refvartransformer.go
  api/internal/accumulator/resaccumulator.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, size/L

#3437 In kyaml, loosen interpretation of string node and add tests.
  kyaml/yaml/fns_test.go
  kyaml/yaml/types.go
  kyaml/yaml/types_test.go
Labels: approved, cncf-cla: yes, size/M

#3431 keep \n in the end of resource yaml
  api/krusty/configmaps_test.go
  kyaml/kio/byteio_reader.go
Labels: approved, cncf-cla: yes, size/M

#3439 Clarify var-related error message.
  api/filters/refvar/refvar.go
  api/filters/refvar/refvar_test.go
Labels: cncf-cla: yes

#3438 Fix 3424 by avoiding a JSON round trip
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/internal/accumulator/refvartransformer_test.go
  api/krusty/issue3424_test.go
  api/resource/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3372 Refactor resource to use annotations in the yaml instead of fields in resource struct
  api/builtins/HashTransformer.go
  api/builtins/NamespaceTransformer.go
  api/builtins/PatchTransformer.go
  api/builtins/PrefixSuffixTransformer.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/target/kusttarget_test.go
  api/krusty/kustomizer.go
  api/krusty/transformerplugin_test.go
  api/resmap/factory_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/factory.go
  api/resource/resource.go
  api/resource/resource_test.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer_test.go
  plugin/builtin/labeltransformer/LabelTransformer_test.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer_test.go
  plugin/someteam.example.com/v1/sedtransformer/SedTransformer_test.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer_test.go
Labels: approved, cncf-cla: yes, size/XL

#3445 [kio] Unwrap ResourceList with a functionConfig but no items
  kyaml/kio/byteio_reader.go
  kyaml/kio/byteio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3450 Add a test that only loads an annotated resource.
  api/krusty/basic_io_test.go
Labels: approved, cncf-cla: yes, size/M

#3453 fix GetFieldValue cannot handle slice index
  api/internal/wrappy/wnode.go
  api/krusty/namespaces_test.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3454 Add more tests and explain some quoting behavior.
  api/internal/target/kusttarget_test.go
  api/krusty/basic_io_test.go
  api/krusty/configmaps_test.go
  api/krusty/kustomizer.go
  api/krusty/variableref_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/resource.go
  api/testutils/kusttest/harness.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3441 Update name references by checking both the original and current namespaces
  api/filters/nameref/nameref.go
  api/krusty/namespaces_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3460 Fix 3412, retaining quotes in configmap data fields
  api/filters/annotations/annotations.go
  api/filters/filtersutil/filtersutil.go
  api/filters/labels/labels.go
  api/internal/generators/configmap.go
  api/internal/generators/secret.go
  api/internal/generators/utils.go
  api/krusty/configmaps_test.go
  kyaml/yaml/datamap.go
  kyaml/yaml/datamap_test.go
  kyaml/yaml/rnode.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3461 Add another test covering fix of 3412
  api/krusty/configmaps_test.go
Labels: approved, cncf-cla: yes, size/M

#3465 Add test covering pod disruption budget treatment.
  api/krusty/poddisruptionbudget_test.go
Labels: approved, cncf-cla: yes, size/M

#3467 Add calvin duplicator example plugin.
  plugin/someteam.example.com/v1/calvinduplicator/CalvinDuplicator.go
  plugin/someteam.example.com/v1/calvinduplicator/CalvinDuplicator_test.go
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
Labels: approved, cncf-cla: yes, size/XL

#3466 Rename id annotations to build annotations.
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/target/kusttarget_test.go
  api/internal/wrappy/factory.go
  api/k8sdeps/kunstruct/factory.go
  api/konfig/general.go
  api/krusty/kustomizer.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/resource.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
Labels: approved, cncf-cla: yes, size/M

#3462 $patch: delete of not existing elements
  api/krusty/patchdelete_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3469 Always quote non-string values in labels and annotations
  api/filters/annotations/example_test.go
  api/krusty/basic_io_test.go
  api/krusty/fnplugin_test.go
  api/krusty/variableref_test.go
  kyaml/yaml/datamap.go
  kyaml/yaml/rnode.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3470 Annotate code with decisions on issue 3304 in kyaml conversion
  api/internal/accumulator/refvartransformer_test.go
  api/krusty/configmaps_test.go
  api/krusty/multiplepatch_test.go
  api/krusty/poddisruptionbudget_test.go
  api/krusty/variableref_test.go
  api/resmap/factory_test.go
  api/resource/factory_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
Labels: approved, cncf-cla: yes, size/L

#3471 Merge expansion package into refvar package.
  api/filters/refvar/expand.go
  api/filters/refvar/expand_test.go
  api/filters/refvar/refvar.go
  api/filters/refvar/refvar_test.go
  api/go.sum
  api/internal/accumulator/refvartransformer.go
Labels: approved, cncf-cla: yes, size/M

#3472 Reproduce issue #3449
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes

#3473 Fix unfiled bug in port replacement where ports were being quoted.
  api/filters/refvar/doc.go
  api/filters/refvar/expand.go
  api/filters/refvar/expand_test.go
  api/filters/refvar/refvar.go
  api/filters/refvar/refvar_test.go
  api/go.sum
  api/internal/accumulator/refvartransformer.go
  api/internal/wrappy/wnode.go
  api/krusty/variableref_test.go
Labels: approved, cncf-cla: yes, size/L

#3474 Pin to kyaml v0.10.6 and cli-utils v0.22.4
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, size/M

#3475 Pin to cmd/config v0.8.8
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3476 Pin to api v0.7.2
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
  plugin/untested/v1/replacementtransformer/go.mod
  plugin/untested/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/L

#3477 Back to development mode; unpin the modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
  plugin/untested/v1/replacementtransformer/go.mod
  plugin/untested/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/L

#3478 Test examples against v3.9.2 and v3.8.9
  Makefile
Labels: approved, cncf-cla: yes, size/S

#3494 [kyaml] Framework/TemplateCommand usability improvements
  kyaml/fn/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3503 Add support for setting new tag while preserving the current name
  kustomize/internal/commands/edit/set/setimage.go
  kustomize/internal/commands/edit/set/setimage_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#3500 support anchor in filedspec
  api/filters/fieldspec/fieldspec.go
  api/krusty/accumulation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3496 Use `/usr/bin/env bash` instead of `/bin/bash` in scripts
  Makefile
  scripts/check-go-mod.sh
  scripts/check-multi-module.sh
  scripts/kyaml-pre-commit.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3499 Fix wrong Validator dir
  plugin/someteam.example.com/v1/validator/Validator
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3491 add error message for AsYAML
  api/resmap/reswrangler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3495 Add support to install kustomize to specified directory
  hack/install_kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3484 Demonstrate issue #3377 is fixed.
  api/krusty/issue3377_test.go
Labels: approved, cncf-cla: yes, size/L

#3506 $patch:delete should not add elements when element is not found
  api/builtins/PatchStrategicMergeTransformer.go
  api/krusty/patchdelete_test.go
  kyaml/yaml/merge2/merge2.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3483 Bug: configMapRefs in patches are not resolved correctly in diamond structure
  api/krusty/diamondpatchref_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L

#3498 Update README.md
  examples/springboot/README.md
Labels: cncf-cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/XS

#3512 Add test for issue 3489 and improve error messages.
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
  api/filters/nameref/nameref.go
  api/filters/nameref/nameref_test.go
  api/filters/refvar/refvar_test.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  api/krusty/namereference_test.go
  api/krusty/resourceconflict_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3514 Add test for ports issue #3513
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3517 Expose smart path splitter as a utility.
  api/filters/fieldspec/fieldspec.go
  api/internal/utils/pathsplitter.go
  api/internal/utils/pathsplitter_test.go
  api/types/fieldspec.go
  api/types/fieldspec_test.go
Labels: approved, cncf-cla: yes, size/L

#3518 Improve name reference transformer testing.
  api/filters/nameref/nameref.go
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/accumulator/loadconfigfromcrds_test.go
  api/internal/accumulator/namereferencetransformer.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/plugins/builtinconfig/namebackreferences.go
  api/internal/plugins/builtinconfig/namebackreferences_test.go
  api/internal/plugins/builtinconfig/transformerconfig_test.go
  api/internal/wrappy/wnode_test.go
  api/konfig/builtinpluginconsts/namereference.go
  api/krusty/namespaces_test.go
  api/resmap/reswrangler.go
  api/resource/resource.go
Labels: approved, cncf-cla: yes, size/XL
