Repository kubernetes-sigs/kustomize, pull requests merged in 2021-06, with the labels that each got.

#3940 add an option to include local configs
  api/resource/factory.go
  plugin/builtin/iampolicygenerator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#3925 Fully specify KRM Functions Spec and graduate it to v1.
  cmd/config/docs/api-conventions/config-io.md
  cmd/config/docs/api-conventions/functions-spec.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3955 Check for empty GKNN when formatting results
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/result.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3931 Fix issues with replacements
  api/filters/fieldspec/fieldspec.go
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/internal/utils/pathsplitter.go
  api/internal/utils/pathsplitter_test.go
Labels: approved, cncf-cla: yes, size/L

#3939 [kyaml] Improvements to frameworktestutil
  kyaml/fn/framework/example_test.go
  kyaml/fn/framework/frameworktestutil/frameworktestutil.go
  kyaml/fn/framework/processors_test.go
  kyaml/fn/framework/testdata/validation/error/errors.txt
  kyaml/fn/framework/testdata/validation/error/input.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3962 remove metadata field from resourceRef schema
  kyaml/fn/framework/command/example_test.go
  kyaml/fn/framework/framework_test.go
  kyaml/fn/framework/result.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3968 Don't run helm inflator test against released version.
  hack/testExamplesAgainstKustomize.sh
Labels: approved, cncf-cla: yes, size/S

#3964 Handle errors
  api/filesys/fsnode.go
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/accumulator/loadconfigfromcrds_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/generators/configmap.go
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/utils/utils.go
  api/internal/plugins/utils/utils_test.go
  api/konfig/plugins_test.go
  api/kv/kv_test.go
  cmd/config/completion/completion.go
  cmd/config/internal/commands/annotate.go
  cmd/pluginator/internal/builtinplugin/builtinplugin.go
  kustomize/commands/edit/add/addbase_test.go
  kustomize/commands/edit/add/addcomponent_test.go
  kustomize/commands/edit/add/addmetadata_test.go
  kustomize/commands/edit/add/addpatch_test.go
  kustomize/commands/edit/add/addresource_test.go
  kustomize/commands/edit/add/addtransformer_test.go
  kustomize/commands/edit/add/flagsandargs_test.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
  kyaml/yaml/rnode_test.go
  kyaml/yaml/types.go
  plugin/someteam.example.com/v1/calvinduplicator/CalvinDuplicator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3965 handle comments in list correctly
  kyaml/comments/comments.go
  kyaml/comments/comments_test.go
  kyaml/kio/byteio_writer.go
  kyaml/kio/byteio_writer_test.go
  kyaml/kio/filters/fmtr_test.go
  kyaml/yaml/serialization.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3963 small `api` changes for kustomize fix
  api/filesys/filesystem.go
  api/filesys/fsnode.go
  api/filesys/fsondisk.go
  api/types/replacement.go
  api/types/selector.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3972 Document contributor roles
  CONTRIBUTING.md
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#3956 replacements should be able to use previous IDs
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/internal/utils/makeResIds.go
  api/krusty/replacementtransformer_test.go
  api/resource/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3977 Commit roadmap presented to SIG-CLI
  roadmap-2021.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3984 Replacement with dot
  api/filters/replacement/replacement_test.go
  api/internal/utils/pathsplitter.go
  api/internal/utils/pathsplitter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3982 Ensure 'not exist' errors wrap os.ErrNotExist
  api/filesys/filesystem_test.go
  api/filesys/fsnode.go
  api/filesys/fsondisk.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#3926 convert vars to replacements
  kustomize/commands/commands.go
  kustomize/commands/edit/all.go
  kustomize/commands/edit/fix/convert.go
  kustomize/commands/edit/fix/convert_test.go
  kustomize/commands/edit/fix/fix.go
  kustomize/commands/edit/fix/fix_test.go
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
  kustomize/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3987 Allow users to customize handling of deleted resources for merge3
  kyaml/kio/filters/merge3.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3992 Allow the Handle function of the ResourceHandler interface to return an error
  kyaml/kio/filters/merge3.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3986 Filesys default
  api/filesys/filesystem.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#3996 expose --as-current-user flag to kustomize build command
  api/internal/plugins/fnplugin/fnplugin.go
  api/types/pluginrestrictions.go
  cmd/config/internal/commands/run-fns.go
  kustomize/commands/build/flagsforfunctions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3991 convert vars to replacements: mapping value with dot
  kustomize/commands/edit/fix/convert.go
  kustomize/commands/edit/fix/convert_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3999 Test api in workflows
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4000 Update kubectl kustomize section of readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3998 Remove debug fmt.Println breaking kpt Starlark output
  kyaml/runfn/runfn.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3994 Add a file sys.FileSystem interface to kio.ignoreFilesMatcher
  kyaml/kio/ignorefilesmatcher.go
  kyaml/kio/ignorefilesmatcher_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#4005 change marshal indent to 2
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/yaml/alias.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#4006 Introduce Validate Data Map Function
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4018 Handle null values while formatting
  kyaml/kio/filters/fmtr_test.go
  kyaml/yaml/compatibility.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4020 Pin to kyaml
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#4022 Pin to cmd/config v0.9.13
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4023 add missing json tags
  kyaml/yaml/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4025 Pin to api v0.8.11
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#4026 release process: upgrade to goreleaser v0.172.1 calling go1.16.5
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/S

#4027 Temporarily remove windows build.
  releasing/cloudbuild.sh
  releasing/localbuild.sh
Labels: cncf-cla: yes
