Repository kubernetes-sigs/kustomize, pull requests merged in 2021-04, with the labels that each got.

#3735 add replacement filter to support replacmenttransformer
  api/filters/replacement/doc.go
  api/filters/replacement/example_test.go
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/internal/crawl/cmd/backend/main.go
  api/internal/crawl/crawler/github/crawler.go
  api/internal/crawl/crawler/github/split_search_ranges_test.go
  api/resmap/selector_test.go
  api/types/patch_test.go
  api/types/replacement.go
  api/types/selector.go
  api/types/selector_test.go
  api/types/var.go
  api/types/var_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3771 add more tests for replacement filter
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/types/replacement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3774 Fix go sum files.
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.sum
  cmd/pluginator/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3782 add use of rejects field in replacement filter
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/types/replacement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3783 add natasha to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS

#3775 Enable LocalPackageReader to ignore specific path
  kyaml/kio/pkgio_reader.go
  kyaml/kio/pkgio_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3773 use field options to refine replacements
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/types/replacement.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3788 upgrade to helm 3.5.4 and imdario/mergo v0.3.12
  Makefile
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader.go
  api/internal/target/kusttarget.go
  api/resmap/resmap.go
  cmd/pluginator/go.sum
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
  hack/testExamplesAgainstKustomize.sh
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3790 Enhance the enhanced test harness.
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  api/testutils/kusttest/harnessenhanced.go
  api/types/pluginconfig.go
Labels: approved, cncf-cla: yes, size/M

#3792 Fix nits, add internal GetRoot func.
  api/internal/target/kusttarget_configplugin.go
  api/testutils/kusttest/harnessenhanced.go
Labels: cncf-cla: yes

#3793 Add check of UpdateExpectedFromActual before skipping test
  kyaml/fn/framework/frameworktestutil/frameworktestutil.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3784 Add flag --enable-helm
  api/builtins/HelmChartInflationGenerator.go
  api/internal/target/kusttarget_configplugin.go
  api/krusty/helmchartinflationgenerator_test.go
  api/testutils/kusttest/harnessenhanced.go
  api/types/helmchartargs.go
  api/types/kustomization.go
  api/types/pluginconfig.go
  examples/chart.md
  hack/testExamplesAgainstKustomize.sh
  kustomize/commands/build/build.go
  kustomize/commands/build/flagenablehelm.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
  plugin/builtin/helmchartinflationgenerator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3750 Fix init command in wordpress example
  examples/wordpress/README.md
  examples/wordpress/patch.yaml
  examples/zh/vars.md
Labels: cncf-cla: yes, ok-to-test, size/M

#3799 Pin to kyaml@v0.10.17
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3800 Fix go.sum nit
  api/internal/crawl/go.sum
Labels: cncf-cla: yes

#3801 Pin to cmd/config v0.9.10
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3802 Pin to api v0.8.6
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, size/L

#3805 Downgrade mergo to v0.3.7
  api/go.mod
  api/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#3806 Unpin the api
  api/internal/crawl/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, size/L

#3807 Pin to api v0.8.7
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3808 Fix typo
  examples/jsonpatch.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#3809 Back to development mode; unpin the modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#3810 Back to mergo v0.3.5
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, size/L

#3811 Pin to api v0.8.8
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3795 Support immutable attribute on generators
  api/internal/generators/configmap.go
  api/internal/generators/configmap_test.go
  api/internal/generators/secret.go
  api/internal/generators/secret_test.go
  api/internal/generators/utils.go
  api/types/generatoroptions.go
  api/types/generatoroptions_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3813 Back to dev mode; unpin the modules.
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3737 replacement transformer that uses the new replacement filter
  Makefile
  api/builtins/ReplacementTransformer.go
  api/filters/replacement/replacement.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/target/kusttarget_configplugin.go
  api/krusty/replacementtransformer_test.go
  api/resource/resource.go
  api/types/kustomization.go
  api/types/replacementfield.go
  plugin/builtin/replacementtransformer/ReplacementTransformer.go
  plugin/builtin/replacementtransformer/ReplacementTransformer_test.go
  plugin/builtin/replacementtransformer/go.mod
  plugin/builtin/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3820 Make fsNode handle correctly consecutive reads and writes
  api/filesys/fsnode.go
  api/filesys/fsnode_test.go
  api/testutils/kusttest/harness.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#3834 Pin plugins to v0.0.0
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replacementtransformer/go.mod
  plugin/builtin/replacementtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/untested/v1/gogetter/go.mod
Labels: approved, cncf-cla: yes, size/M

#3837 modify Error log info
  api/resmap/reswrangler.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#3835 Use resid.ResId in replacements.
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/krusty/replacementtransformer_test.go
  api/resid/resid.go
  api/resid/resid_test.go
  api/resmap/selector_test.go
  api/types/patch_test.go
  api/types/replacement.go
  api/types/selector.go
  api/types/selector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3836 Update OWNER_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#3839 Add testharness mkdir function.
  api/testutils/kusttest/harnessenhanced.go
Labels: cncf-cla: yes

#3822 Fix typo
  examples/inlinePatch.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#3827 remove go-openapi/spec,validate,strfmt
  api/go.mod
  api/go.sum
  api/internal/accumulator/loadconfigfromcrds.go
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.sum
  kyaml/fieldmeta/fieldmeta.go
  kyaml/fix/fixsetters/fieldmetav1.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_benchmark_test.go
  kyaml/setters2/add.go
  kyaml/setters2/delete.go
  kyaml/setters2/list.go
  kyaml/setters2/set.go
  kyaml/setters2/set_test.go
  kyaml/setters2/settersutil/deletercreator.go
  kyaml/setters2/settersutil/fieldsetter.go
  kyaml/setters2/settersutil/settercreator.go
  kyaml/setters2/settersutil/substitutioncreator.go
  kyaml/setters2/types.go
  kyaml/setters2/util.go
  kyaml/setters2/walk.go
  kyaml/yaml/compatibility.go
  kyaml/yaml/schema/schema_test.go
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#3843 Update go.sum in replacements.
  plugin/builtin/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/L

#3821 Support multiple implementations for IsSameResource
  cmd/config/internal/commands/merge3.go
  kyaml/kio/filters/merge3.go
  kyaml/kio/filters/merge3_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3844 Fix small golint warning
  cmd/config/internal/commands/annotate.go
  cmd/config/internal/commands/cat.go
  cmd/config/internal/commands/cmdcreatesetter.go
  cmd/config/internal/commands/cmdcreatesubstitution.go
  cmd/config/internal/commands/cmddeletesetter.go
  cmd/config/internal/commands/cmddeletesubstitution.go
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/count.go
  cmd/config/internal/commands/fmt.go
  cmd/config/internal/commands/grep.go
  plugin/builtin/patchtransformer/PatchTransformer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
