Repository kubernetes-sigs/kustomize, pull requests merged in 2021-12, with the labels that each got.

#4325 feat: Add Sort method to kyaml fn Results
  kyaml/fn/framework/result.go
  kyaml/fn/framework/result_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4326 deprecate StringPrefixer and DatePrefixer
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#4327 use internal.config.kubernetes.io prefix instead of internal.config.k8s.io
  api/filters/fieldspec/fieldspec_test.go
  api/filters/refvar/refvar_test.go
  cmd/config/internal/commands/e2e/e2e_test.go
  kyaml/kio/kioutil/kioutil.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#4328 Remove the deprecation warning for a few RNode helpers
  kyaml/yaml/rnode.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4329 [fix] configMapGenerator: extra space in end of line gives "\n" instead of line breaks
  api/internal/generators/utils.go
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/configmaps_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4267 Proposal: Option for transformer annotations
  proposals/21-11-transformer-annotations.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#4332 collect origin data only when the option is set
  api/internal/target/kusttarget.go
  api/resource/origin.go
  api/resource/origin_test.go
  api/types/kustomization.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4342 Remove module span check
  Makefile
  cmd/prchecker/go.mod
  cmd/prchecker/go.sum
  cmd/prchecker/main.go
  cmd/prchecker/main_test.go
  hack/check-multi-module.sh
Labels: cncf-cla: yes, approved, size/XL, lgtm

#4221 docs: Update Plugin Links
  docs/plugins/README.md
  docs/plugins/builtins.md
  docs/plugins/execPluginGuidedExample.md
  docs/plugins/goPluginCaveats.md
  docs/plugins/goPluginGuidedExample.md
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#3924 Add ARCHITECTURE.md
  ARCHITECTURE.md
Labels: cncf-cla: yes, size/L, approved, lifecycle/rotten, lgtm

#4318 Refactor the PrefixSuffixTransformer into separate prefix- and suffix transformers
  Makefile
  api/builtins/builtins.go
  api/filters/prefix/doc.go
  api/filters/prefix/example_test.go
  api/filters/prefix/prefix.go
  api/filters/prefix/prefix_test.go
  api/filters/prefixsuffix/doc.go
  api/filters/suffix/doc.go
  api/filters/suffix/example_test.go
  api/filters/suffix/suffix.go
  api/filters/suffix/suffix_test.go
  api/internal/builtins/PrefixTransformer.go
  api/internal/builtins/SuffixTransformer.go
  api/internal/plugins/builtinhelpers/builtinplugintype_string.go
  api/internal/plugins/builtinhelpers/builtins.go
  api/internal/target/kusttarget_configplugin.go
  api/konfig/builtinpluginconsts/defaultconfig.go
  api/konfig/builtinpluginconsts/namesuffix.go
  api/krusty/customconfigofbuiltinplugin_test.go
  api/krusty/customconfigreusable_test.go
  api/krusty/legacyprefixsuffixtransformer_test.go
  hack/generateBuiltinKrmFunctions.sh
  plugin/builtin/prefixtransformer/PrefixTransformer.go
  plugin/builtin/prefixtransformer/PrefixTransformer_test.go
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
  plugin/builtin/suffixtransformer/SuffixTransformer.go
  plugin/builtin/suffixtransformer/SuffixTransformer_test.go
  plugin/builtin/suffixtransformer/go.mod
  plugin/builtin/suffixtransformer/go.sum
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm, tide/merge-method-squash, ok-to-test

#4055 ConfigMapGenerator should not update unrelated ClusterRole rule
  api/krusty/namereference_test.go
Labels: cncf-cla: yes, size/M, approved, lifecycle/rotten, lgtm, ok-to-test

#4344 improve gvk and resid strings for error messages
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/krusty/complexcomposition_test.go
  api/krusty/component_test.go
  api/krusty/diamondcomposition_test.go
  api/krusty/repeatbase_test.go
  api/resmap/reswrangler.go
  api/resource/resource_test.go
  kyaml/resid/gvk.go
  kyaml/resid/gvk_test.go
  kyaml/resid/resid.go
  kyaml/resid/resid_test.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4341 add origin annotation for resources generated by generators
  api/internal/plugins/loader/loader.go
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_configplugin.go
  api/krusty/buildmetadata_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resource/origin.go
  api/resource/resource.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#4310 Upgrade cobra for better zsh support
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  kyaml/go.mod
  kyaml/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/iampolicygenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replacementtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/suffixtransformer/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm, ok-to-test

#4355 test coverage for origin annotations for generated resources
  api/krusty/buildmetadata_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4352 prevent internal annotations from showing up in the errors thrown by filters
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
  api/filters/refvar/refvar_test.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  kyaml/resid/resid.go
  kyaml/resid/resid_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4334 Handle HTTP error codes in file loader
  api/internal/target/kusttarget.go
  api/krusty/remoteload_test.go
  api/loader/errors.go
  api/loader/fileloader.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
