Repository kubernetes-sigs/kustomize, pull requests merged in 2021-03, with the labels that each got.

#3666 updated go version to 1.16
  api/go.mod
  api/internal/crawl/go.mod
  cmd/config/go.mod
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.mod
  cmd/gorepomod/go.mod
  cmd/k8scopy/go.mod
  cmd/mdtogo/go.mod
  cmd/pluginator/go.mod
  cmd/prchecker/go.mod
  functions/examples/application-cr/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/validator-kubeval/image/go.mod
  functions/examples/validator-resource-requests/image/go.mod
  hack/go.mod
  kustomize/go.mod
  kyaml/go.mod
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/valueaddtransformer/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/replacementtransformer/go.mod
  site/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#3667 upgraded to yaml.v2 v2.4.0
  api/go.mod
  api/go.sum
  api/internal/crawl/go.sum
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/configmaps_test.go
  api/krusty/stringquoteblank_test.go
  api/krusty/variableref_test.go
  cmd/config/go.sum
  cmd/pluginator/go.sum
  kustomize/go.sum
  kyaml/go.mod
  kyaml/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
  plugin/untested/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3669 Add benchmarks to measure impact of swagger parsing
  kyaml/openapi/openapi_benchmark_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3673 Return error instead of panicking for duplicate keys
  api/builtins/NamespaceTransformer.go
  api/ifc/ifc.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/target/multitransformer.go
  api/internal/wrappy/factory_test.go
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
  api/krusty/duplicatekeys_test.go
  api/resmap/merginator.go
  api/resmap/reswrangler.go
  api/resource/factory.go
  api/resource/resource.go
  kustomize/commands/build/writer.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: cncf-cla: yes, lgtm, size/L

#3679 add test for multibyte string
  api/krusty/multibytecharacter_test.go
Labels: cncf-cla: yes, lgtm, size/M

#3684 Full tree go mod tidy
  api/go.sum
  api/internal/crawl/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.sum
  functions/examples/application-cr/image/go.sum
  hack/go.sum
  kustomize/go.sum
  kyaml/go.sum
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
  plugin/untested/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/L

#3686 Extract flags that enable alpha function features.
  kustomize/commands/build/build.go
  kustomize/commands/build/flagsforfunctions.go
  kustomize/commands/commands.go
Labels: approved, cncf-cla: yes, size/M

#3676 allow most recent release with specific path
  hack/install_kustomize.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#3688 Undo kyaml/go.mod lint replacements.
  kyaml/Makefile
  kyaml/go.mod
Labels: approved, cncf-cla: yes, size/S

#3689 Pin to kyaml v0.10.14
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/S

#3690 Pin to cmd/config v0.9.6
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3691 Fix go.sum
  api/internal/crawl/go.sum
Labels: cncf-cla: yes

#3692 Reinstate configmap/secret generator 'env' field.
  api/krusty/configmaps_test.go
  api/types/kustomization.go
  api/types/kustomization_test.go
  api/types/kvpairsources.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3697 Add PodTemplate field to namereference config.
  api/konfig/builtinpluginconsts/namereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3695 Use portable method to emulate 'readlink -f' behavior
  hack/install_kustomize.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#3699 cleanup image transformer
  api/builtins/ImageTagTransformer.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3700 add env to kustomization openapi spec
  kyaml/openapi/kustomizationapi/swagger.go
  kyaml/openapi/kustomizationapi/swagger.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3701 Pin to kyaml v0.10.15
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes

#3702 Pin to cmd/config v0.9.7
  kustomize/go.mod
  kustomize/go.sum
Labels: approved, cncf-cla: yes, size/XS

#3704 Pin to api v0.8.5
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.mod
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixsuffixtransformer/go.mod
  plugin/builtin/prefixsuffixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.mod
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
  plugin/untested/v1/replacementtransformer/go.mod
  plugin/untested/v1/replacementtransformer/go.sum
Labels: approved, cncf-cla: yes, size/L

#3709 Remove branching on kyaml enablement
  api/filters/patchstrategicmerge/patchstrategicmerge.go
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/refvartransformer_test.go
  api/konfig/general.go
  api/krusty/basic_io_test.go
  api/krusty/configmaps_test.go
  api/krusty/kustomizer.go
  api/krusty/multiplepatch_test.go
  api/krusty/namereference_test.go
  api/krusty/options.go
  api/krusty/poddisruptionbudget_test.go
  api/provider/depprovider.go
  api/resmap/factory_test.go
  api/resource/factory_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
  plugin/builtin/secretgenerator/SecretGenerator_test.go
Labels: approved, cncf-cla: yes, size/L

#3713 HelmChartInflationGenerator: inherit environment variables to helm command
  api/builtins/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3720 support new version string in helm
  api/builtins/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3725 Fix broken link kep 1802
  examples/components.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3708 Take provenance version into account for build test
  kustomize/commands/build/build_test.go
Labels: cncf-cla: yes, size/S

#3644 allow general name and kind changes via an options field in patches
  api/builtins/PatchTransformer.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/target/kusttarget_configplugin.go
  api/krusty/gvknpatch_test.go
  api/krusty/options.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/factory.go
  api/resource/resource.go
  api/resource/resource_test.go
  api/types/patch.go
  kustomize/commands/build/build.go
  kustomize/commands/build/flagallowresourceidchanges.go
  kustomize/commands/edit/remove/removepatch.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer_test.go
  plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#3721 Remove the wrappy package in service of 3588
  api/builtins/HashTransformer.go
  api/builtins/NamespaceTransformer.go
  api/filters/namespace/namespace.go
  api/go.mod
  api/go.sum
  api/hasher/hasher.go
  api/hasher/hasher_test.go
  api/ifc/ifc.go
  api/internal/target/multitransformer.go
  api/internal/wrappy/factory.go
  api/internal/wrappy/factory_test.go
  api/internal/wrappy/wnode.go
  api/internal/wrappy/wnode_test.go
  api/krusty/duplicatekeys_test.go
  api/provider/depprovider.go
  api/resid/gvk.go
  api/resid/gvk_test.go
  api/resmap/factory.go
  api/resmap/factory_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/factory.go
  api/resource/factory_test.go
  api/resource/resource.go
  api/resource/resource_test.go
  api/types/fieldspec.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
  kustomize/commands/commands.go
  kustomize/commands/create/create.go
  kustomize/commands/create/create_test.go
  kustomize/commands/edit/add/all.go
  kustomize/commands/edit/add/configmap.go
  kustomize/commands/edit/add/secret.go
  kustomize/commands/edit/all.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3727 Allow patch removal of emptyDir {}
  api/builtins/PatchStrategicMergeTransformer.go
  api/filters/nameref/nameref.go
  api/hasher/hasher_test.go
  api/krusty/multiplepatch_test.go
  api/resource/resource.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3729 handle helm output properly
  api/builtins/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3730 Type alias for spec.Schema
  api/internal/accumulator/loadconfigfromcrds.go
Labels: approved, cncf-cla: yes, size/XS

#3734 Remove dead merge conflict code.
  api/builtins/PatchStrategicMergeTransformer.go
  api/filters/nameref/nameref_test.go
  api/internal/conflict/factory.go
  api/internal/conflict/smpatchmergeonlydetector.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/maker_test.go
  api/internal/target/multitransformer.go
  api/krusty/kustomizer.go
  api/krusty/multiplepatch_test.go
  api/provider/depprovider.go
  api/resmap/factory.go
  api/resmap/factory_test.go
  api/resmap/merginator.go
  api/resmap/reswrangler_test.go
  api/resource/conflictdetector.go
  api/testutils/kusttest/harnessenhanced.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/main.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3738 Make dir optional for tree command
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/tree_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3731 added test showing broken namespace reference when combining resource…
  api/krusty/validatingwebhook_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#3740 Fix nits in 3731
  api/krusty/validatingwebhook_test.go
Labels: approved, cncf-cla: yes, size/S

#3747 remove old untested replacement transformer
  plugin/untested/v1/replacementtransformer/ReplacementTransformer.go
  plugin/untested/v1/replacementtransformer/ReplacementTransformer_test.go
  plugin/untested/v1/replacementtransformer/go.mod
  plugin/untested/v1/replacementtransformer/go.sum
Labels: cncf-cla: yes, lgtm, size/XL

#3743 Add labels field to kustomization
  api/internal/target/kusttarget_configplugin.go
  api/krusty/inlinelabels_test.go
  api/types/kustomization.go
  api/types/kustomization_test.go
  api/types/labels.go
  kustomize/commands/edit/fix/fix.go
  kustomize/commands/edit/fix/fix_test.go
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3748 Check if value is provided
  cmd/config/internal/commands/cmdset.go
  cmd/config/internal/commands/cmdset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3744 Do no require exec/go plugin home to use fn plugins
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/loader/loader.go
  api/internal/plugins/loader/loader_test.go
  api/internal/plugins/utils/utils.go
  api/internal/target/maker_test.go
  api/konfig/plugins.go
  api/konfig/plugins_test.go
  api/krusty/fnplugin_test.go
  api/krusty/kustomizer.go
  api/krusty/options.go
  api/testutils/kusttest/harness.go
  api/testutils/kusttest/harnessenhanced.go
  api/types/errunabletofind.go
  api/types/pluginconfig.go
  kustomize/commands/build/build.go
Labels: cncf-cla: yes, size/L

#3754 Fix indentation
  examples/customOpenAPIschema.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#3733 Add CustomResourceDefinition webhook namespace transformer
  api/konfig/builtinpluginconsts/namespace.go
  api/krusty/namespaces_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3759 Don't print Krmfile file in tree output
  cmd/config/internal/commands/tree.go
  cmd/config/internal/commands/tree_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3558 Makefile: check and use GOBIN environment variable first
  Makefile
  cmd/config/Makefile
  cmd/gorepomod/Makefile
  functions/examples/application-cr/Makefile
  functions/examples/injection-tshirt-sizes/Makefile
  functions/examples/template-go-nginx/Makefile
  functions/examples/template-heredoc-cockroachdb/Makefile
  functions/examples/validator-kubeval/Makefile
  functions/examples/validator-resource-requests/Makefile
  hack/testExamplesAgainstKustomize.sh
  hack/testUnitKustomizePlugins.sh
  kyaml/Makefile
  kyaml/openapi/Makefile
  kyaml/openapi/scripts/fetchSchemaFromCluster.sh
  kyaml/openapi/scripts/generateSwaggerDotGo.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
