Repository kubernetes-sigs/kustomize, pull requests merged in 2022-11, with the labels that each got.

#4856 Address TODO in PR #4652
  api/loader/fileloader.go
  api/loader/fileloader_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#4857 Improve readability of `ifc.Loader`'s `Repo()` method
  api/ifc/ifc.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  kustomize/commands/internal/util/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#4859 Implement `localizer` skeleton for `kustomize localize`
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4855 add koba1t to reviews
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4863 Fix `RepoSpec` query extraction
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4802 grammar: replace all occurrences of "the the" with "the"
  api/internal/plugins/builtinconfig/namebackreferences.go
  cmd/gorepomod/README.md
  cmd/gorepomod/usage.go
  kyaml/fn/framework/example/doc.go
  kyaml/kio/byteio_writer.go
  kyaml/openapi/openapi.go
  kyaml/yaml/walk/associative_sequence.go
  proposals/00-00-template.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#4860 Improve `localizer` readability
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4865 Implement `localizeFile()` skeleton for patches
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/internal/localizer/locloader.go
  api/internal/localizer/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4874 New token, hopefully without trailing whitespace error
  releasing/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved

#4875 Third try new token without newline
  releasing/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved

#4876 Regenerate token and encrypt without newline (attempt 4)
  releasing/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved

#4840 Update golangci-lint version (1.49.0 -> 1.50.1) and enable linters: dupword and testableexamples
  .golangci.yml
  Makefile-tools.mk
  cmd/pluginator/internal/krmfunction/converter.go
  kyaml/filesys/util.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4868 chore: upgrade helm version
  Makefile-tools.mk
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4887 Get rid of statik and fix failing tests
  Makefile-tools.mk
  cmd/pluginator/Makefile
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  cmd/pluginator/internal/krmfunction/converter.go
  cmd/pluginator/internal/krmfunction/converter_test.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/go.mod.src
Labels: cncf-cla: yes, size/M, approved, lgtm

#4619 install_kustomize: support linux/aarch64, with fallback to old behavior
  hack/install_kustomize.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#4878 Calculate `localize`d path for remote file
  api/internal/localizer/util.go
  api/internal/localizer/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#4869 Load built-in plugins for `kustomize localize`
  api/internal/localizer/builtinplugins.go
  api/internal/localizer/errors.go
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4890 merge2: preserve explicitly set null values
  api/filters/patchstrategicmerge/patchstrategicmerge_test.go
  kyaml/yaml/merge2/merge2.go
  kyaml/yaml/merge2/scalar_test.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4885 Contain `RepoSpec` path in repo
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4893 Fix pluginator incompatibility with nolint lines
  api/internal/builtins/HelmChartInflationGenerator.go
  cmd/pluginator/internal/builtinplugin/builtinplugin.go
  cmd/pluginator/internal/krmfunction/converter_test.go
  cmd/pluginator/internal/krmfunction/funcwrappersrc/fakeplugin.go
  plugin/builtin/annotationstransformer/AnnotationsTransformer.go
  plugin/builtin/configmapgenerator/ConfigMapGenerator.go
  plugin/builtin/hashtransformer/HashTransformer.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/iampolicygenerator/IAMPolicyGenerator.go
  plugin/builtin/imagetagtransformer/ImageTagTransformer.go
  plugin/builtin/labeltransformer/LabelTransformer.go
  plugin/builtin/legacyordertransformer/LegacyOrderTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go
  plugin/builtin/patchtransformer/PatchTransformer.go
  plugin/builtin/prefixtransformer/PrefixTransformer.go
  plugin/builtin/replacementtransformer/ReplacementTransformer.go
  plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go
  plugin/builtin/secretgenerator/SecretGenerator.go
  plugin/builtin/suffixtransformer/SuffixTransformer.go
  plugin/builtin/valueaddtransformer/ValueAddTransformer.go
  plugin/someteam.example.com/v1/calvinduplicator/CalvinDuplicator.go
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
  plugin/someteam.example.com/v1/someservicegenerator/SomeServiceGenerator.go
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4852 remove PSP as v1.25 remove it
  cmd/config/docs/api-conventions/functions-spec.md
  cmd/config/internal/generateddocs/api/docs.go
  kyaml/openapi/openapi.go
Labels: cncf-cla: yes, size/XS, approved, lgtm
