Repository kubernetes-sigs/kustomize, pull requests merged in 2022-09, with the labels that each got.

#4758 Emit a warning when using missing field in FunctionSpec
  api/internal/plugins/fnplugin/fnplugin.go
  api/internal/plugins/loader/loader.go
  api/krusty/fnplugin_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/fn/runtime/runtimeutil/runtimeutil_test.go
  kyaml/runfn/runfn.go
  kyaml/runfn/runfn_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4770 Fix broken links
  kyaml/resid/gvk.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test, approved, kind/documentation, sig/docs, lgtm, kind/cleanup

#4791 Performance fix for fetching previous resource IDs
  api/internal/utils/makeResIds.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#4798 Fix flaky
  api/krusty/testdata/localize/remote/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4806 update golangci-lint version to v1.49.0
  .golangci.yml
  Makefile-tools.mk
  api/krusty/namespaces_test.go
  api/resmap/reswrangler_test.go
  api/types/helmchartargs.go
  cmd/config/internal/commands/cmdxargs.go
  cmd/config/internal/commands/e2e/e2e_test.go
  cmd/config/internal/commands/grep.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  kyaml/filesys/fsnode_test.go
  kyaml/filesys/util.go
  kyaml/fn/framework/function_definition.go
  kyaml/fn/runtime/exec/exec.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/runfn/runfn_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4809 convert PrevIds to use apiVersion instead meta
  api/internal/utils/makeResIds.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4709 migrate site content: contributing docs
  site/content/en/community/_index.md
  site/content/en/contribute/_index.md
  site/content/en/contribute/bugs/_index.md
  site/content/en/contribute/community/_index.md
  site/content/en/contribute/features/_index.md
  site/content/en/contribute/howitworks/_index.md
  site/content/en/contribute/mac/_index.md
  site/content/en/faq/_index.md
  site/content/en/faq/eschewedfeatures.md
  site/content/en/faq/versioningPolicy.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test
