Repository kubernetes-sigs/kustomize, pull requests merged in 2022-04, with the labels that each got.

#4543 Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4563 Add permissions to GitHub actions
  .github/workflows/go.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4565 Raise error for external generators or transformers
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#4571 Install goreleaser into go 1.18 image for build
  Makefile-tools.mk
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
  releasing/run-goreleaser.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#4577 fix error message using replacement wildcard and create option
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#4568 openapi parsing performance improvement with protobuffer
  api/Makefile
  api/go.mod
  api/go.sum
  api/krusty/openapicustomschema_test.go
  api/krusty/openapitests/openapicustomschema_test.go
  api/krusty/openapiversion_test.go
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/config/internal/commands/cmdset_test.go
  cmd/pluginator/go.sum
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  kustomize/go.sum
  kyaml/go.mod
  kyaml/go.sum
  kyaml/openapi/kubernetesapi/v1212/swagger.go
  kyaml/openapi/kubernetesapi/v1212/swagger.pb
  kyaml/openapi/kubernetesapi/v1218pb/doc.go
  kyaml/openapi/kubernetesapi/v1218pb/swagger.go
  kyaml/openapi/kubernetesapi/v1218pb/swagger.pb
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_benchmark_test.go
  kyaml/setters2/set_test.go
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/iampolicygenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replacementtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/suffixtransformer/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm, tide/merge-method-squash

#4489 fix containerized function mounts issue
  Makefile
  api/internal/plugins/loader/loader.go
  api/krusty/fnplugin_test.go
  kyaml/fn/runtime/container/container.go
  kyaml/fn/runtime/container/container_test.go
  kyaml/fn/runtime/runtimeutil/functiontypes.go
  kyaml/runfn/runfn.go
  plugin/builtin/hashtransformer/HashTransformer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash
