Repository kubernetes-sigs/kustomize, pull requests merged in 2022-01, with the labels that each got.

#4369 feat: add SetEntryCallback to labels filter
  api/filters/labels/labels.go
  api/filters/labels/labels_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4312 Fixes 4240; added null check on namespace when resource is a RoleBinding
  api/internal/accumulator/namereferencetransformer.go
  api/krusty/blankvalues_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#4294 fix: prevent read file from throwing away OpenAPI config
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4370 Fix helm globals
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4357 define methods, types, and unit tests for transformer annotations
  api/internal/target/kusttarget.go
  api/internal/utils/annotations.go
  api/krusty/originannotation_test.go
  api/resmap/resmap.go
  api/resmap/reswrangler.go
  api/resmap/reswrangler_test.go
  api/resource/origin.go
  api/resource/origin_test.go
  api/resource/resource.go
  api/resource/resource_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4385 Revert "[fix] configMapGenerator: extra space in end of line gives "\n" instead of line breaks"
  api/internal/generators/utils.go
  api/krusty/baseandoverlaymedium_test.go
  api/krusty/configmaps_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4377 deprecate enable-managedby-label flag in favor of a field
  api/krusty/kustomizer.go
  api/krusty/managedbylabel_test.go
  api/types/kustomization.go
  kustomize/commands/build/build.go
  kustomize/commands/build/flagaddmanagedby.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4373 set transformer annotations when the option is specified
  api/internal/plugins/loader/loader.go
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_configplugin.go
  api/internal/target/multitransformer.go
  api/internal/target/vars_test.go
  api/internal/utils/annotations.go
  api/krusty/helmchartinflationgenerator_test.go
  api/krusty/kustomizer.go
  api/krusty/originannotation_test.go
  api/krusty/transformerannotation_test.go
  api/resource/resource_test.go
  api/types/kustomization.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#4411 fix deprecated help message to `kustomize fn run --help`
  cmd/config/docs/commands/run-fns.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4410 Add TrackableFilter interface
  api/filters/annotations/annotations.go
  api/filters/annotations/annotations_test.go
  api/filters/filtersutil/setters.go
  api/filters/labels/labels.go
  api/filters/labels/labels_test.go
  kyaml/kio/kio.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#4396 Add benchmark test for parsing openapi in protobuf format
  kyaml/go.mod
  kyaml/go.sum
  kyaml/openapi/kubernetesapi/v1218pb/doc.go
  kyaml/openapi/kubernetesapi/v1218pb/swagger.go
  kyaml/openapi/kubernetesapi/v1218pb/swagger.pb
  kyaml/openapi/openapi_benchmark_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#4418 Imagetag trackable filter
  api/filters/imagetag/imagetag.go
  api/filters/imagetag/imagetag_test.go
  api/filters/imagetag/updater.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4413 new command `kustomize edit add buildmetadata`
  api/internal/target/kusttarget.go
  api/types/kustomization.go
  kustomize/commands/edit/add/addbuildmetadata.go
  kustomize/commands/edit/add/addbuildmetadata_test.go
  kustomize/commands/edit/add/all.go
  kustomize/commands/edit/remove/all.go
  kustomize/commands/edit/remove/removebuildmetadata.go
  kustomize/commands/edit/remove/removebuildmetadata_test.go
  kustomize/commands/edit/set/all.go
  kustomize/commands/edit/set/setbuildmetadata.go
  kustomize/commands/edit/set/setbuildmetadata_test.go
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
  kustomize/commands/internal/util/util_test.go
  kustomize/commands/internal/util/validate.go
  plugin/builtin/prefixtransformer/PrefixTransformer.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4426 Update owners file
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, approved, lgtm

#4425 fix: set FieldPath for SequenceNode elements
  api/filters/fieldspec/fieldspec.go
  api/filters/fieldspec/fieldspec_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
