Repository kubernetes-sigs/kustomize, pull requests merged in 2022-08, with the labels that each got.

#4742 prevent testing lib from being compiled in
  kyaml/filesys/fsondisk_test.go
  kyaml/filesys/fsondisk_unix.go
  kyaml/filesys/fsondisk_windows.go
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash

#4744 pin to cmd/config 0.10.9
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved

#4745 pin to api v0.12.1
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved

#4751 [address #4717] create template/metadata when using includeTemplates if not present
  api/internal/target/kusttarget_configplugin.go
  api/krusty/inlinelabels_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#4753 Revert "[address #4717] create template/metadata when using includeTemplates if not present"
  api/internal/target/kusttarget_configplugin.go
  api/krusty/inlinelabels_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4648 docs(examples): Fix URL to installation instructions in examples
  examples/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4748 Getting started guide part 2
  site/content/en/docs/Getting started/first_kustomization.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4764 Update internal go-yaml fork to v3.0.1
  kyaml/internal/forked/github.com/go-yaml/yaml/.github/workflows/semgrep.yaml
  kyaml/internal/forked/github.com/go-yaml/yaml/decode.go
  kyaml/internal/forked/github.com/go-yaml/yaml/decode_test.go
  kyaml/internal/forked/github.com/go-yaml/yaml/parserc.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4652 Load and calculate Destination of files for `kustomize localize`
  api/go.mod
  api/go.sum
  api/ifc/ifc.go
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/internal/localizer/doc.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
  api/internal/localizer/util_test.go
  api/internal/target/kusttarget.go
  api/krusty/kustomizer.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  kustomize/commands/internal/util/util_test.go
  kyaml/filesys/filesystem.go
  kyaml/filesys/fsondisk_test.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/suffixtransformer/go.mod
  plugin/builtin/suffixtransformer/go.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash, ok-to-test

#4773 run openapi tests with other krusty tests
  api/Makefile
  api/krusty/openapicustomschema_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4759 Enable SSH tests
  api/krusty/remoteload_test.go
  api/krusty/testdata/repo_read_only_ssh_key.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#4775 Revert "Load and calculate Destination of files for `kustomize localize`"
  api/go.mod
  api/go.sum
  api/ifc/ifc.go
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/internal/localizer/doc.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
  api/internal/localizer/util_test.go
  api/internal/target/kusttarget.go
  api/krusty/kustomizer.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  kustomize/commands/internal/util/util_test.go
  kyaml/filesys/filesystem.go
  kyaml/filesys/fsondisk_test.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/suffixtransformer/go.mod
  plugin/builtin/suffixtransformer/go.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm

#4777 expand and clean up repospec_test
  api/internal/git/repospec_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4779 Reinstate #4652 without url-related code
  api/ifc/ifc.go
  api/internal/git/repospec.go
  api/internal/localizer/doc.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
  api/internal/localizer/util_test.go
  api/loader/fileloader.go
  api/loader/fileloader_test.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  kustomize/commands/internal/util/util_test.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/suffixtransformer/go.mod
  plugin/builtin/suffixtransformer/go.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#4719 Remove dots from short descriptions
  cmd/config/configcobra/cfg.go
  cmd/config/configcobra/fn.go
  kustomize/commands/build/build.go
  kustomize/commands/build/build_test.go
  kustomize/commands/edit/add/addcomponent.go
  kustomize/commands/edit/add/addgenerator.go
  kustomize/commands/edit/add/addpatch.go
  kustomize/commands/edit/add/addresource.go
  kustomize/commands/edit/add/addtransformer.go
  kustomize/commands/edit/add/all.go
  kustomize/commands/edit/add/configmap.go
  kustomize/commands/edit/remove/all.go
  kustomize/commands/edit/set/all.go
  kustomize/commands/edit/set/set_name_prefix.go
  kustomize/commands/edit/set/set_name_suffix.go
Labels: cncf-cla: yes, size/M, approved, lgtm
