Repository kubernetes-sigs/kustomize, pull requests merged in 2022-10, with the labels that each got.

#4663 fix: handle error of remove annotations
  api/krusty/kustomizer.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#4808 Add support for helm --no-hooks flag
  api/internal/builtins/HelmChartInflationGenerator.go
  api/types/helmchartargs.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#4826 update actions/checkout
  .github/workflows/go.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4805 [address #4717] Re-do create template/metadata when using includeTemplates if not present
  api/internal/plugins/builtinconfig/transformerconfig.go
  api/internal/target/kusttarget_configplugin.go
  api/konfig/builtinpluginconsts/commonlabels.go
  api/konfig/builtinpluginconsts/defaultconfig.go
  api/konfig/builtinpluginconsts/metadatalabels.go
  api/konfig/builtinpluginconsts/templatelabels.go
  api/krusty/inlinelabels_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#4820 preallocate memory
  kyaml/sets/string.go
  kyaml/yaml/filters.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4733 add `edit fix` for patchesStrategicMerge to patches
  api/types/kustomization.go
  kustomize/commands/edit/fix/fix.go
  kustomize/commands/edit/fix/fix_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4654 fix: krm exec function working dir
  api/internal/plugins/loader/loader.go
  api/internal/plugins/loader/loader_test.go
  api/internal/target/kusttarget.go
  api/krusty/fnplugin_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4844 fix `TestRemoteLoad_LocalProtocol`
  api/krusty/remoteloader_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, tide/merge-method-squash
