Repository kubernetes-sigs/kustomize, pull requests merged in 2022-07, with the labels that each got.

#4668 Address nits on `localize` proposal and correct mistakes
  examples/remoteBuild.md
  proposals/22-04-localize-command.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4689 doc(first_kustomization): change the wrong command (I think)
  site/content/en/docs/Getting started/first_kustomization.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4698 Update kyaml in functions/examples and e2econtainerconfig
  cmd/config/internal/commands/e2e/e2econtainerconfig/Dockerfile
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.mod
  cmd/config/internal/commands/e2e/e2econtainerconfig/go.sum
  cmd/config/internal/commands/e2e/e2econtainerconfig/main.go
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
  functions/examples/injection-tshirt-sizes/Makefile
  functions/examples/injection-tshirt-sizes/README.md
  functions/examples/injection-tshirt-sizes/image/Dockerfile
  functions/examples/injection-tshirt-sizes/image/go.mod
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/injection-tshirt-sizes/image/main.go
  functions/examples/injection-tshirt-sizes/local-resource/example-use.yaml
  functions/examples/injection-tshirt-sizes/local-resource/kustomization.yaml
  functions/examples/injection-tshirt-sizes/local-resource/transformer.yaml
  functions/examples/template-go-nginx/README.md
  functions/examples/template-go-nginx/image/Dockerfile
  functions/examples/template-go-nginx/image/go.mod
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/template-go-nginx/image/main.go
  functions/examples/template-go-nginx/local-resource/example-use.yaml
  functions/examples/template-go-nginx/local-resource/kustomization.yaml
Labels: cncf-cla: yes, size/XXL, approved, lgtm, ok-to-test

#4683 Adds tests exhibiting possible bug in NamespaceTransformer
  api/krusty/namedspacedserviceaccounts_test.go
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#4703 Fix NameReference transformer handling of self-references in annotations
  api/krusty/namedspacedserviceaccounts_test.go
  api/krusty/namereference_test.go
  api/resource/resource.go
  api/resource/resource_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4705 update release tools for go workspace mode
  cmd/gorepomod/internal/edit/editor.go
  releasing/README.md
  releasing/run-goreleaser.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#4708 Option to customize NamespaceTransformer overwrite behaviour
  .golangci.yml
  Makefile-tools.mk
  api/filters/filtersutil/setters.go
  api/filters/filtersutil/setters_test.go
  api/filters/nameref/nameref.go
  api/filters/namespace/namespace.go
  api/internal/builtins/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
  plugin/builtin/namespacetransformer/go.mod
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4711 [fix] failed docker build on post-kustomize-push-images CI
  .dockerignore
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4667 replacements: fix issue with `create: true` option when there is an existing field
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4726 Update error message for m1 mac users trying to fetch older versions
  hack/install_kustomize.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4704 Option to customize NamespaceTransformer role binding subject handling
  api/filters/namespace/namespace.go
  api/internal/builtins/NamespaceTransformer.go
  api/konfig/builtinpluginconsts/namespace.go
  plugin/builtin/namespacetransformer/NamespaceTransformer.go
  plugin/builtin/namespacetransformer/NamespaceTransformer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4729 allow colon in filenames
  kyaml/filesys/fsnode.go
  kyaml/filesys/fsnode_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4730 Emit a warning when env loading bug is being relied on
  api/kv/kv.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4734 update go.sum files
  api/go.sum
  cmd/config/go.sum
  cmd/depprobcheck/go.sum
  cmd/gorepomod/go.sum
  cmd/k8scopy/go.sum
  cmd/pluginator/go.sum
  functions/examples/application-cr/image/go.sum
  functions/examples/injection-tshirt-sizes/image/go.sum
  functions/examples/template-go-nginx/image/go.sum
  functions/examples/validator-kubeval/image/go.sum
  functions/examples/validator-resource-requests/image/go.sum
  kustomize/go.sum
  kyaml/go.sum
  plugin/builtin/iampolicygenerator/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#4732 Update netlify config
  netlify.toml
  site/config.toml
  site/netlify.toml
  site/package-lock.json
  site/package.json
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#4735 update statik
  cmd/pluginator/internal/krmfunction/funcwrapper/statik.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4736 pin to kyaml v0.13.8
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/suffixtransformer/go.mod
Labels: cncf-cla: yes, approved, size/XL

#4737 pin cmd/config 0.10.8
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved

#4738 pin to api v0.12.0
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, approved, size/XL

#4739 update latest release number to 4.5.6
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
