Repository kubernetes-sigs/kustomize, pull requests merged in 2022-03, with the labels that each got.

#4502 Replace links to removed site
  README.md
Labels: cncf-cla: yes, size/M, approved

#4499 fix: broken reference to roadmap objectives
  ROADMAP.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4503 Remove more links to defunct site
  .github/ISSUE_TEMPLATE/bug_report.md
  hack/krmFunctionBenchmark/readme.md
  kustomize/commands/edit/add/addpatch.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4494 Preserve scalar types when using the replacement filter
  api/filters/replacement/replacement.go
  api/filters/replacement/replacement_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4511 fix broken link
  api/types/kustomization.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#4513 Update valueAdd.md
  examples/valueAdd.md
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#4485 Support for multiple replacements in a single file when replacing using path
  api/internal/builtins/ReplacementTransformer.go
  api/krusty/replacementtransformer_test.go
  plugin/builtin/replacementtransformer/ReplacementTransformer.go
  plugin/builtin/replacementtransformer/ReplacementTransformer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4516 Initial commit for a tutorial on getting started with kustomize
  site/content/en/docs/Getting started/first_kustomization.md
  site/package-lock.json
  site/package.json
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4383 Fix error during expansion of `!!merge <<:` anchor tags
  api/resmap/reswrangler_test.go
  api/resource/factory_test.go
  kyaml/kio/byteio_reader_test.go
  kyaml/yaml/alias.go
  kyaml/yaml/fns.go
  kyaml/yaml/fns_test.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash, ok-to-test

#4527 Bump cobra dependency to pick up latest vulnerability solution
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4421 retain quotes in namespace transformer filter
  api/filters/filtersutil/setters.go
  api/filters/namespace/namespace.go
  api/filters/namespace/namespace_test.go
  api/filters/replicacount/replicacount.go
  api/filters/replicacount/replicacount_test.go
  api/internal/generators/configmap_test.go
  api/internal/generators/utils.go
  cmd/config/internal/commands/run-fns.go
  kyaml/fn/framework/command/command_test.go
  kyaml/fn/framework/command/testdata/standalone/config.yaml
  kyaml/fn/framework/command/testdata/standalone/expected.yaml
  kyaml/setters2/set.go
  kyaml/yaml/fns.go
  kyaml/yaml/rnode.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4497 Fix 3812; Error message changed and check for MalformedYamlError
  api/internal/kusterr/yamlformaterror.go
  api/internal/target/kusttarget.go
  api/krusty/basic_io_test.go
  api/krusty/component_test.go
  api/loader/fileloader.go
  cmd/config/internal/commands/fmt_test.go
  kyaml/kio/byteio_reader.go
  kyaml/kio/filters/fmtr_test.go
Labels: cncf-cla: yes, size/M, ok-to-test

#4530 Pin to kyaml v0.13.4
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/suffixtransformer/go.mod
Labels: cncf-cla: yes, size/M, approved

#4532 Pin to cmd/config v0.10.5
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved

#4533 Pin to api v0.11.3
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved

#4534 Add git to image build docker step
  kustomize.Dockerfile
Labels: cncf-cla: yes, size/XS, approved

#4535 Back to development mode; unpin the modules
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved

#4536 Test examples against latest release
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#4541 Added test for bug 4487: cannot parse keys with dots
  kyaml/yaml/rnode_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#4538 move to google/gnostic v0.5.7-v3refs
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  kyaml/go.mod
  kyaml/go.sum
  kyaml/openapi/openapi_benchmark_test.go
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/iampolicygenerator/go.sum
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/legacyordertransformer/go.sum
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replacementtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/suffixtransformer/go.sum
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/starlarkmixer/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#4545 Add more name refs to PodTemplate for ConfigMap and Secret
  api/konfig/builtinpluginconsts/namereference.go
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test

#4537 Converge local and cloud gorelease scripts, improve release notes
  .gitignore
  releasing/README.md
  releasing/cloudbuild-local.sh
  releasing/cloudbuild.sh
  releasing/cloudbuild.yaml
  releasing/compile-changelog.sh
  releasing/localbuild.sh
  releasing/run-goreleaser.sh
  releasing/vendor_kustomize.diff
  releasing/vendor_kustomize.sh
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#4547 Update kyaml to v0.13.6
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/suffixtransformer/go.mod
Labels: cncf-cla: yes, size/M, approved

#4548 Improve logging for changelong builder
  releasing/README.md
  releasing/compile-changelog.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#4549 Update cmd/config to v0.10.6
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4550 Update api to api/v0.11.4
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#4551 Debug exit 141 failure
  releasing/compile-changelog.sh
Labels: cncf-cla: yes, size/XS, approved

#4552 Copy of go 1.18 created version mismatch, reverting for now
  releasing/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#4553 unpin modules and test against latest release
  Makefile
  api/go.mod
  api/go.sum
  cmd/config/go.mod
  cmd/config/go.sum
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/M, approved
