Repository kubernetes-sigs/kustomize, pull requests merged in 2023-01, with the labels that each got.

#4933 Localize legacy fields
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4912 Localize resources
  api/internal/localizer/errors.go
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4957 Remove Functionality that Pulls Env Variables from Empty Keys
  api/kv/kv.go
  api/kv/kv_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, release-note-action-required

#4929 Error on duplicate fields in Kustomization
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/internal/target/kusttarget_test.go
  api/krusty/basic_io_test.go
  api/krusty/configmaps_test.go
  api/krusty/crd_test.go
  api/krusty/disablenamesuffix_test.go
  api/krusty/generatormergeandreplace_test.go
  api/krusty/generatoroptions_test.go
  api/krusty/gvknpatch_test.go
  api/krusty/inlinepatch_test.go
  api/krusty/kustomizationmetadata_test.go
  api/krusty/localconfig_test.go
  api/krusty/managedbylabel_test.go
  api/krusty/namespacedgenerators_test.go
  api/krusty/nameupdateinroleref_test.go
  api/krusty/originannotation_test.go
  api/krusty/poddisruptionbudget_test.go
  api/krusty/transformerannotation_test.go
  api/types/kustomization.go
  api/types/kustomization_test.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, triage/accepted

#4922 Rename Orgrepo and Path
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/internal/localizer/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#4954 Iteration on parseHostSpec refactor
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/internal/localizer/util_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-action-required

#4980 Uncommitted updates from running go mod tidy and go work sync
  Makefile-plugins.mk
  api/internal/builtins/HelmChartInflationGenerator.go
  cmd/depprobcheck/go.mod
  cmd/depprobcheck/go.sum
  cmd/gorepomod/go.mod
  cmd/gorepomod/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  plugin/builtin/sortordertransformer/go.mod
  plugin/builtin/sortordertransformer/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#4970 Replace github/pkg/errors with sigs.k8s.io/kustomize/kyaml/errors
  api/filters/nameref/nameref.go
  api/go.mod
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/builtins/HelmChartInflationGenerator.go
  api/internal/builtins/PatchJson6902Transformer.go
  api/internal/builtins/SortOrderTransformer.go
  api/internal/git/gitrunner.go
  api/internal/plugins/compiler/compiler.go
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/fnplugin/fnplugin.go
  api/internal/plugins/loader/loader.go
  api/internal/target/errmissingkustomization.go
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_configplugin.go
  api/internal/utils/errtimeout.go
  api/kv/kv.go
  api/resmap/factory.go
  api/resmap/reswrangler.go
  api/types/erronlybuiltinpluginsallowed.go
  api/types/errunabletofind.go
  go.work.sum
  kustomize/commands/edit/remove/removepatch.go
  kustomize/commands/edit/remove/removetransformer_test.go
  kustomize/go.mod
  kyaml/filesys/filesystem_test.go
  kyaml/go.mod
  kyaml/go.sum
  kyaml/internal/forked/github.com/qri-io/starlib/util/util.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/patchjson6902transformer/PatchJson6902Transformer.go
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/sortordertransformer/SortOrderTransformer.go
  plugin/builtin/sortordertransformer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/DatePrefixer.go
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/StringPrefixer.go
  plugin/someteam.example.com/v1/stringprefixer/go.mod
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4943 Localize patch, ReplacementTransformer
  api/internal/localizer/builtinplugins.go
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#4974 Expose localize test helpers
  api/krusty/localizer/runner_test.go
  api/testutils/localizertest/filesystem.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4947 feat: Allow path starting with slash
  kyaml/utils/pathsplitter.go
  kyaml/utils/pathsplitter_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#4983 Refactor parseGitURL
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/krusty/remoteloader_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4992 fix(docs): update link to plugin doc
  examples/goGetterGeneratorPlugin.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#4973 Remove long-ignored Inventory field from Kustomization type
  api/krusty/options.go
  api/types/inventory.go
  api/types/kustomization.go
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, release-note-action-required, kind/cleanup

#4985 Proposal: Remove RepoSpec manipulation of .git suffix
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
  api/internal/localizer/util.go
  api/krusty/originannotation_test.go
  api/krusty/remoteloader_test.go
  api/krusty/transformerannotation_test.go
  api/resource/origin_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-action-required

#4986 repospec: support ssh urls with ssh certificates
  api/internal/git/repospec.go
  api/internal/git/repospec_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#4994 Fix `RepoSpec` CI failures on master
  api/internal/git/repospec_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#4834 api/resource: retain disableNameSuffixHash on merge and replace
  api/krusty/generatormergeandreplace_test.go
  api/krusty/generatoroptions_test.go
  api/resource/resource.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4990 Improve panic error message to include the parse error.
  kyaml/openapi/openapi.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4995 Follow up fixes
  api/internal/git/repospec.go
  api/krusty/generatoroptions_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#4944 Refactor mapping node traversal and optimize RNode.GetAnnotations and RNode.GetLabels
  api/internal/utils/makeResIds.go
  kyaml/yaml/fns.go
  kyaml/yaml/rnode.go
  kyaml/yaml/rnode_test.go
  kyaml/yaml/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#4978 Localize helm fields
  api/internal/builtins/HelmChartInflationGenerator.go
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/krusty/localizer/runner_test.go
  api/types/helmchartargs.go
  plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#5004 Make TestResourcesRepoNotFile Less Specific
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4989 Localize ConfigMapGenerator, SecretGenerator
  api/internal/localizer/builtinplugins.go
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#4967 fix: add lock for kubernetesOpenAPIVersion
  kyaml/Makefile
  kyaml/openapi/openapi.go
  kyaml/openapi/openapi_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#5009 Warn against partial releases
  releasing/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5007 Localize HelmChartInflationGenerator
  api/internal/localizer/builtinplugins.go
  api/internal/localizer/localizer_test.go
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5010 Expose path to `localize` destination
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/krusty/localizer/runner.go
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#5011 Run test-go-mod unpinned
  Makefile
  hack/with-unpinned-kust-dev.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#5012 make TestResourcesRepoNotFile even less specific
  api/krusty/localizer/runner_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm
