Repository kubernetes-sigs/kustomize, pull requests merged in 2023-07, with the labels that each got.

#5225 Add accumulateResources error tests for local files
  api/krusty/accumulation_test.go
  api/loader/fileloader_test.go
  api/testutils/kusttest/ondisk.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5189 Add test for issue #5131
  api/krusty/remoteloader_test.go
  api/krusty/testdata/remoteload/with-submodule/README.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#5245 Fix typo in help for the create subcommand
  kustomize/commands/create/create.go
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm, priority/important-longterm, ok-to-test, triage/accepted
