Repository kubernetes-sigs/kustomize, pull requests merged in 2023-10, with the labels that each got.

#5315 refactor: change "add configmap/secret" commands to reuse code and improve tests
  kustomize/commands/edit/add/configmap.go
  kustomize/commands/edit/add/configmapSecretFlagsAndArgs.go
  kustomize/commands/edit/add/configmapSecretFlagsAndArgs_test.go
  kustomize/commands/edit/add/configmap_test.go
  kustomize/commands/edit/add/secret.go
  kustomize/commands/edit/add/secret_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#5265 doc: update example to use tag v3.3.1
  examples/remoteBuild.md
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#5353 git submodule need origin
  api/internal/git/cloner.go
  api/krusty/remoteloader_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#5374 Path for glossary.md corrected
  examples/configGeneration.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#5367 fix: add namespace option to 'edit add configmap' command
  api/types/generatorargs.go
  kustomize/commands/edit/add/configmap.go
  kustomize/commands/edit/add/configmapSecretFlagsAndArgs.go
  kustomize/commands/edit/add/configmap_test.go
  kustomize/commands/edit/add/secret.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#5370 merge2: fix duplicate test case
  kyaml/yaml/merge2/scalar_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#5394 Update cmd/config to v0.12.0
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5397 fix release binary archive contains unnecessary dir
  releasing/create-release.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5409 refactor: move reusable bits in preparation for new 'edit set' commands
  go.work.sum
  kustomize/commands/edit/add/configmap.go
  kustomize/commands/edit/add/configmap_test.go
  kustomize/commands/edit/add/secret.go
  kustomize/commands/edit/add/secret_test.go
  kustomize/commands/internal/util/configmapSecretFlagsAndArgs.go
  kustomize/commands/internal/util/configmapSecretFlagsAndArgs_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#5408 fix add checksum create step in release scripts
  releasing/create-release.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#5351 update kustomize roadmap 23-24
  ROADMAP.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5420 Update security contacts for sig-cli
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5423 update roadmap based on review comments
  CONTRIBUTING.md
  ROADMAP.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#5368 Add Generator Tasks to Documentation
  site/content/en/docs/Reference/API/Kustomization File/configMapGenerator.md
  site/content/en/docs/Reference/API/Kustomization File/secretGenerator.md
  site/content/en/docs/Tasks/_index.md
  site/content/en/docs/Tasks/configmap_generator.md
  site/content/en/docs/Tasks/configmaps_and_secrets.md
  site/content/en/docs/Tasks/labels_and_annotations.md
  site/content/en/docs/Tasks/namespaces_and_names.md
  site/content/en/docs/Tasks/secret_generator.md
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash, ok-to-test

#5381 hotfix: return error instead of log at `FromMapAndOption`
  api/internal/plugins/utils/utils_test.go
  api/resmap/reswrangler_test.go
  api/resource/factory.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test
