Repository kubernetes-sigs/kustomize, pull requests merged in 2023-06, with the labels that each got.

#5170 change: components apply after all generators and transformers applied
  api/internal/target/kusttarget.go
  api/krusty/component_test.go
  go.work.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5030 be error when no path matching
  kustomize/commands/create/create_test.go
  kustomize/commands/edit/add/addcomponent_test.go
  kustomize/commands/edit/add/addresource_test.go
  kustomize/commands/internal/util/util.go
  kustomize/commands/internal/util/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#5195 add Anna to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5177 Test accumulateResources errors for remote files
  api/krusty/accumulation_test.go
  api/krusty/remoteloader_test.go
  api/loader/fileloader_test.go
  api/testutils/kusttest/ondisk.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#5213 pin to cmd/config
  go.work.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/S, approved
