Repository kubernetes-sigs/kustomize, pull requests merged in 2024-05, with the labels that each got.

#5688 refactor: function in stdlib now
  kustomize/commands/edit/fix/convert.go
Labels: cncf-cla: yes, size/S, needs-ok-to-test, approved, lgtm

#5703 Update cmd/config to v0.14.1
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5693 fix: always show accumulation errors
  api/internal/target/kusttarget.go
  api/internal/target/kusttarget_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#5699 chore: add deprecation comment to commonLabels
  api/types/kustomization.go
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm
