Repository kubernetes-sigs/kustomize, pull requests merged in 2024-02, with the labels that each got.

#5411 Add --load-restrictor completion
  kustomize/commands/build/build.go
  kustomize/commands/build/flagloadrestrictor.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#5529 chore: pin dev deps in the dev container
  site/Dockerfile
Labels: cncf-cla: yes, size/S, approved, lgtm

#5438 Add condtional checks on jobs to skip on document changes.
  .github/workflows/go.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#5528 Remove typo in documentation
  examples/remoteBuild.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#5533 chore: add hack/latest_version.sh
  hack/latest_version.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#5539 Include exec plugin `stderr` with wrapped error
  api/internal/plugins/execplugin/execplugin.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test, approved, lgtm

#5510 Skip KUSTOMIZE_PLUGIN_CONFIG_* env variables when too large
  api/internal/plugins/execplugin/execplugin.go
  api/internal/plugins/execplugin/execplugin_test.go
Labels: cncf-cla: yes, size/L, needs-ok-to-test, approved, lgtm

#5550 use Strict unmarshal when read TransformerConfig
  api/internal/plugins/builtinconfig/loaddefaultconfig.go
  api/internal/plugins/builtinconfig/loaddefaultconfig_test.go
  api/internal/target/kusttarget_test.go
  api/krusty/customconfig_test.go
  api/krusty/transformersimage_test.go
  api/krusty/variableref_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#5201 fix(examples): move examples from patchesStrategicMerge to patches
  examples/breakfast.md
  examples/components.md
  examples/configGeneration.md
  examples/helloWorld/README.md
  examples/inlinePatch.md
  examples/ldap/overlays/production/kustomization.yaml
  examples/ldap/overlays/staging/kustomization.yaml
  examples/mySql/README.md
  examples/wordpress/README.md
  examples/wordpress/kustomization.yaml
  examples/zh/breakfast.md
  examples/zh/configGeneration.md
  examples/zh/helloWorld.md
  examples/zh/mysql.md
  examples/zh/vars.md
Labels: cncf-cla: yes, size/L, needs-ok-to-test, approved, lifecycle/stale, lgtm

#5523 Add kustomization and transformer references
  site/content/en/docs/Reference/API/Kustomization File/commonAnnotations.md
  site/content/en/docs/Reference/API/Kustomization File/commonLabels.md
  site/content/en/docs/Reference/API/Kustomization File/labels.md
  site/content/en/docs/Reference/API/Kustomization File/namePrefix.md
  site/content/en/docs/Reference/API/Kustomization File/nameSuffix.md
  site/content/en/docs/Reference/API/Kustomization File/namespace.md
  site/content/en/docs/Reference/API/Transformers/LabelTransformer.md
  site/content/en/docs/Reference/API/Transformers/NamespaceTransformer.md
  site/content/en/docs/Reference/API/Transformers/PrefixTransformer.md
  site/content/en/docs/Reference/API/Transformers/SuffixTransformer.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5525 Allow importing kustomize API's without relying on `plugins`
  api/internal/plugins/loader/load_go_plugin.go
  api/internal/plugins/loader/load_go_plugin_disabled.go
  api/internal/plugins/loader/loader.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test
