Repository kubernetes-sigs/kustomize, pull requests merged in 2024-01, with the labels that each got.

#4558 Proposal: Replacements and Patch value in the structured data
  proposals/22-03-value-in-the-structured-data.md
Labels: cncf-cla: yes, approved, kind/feature, size/XL, lgtm, priority/important-longterm, kind/design, kind/api-change, ok-to-test, triage/under-consideration

#5447 Add generator kustomization references
  site/content/en/docs/Reference/API/Generators/ConfigMapGenerator.md
  site/content/en/docs/Reference/API/Generators/SecretGenerator.md
  site/content/en/docs/Reference/API/Generators/_index.md
  site/content/en/docs/Reference/API/Kustomization File/bases.md
  site/content/en/docs/Reference/API/Kustomization File/configMapGenerator.md
  site/content/en/docs/Reference/API/Kustomization File/generatorOptions.md
  site/content/en/docs/Reference/API/Kustomization File/kustomization.md
  site/content/en/docs/Reference/API/Kustomization File/secretGenerator.md
  site/content/en/docs/Reference/API/included/_index.md
  site/content/en/docs/Reference/API/included/generatorargs.md
  site/content/en/docs/Reference/API/included/secretargs.md
  site/content/en/includes/index.md
  site/layouts/shortcodes/include.html
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#5451 Feature/dependency pinning and update automation
  cmd/gorepomod/README.md
  cmd/gorepomod/go.mod
  cmd/gorepomod/go.sum
  cmd/gorepomod/gorepomod_test.go
  cmd/gorepomod/internal/arguments/args.go
  cmd/gorepomod/internal/edit/editor.go
  cmd/gorepomod/internal/git/runner.go
  cmd/gorepomod/internal/mod/module.go
  cmd/gorepomod/internal/repo/dotgitdata.go
  cmd/gorepomod/internal/repo/dotgitdata_test.go
  cmd/gorepomod/internal/repo/manager.go
  cmd/gorepomod/internal/repo/managerfactory.go
  cmd/gorepomod/internal/repo/protomodule.go
  cmd/gorepomod/internal/semver/semver.go
  cmd/gorepomod/internal/utils/utils.go
  cmd/gorepomod/internal/utils/utils_test.go
  cmd/gorepomod/main.go
  go.work.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm, tide/merge-method-squash, ok-to-test

#5518 Update owners file
  OWNERS_ALIASES
  kustomize/OWNERS
  site/OWNERS
Labels: cncf-cla: yes, size/M, approved, lgtm

#5463 Fix version tag management
  Makefile
  api/go.mod
  api/go.sum
  api/provenance/provenance.go
  api/provenance/provenance_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#5234 fix edit set image to parse both tag and digest
  api/pkg/util/image.go
  kustomize/commands/edit/set/setimage.go
  kustomize/commands/edit/set/setimage_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#5511 Add buildMetadata task and ref
  site/content/en/docs/Reference/API/Kustomization File/bases.md
  site/content/en/docs/Reference/API/Kustomization File/buildMetadata.md
  site/content/en/docs/Tasks/build_metadata.md
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#5521 add license for api/pkg/util/image.go
  api/pkg/util/image.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5512 Fix running docs site with docker
  site/Dockerfile
  site/Makefile
  site/README.md
  site/hugo.toml
  site/netlify.toml
  site/scripts/hash-files.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash
