Repository kubernetes-sigs/kustomize, pull requests merged in 2024-06, with the labels that each got.

#5544 Run kustomize build with kustomize localize and add a no-verify flag.
  kustomize/commands/localize/localize.go
  kustomize/commands/localize/localize_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#5689 Fix sortOptions removal when running edit command
  kustomize/commands/internal/kustfile/kustomizationfile.go
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#5698 fix(namereference): add configuration for new admission API
  api/internal/konfig/builtinpluginconsts/namereference.go
  api/krusty/namereference_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#5691 Pin kustomize image in cockroachdb example
  functions/examples/template-heredoc-cockroachdb/Makefile
  functions/examples/template-heredoc-cockroachdb/image/Dockerfile
Labels: cncf-cla: yes, size/M, approved, lgtm

#5718 fix lint error in kustomizationfile_test.go
  go.work.sum
  kustomize/commands/internal/kustfile/kustomizationfile_test.go
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#5506 fix some comments
  api/internal/target/kusttarget.go
  cmd/config/internal/commands/run-fns.go
  cmd/config/internal/inpututil/inpututil.go
  kustomize/commands/edit/remove/removemetadata.go
  kyaml/fn/framework/selector.go
  kyaml/fn/runtime/container/container.go
  kyaml/kio/ignorefilesmatcher.go
  kyaml/openapi/kustomizationapi/swagger.go
  kyaml/openapi/openapi.go
  kyaml/yaml/alias.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#5413 chore(docs): fix grammar error in comment
  kyaml/fn/framework/processors.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test
