Repository kubernetes-sigs/kustomize, pull requests merged in 2024-04, with the labels that each got.

#5236 Fix name in a configMapRef missing hash #5047
  api/filters/nameref/nameref.go
  api/krusty/configmaps_test.go
  api/resource/resource.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#5629 add favicons for kustomize site
  site/static/favicons/android-144x144.png
  site/static/favicons/android-192x192.png
  site/static/favicons/android-36x36.png
  site/static/favicons/android-48x48.png
  site/static/favicons/android-72x72.png
  site/static/favicons/android-96x96.png
  site/static/favicons/apple-touch-icon-180x180.png
  site/static/favicons/favicon-1024.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-256.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/pwa-192x192.png
  site/static/favicons/pwa-512x512.png
  site/static/favicons/tile150x150.png
  site/static/favicons/tile310x150.png
  site/static/favicons/tile310x310.png
  site/static/favicons/tile70x70.png
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#5636 Update site/Dockerfile to use pinned hugo version
  .dockerignore
  site/Dockerfile
  site/Makefile
  site/README.md
  site/netlify.toml
Labels: cncf-cla: yes, size/M, approved, lgtm

#5637 Fix gorepomod make test
  cmd/gorepomod/Makefile
  cmd/gorepomod/usage.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5640 Update cmd/config to v0.14.0
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5644 fix version subcommand is not working after release build
  api/provenance/provenance.go
  api/provenance/provenance_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#5079 perf: improve applyOrdering by avoid call to GetByCurrentId
  api/internal/builtins/SortOrderTransformer.go
  plugin/builtin/sortordertransformer/SortOrderTransformer.go
Labels: cncf-cla: yes, size/L, approved, lifecycle/rotten, kind/feature, lgtm, priority/important-longterm, ok-to-test, triage/accepted

#5625 fix: return error instead of log.Fatalf()
  api/internal/accumulator/namereferencetransformer_test.go
  api/internal/accumulator/resaccumulator_test.go
  api/internal/plugins/execplugin/execplugin_test.go
  api/internal/plugins/utils/utils_test.go
  api/internal/target/kusttarget_test.go
  api/resmap/reswrangler_test.go
  api/resource/factory.go
  api/resource/factory_test.go
  api/resource/idset_test.go
  api/resource/resource_test.go
  api/testutils/resmaptest/rmbuilder.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#5556 feat: support labels key in transformer configuration
  api/internal/accumulator/loadconfigfromcrds.go
  api/internal/plugins/builtinconfig/loaddefaultconfig_test.go
  api/internal/plugins/builtinconfig/transformerconfig.go
  api/internal/plugins/builtinconfig/transformerconfig_test.go
  api/internal/target/kusttarget_configplugin.go
  api/internal/target/kusttarget_test.go
  api/krusty/customconfig_test.go
  api/types/labels.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, tide/merge-method-squash

#5500 add testcase that check yield malformed yaml errors
  api/krusty/accumulation_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#5681 chore: remove unused function
  kustomize/commands/edit/fix/convert.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#5651 fix: use `fmt.Errorf` instead of non-existing `errors.New`
  api/Makefile
  api/internal/plugins/loader/load_go_plugin_disabled.go
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash, ok-to-test

#5294 feat: localize absolute paths
  api/internal/localizer/localizer.go
  api/internal/localizer/localizer_test.go
  api/internal/localizer/locloader.go
  api/internal/localizer/locloader_test.go
  api/internal/localizer/util.go
  api/internal/localizer/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
