Repository kubernetes-sigs/kustomize, pull requests merged in 2025-01, with the labels that each got.

#5833 add go work verification step for github actions
  .github/workflows/go.yml
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash

#5839 Update cmd/config to v0.19.0
  go.work.sum
  kustomize/go.mod
  kustomize/go.sum
Labels: cncf-cla: yes, size/XS, approved, lgtm

#5840 Update api to v0.19.0
  cmd/pluginator/go.mod
  cmd/pluginator/go.sum
  kustomize/go.mod
  kustomize/go.sum
  plugin/builtin/annotationstransformer/go.mod
  plugin/builtin/annotationstransformer/go.sum
  plugin/builtin/configmapgenerator/go.mod
  plugin/builtin/configmapgenerator/go.sum
  plugin/builtin/hashtransformer/go.mod
  plugin/builtin/hashtransformer/go.sum
  plugin/builtin/helmchartinflationgenerator/go.mod
  plugin/builtin/helmchartinflationgenerator/go.sum
  plugin/builtin/iampolicygenerator/go.mod
  plugin/builtin/iampolicygenerator/go.sum
  plugin/builtin/imagetagtransformer/go.mod
  plugin/builtin/imagetagtransformer/go.sum
  plugin/builtin/labeltransformer/go.mod
  plugin/builtin/labeltransformer/go.sum
  plugin/builtin/namespacetransformer/go.mod
  plugin/builtin/namespacetransformer/go.sum
  plugin/builtin/patchjson6902transformer/go.mod
  plugin/builtin/patchjson6902transformer/go.sum
  plugin/builtin/patchstrategicmergetransformer/go.mod
  plugin/builtin/patchstrategicmergetransformer/go.sum
  plugin/builtin/patchtransformer/go.mod
  plugin/builtin/patchtransformer/go.sum
  plugin/builtin/prefixtransformer/go.mod
  plugin/builtin/prefixtransformer/go.sum
  plugin/builtin/replacementtransformer/go.mod
  plugin/builtin/replacementtransformer/go.sum
  plugin/builtin/replicacounttransformer/go.mod
  plugin/builtin/replicacounttransformer/go.sum
  plugin/builtin/secretgenerator/go.mod
  plugin/builtin/secretgenerator/go.sum
  plugin/builtin/sortordertransformer/go.mod
  plugin/builtin/sortordertransformer/go.sum
  plugin/builtin/suffixtransformer/go.mod
  plugin/builtin/suffixtransformer/go.sum
  plugin/builtin/valueaddtransformer/go.mod
  plugin/builtin/valueaddtransformer/go.sum
  plugin/someteam.example.com/v1/bashedconfigmap/go.mod
  plugin/someteam.example.com/v1/bashedconfigmap/go.sum
  plugin/someteam.example.com/v1/calvinduplicator/go.mod
  plugin/someteam.example.com/v1/calvinduplicator/go.sum
  plugin/someteam.example.com/v1/dateprefixer/go.mod
  plugin/someteam.example.com/v1/dateprefixer/go.sum
  plugin/someteam.example.com/v1/printpluginenv/go.mod
  plugin/someteam.example.com/v1/printpluginenv/go.sum
  plugin/someteam.example.com/v1/secretsfromdatabase/go.mod
  plugin/someteam.example.com/v1/secretsfromdatabase/go.sum
  plugin/someteam.example.com/v1/sedtransformer/go.mod
  plugin/someteam.example.com/v1/sedtransformer/go.sum
  plugin/someteam.example.com/v1/someservicegenerator/go.mod
  plugin/someteam.example.com/v1/someservicegenerator/go.sum
  plugin/someteam.example.com/v1/stringprefixer/go.mod
  plugin/someteam.example.com/v1/stringprefixer/go.sum
  plugin/someteam.example.com/v1/validator/go.mod
  plugin/someteam.example.com/v1/validator/go.sum
  plugin/untested/v1/gogetter/go.mod
  plugin/untested/v1/gogetter/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#5844 build(deps): bump golang.org/x/net from 0.28.0 to 0.33.0 in /hack
  cmd/depprobcheck/go.mod
  cmd/depprobcheck/go.sum
  functions/examples/application-cr/image/go.mod
  functions/examples/application-cr/image/go.sum
  functions/examples/fn-framework-application/go.mod
  functions/examples/fn-framework-application/go.sum
  go.work.sum
  hack/go.mod
  hack/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#5656 Update readme to remove deprecated configuration 'commonLabels'.
  README.md
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#5853 Step down as commands approver
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm
